### ISSUE TITLE
Repository Cleaning

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#107]
The repository was 750MB. It was pruned down to 250MB, but since this package is now less than 10 lines on master (and will be tagged soon), it's less than ideal that its folder is that large. The documentation was moved to DiffEqDocs, DiffEqTutorials, and DiffEqBenchmarks. The vast majority of the extra stuff is buildup due to these notebooks and pictures. I would like to clean these out of the repository since this will not break previous versions but reduce the size to something much more manageable.

However, from the previous mistake (https://github.com/JuliaLang/METADATA.jl/pull/6963#issuecomment-258666169) it's clear that doing this kind of cleaning will change the SHA1s. Thus for this to really work, I will need to put in a METADATA PR changing the SHA1s in the previous tags. 

@tkelman

**Comment by tkelman** [comment]
See also the discussion at https://github.com/tbreloff/Plots.jl/issues/264. Existing tags are really intended to remain fixed, the sha's should not be changed. If you do make this kind of change, it could easily cause problems in updating for anyone with an existing clone. Looking at the github traffic there were apparently 300+ clones, nearly 100 uniques over the past 2 weeks.

**Comment by ChrisRackauckas** [comment]
I still think that 250MB of wasted space (since all of this just old documentation which is no longer even linked) is a large enough size that this is something that should be handled. I did come up with a long term solution (separate repos for docs/tutorials), it's just that Git histories make this still a problem. So I think that I would still like to try to make something happen.

 There will be a major breaking change by tagging this current master. That's why I am thinking doing these changes together. DiffEq currently has the fortune that its ecosystem depends mostly on itself, and there are not version requirements on it (DifferentialEquations does not have dependents). Unless someone has specifically pinned a version, everyone will be on the latest release except for those on v0.4.  So since it will never necessarily be a good thing to mess with the histories, I think fixing this now will be much easier than fixing it later. (This is very different than the Stats/StatsBase change, which did have a lot of dependents at the time of the switch. I think it was a good thing they switched when they did!)

Can we run a test? Make a repository with a simple code and some .gifs in it, take a  version, clear the repo of the .gifs, change the tag SHA1s, and see if `Pkg.update()` handles it?

And maybe https://github.com/JuliaDiffEq/Roadmap/issues/8 should be discussed concurrently.

**Comment by ChrisRackauckas** [comment]
@StefanKarpinski mentioned in https://github.com/tbreloff/Plots.jl/issues/264 about doing the test:

>We could just overwrite all the SHA1s for versions in METADATA, but that seems like a huge risk to me – it's basically indistinguishable from an attack on METADATA and I'm not sure how the package manager will react. We could do some testing first and see what happens?

Can I run something like that right now? Can I make/register a repo for this, or would you like to?

**Comment by oxinabox** [comment]
If we ever got [shallow cloning for Pkg.](https://github.com/JuliaLang/julia/issues/17963)
that would just solve this, right?

And I think in the long term, not using Github as a CDN is pretty desirable.

**Comment by ChrisRackauckas** [comment]
Maybe @ViralBShah and @Keno should be in on this as well.

**Comment by ChrisRackauckas** [comment]
Can we please give this some consideration? I am going to be tagging a major breaking change in about a week (getting rid of almost all of the code here for the modularization changes https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/59) but this will still be a very important package in the ecosystem. This major change will also be coupled with blog posts and other forms of social media outreach and so it will be the best time to make such a large change. Could I please have the permission to register and try it on a test repo?

**Comment by ViralBShah** [comment]
The basic takeaway has been so far that there is no way to clean the history at the moment. Your best bet is to create a new package with a different name. :-(

Or wait for Pkg3, which is maybe 3-4 months away.

**Comment by ChrisRackauckas** [comment]
>Or wait for Pkg3, which is maybe 3-4 months away.

Pkg3 will solve this? How?

**Comment by ViralBShah** [comment]
@stefankarpinski

Basically we won't have the existing METADATA, allowing for a clean break.

**Comment by ChrisRackauckas** [comment]
Okay, then I can wait and do the repo-clean when that change happens? That works for me. I'm in no rush if there's an easy solution in the pipeline.

**Comment by ChrisRackauckas** [comment]
Can we make a move on this, or at least have a very clear move in place for the Pkg3 transition? 

The issue here is that the history cannot be edited to get rid of the big files without changing the SHA1s. Some ways to handle this would be:

1. Edit the history and fix the SHA1s in METADATA
2. Delete some previous tags from METADATA, and tag a new version after doing history edits that dump all of the oldest versions.
3. When transitioning to Pkg3, only register a new tag and dump the history then (if the break is actually allowed to be "clean" like that, i.e. breaking the previous METADATA version)
4. Get single branch cloning or tarball downloads as part of Pkg3, which doesn't solve the problem but masks it.
5. If Pkg3 isn't tied to SHAs, then it fixes itself in the transition one it's okay to break Pkg installs?

**Comment by Keno** [comment]
> If Pkg3 isn't tied to SHAs, then it fixes itself in the transition one it's okay to break Pkg installs?

This is the case, Pkg3 uses tree hashes, so as long as the tree is the same for tagged versions it doesn't care about the commit history.

**Comment by YingboMa** [comment]
I think that this issue can be closed with `Pkg3`.

**Comment by ChrisRackauckas** [comment]
I still would like to do a repo clean. Users just aren't effected anymore though so its priority is much lower.

**Comment by tkelman** [comment]
Users of all past versions of Julia and the package would be.
