### ISSUE TITLE
Improved ODE Plot Recipe

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#111]
The current recipes are nice, but many times people would rather plot the phase plot than the timeseries. I think it would be nice to have a `plot(sol,phase=[1,3,5])` to choose what coordinates to do a phase plot from, with the timeplot occuring as the default with `phase=[]`.

**Comment by Armavica** [comment]
The default currently plots all of a system's variables against time, but sometimes some of them just clutter the graph or can't be plotted with the rest because of scale issues. I was thinking that we could generalize your idea by finding a way to specify which of a system's variables we want to plot the timeseries of, the default remaining to plot them all. Something like this could be the interface, although I am not convinced that there is no better way to do it:

* `vars=[1,3,4]` plots the timeseries of variables 1, 3 and 4;
* `vars=(1,3)` plots the 2D phase portrait (1,3);
* `vars=(1,3,5)` plots the 3D phase portrait (1,3,5);
* One can insert a list anywhere in the phase portrait tuples to superpose several phase portraits:
`vars=(1,[5,6])` plots the 2D phase portraits (1,5) and (1,6) on the same graph;
* If there are several lists in the tuples, they should all have the same size. In which case we take them element by element and superpose the corresponding phase portraits: `vars=([1,2,3],4,[5,6,7])` would result in the drawing of (1,4,5), (2,4,6), and (3,4,7).

**Comment by ChrisRackauckas** [comment]
>One can insert a list anywhere in the phase portrait tuples to superpose several phase portraits: vars=(1,[5,6]) plots the 2D phase portraits (1,5) and (1,6) on the same graph;

What does it mean when two phase portraits are in the same graph? Does the y-axis then mean two things for this case?

**Comment by Armavica** [comment]
It is not different than when you plot the timeseries of two variables on the same graph. In this case 5 and 6 could be the same thing but related to two different components of the system (like their respective position), or different things related to the same component (like the two components of the velocity vector in 2D for example).

If you want a concrete example, here's three agents that start equally distant and that run towards each other:
```julia
using DifferentialEquations
using RecursiveArrayTools
using Plots

function f(t, u)
    u2 = [u[2:end,:]; u[1:1,:]]
    du = u2-u
    for i = 1:size(du,1)
        n = norm(du[i,:])
        du[i,:] /= n
    end
    return du
end

u0 = [0. 0.; 1. 0.; 1/2 sqrt(3)/2]
tspan = (0., .666)
prob = ODEProblem(f, u0, tspan)
sol = solve(prob, dtmax=.01)

# plot(sol, vars=([1,3,5], [2,4,6]))
usol = vecvec_to_mat(sol.u')
p = plot(usol[:,1], usol[:,2])
plot!(p, usol[:,3], usol[:,4])
plot!(p, usol[:,5], usol[:,6])
```

**Comment by ChrisRackauckas** [comment]
Thanks for the example. When I see it in action it makes a lot of sense. I actually like most of the notation a lot: the `([1,3,5], [2,4,6])` looks like a regex which matches 1 and 2, 3 and 4, and 5 and 6. Maybe the timeseries notation isn't the best, but if documented correctly is perfectly fine.

If you want to take a crack at it, the recipe is here: https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/solutions/solution_interface.jl#L46

Also note that this will actually work:

```julia
sol[:,1]
```

**Comment by Armavica** [comment]
> Also note that this will actually work: `sol[:,1]`
Thank you for the remark, I am not familiar with the interface yet. But then the order of the variables is different: `([1,2,3], [4,5,6])`.

I'll give it a try when I have time, maybe this weekend.

**Comment by Armavica** [comment]
Wait, there is something else: what if you want to plot the position of a particle in `(x, y, t)`?

Perhaps we should reconsider your idea of `:t` to denote the time. Or use the number `0`?

**Comment by ChrisRackauckas** [comment]
In response to @alavendelm, when this gets re-worked the docs should probably mention the options currently available to the recipe:

- plot_analytic: Defaults to false. If you used a test problem, this will show the analytical solution. This is mostly for testing and algorithm development.
- denseplot: Defaults to true. This makes the plot use the continuous output to plot `plotdensity` evenly spaced points throughout the desired time interval. This makes the plot smoother even if there are very few points.
- plotdensity: Defaults to 100. This is the number of points taken.

If the interpolation doesn't exist, then plotdensity is by default false and it just directly plots the timeseries of each component.

**Comment by alavendelm** [comment]
At the least, it would be useful to link from docs to the relevant plot recipe so users can go looking in the right place.

**Comment by ChrisRackauckas** [comment]
The example in DiffEqTutorials for plotting should really get beefed up too. It should show how to do the plotting by hand, since no matter what we do it won't cover every case, and dealing with `Vector{Vector{T}}` types isn't easy (unless you just `vecvec_to_mat` via RecursiveArrayTools.jl).

**Comment by ChrisRackauckas** [comment]
The first PR along these lines was just pulled in https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/15

A few things we are still tossing around:

1. Default value for `plotdensity` (the number of evenly spaced points to plot when the dense output is available). I am suggesting `plotdensity = length(sol)*10`. My admittedly non-rigorous tests show that it works quite well. The current setting of `plotdensity = 100` is just bad it should adjust with the length of the solution, mostly because we know that the solution is more complicated when more numerical steps are needed, and thus adjusting the default by the length takes this into account. 10 was just a magic number that usually will give more than 100, many times less than 1000, but ehh.

2. Default labels from ParameterizedFunctions. I might take a crack at this after a nap. Basically, it can just check if it's a `ParameterizedFunction` and, if so, grab the symbols for the label. It should be a little smarter than that though and check if the field `syms` is defined first, so that way it doesn't break the case of hand-defined `ParameterizedFunctions`, and `syms` should be added to the documented interface.

3. Documentation. The plotting documentation should detail the `vars` behavior, and a DiffEqTutorial should show how to do a bunch of customization of the plots.

4. 3D. It would be nice to extend the `vars` just a little bit further to do 3D. I don't know if this is possible... but it's definitely worth a try. Automatic 3D timeseries and phase diagrams would just be a killer feature. 

5. nD. If we can do 3D, then we should get n-dimensional plots working. It shouldn't be much more work (instead of directly writing 3D, write to a collection and splat), and right now it won't really do anything, but there are "down the line" changes to recipe libraries which will change this up. Specifically, I have already thrown around the idea of making a dimensional reduction library, in which case an nD plot would get intercepted so that `dim_reduce = :tSNE2` would do a reduction to a 2D plane by tSNE, etc. Other libraries could implement MATLAB-like slicing of 4D data, in which case for the same reasons it will "just work" on these solutions. So we might as well have it available and ready.

**Comment by ChrisRackauckas** [comment]
I knocked out number 2. It looks like this:

```julia
using DifferentialEquations, Plots
plotly()

f = @ode_def LotkaVolterra begin
  dwolves = a*wolves - b*wolves*rabbits
  drabbits = -c*rabbits + d*wolves*rabbits
end a=>1.5 b=>1 c=3 d=1

tspan = (0.0,10.0)
u0 = [1.0,1.0]

prob = ODEProblem(f,u0,tspan)
sol = solve(prob)

plot(sol)
plot(sol,vars=(1,2))
```

which generates:

![newplot 16](https://cloud.githubusercontent.com/assets/1814174/21445135/206894f4-c86a-11e6-926a-d6c29e8efac9.png)

![newplot 17](https://cloud.githubusercontent.com/assets/1814174/21445137/2582617c-c86a-11e6-8c69-bf0c43dceb13.png)

**Comment by ChrisRackauckas** [comment]
Number 1, dealing with `plotdensity`, looks like it's supersceded by a function plot recipe:

https://github.com/tbreloff/Plots.jl/issues/621

So instead, when we have a dense plot, we can just give Plots.jl some anonymous functions like `(t)->sol(t)[i]`. Not the most efficient but it shouldn't be an issue (if someone has a dense solution, there's no way it's a huge matrix anyways). This will really cut down on the amount of code.

All that's left then is 3D and nD. I am not seeing an easy way to do this given how you enumerate `vars`. Maybe @Armavica has an idea.

**Comment by Armavica** [comment]
What is the problem with n-tuples for nD? `(1,2,3)` -> `x=u1, y=u2, z=u3`, distributivity works the same way, and it is an error to give tuples of different sizes? And single integers are still converted to 2D timeseries.

**Comment by ChrisRackauckas** [comment]
>What is the problem with n-tuples for nD? 

There shouldn't be a problem, it's just about coding it.

**Comment by ChrisRackauckas** [comment]
You can now choose the variables by the symbols in the ParameterizedFunction as well:

```julia
using DifferentialEquations, Plots
lorenz = @ode_def Lorenz begin
  dx = σ*(y-x)
  dy = ρ*x-y-x*z
  dz = x*y-β*z
end σ = 10. β = 8./3. ρ => 28.

u0 = [1., 5., 10.]
tspan = (0., 100.)
prob = ODEProblem(lorenz, u0, tspan)
sol = solve(prob)

xyzt = plot(sol, plotdensity=10000,lw=1.5)
xy = plot(sol, plotdensity=10000, vars=(:x,:y))
xz = plot(sol, plotdensity=10000, vars=(:x,:z))
yz = plot(sol, plotdensity=10000, vars=(:y,:z))
plot(xyzt, plot(xy, xz, yz, layout=(1,3),w=1), layout=(2,1))
```

![lorenz](https://cloud.githubusercontent.com/assets/1814174/21514802/fe837e2c-cc7d-11e6-9603-2aaad3398d33.png)


I think all that's left is higher dimensions?

**Comment by ChrisRackauckas** [comment]
I found out how to do the n-dimensional change, and so 3D was free.

![vars_plotting_example](https://cloud.githubusercontent.com/assets/1814174/21520737/9c201122-ccab-11e6-963e-dbcc267caa74.png)

Closing this issue since we accomplished what we set out to do here. Of course, further improvements can be made, but those should be addressed in a more specific issue.
