### ISSUE TITLE
Insert an Install page in DiffEqDocs

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#113]
The JuliaDiffEq ecosystem is difficult to conceive at first with all the changes taking place. It would be good to have an Install page just after the home page or an Install notebook that would take the newcomers and the return users from the Julia> onward.
The practical approach of many Julia users is to throw everything away and start again when something goes wrong with the packages. 
The Install page should start from Julia 0.5, Ijulia and Conda in place and distinguish Windows and Ubuntu right from the beginning. An important point in Windows is that the JuliaDiffEq ecosystem is created inside the C:\Users\XXX\.julia\ folder. This create some paths issues with Plots, ImageMagick and others.

**Comment by ChrisRackauckas** [comment]
>This create some paths issues with Plots, ImageMagick and others.

Can you explain those a little bit? The most the install should require is `Pkg.add("DifferentialEquations")`. That seems to work on Travis, AppVeyor, and for me, but if there's an installation issue out there I'd like to know about it.

But maybe there should be an install page that explains DifferentialEquations -> Plots -> optionally ImageMagick for animations. Those are the only three you should need to install, plus optionally ODEInterface.jl. Note that there will be some overhauls of Plots' animation setup soon though.

**Comment by finmod** [comment]
The installation sequence should be stated before Pkg.add("DifferentialEquations") because you just don't know how users have arrived to Julia i.e. python -> Julia or Julia -> python. This brings issues like Ananconda, Miniconda, 2.7, 3.5 with various quirks to bear. It is better to indicate what the path to least troubles is: Julia 0.5 from (...) , Pkg.add("Ijulia"), Pkg.add("Juno"), Pkg.add("Conda"), etc. and Pkg.add("DifferentialEquations") to start enjoying the show.

The Windows path problem is: DifferentialEquations is installed in .julia folder. When you run a Tutorial creating some output like .gif, .png etc. they go to an other hidden folder \AppData\.....and therefore are not available inside the folder where the DiffEqTutorials tutorial notebook is located. In short the additional material required to run a Tutorial from DiffEqTutorials should be created and available in that location.

**Comment by ChrisRackauckas** [comment]
>The Windows path problem is: DifferentialEquations is installed in .julia folder. When you run a Tutorial creating some output like .gif, .png etc. they go to an other hidden folder \AppData.....and therefore are not available inside the folder where the DiffEqTutorials tutorial notebook is located. In short the additional material required to run a Tutorial from DiffEqTutorials should be created and available in that location.

In these functions a filename can be given, like `animate(sol,filename="output.gif")`. It probably is running from the location of the Julia process and not the folder that Julia opens from. The easiest fix would probably be for Plots.jl to save by default to the home folder.

**Comment by ChrisRackauckas** [comment]
>It is better to indicate what the path to least troubles is: Julia 0.5 from (...) , Pkg.add("Ijulia"), Pkg.add("Juno"), Pkg.add("Conda"), etc. and Pkg.add("DifferentialEquations") to start enjoying the show.

`Pkg.add("Juno")` shouldn't be needed. `Pkg.add("IJulia")` should add Conda, so `Pkg.add("Conda")` shouldn't be needed. So it should just be `Pkg.add("IJulia")` for the optional notebooks, and `Pkg.add("DifferentialEquations")`. I think that's how I currently have it to?

>This brings issues like Ananconda, Miniconda, 2.7, 3.5 with various quirks to bear.

But yes, I don't quite know how to deal with these. These issues can get pretty specific. My hope is that users are at least familiar with Julia enough to know where these errors are coming from (IJulia) to go to the IJulia page which explains these issues. But it seems that's not something I can rely on much anymore: some people are just coming to Julia to try this, so indeed the "first-install" experience may need some work, anticipated Python user issues.

**Comment by ChrisRackauckas** [comment]
The newest version of the docs mentions installs before each usage. In addition, for Plots, it's mentioned in the plotting section of the docs and the ODE tutorial. All of the other tutorials now mention that you should read the ODE tutorial first. Closing this. If there's any other cases that come up, please open a new issue for that case. Hopefully this helps!

**Comment by ChrisRackauckas** [comment]
Note you will have to wait a bit (maybe a day or so?) before the updated docs build.
