### ISSUE TITLE
docs: examples link broken

### ISSUE THREAD

**Issue by ggggggggg** [JuliaDiffEq/DifferentialEquations.jl#124]
Here: https://juliadiffeq.github.io/DiffEqDocs.jl/latest/tutorials/ode_example.html
we find the text:
```
This tutorial will introduce you to the functionality for solving ODEs. Other introductions can be found by checking out the IJulia notebooks in the examples folder.
```
the second line contains a link which 404s for me.

**Comment by ChrisRackauckas** [comment]
If you refresh the pages the links should now be fixed.
