### ISSUE TITLE
isoutofdomain does not work as intended

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#125]
`isoutofdomain`, though a very nice idea, is flawed when executed in the simple way. If one rejects steps when `isoutofdomain` is false, the error is not necessarily small. The problem with this is that the way adaptive stepsize methods adjust the size of the next step is via the stepsize. Thus it can (and usually will) have the incorrect response of actually increasing the stepsize, causing the solution to stall as it will increase the stepsize until the error is large, and then decrease, and get stuck.

Instead, the behavior needs to be modified so that one is guaranteed that the stepsize will decrease. One way to do this would be to take the minimum of `dt/2` and `q*dt`. That would be easy, safe, and would respect the "efficient" stepsize behavior in the region where it's changes dominate.

**Comment by mauro3** [comment]
The implementation in ODE.jl is correct:
https://github.com/JuliaDiffEq/ODE.jl/blob/8d4827b93609118633478acf09a74247f47cd97e/src/runge_kutta.jl#L424, or not?

**Comment by ChrisRackauckas** [comment]
Ahh, that way works. Thanks for sharing. When I asked before you noted that it would just reject. Yes, scaling by `facmin` will definitely do the trick. It might be over conservative though? With the new interface on OrdinaryDiffEq.jl, I think using the local interpolation `integrator(t)` to rootfind the moment it leaves the domain, and backtrack to just before that would be the best way to do it. It might even be simple to implement using Roots.jl just like an event-finding interface. (Actually, if I refactor the event location finding... it could just call the same function...)

**Comment by ChrisRackauckas** [comment]
Oh, you can't rootfind, but yeah can use bisection via the interpolant. That would be quick and still ensure the property.

**Comment by mauro3** [comment]
Yes, probably too conservative to use `facmin`.  The root-finding might be too complicated though.  Also, it may not work as the equation is out of its domain it may not be well defined.

**Comment by ChrisRackauckas** [comment]
Rootfinding isn't what you want because you're trying to enforce a domain constraint, not hit the domain. If you hit the domain, you already went too far (and if you're trying to do something like that, then you want to use events). Pulling it down by `qmin`/`facmin` is the right strategy. I implemented that into OrdinaryDiffEq.jl.
