### ISSUE TITLE
Parameter estimation example in JuliaDiffEq

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#126]
Optim and LeastSquaresOptim have now been updated (@matthieugomez) and you have implemented substantial changes in the JuliaDiffEq ecosystem. Can you pls revisit the Parameter estimation example in docs to extend it to using build_lsoptim_objective and estimating all three or four parameters of the Lotka-Volterra example?

**Comment by ChrisRackauckas** [comment]
Done. The docs should build with a 4-parameter example showing `build_lsoptim_objective`. I also updated the tests to track this case:

https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/blob/master/test/runtests.jl

**Comment by finmod** [comment]
Spot on. Thanks.
