### ISSUE TITLE
ODELocalSensitivityProblem requires use of macro

### ISSUE THREAD

**Issue by rlecover007** [JuliaDiffEq/DifferentialEquations.jl#134]
Although in the documentation it appears that ODELocalSensitivityProblem just requires a ParamterizedFunction, its use in fact requires the use of the @ode_def macro. This is inconvenient in some cases (lots of parameters).

Same code demonstrating the issue. 

```julia
pf_func = function (t,u,p,du)
  du[1] = p[1] * u[1] - p[2] * u[1]*u[2]
  du[2] = -3 * u[2] + u[1]*u[2]
end

function SampleProblem()

	pf = ParameterizedFunction(pf_func,[1.5,1.0])
	@show typeof(pf)
	prob = ODELocalSensitivityProblem(pf, [1.0; 1.0], (0.0, 10.0))

	sol = solve(prob,Rosenbrock23())

	plot(sol)
end
```

**Comment by ChrisRackauckas** [comment]
This is related: https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/15

**Comment by ChrisRackauckas** [comment]
Fixed. Local and adjoint sensitivities now work with general parameterized functions.

**Comment by rlecover007** [comment]
Most awesome!
