### ISSUE TITLE
@ode_def doesn't easily allow for use of "non-numbers"

### ISSUE THREAD

**Issue by rlecover007** [JuliaDiffEq/DifferentialEquations.jl#136]
It is very difficult to assign parameters using the ode_def marco that aren't already "numbers". Also, interpolation doesn't work. Code to recreate: 

vec = rand(1,4)
f = @ode_def LotkaVolterraExample begin
dx = ax - bxy
dy = -cy + dxy
end a=>vec[1] b=>vec[2] c=>vec[3] d=vec[4]

prob = ODELocalSensitivityProblem(f,[1.0;1.0],(0.0,10.0))

f = @ode_def LotkaVolterraExample begin
                dx = a*x - b*x*y
                dy = -c*y + d*x*y
              end a=>$(vec[1]) b=>$(vec[2]) c=>$(vec[3]) d=$(vec[4])
Also fails

**Comment by ChrisRackauckas** [comment]
And for reference, the horrifying code that works:

```julia
using ParameterizedFunctions
v = rand(4)
params = Expr[:(a=>$(v[1]));:(b=>$(v[2]));:(c=>$(v[3]));:(d=$(v[4]))]
ParameterizedFunctions.ode_def_opts(:LotkaVolterraExample,Dict{Symbol,Bool}(
    :build_tgrad => false,
    :build_jac => false,
    :build_expjac => false,
    :build_invjac => false,
    :build_invW => false,
    :build_hes => false,
    :build_invhes => false,
    :build_dpfuncs => false),:(begin
      dx = ax - bxy
      dy = -cy + dxy
    end),params...)

using DiffEqSensitivity
prob = ODELocalSensitivityProblem(f,[1.0;1.0],(0.0,10.0))
```

The API needs to be improved here, and I think it should be done simultaneously with the expansion of the syntax to allow for DAEs

https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/5

expanding the syntax to allow for user-defined functions:

https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/3

allow for intermediate computations:

https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/11

accept expressions for parameters:

https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/12

and make it possible to define delay equations.

On the surface, these problems are all highly related (it's just about improving the parsing), and so there does exist one strategy which will do all of this. What is that strategy? I'm not quite sure yet, but I'm looking at string macros. So I wouldn't expect an improvement "soon", but I want a good solution which tackles all of these by at least by JuliaCon.

**Comment by ChrisRackauckas** [comment]
This is because it's a macro, and it won't be able to use runtime values. ParameterizedFunctions.jl is getting a re-design which won't need to use macros as much, and this will fix the issue. I'm closing this because what it's directly referring to will not ever be possible without using `@eval`, instead a separate direction which will allow a use-case like this will be possible.

**Comment by ChrisRackauckas** [comment]
An easy workaround is the following:

```julia
vec = rand(1,4)
f = @ode_def LotkaVolterraExample begin
dx = ax - bxy
dy = -cy + dxy
end a=>1.0 b=>1.0 c=>1.0 d=>1.0
f.a,f.b,f.c,f.d = vec...
```

This won't work with `=`, but that's because `=` is for compile-time constants, and those random numbers are not compile-time constants.
