### ISSUE TITLE
Callbacks not repeatable

### ISSUE THREAD

**Issue by bjhockman63** [JuliaDiffEq/DifferentialEquations.jl#138]
I have been playing around with the simple bouncing ball example provided in the documentation and noticed that the callback condition often fails to trigger, sometimes on the first instance, but other times after many bounces. For example, just by extending the tspan to 50 seconds in the default example code, the ball falls through the ground on the 6th impact. It happens on the second impact when the initial drop height is reduced below 10.

Why does the callback condition seems to always fail after some number of triggers?

**Comment by ChrisRackauckas** [comment]
>Why does the callback condition seems to always fail after some number of triggers?

This is fixed on master. There are many different and contrasting reasons why it can happen, partially due to floating point not being exact, and then also due to stepping behavior. An explanation of some of the new heuristics on master is here:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/31#issuecomment-276190185

**Comment by ChrisRackauckas** [comment]
Note that master will be a little hard to run because a few packages need to update. But I hope to have everything tagged by the end of the week.

**Comment by bjhockman63** [comment]
Thanks for the quick reply, Chris. I'll check back early next week.
One "hacky" solution seems to be to reduce the dtmax variable considerably, but (a) this doesn't work every time, and (b) it obviously slows down the integration prohibitively.
How would the performance compare if the BallBounce instead used a DiscreteCallback for the logical check u[1]<0? Would it still be able to rootfind to converge on the transition (i.e. round impact)?

**Comment by ChrisRackauckas** [comment]
It wouldn't rootfind. But the problem should be solved so a hacky solution shouldn't be needed after tags.

**Comment by ChrisRackauckas** [comment]
The tags should have gone through this morning. If you `Pkg.update()` you should get a new version where this is fixed.

However, I do have to note that if you push the event handling too far, you can always find ways to break it if you are using the default parameters (of course, this is too of any event handling system). Thus I included a new section to the documentation which discusses how to tweak the defaults to handle different cases. You can find that here:

http://docs.juliadiffeq.org/latest/features/callback_functions.html#Tweaking-the-Defaults-to-Specialized-Event-Detection-To-Your-Problem-1

Please let me know if you have any further issues.
