### ISSUE TITLE
Saveat indices

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#139]
With the interpolations change, it's now possible to very performantly only generate the values at specific indices. This opens up the possibility for letting `saveat` only save certain values. For example, using the syntax of https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/132 , we can implement:

```julia
sol = solve(prob,alg,saveat=0.25,saveat_idxs=1:2:5)
```

which, at every 0.25 time units, will save only the values of components 1, 3, and 5. This would be a nice control which can greatly reduce memory requirements for intermediate saves.

**Comment by Datseris** [comment]
That is actually a great addition! I am guessing that `saveat_idxs` will support any kind of container of Integers?

**Comment by ChrisRackauckas** [comment]
Yes. I've only tested Ranges and arrays of integers in the interpolation extension, https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/127, but in theory the rest all work via dispatch.

**Comment by ChrisRackauckas** [comment]
Implemented
