### ISSUE TITLE
Extendable Data Array Type

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#140]
I want to create an extendable data array type which is easy to use in DifferentialEquations.jl methods. An example of such an array from @ronisbr which adds one field is as follows:

```julia
type SimType{T} <: AbstractArray{T,1}
    x::Array{T,1}
    f1::T
end

function SimType{T}(::Type{T}, length::Int64)
    return SimType{T}(zeros(length), T(0))
end

function SimType{T}(S::SimType{T})
    return SimType(T, length(S.x))
end

function SimType{T}(S::SimType{T}, dims::Dims)
    return SimType(T, prod(dims))
end

similar{T}(A::SimType{T}) = begin
    R = SimType(A)
    R.f1 = A.f1
    R
end

similar{T}(A::SimType{T}, ::Type{T}, dims::Dims) = begin
    R = SimType(A, dims)
    R.f1 = A.f1
    R
end

done(A::SimType, i::Int64) = done(A.x,i)
eachindex(A::SimType)      = eachindex(A.x)
next(A::SimType, i::Int64) = next(A.x,i)
start(A::SimType)          = start(A.x)

length(A::SimType) = length(A.x)
ndims(A::SimType)  = ndims(A.x)
size(A::SimType)   = size(A.x)

recursivecopy!(B::SimType, A::SimType) = begin
    recursivecopy!(B.x, A.x)
    B.f1 = A.f1
end

getindex( A::SimType,    i::Int...) = (A.x[i...])
setindex!(A::SimType, x, i::Int...) = (A.x[i...] = x)
```

This can be generalized a little bit. Instead, an abstract type

```julia
abstract DEDataArray{T} <: AbstractArray{T,1}
```

Can can be created which implements the interface as is shown here in a way that assumes the array part (the continuous variables) is the field named `x`. Then a user would just have to do something like

```julia
type EasySimType{T} <: DEDataArray{T}
  x::Vector{T}
  f1::T
end
```

and this array would then work correctly in the `*DiffEq` solvers. The only part which would be difficult is that implementing the `recursivecopy!` would need to be done via a generated function since otherwise using `getfield` is slow an not type-stable, and there's no other way to know the fields of the type in advance. This can go into DiffEqBase since it's lightweight, pretty basic, and pretty universally useful.

**Comment by ronisbr** [comment]
Hi @ChrisRackauckas,

Good! This will greatly improve the usability of this package. For your information, I tried to make something more automatic inside `recursivecopy!` but I had no success (the good point is that I am not a good julia programmer yet :D).

**Comment by ChrisRackauckas** [comment]
Solved via the new `DEDataArray` interface. Documentation page:

http://docs.juliadiffeq.org/latest/features/data_arrays.html#Data-Arrays-1

It's included as part of DiffEqBase.jl, and is currently only on master. A release with this will be tagged soon enough.
