### ISSUE TITLE
using DifferentialEquations fails

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#141]
Since yesterday, using DifferentialEquations, RecursiveArrayTools fails as follows:

INFO: Precompiling module Optim.
ERROR: LoadError: LoadError: syntax: invalid assignment location "OptimizationTrace{T}"
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Denis\.julia\v0.5\Optim\src\types.jl, in expression starting on line 57
while loading C:\Users\Denis\.julia\v0.5\Optim\src\Optim.jl, in expression starting on line 46

LoadError: Failed to precompile Optim to C:\Users\Denis\.julia\lib\v0.5\Optim.ji.
while loading C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\DifferentialEquations.jl, in expression starting on line 10

 in compilecache(::String) at .\loading.jl:593
 in require(::Symbol) at .\loading.jl:422
 in _include_from_serialized(::String) at .\loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:217
 in require(::Symbol) at .\loading.jl:371
 in _include_from_serialized(::String) at .\loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:217
 in require(::Symbol) at .\loading.jl:371
 in include_from_node1(::String) at .\loading.jl:488
 in eval(::Module, ::Any) at .\boot.jl:234
 in require(::Symbol) at .\loading.jl:415

Also Pkg.test("DifferentialEquations") fails with a compatibility issue with Color.

**Comment by ChrisRackauckas** [comment]
@pkofod do you know about this?

**Comment by ChrisRackauckas** [comment]
What packages do you have checked out? If Optim or any of the JuliaNLSolvers packages are checked out, you may want to go back to release.

**Comment by pkofod** [comment]
Don't know what caused this, but there have been some problems with other packages? Can you change the require of optim to v0.7.4 then it might help. Unfortunelate I don't have any time these days

**Comment by ChrisRackauckas** [comment]
Hopefully that works for @finmod . If anyone else reports this issue, I'll put a version limit in METADATA.

**Comment by finmod** [comment]
There are two problems here. First, Pkg.test("DifferentialEquations") fails with is message:
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.test("DifferentialEquations")
INFO: Computing test dependencies for DifferentialEquations...
WARNING: julia is fixed at 0.5.0 conflicting with requirement for Color: [0.3.0,0.4.0)
ERROR: fixed packages introduce conflicting requirements for FixedPointNumbers: 
         Color requires versions [0.0.0,0.0.10)
         ImageMagick requires versions [0.3.0,∞)
       the requirements are unsatisfiable because their intersection is empty
 in check_requirements(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\query.jl:191
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:492
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\entry.jl:476
 in #test!#58(::Bool, ::Function, ::String, ::Array{AbstractString,1}, ::Array{AbstractString,1}, ::Array{AbstractString,1}) at .\pkg\entry.jl:693
 in (::Base.Pkg.Entry.#kw##test!)(::Array{Any,1}, ::Base.Pkg.Entry.#test!, ::String, ::Array{AbstractString,1}, ::Array{AbstractString,1}, ::Array{AbstractString,1}) at .\<missing>:0
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:725
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258

This affects all packages and all operating systems. I just don't know how to straighten out Color.

Then, using DifferentialEquations continues to give the same error.

**Comment by ChrisRackauckas** [comment]
Color, FixedPointNumbers, ImageMagick. None of those are DifferentialEquations.jl dependencies. They are Plots.jl dependencies, but that doesn't show up in the tests. Something is really weird here. Can you post your Pkg.status()?

**Comment by finmod** [comment]
Here it is. I used Plots for producing the usual graphs for Lotke-Volterra or Lorenz

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.status()
55 required packages:
 - ArbFloats                     0.1.15
 - BaseTestNext                  0.2.2
 - CUDArt                        0.2.3+             master
 - Clp                           0.3.0
 - Color                         0.4.8+             aaff2eac
 - Combinatorics                 0.3.2+             master
 - DataFrames                    0.8.5
 - DecFP                         0.1.5              master
 - Decimals                      0.1.0
 - DiffEqBase                    0.10.0
 - DiffEqProblemLibrary          0.4.0
 - DifferentialEquations         1.7.0
 - Distances                     0.4.0
 - DoubleDouble                  0.2.0
 - DualNumbers                   0.2.3
 - ForwardDiff                   0.3.4+             master
 - GLM                           0.6.1
 - GLPKMathProgInterface         0.3.0
 - GR                            0.19.0
 - Gadfly                        0.5.3
 - GaussianMixtures              0.1.0+             master
 - GaussianProcesses             0.4.0+             master
 - Graphs                        0.7.1
 - IJulia                        1.4.1
 - ImageMagick                   0.2.1+             master
 - Interact                      0.4.3
 - Ipopt                         0.2.6
 - JuMP                          0.15.0+            master
 - Juno                          0.2.5
 - LeastSquaresOptim             0.2.1
 - LowRankModels                 0.2.0
 - Mads                          0.3.5
 - ManifoldLearning              0.1.0+             master
 - MathProgBase                  0.5.10
 - MatlabCompat                  0.1.2
 - NLopt                         0.3.3
 - NLsolve                       0.9.1
 - Nemo                          0.5.1
 - ODE                           0.2.1+             master
 - ODEInterface                  0.1.0
 - OrdinaryDiffEq                1.3.1
 - ParallelDataTransfer          0.1.1
 - ParameterizedFunctions        1.0.0
 - PyCall                        1.10.0+            master
 - PyPlot                        2.3.1
 - QuantEcon                     0.9.0
 - RDatasets                     0.2.0
 - ReverseDiffSource             0.3.0
 - ReverseDiffSparse             0.7.1
 - Roots                         0.3.0
 - ScikitLearn                   0.2.4              master
 - StatPlots                     0.2.1
 - Sundials                      0.7.0+             master
 - SymEngine                     0.1.2+             master
 - Unitful                       0.0.4+             master
156 additional packages:
 - AffineInvariantMCMC           0.1.3
 - AlgebraicDiffEq               0.1.0
 - Anasol                        0.1.10
 - ArrayViews                    0.6.4
 - AutoHashEquals                0.1.1
 - AxisAlgorithms                0.1.6
 - AxisArrays                    0.0.3
 - BIGUQ                         0.2.0
 - BinDeps                       0.4.5
 - BlackBoxOptim                 0.2.1
 - Blosc                         0.1.7
 - BufferedStreams               0.3.0
 - CDDLib                        0.1.2
 - CUDAdrv                       0.2.1
 - Cairo                         0.2.35
 - Calculus                      0.2.0
 - CatIndices                    0.0.1
 - Cbc                           0.3.0
 - ChunkedArrays                 0.1.1
 - Clustering                    0.7.0
 - Codecs                        0.2.0
 - ColorTypes                    0.3.3
 - ColorVectorSpace              0.2.0
 - Colors                        0.7.1
 - Compat                        0.17.0
 - Compose                       0.4.5
 - ComputationalResources        0.0.1
 - Conda                         0.5.1
 - Contour                       0.2.0
 - CustomUnitRanges              0.0.3
 - DSP                           0.1.1
 - DataArrays                    0.3.12
 - DataStructures                0.5.2
 - Dates                         0.4.4
 - DelayDiffEq                   0.1.0
 - DiffBase                      0.0.4
 - DiffEqCallbacks               0.0.1
 - DiffEqDevTools                0.6.0
 - DiffEqMonteCarlo              0.0.1
 - DiffEqPDEBase                 0.0.3
 - DiffEqParamEstim              0.1.0
 - DiffEqSensitivity             0.0.4
 - Distributions                 0.12.0
 - DocStringExtensions           0.3.1
 - Documenter                    0.9.0
 - EllipsisNotation              0.0.2
 - FFTViews                      0.0.1
 - FactCheck                     0.4.3
 - FileIO                        0.3.0+             master
 - FiniteElementDiffEq           0.2.1
 - FixedPointNumbers             0.3.3
 - FixedSizeArrays               0.2.5
 - Formatting                    0.2.0
 - GLPK                          0.4.0
 - GZip                          0.2.20
 - Games                         0.0.0-             master (unregistered)
 - GenericSVD                    0.0.2
 - GeometryTypes                 0.2.2
 - GeostatInversion              0.1.3
 - Graphics                      0.1.3
 - Grid                          0.4.2
 - HDF5                          0.7.3
 - Hexagons                      0.0.4
 - Hiccup                        0.1.1
 - ImageAxes                     0.1.0
 - ImageCore                     0.1.1
 - ImageFiltering                0.1.1
 - ImageMetadata                 0.2.0
 - ImageView                     0.3.1
 - Images                        0.7.0
 - IndirectArrays                0.1.0
 - IniFile                       0.2.5
 - InplaceOps                    0.1.0
 - Interpolations                0.3.6
 - IntervalSets                  0.0.2
 - IterativeSolvers              0.2.2
 - Iterators                     0.2.0
 - JLD                           0.6.9
 - JSON                          0.8.2
 - KernelDensity                 0.3.0
 - Klara                         0.7.1
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.5
 - LearnBase                     0.1.2
 - LegacyStrings                 0.2.0
 - LibExpat                      0.2.4
 - Libz                          0.2.3
 - LightGraphs                   0.7.2
 - LightXML                      0.4.0
 - LineSearches                  0.1.5
 - Loess                         0.1.0
 - Logging                       0.3.1
 - LossFunctions                 0.0.3
 - LsqFit                        0.1.1
 - MAT                           0.3.1
 - MacroTools                    0.3.4
 - MappedArrays                  0.0.5
 - Measures                      0.0.3
 - Media                         0.2.5
 - MetaProgTools                 0.1.5
 - MultivariateStats             0.3.1
 - NMF                           0.2.5
 - NaNMath                       0.2.2
 - NearestNeighbors              0.0.5
 - Nettle                        0.2.4
 - OffsetArrays                  0.2.12
 - Optim                         0.7.5+             master
 - PDMats                        0.5.4
 - Parameters                    0.6.0
 - ParserCombinator              1.7.11
 - PlotThemes                    0.1.1
 - PlotUtils                     0.3.0
 - Plots                         0.10.3
 - Polyhedra                     0.1.3
 - PolynomialFactors             0.0.3
 - Polynomials                   0.1.2
 - PositiveFactorizations        0.0.4
 - Primes                        0.1.2
 - ProgressMeter                 0.3.3
 - QuadGK                        0.1.1
 - RData                         0.0.4
 - RangeArrays                   0.1.1
 - Ranges                        0.0.1
 - Ratios                        0.0.4
 - Reactive                      0.3.7
 - ReadableNumbers               0.0.3
 - RecipesBase                   0.1.0
 - RecursiveArrayTools           0.2.0
 - Reexport                      0.0.3
 - Requires                      0.3.0
 - ResettableStacks              0.1.0
 - ReusableFunctions             0.1.13
 - Rmath                         0.1.6
 - RobustPmap                    0.1.12
 - SHA                           0.3.1
 - SIUnits                       0.1.0
 - ScikitLearnBase               0.2.1
 - ShowItLikeYouBuildIt          0.0.1
 - Showoff                       0.0.7
 - SimpleTraits                  0.2.0
 - SortingAlgorithms             0.1.0
 - StaticArrays                  0.1.4
 - StatsBase                     0.13.0
 - StatsFuns                     0.4.0
 - StochasticDiffEq              1.0.2
 - StokesDiffEq                  0.1.0
 - TexExtensions                 0.0.3
 - TiledIteration                0.0.1
 - Tk                            0.4.0
 - URIParser                     0.1.8
 - VectorizedRoutines            0.0.2
 - WinRPM                        0.2.3
 - Winston                       0.12.1
 - WoodburyMatrices              0.2.2
 - YAML                          0.1.10
 - ZMQ                           0.4.1

julia>

**Comment by ChrisRackauckas** [comment]
You have a ton of master branches that I wouldn't not know how to handle. Why are you on Optim master? Color master? If you don't have a specific reason, I would get off of those. Most likely those are causing your problem.

**Comment by finmod** [comment]
So I should get most if not all the packages out of master. How do you do that? To get into master, you do Pkg.checkout("pkg") but to get out as you suggest?

**Comment by pkofod** [comment]
`Pkg.free("Optim")` should do

**Comment by ChrisRackauckas** [comment]
Yes, `Pkg.free` will get you back to release.

>So I should get most if not all the packages out of master.

Yes. There is no guarantee that the master branch of any package is working. In many cases it is, but in many cases... it isn't. If you aren't associated with the development or testing some unreleased feature, you shouldn't use the master branch. Even if you test, you should `Pkg.free` once you are done trying it out. I would only stay on the master branches of packages which I am developing since that's the only way I'd know what's on master.

**Comment by finmod** [comment]
Thank you. Pkg.free() did it in the end. It involved 16 packages and the main culprit appears to have been ImageMagick. Then there was a problem with Color which is deprecated and there is still a problem with TestImages. Pkg.test("DifferentialEquations") and others are now fine.
