### ISSUE TITLE
Non-Linear Solve for ODE System Steady State

### ISSUE THREAD

**Issue by gomorgan** [JuliaDiffEq/DifferentialEquations.jl#146]
Would be useful to be able to compute steady state solutions to ODE systems, rather than having to explicitly construct large matrices. Compatibility with ParameterizedFunctions.jl would be useful too.

Thanks!

**Comment by ChrisRackauckas** [comment]
Hey,

Yes, we should definitely implement something like this. It would probably do well in:

https://github.com/JuliaDiffEq/DiffEqBifurcate.jl

The development on that stopped for a bit due to segfaults in the wrapper of PyDSTool:

https://github.com/JuliaDiffEq/PyDSTool.jl

But some simple steady state finders directly from an ODEProblem or function for an ODE wouldn't be hard. Quoting from Gitter:

> if it's written as `f(t,u)` for the ODE solvers, then you can make it a single variable via `g = u -> f(0,u)`, and then use NLSolve.jl on that.
> `g = u -> (du = similar(u); f(0,u,du); du)` or `g = (u,du) ->  f(0,u,du)` depending on what NLSolve.jl needs (I think it can do the latter? Which would be faster)

A function to do this could be put into DiffEqBifurcate to give a simple implementation.

**Comment by ChrisRackauckas** [comment]
Update: there is no DiffEqBifurcate.jl anymore. It's all in PyDSTool.jl, which now works and is included with the standard DifferentialEquations.jl build. That does bifurcation plotting.

For steady state finding, we can put something like this together. This is an entire other class of methods as well for fast finding steady states which I'd like to implement. But let's do the basic nonlinear solve methods first.

**Comment by ChrisRackauckas** [comment]
Design: I am thinking there should be a `SteadyStateProblem(f,u0)` where `f` is the ODE and `u0` is the initial guess, and we can just extend solve to have algorithms that give back steady states for this. Obviously `f` needs to be homogeneous, but we should accept `f(t,u)` and `f(t,u,du)` to make it easy to go from an ODE to the steady states. Maybe `SteadyStateProblem(prob)` to convert an ODE problem?

**Comment by gomorgan** [comment]
`SteadyStateProblem(prob)` could be a reasonably neat solution, though in my experience `prob` has required modification for the steady state solution. That may not be the case for every problem though.

I expect the number of non-linear solvers and optimisation functions is likely to be quite large - though plenty have been implemented already.

**Comment by ChrisRackauckas** [comment]
Created SteadyStateDiffEq.jl

```julia
using SteadyStateDiffEq, DiffEqBase, NLsolve

# `t` is ignored and set to zero
function f(t,u,du)
  du[1] = 2 - 2u[1]
  du[2] = u[1] - 4u[2]
end
u0 = zeros(2)

# Build it directly
prob = SteadyStateProblem(f,u0)
sol = solve(prob,SSRootfind())

# Or just use an existing ODEProblem
prob = ODEProblem(f,u0,(0.0,1.0))
prob = SteadyStateProblem(prob)

# You can pass in an NLsolve function. Needs to be generalized a bit.
sol = solve(prob,SSRootfind(nlsolve = (f,u0) -> NLsolve.nlsolve(f,u0,autodiff=true,method=:newton,iterations=Int(1e6))))
```

It can definitely use
