### ISSUE TITLE
Improve citations

### ISSUE THREAD

**Issue by sdwfrost** [JuliaDiffEq/DifferentialEquations.jl#148]
Hi @ChrisRackauckas 

Can the citations be improved? For example, [LSODA.jl](https://github.com/rveltz/LSODA.jl) includes the algorithm, but not a link to the actual repository - cf all the packages in the JuliaDiffEq ecosystem.

I see that you also lifted my SIR epidemic model from [Gillespie.jl](https://github.com/sdwfrost/Gillespie.jl), down to the exact parameter values. It's just a toy example, and it's important and good to replicate things, but it's not fitting that neither the existing example or the library are overlooked, just because they're outside the ecosystem.

**Comment by ChrisRackauckas** [comment]
Most of the JuliaDiffEq software doesn't have a setup software citation. But there's a link to the JORS format in the header. That said, I added a recommended citation for LSODA.jl. I could not find a paper related to it, so this is all I could come up with. You can submit a PR anytime to update this at this file:

https://github.com/JuliaDiffEq/juliadiffeq.github.io/blob/master/citing.md 

As far the example, I am sorry I assumed that the SIR model would be something that would be common enough to not be cited anymore. To make sure this isn't an issue, I put a small plug in there:

https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/src/tutorials/discrete_stochastic_example.md#defining-a-model-using-reactions

Is there a "first SIR Gillespie model formulation" paper that I should be pointing to instead?

**Comment by sdwfrost** [comment]
It just seemed a bit inconsistent that there were URLs for some packages but not others; many wrappers won't end up with publications. I'll ask @rveltz to put up LSODA.jl on zenodo or something; perhaps this is a pattern that should be encouraged if JuliaDiffEq is going to be an umbrella over multiple solvers etc.?

As for the SIR model I was just lazy and cited [Wikipedia](https://en.wikipedia.org/wiki/Compartmental_models_in_epidemiology#The_SIR_model_without_vital_dynamics) for the model itself. I think its important to be consistent about attribution, however, even if it is as something as minor as a web link. It's not that the SIR model itself isn't common; it's just clear that you saw my code (hey, you've even improved it) and implemented a model. Perhaps zenodo is a bit too inclusive (your PRs count towards authorship in [Zenodo](https://zenodo.org/record/161545#.WN04jRIrJBw), but the point of open software is that you can do what you want, with attribution. Feel free to close the issue.

**Comment by ChrisRackauckas** [comment]
>It just seemed a bit inconsistent that there were URLs for some packages but not others; many wrappers won't end up with publications. I'll ask @rveltz to put up LSODA.jl on zenodo or something; perhaps this is a pattern that should be encouraged if JuliaDiffEq is going to be an umbrella over multiple solvers etc.?

That's probably a good idea. I think every scientific software should have some good way of citing it, so maybe Zenodo would be a good thing for each "large enough" solver package.

>hey, you've even improved it

Not yet! I'm sure your code will still win in benchmarks, for now. But I think this code can be faster because of the sparse representation of the reactions. There are some difficulties to work out though, given it's design. 

>Perhaps zenodo is a bit too inclusive

It is. If I listened to Zenodo, then the Gitter badger (the bot which adds a badge for Gitter the first time you make a channel) would be a co-author.
