### ISSUE TITLE
Saving Tools

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#151]
There should be ways to easily save out the solution type to data. Something to save to a DataFrame/DataTable, and something to save to JLD.

**Comment by ChrisRackauckas** [comment]
Should be a DiffEqIO.jl, if anyone wants to work on this. Should just need DiffEqBase.jl, and make functions to translate the solution types to data formats.

**Comment by bradleyashton** [comment]
I guess the question for me would be: how would this tie in with parallel execution on cluster architecture? Can I launch a bunch of jobs on different Julia nodes, and have them save their results separately, and then collect them on one node for data processing? Would this play nicely with the MonteCarlo function?

**Comment by ChrisRackauckas** [comment]
>I guess the question for me would be: how would this tie in with parallel execution on cluster architecture? Can I launch a bunch of jobs on different Julia nodes, and have them save their results separately, and then collect them on one node for data processing? Would this play nicely with the MonteCarlo function?

I have no clue. This might be something where a distributed database is needed? Or maybe there is some way to have each process generate a JLD file with the solutions it made, and then concatenate all of these files together? I am going to ask on Discourse and see if some data guru has some ideas.

**Comment by ChrisRackauckas** [comment]
https://discourse.julialang.org/t/suggested-formats-for-saving-and-serialization/3230/1
https://discourse.julialang.org/t/how-to-handle-and-store-large-amounts-of-distributed-generated-data/3231/1

I opened up two threads on the Discourse. One on what kind of saving formats to target, and one on how distributed saving could work. Hopefully we get some ideas generated there to guide our next steps.

**Comment by ChrisRackauckas** [comment]
I'm not sure about this `pwrite` stuff. Too C for me... someone else might need to contribute there.

But I can setup a DataStream.

**Comment by ChrisRackauckas** [comment]
It looks like we'll have a conversion to data formats due to this:

https://github.com/davidanthoff/IterableTables.jl/pull/22

**Comment by ChrisRackauckas** [comment]
This is pretty much completed by IterableTables.jl. I added an index to the `output_func` of the Monte Carlo so that way you could write to files of different names for each Monte Carlo trajectory. IterableTables.jl lets you write to DataFrames and CSVs. JLD lets you save out the arrays (though not the `sol` type just yet). I'll wait until there's a `pwrite` in Base before venturing there, but using separate files for parallel and having the filesystem handle it is probably fine for now (probably better than anything I'd cook up). So this is essentially done.

**Comment by bradleyashton** [comment]
Superb! I'll do some more testing

**Comment by ChrisRackauckas** [comment]
You have to pull up the PR branch because it's not merged yet:

https://github.com/davidanthoff/IterableTables.jl/pull/22#issuecomment-294619400

This is the kind of stuff I was doing in tests:

https://github.com/JuliaDiffEq/DiffEqIO.jl/blob/master/test/runtests.jl

Now now since it's `output_func(sol,i)`, you can use the `i` in the CSV name. This will at least handle the "large problems" domain pretty well, where computational costs and running out of memory dominate.
