### ISSUE TITLE
IOPub data rate exceeded

### ISSUE THREAD

**Issue by bradleyashton** [JuliaDiffEq/DifferentialEquations.jl#153]
I am encountering a new problem with plotting the output from DifferentialEquations.jl

```julia
using Plots; plotly()
plot(real(sol[:,1]))
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
```

**Comment by ChrisRackauckas** [comment]
I honestly have no idea what IOPub is. Does this have something to do with Jupyter notebooks / IJulia? Or is this straight Plots.jl in the REPL?

**Comment by bradleyashton** [comment]
I should have said: it is run in a Jupyter notebook. Also, I just noticed that if I don't use plotly everything works ok, so looks like this issue is misplaced here.

**Comment by ChrisRackauckas** [comment]
Oh okay. It must be a limitation for the size of a Plotly plot.
