### ISSUE TITLE
Cannot using DifferentialEquations, fail to precompipe StokesDiffEq

### ISSUE THREAD

**Issue by ggggggggg** [JuliaDiffEq/DifferentialEquations.jl#161]
Possibly useful debugging info below.

```
julia> using DifferentialEquations
INFO: Precompiling module StokesDiffEq.
ERROR: LoadError: LoadError: invalid subtyping in definition of StokesSolution
...

julia> versioninfo()
Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge

julia> for (k,v) in Pkg.installed()
       println("$k => $v")
       end
ForwardDiff => 0.4.2
DelayDiffEq => 0.3.0
ParameterizedFunctions => 1.3.0
InplaceOps => 0.1.0
EllipsisNotation => 0.1.0
Juno => 0.2.7
MultiScaleArrays => 0.1.0
StochasticDiffEq => 2.0.1
AlgebraicDiffEq => 0.1.0
DiffEqJump => 0.3.1
DataStructures => 0.5.3
Compat => 0.24.0
ChunkedArrays => 0.1.1
PolynomialFactors => 0.0.4
OrdinaryDiffEq => 2.0.1
Calculus => 0.2.2
Measures => 0.1.0
StatsFuns => 0.5.0
RecipesBase => 0.1.0
LearnBase => 0.1.5
SpecialFunctions => 0.1.1
Showoff => 0.1.1
Distributions => 0.12.5
DiffEqDevTools => 0.8.1
Primes => 0.1.3
FixedPointNumbers => 0.3.7
SHA => 0.3.2
ModelTES => 0.0.0-
Media => 0.2.7
Combinatorics => 0.4.0
IterativeSolvers => 0.2.2
Iterators => 0.3.1
ColorTypes => 0.4.1
LsqFit => 0.2.0
Polynomials => 0.1.5
PlotThemes => 0.1.1
StokesDiffEq => 0.1.0
GenericSVD => 0.0.2
PDMats => 0.6.0
DiffEqSensitivity => 0.2.2
Sundials => 0.11.1
Optim => 0.7.8
SimpleTraits => 0.5.0
Conda => 0.5.3
DiffEqFinancial => 0.2.0
Hiccup => 0.1.1
PyCall => 1.12.0
PlotUtils => 0.3.0
FixedSizeArrays => 0.2.5
JSON => 0.10.0
StatsBase => 0.14.1
Distances => 0.4.1
Plots => 0.10.3
DiffEqBiological => 0.0.1
DiffEqMonteCarlo => 0.3.0
PyPlot => 2.3.1
DiffEqCallbacks => 0.1.0
QuadGK => 0.1.2
BinDeps => 0.4.7
DifferentialEquations => 1.10.1
DiffEqNoiseProcess => 0.0.2
PositiveFactorizations => 0.0.4
Parameters => 0.7.2
DiffEqPDEBase => 0.3.1
DiffEqBase => 1.1.1
Reexport => 0.0.3
NaNMath => 0.2.4
URIParser => 0.1.8
LossFunctions => 0.0.3
VectorizedRoutines => 0.0.2
DiffEqParamEstim => 0.3.0
Rmath => 0.1.6
LineSearches => 0.1.5
DiffBase => 0.1.0
Roots => 0.3.0
LaTeXStrings => 0.2.1
Ranges => 0.0.1
FiniteElementDiffEq => 0.3.0
SymEngine => 0.1.5
Colors => 0.7.3
MacroTools => 0.3.6
ResettableStacks => 0.1.0
NLsolve => 0.9.1
RecursiveArrayTools => 0.5.0

```

**Comment by ChrisRackauckas** [comment]
Yes, this was noticed earlier today. Sorry we missed this. It will be fixed when either of these two are merged:

https://github.com/JuliaLang/METADATA.jl/pull/9137
https://github.com/JuliaLang/METADATA.jl/pull/9144

@tkelman, is the version bound not being merged because of the Travis failure?

**Comment by tkelman** [comment]
yeah

**Comment by ChrisRackauckas** [comment]
Well that tag https://github.com/JuliaLang/METADATA.jl/pull/9144 will fix it anyways. That should be fine while we wait on v0.5.2 or v0.6 for the proper version bound. Is there a timeline on either of those?

**Comment by tkelman** [comment]
PR's are open for both. Should be a day or so for pkgeval regression testing.

**Comment by ChrisRackauckas** [comment]
Found them, thanks

https://github.com/JuliaLang/julia/pull/21694
https://github.com/JuliaLang/julia/pull/21684

**Comment by ChrisRackauckas** [comment]
In the meantime, can the tag https://github.com/JuliaLang/METADATA.jl/pull/9144 get fast tracked to fix this issue?

**Comment by tkelman** [comment]
Sure. You may want to look into splitting JuliaDiffEq up a bit into multiple orgs to spread out the CI load on Travis, or have some other contributors volunteer space on their appveyor accounts.

**Comment by ChrisRackauckas** [comment]
Yeah, I've been thinking about doing something like that. In general, it only gets bogged down when one of these big pushes happen. But yeah, the tests keep growing and Travis doesn't seem to go any faster...

**Comment by ChrisRackauckas** [comment]
@ggggggggg `Pkg.update()` and give it a try now.

**Comment by miguelraz** [comment]
I can volunteer space on my Travis, am not using it for anything atm.
Care to volunteer some instructions as to how to do so @tkelman ?

**Comment by ChrisRackauckas** [comment]
It's not difficult. The difficult part is being smart about how we do Travis for permissions reasons (hence the suggestion of a separate org). AppVeyor is tied to personal accounts though, so you can add projects to your AppVeyor and PR for the badge to point to your AppVeyor. Definitely do that for DiffTools.

**Comment by tkelman** [comment]
Travis queue limits are per github organization. AppVeyor queue limits are per account, and which AppVeyor account you enable a repo on doesn't have to correspond to a github user or organization.

**Comment by ggggggggg** [comment]
thanks, it works now
