### ISSUE TITLE
diagonal real noises for complex vars

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaDiffEq/DifferentialEquations.jl#163]
for creating real noises where `du` is complex I used to do

```julia
inline function my_noise_function!(rand_vec,integrator)
  for i in eachindex(rand_vec)
    rand_vec[i] = randn()
  end
end

my_noise = NoiseProcess{:White,true,typeof(my_noise_function!)}(my_noise_function!)
```

and it seems like I should be constructing a diagonal matrix now.  http://juliadiffeq.org/2017/04/30/API_changes.html 

This feels like overkill. Any new syntax for diagonal noise that differs from `du` type?

**Comment by ChrisRackauckas** [comment]
Yes, see the new `NoiseProcess` page.

http://docs.juliadiffeq.org/latest/features/noise_process.html

You would want to do:

```juila
function dist(rand_vec,W,dt)
  for i in eachindex(rand_vec)
    rand_vec[i] = randn()
  end
  rand_vec .*= sqrt(abs(dt))
end
function bridge(rand_vec,W,W0,Wh,q,h)
  for i in eachindex(rand_vec)
    rand_vec[i] = randn()
  end
  rand_vec .= sqrt((1.-q).*q.*abs(h)).*rand_vec.+q.*(Wh.-W0).+W0
end
```

That's the distribution of Brownian bridge for real-valued noise, regardless of the typing W. Then you'd use:

```julia
my_noise= NoiseProcess(t0,W0,Z0,dist,bridge)
```

where `W0` and `Z0` are arrays of the appropriate size and `t0` is the starting time for the noise process. This is what you'd pass in as `noise=my_noise`.

Please feel free to request some docs changes. I may need to add more mathematical explanations in here, but hopefully it comes off clear that the first equation is just that the distribution is `dW ~ N(0,dt)`, and the second one is the Brownian Bridge statistic with `W(0)=W0`, `W(h)=Wh`, `W(q)~ N(q.*(Wh.-W0).+W0,sqrt((1.-q).*q.*abs(h)))`. The Brownian Bridge is what's required for adaptivity, and so if this is `nothing` you just lose adaptivity. But this extension allows adaptivity to work even if the user defines colored noise (but the bridging distribution needs to be worked out!)

**Comment by AshtonSBradley** [comment]
Thanks, this is very helpful. Now  I do 
```Julia
a0 = sqrt(N0/2)*(randn(6)+im*randn(6))
a0[2] = conj(a0[1]);a0[4]=conj(a0[3]);a0[6]=conj(a0[5]);
#
my_noise= NoiseProcess(0,ones(a0),Z0=nothing,dist,bridge)
prob = SDEProblem(f,g,a0,tspan,noise=my_noise)
```

then

```Julia
compile...
MethodError: no method matching DiffEqNoiseProcess.NoiseProcess{T,T2,T3,ZType,F,F2,inplace,S1,S2,RSWM}(::Int64, ::Array{Complex{Float64},1}, ::#dist, ::#bridge; Z0=nothing)
Closest candidates are:
  DiffEqNoiseProcess.NoiseProcess{T,T2,T3,ZType,F,F2,inplace,S1,S2,RSWM}(::Any, ::Any, ::Any, ::Any, ::Any; iip, rswm) at /Users/abradley/.julia/v0.5/DiffEqNoiseProcess/src/types.jl:30 got unsupported keyword argument "Z0"
  DiffEqNoiseProcess.NoiseProcess{T,T2,T3,ZType,F,F2,inplace,S1,S2,RSWM}{T}(::Any) at sysimg.jl:53 got unsupported keyword argument "Z0"

 in #boser#13(::Symbol, ::Function, ::Int64) at ./In[9]:13
 in boser(::Int64) at ./In[9]:3
```

If I try to make `W0` real `W0=randn(6)` I get the same error (should `W0` should be the same type (real or complex) as the noise that is to be created?)

**Comment by ChrisRackauckas** [comment]
`my_noise= NoiseProcess(0,ones(a0),nothing,dist,bridge)`

**Comment by AshtonSBradley** [comment]
```julia
my_noise= NoiseProcess(0,ones(a0),nothing,dist,bridge)
prob = SDEProblem(f,g,a0,tspan,noise=my_noise)

monte_prob = MonteCarloProblem(prob::SDEProblem;
                  output_func = (sol,i) -> sol,
                  prob_func= (prob,i)->prob)

return solve(monte_prob,alg,saveat=t,num_monte=Ntraj,parallel_type=parallel_type)

compile...
MethodError: no method matching isless(::Complex{Float64}, ::Float64)
Closest candidates are:
  isless(::Float64, ::Float64) at float.jl:283
  isless(::AbstractFloat, ::AbstractFloat) at operators.jl:40
  isless(::ForwardDiff.Dual{N,T<:Real}, ::AbstractFloat) at /Users/abradley/.julia/v0.5/ForwardDiff/src/dual.jl:160
```

Or, if I put back the `dt`

```Julia
solve(monte_prob,alg,dt=dt,saveat=t,num_monte=Ntraj,parallel_type=parallel_type)

InexactError()

 in calculate_step!(::DiffEqNoiseProcess.NoiseProcess{Int64,Array{Complex{Float64},1},Void,Void,#dist,#bridge,true,DataStructures.Stack{Tuple{Int64,Array{Complex{Float64},1},Void}},ResettableStacks.ResettableStack{Tuple{Int64,Array{Complex{Float64},1},Void}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64}}, ::Float64) at /Users/abradley/.julia/v0.5/DiffEqNoiseProcess/src/interface.jl:157
```

```julia
- DifferentialEquations         2.1.0              master

Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by ChrisRackauckas** [comment]
Make sure there's a runnable example with each error. Makes it easier.

>Or, if I put back the dt

`Pkg.update()`. The hotfix for that `dt` bug with complex numbers is already in.

>InexactError()

This is because "time" in the noise process is an integer. Change

```julia
my_noise= NoiseProcess(0,ones(a0),nothing,dist,bridge)
```

to

```julia
my_noise= NoiseProcess(0.0,ones(a0),nothing,dist,bridge)
```

Notice the difference is that `t0=0.0` is a Float64. The inexact error was trying to turn time into an Int. 

Two other things to mention. First of all, notice that

```julia
monte_prob = MonteCarloProblem(prob::SDEProblem;
                  output_func = (sol,i) -> sol,
                  prob_func= (prob,i)->prob)
```

is just using the defaults. You can just make this

```julia
monte_prob = MonteCarloProblem(prob)
```

In the documentation, it shows the default values for the keyword arguments and the dispatches, but there's no need to copy that. Also, if you're using `SRA1`, you need to have Z0 defined:

```julia
my_noise= NoiseProcess(0.0,ones(a0),ones(a0),dist,bridge)
```

I'm not quite sure how to document that. I think it might be easier just to allow the user to pass the algorithm that they plan on using, but getting that dispatch structure in place will be weird.

**Comment by AshtonSBradley** [comment]
Ah! thanks so much for this!!

**Comment by ChrisRackauckas** [comment]
Is this complete?
