### ISSUE TITLE
Error and warn for interface incompatibilities

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#166]
Something that came up in https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/159 is that we should warn users when stiff methods are not able to use `tgrad` and `jac`. This means that, if these dispatches are defined, we should throw a warning when `verbose=true` in:

- [x] Sundials
- [x] DASKR
- [x] LSODA
- [x] ODE

**Comment by ChrisRackauckas** [comment]
`save_idxs`, when not nothing, should error on:

- [ ] Sundials
- [ ] DASKR
- [ ] LSODA
- [ ] ODEInterfaceDiffEq

**Comment by ChrisRackauckas** [comment]
Adavanced stepsize control should warn on the following:

- [ ] Sundials
- [ ] DASKR
- [ ] LSODA
- [ ] ODE

**Comment by ChrisRackauckas** [comment]
@ScottPJones most of them should do something like this. For example, ODE should have `save_idxs=nothing` added to the keyword args for its common interface (common.jl), and then at the top it should check:

```julia
if save_idxs != nothing && verbose == true
  warn("The save_idxs argument is ignored by this solver. Please see http://docs.juliadiffeq.org/latest/basics/compatibility_chart.html")
end
```

The adaptive stepsize control options are all of the ones here:

http://docs.juliadiffeq.org/latest/basics/common_solver_opts.html#Advanced-Adaptive-Stepsize-Control-1

And the `tgrad` + `jac`, they need to use the traits: `has_jac(prob.f)` and `has_tgrad(f)`.

**Comment by ChrisRackauckas** [comment]
The `tgrad` and `jac` stuff should check `typeof(prob.f) <: AbstractParameterizedFunction` and not throw a warning in that case. Otherwise using the macros would be super noisy in most algorithms

**Comment by ScottPJones** [comment]
The part about warning when `dense == true` I don't understand for `ODE`, because that keyword by default *is* true, so why would it warn?

**Comment by ChrisRackauckas** [comment]
Since it should be false. At one point a wrapper had interpolations for ODE.jl, but that's no longer the case (long explanation).

**Comment by ScottPJones** [comment]
So, I also need to change the default for dense for all of those to false?

**Comment by ChrisRackauckas** [comment]
It should only be accidentally true on ODE I believe?

**Comment by ScottPJones** [comment]
Currently, it's always true, unless you explicitly pass it as false

**Comment by ChrisRackauckas** [comment]
For Sundials, DASKR, LSODA?

**Comment by ScottPJones** [comment]
I'm starting with ODE.jl first, will let you review it to make sure my techniques are good and you approve of them, before moving on to the others (which hopefully will be trivial, after doing the first one)

**Comment by ChrisRackauckas** [comment]
No love ODEInterfaceDiffEq?

**Comment by ScottPJones** [comment]
Oh, yeah!  Next up!

**Comment by ChrisRackauckas** [comment]
For the first part:

```julia
if !(typeof(prob.f) <: AbstractParameterizedFunction) && has_jac(f) && typeof(alg) <: ...
  warn("Explicit Jacobian given to this stiff solver is ignored. See http://docs.juliadiffeq.org/latest/basics/compatibility_chart.html"
end
```

For ODE.jl, it should only check `ode23s`. For Sundials, only `CVODE_BDF` in the first method, and then it doesn't need an alg check in the second. DASKR doesn't need an alg check. Neither does LSODA.

**Comment by ScottPJones** [comment]
I can tackle it, but I think it should be in another set of PRs.
When you say that it doesn't need an alg check, do you mean it still needs to check `prob.f` and `has_jac(prob.f)`, but not the `typeof(alg) <: ...` part?

**Comment by ChrisRackauckas** [comment]
Example that I just did in ODEInterfaceDiffEq:

```julia
if !(typeof(prob.f) <: AbstractParameterizedFunction) && has_tgrad(prob.f) && !(typeof(alg) <: Union{dopri5,dop853,odex})
    warn("Explicit t-gradient given to this stiff solver is ignored. See http://docs.juliadiffeq.org/latest/basics/compatibility_chart.html")
end
```

**Comment by ChrisRackauckas** [comment]
>When you say that it doesn't need an alg check, do you mean it still needs to check prob.f and has_jac(prob.f), but not the typeof(alg) <: ... part?

Yes

**Comment by ChrisRackauckas** [comment]
Oh we missed something `dense` should default to true, unless `save_everystep` is false. This is

```julia
dense = save_everystep
```

should be the setting in the keyword arguments. This needs to be updated.

**Comment by ScottPJones** [comment]
Can this issue be closed now? (fixed by various PRs in the solvers)

**Comment by ChrisRackauckas** [comment]
Nice work!
