### ISSUE TITLE
Too long steps in solver?

### ISSUE THREAD

**Issue by robertdj** [JuliaDiffEq/DifferentialEquations.jl#167]
Consider a system of ODE's where one solution component should be piecewise linear oscilations and the other is an exponential function:
```
using DifferentialEquations
using ODEInterfaceDiffEq

function foo(t,u,du)
    # Without this condition the solution is constant
    if t < 0.1
        du[1] = -1
    end

    if u[1] > 1
        du[1] = -1
    elseif u[1] < -1
        du[1] = 1
    end
    du[2] = -u[2]
end

prob = ODEProblem(foo, ones(2), (0.0, 5.0))
```
A correct looking solution from `sol = solve(prob, Rosenbrock23())`:
![rosenbrock](https://cloud.githubusercontent.com/assets/5703657/25894680/10ff5c98-357d-11e7-9875-424d2ab59602.png)

A solution from `sol = solve(prob, radau())`:
![radau](https://cloud.githubusercontent.com/assets/5703657/25894707/2e2c602c-357d-11e7-86ee-4237ccb33c35.png)

If instead we have `du[2] = 0` in `foo` (or something similar where *both* solutions have long, flat streaks), `Rosenbrock` also fails:
![rosenbrock2](https://cloud.githubusercontent.com/assets/5703657/25894822/bb4cad9a-357d-11e7-8af5-faf00df3fa5f.png)

The only explanation I can think of for the premature change of sign in `foo` is that the multistep nature of `Rosenbrock` evaluates `foo` in regions of different signs. 

Is it possible to get around this? E.g. by changing sign only in the "final" step?

**Comment by ChrisRackauckas** [comment]
>Is it possible to get around this? E.g. by changing sign only in the "final" step?

The bigger issue is that this equation doesn't have a solution. I don't mean a numerical solution, I mean the solution doesn't actually exist. The solution depends on the "stepsize", but as dt-->0, the changes oscillate infinitely often and `du` converges to both 1 and -1. So this cannot have a solution, let alone a unique solution.

Or another way to think of it: if you fixed the stepsize, changing `dt` changes the equation. That cannot have a unique solution, and it's not clear what that should/would converge to (actually, it seems like it would converge to the constant solution).

But I think the real question is, what are you trying to do? If you're trying to flip the sign of `du` every `1` time units, you should do:

```
using DifferentialEquations
function foo(t,u,du)
    # Without this condition the solution is constant
    if t < 0.1
        du[1] = -1
    end

    if iseven(Int(floor(t)))
        du[1] = -1
    else
        du[1] = 1
    end
    du[2] = -u[2]
end

prob = ODEProblem(foo, ones(2), (0.0, 5.0))
sol = solve(prob,Rosenbrock23())

using Plots; plot(sol)
```

Adaptive timestepping seems to handle the discontinuity just fine:

![newplot 32](https://cloud.githubusercontent.com/assets/1814174/25895893/b1d7a658-3536-11e7-8d32-c94221cade3b.png)

Or if you're looking to do something more detailed, like bouncing a ball, you should use the event handling:

http://docs.juliadiffeq.org/latest/features/callback_functions.html

**Comment by robertdj** [comment]
I'm looking at a situation like bouncing a ball. Thanks!
