### ISSUE TITLE
Follow-up on possible bug report: Stepping past tstop

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#172]
@elevien I remember you reported that sometimes you'd have an error with stepping past the end time point? Is that still a thing? Or was it due to bad versioning awhile back?

**Comment by elevien** [comment]
Yes: 

`ERROR: LoadError: Something went wrong. Integrator stepped past tstops but the algorithm was dtchangeable. Please report this error.
 in handle_tstop! at /Users/E/.julia/v0.5/OrdinaryDiffEq/src/integrators/integrator_utils.jl:309 [inlined]
 in solve!(...) at /Users/E/.julia/v0.5/OrdinaryDiffEq/src/solve.jl:314`

So far I'm only able to reproduce this error on one model. Also, the model I'm using is constructed from a custom version of `build_split_jump` I've written to couple `VariableRateJump`s. Basically, I need to play around to see if this issue comes up under normal circumstances.

**Comment by ChrisRackauckas** [comment]
I see. One way that I found this comes up is if you add a `tstop` that's not actually in-front of the current time. You know what, I'll add an error message in that case. This means that I need to make sure the docs tell people to use `add_tstops!` instead of `push!(integrator.opts.tstops,t)` so that way the error catching can work.

**Comment by ChrisRackauckas** [comment]
OrdinaryDiffEq and StochasticDiffEq masters have that error check now. I'd give that a try. Without any more information, that's my best guess.

**Comment by elevien** [comment]
Hmmm, with OrdinaryDiffEq and StochasticDiffEq on master I still get the error above.

**Comment by ChrisRackauckas** [comment]
oh okay. But only on the experimental code? If you can share it, or an MWE from it, I can try to track this down. But I can't find a way to get this error.

**Comment by elevien** [comment]
Yeah, only on the experimental code. I'll build the model without using `build_split_jump` and then start getting rid of jumps to see how much is needed to get this.

**Comment by elevien** [comment]
I'm getting this error again while solving the following model. 

```rate = (t,u) -> 10.*(1-u[3])
affect! = (integrator) -> integrator.u[3] +=1
jump1 = ConstantRateJump(rate,affect!)

rate = (t,u) -> 10.*u[3]
affect! = (integrator) -> integrator.u[3] -=1
jump2 = ConstantRateJump(rate,affect!)

f = function (t,u,du)
  du[1] = u[3]*(u[2]-u[1])-(u[1]-u[1]^2)
  du[2] = u[3]*(u[1]-u[2])
end

tspan = (0.0,50.0)
de_prob = ODEProblem(f,[0.6,0.6,1],tspan)
jump_prob = JumpProblem(de_prob,Direct(),jump1,jump2)
```

This was solved using `Tsit5()` with `dt = 1//2^4`.

**Comment by elevien** [comment]
I should mention this happened while performing Monte Carlo simulations, so you might have to solve this a couple hundred times before having any issues.

**Comment by ChrisRackauckas** [comment]
```julia
using OrdinaryDiffEq, DiffEqJump, DiffEqMonteCarlo

rate = (t,u) -> 10.*u[3]
affect! = (integrator) -> integrator.u[3] +=1
jump1 = ConstantRateJump(rate,affect!)

affect! = (integrator) -> integrator.u[3] -=1
jump2 = ConstantRateJump(rate,affect!)

f = function (t,u,du)
  du[1] = u[3]*(u[2]-u[1])-(u[1]-u[1]^2)
  du[2] = u[3]*(u[1]-u[2])
end

tspan = (0.0,50.0)
de_prob = ODEProblem(f,[0.6,0.6,1],tspan)
jump_prob = JumpProblem(de_prob,Direct(),jump1,jump2)
monte_prob = MonteCarloProblem(jump_prob)

sol = solve(monte_prob,Tsit5(),num_monte=Int(1e4))

for i in 1:Int(1e4)
  @show i
  srand(i)
  sol = solve(jump_prob,Tsit5())
end
```

That generates the MWE:

```julia
srand(2040)
sol = solve(jump_prob,Tsit5())
```

**Comment by ChrisRackauckas** [comment]
```julia
srand(2040)
integrator = init(jump_prob,Tsit5())
step!(integrator)
step!(integrator)
integrator.t

integrator.opts.tstops.valtree[1]
OrdinaryDiffEq.loopheader!(integrator)
integrator.t + integrator.dt
OrdinaryDiffEq.perform_step!(integrator,integrator.cache)
OrdinaryDiffEq.loopfooter!(integrator)
integrator.t
OrdinaryDiffEq.loopheader!(integrator)
OrdinaryDiffEq.top(integrator.opts.tstops) - integrator.t == integrator.dt
integrator.t + integrator.dt == OrdinaryDiffEq.top(integrator.opts.tstops) # false
integrator.t + integrator.dt - OrdinaryDiffEq.top(integrator.opts.tstops) # 2.7755575615628914e-17
```

Floating point error when setting `dt` so that it would exactly hit the next `tstop`. This can be fixed.

**Comment by ChrisRackauckas** [comment]
When a step is accepted, it now fixes floating point errors when it's supposed to exactly hit `tstop`

```julia
    if integrator.accept_step # Accept
      integrator.tprev = integrator.t
      if typeof(integrator.t)<:AbstractFloat
        tstop = top(integrator.opts.tstops)
        abs(ttmp - tstop) < 10eps(integrator.t) ? (integrator.t = tstop) : (integrator.t = ttmp)
      else
        integrator.t = ttmp
      end
```

and instead of using `integrator.tprev + integrator.dt` in checking the callback condition, it now does

```julia
if callback.condition(integrator.t,integrator.u,integrator)
```

so this fixes the case where we set `dt = tstop - t`, but then `t + dt != tstop`. It's rare, but I guess it happens enough that a Monte Carlo simulation of a jump problem hits it. Thanks for filing the issue! Never would've found this otherwise.

**Comment by ChrisRackauckas** [comment]
@huckl3b3rry87 this should actually fix your case too 👍

**Comment by ChrisRackauckas** [comment]
Both the ODE and SDE solvers got the same treatment (and thus by extension the DDE and DAE solvers)

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/9025565498f0b8259b50ce95c42e1e76518454ca

https://github.com/JuliaDiffEq/StochasticDiffEq.jl/commit/bd0516b2db2a189267bdf1e0ab0cb6603e8486fe

Thanks for the MWE.

**Comment by ChrisRackauckas** [comment]
Hotfix being released now.

**Comment by Farnazmdi** [comment]
Hi @ChrisRackauckas, I get the same error when doing optimization for a DDE problem. Could I send my code to you via email? It is a part of my project.

**Comment by ChrisRackauckas** [comment]
Decrease your tolerances a bit and see if you still get the error.

**Comment by Farnazmdi** [comment]
If you mean `abstol` and `reltol`, it still has the error? @ChrisRackauckas 
This is the line that errors
`bboptimize(cost_fcn; SearchRange=bound, reltol=1e-15, abstol=1e-15, MaxSteps=num_steps, Method=:adaptive_de_rand_1_bin_radiuslimited)`

**Comment by ChrisRackauckas** [comment]
I'd need to see the code that's causing that. Feel free to email it to me, but I may not get to it for a bit.

**Comment by Farnazmdi** [comment]
I sent an email to the email address that is one your Github account. Thank you very much, @ChrisRackauckas

**Comment by Farnazmdi** [comment]
Hi @ChrisRackauckas 
Thank you for your time in advance,

[This ](https://github.com/meyer-lab/DrugResponseModel.jl/blob/dde/src/dde-constant.jl)the link to the .jl file containing the functions, and [this ](https://github.com/meyer-lab/DrugResponseModel.jl/blob/dde/src/DDEmodel.ipynb)is the notebook where I call them. I tested all the functions from the problem to the cost function, they work fine, but when it comes to the `bboptimize` it shows this error.

Here I have 2 sets of time-series data (g1 and g2) for 8 trials, which I model with a DDE. Here I want to have just one constant delay term for all 8 trials of g1, and another constant delay term for g2. I want to estimate all 8 trials all at once and this is where I get the error.
If I do it one by one it works fine.

I really appreciate your help.
Best,

**Comment by ChrisRackauckas** [comment]
Hey,
  It doesn't look like those links work. Could you open a new issue with the new links?

**Comment by Farnazmdi** [comment]
Hey,
Sorry, this should work, this is the .jl file with the functions: [link](https://github.com/meyer-lab/DrugResponseModel.jl/blob/master/src/dde-constant.jl)
 and this one is the [notebook](https://github.com/meyer-lab/DrugResponseModel.jl/blob/master/src/DDEmodel.ipynb)

Thank you,

**Comment by Farnazmdi** [comment]
Sorry, I will open a new issue.
