### ISSUE TITLE
Sugestion: optional ilimited iteration.

### ISSUE THREAD

**Issue by jordaorodolfo** [JuliaDiffEq/DifferentialEquations.jl#180]
Good day! Forgive me if I forgot to mention something, mentioned too much, or just posted this as an issue when it shouldn't be: it is my first issue ever in github. 

Anyway, Marvelous package! Congrats to all those involved! There's just a tiny problem for me that may prove a show stopper: the forced iteration limit.
I can understand why always having one limit is important to solve DEs in the greater majority of the use cases; but i argue that, especially with the integrator interface, this limit could become optional.

My use case is an exmaple: I want to use the package to simulate a virtual robot environment where I know exactly their equations of motion and so forth; Even if I know how much time i Want to simulate this environment by these equations, sooner or later I'm going to hit the iteration limit, and I can prove it that the equations are convergent and bounded so any means to stop them from running are unnecessary.
And yes, I know there are specially crafted software suites for these kind of simulations (like gazebo), but some parts of my project are already in julia, and being able to use it seamlessly with the simulation would prove very useful, apart from the knowledge of exactly what's going on without having to look at the documentation or source code of a behemot environment (considering they're available, that is).

I Tried maxiters=Inf, I tried maxiters=-1 (some older C libraries used to have negative values for "don't case") and none of them worked; hence my issue here. Maybe I missed a part of the documentation while looking, if that's it, I'm sorry!

Best regards

**Comment by ChrisRackauckas** [comment]
Huh. I thought Inf would work. What solver algorithm did you try? This is definitely supposed to be part of the options and is just a bug

**Comment by jordaorodolfo** [comment]
Hi there, @ChrisRackauckas!

I tried the BS3 algorithm since the equations are very simple (Basic tricycle from robot motion, 3 variables). Calling,

sol = solve(prob, BS3(), maxiters=Inf)

where prob goes in t \in [0.0, 40.0]. This always gives me InexactError(). Did I miss something, then? I would share the code of the equation if you want it; but it needs other 3-4 methods that are in the same file (to compute the control as this is a control problem), so the whole thing would span a little more than 80 lines, I think. I guess it would be best to send it to you other way, right?

**Comment by ChrisRackauckas** [comment]
That error is from type conversions. Did you specify your initial condition and timespan using floating point numbers?

**Comment by jordaorodolfo** [comment]
Yup. I did. My first mistake was to use integer instead of floats.

It looks like:
initial = [0.0, 0.0, pi*0.5] 
Tspan = (0.0, 40.0)

Now, couldn't the type error be happening at the maxiter check? I did not look at the code of DE.jl so I have no idea.

**Comment by jordaorodolfo** [comment]
Also, if maxiters is an integer, it solves just fine.

**Comment by ChrisRackauckas** [comment]
Oh yeah, Inf is a float. That has an easy fix.

**Comment by jordaorodolfo** [comment]
Nice!! How do I access the fixed one later?

**Comment by ChrisRackauckas** [comment]
Sorry this is taking a bit: JuliaCon madness. I'll fix this up later today and add it to a release. `Pkg.update()` will then solve the problem. I'll close the issue when it's released.

**Comment by jordaorodolfo** [comment]
Thanks, Chris! Really apreciate it.

**Comment by ChrisRackauckas** [comment]
When this PR is merged, the newest version will be released which fixes this:

https://github.com/JuliaLang/METADATA.jl/pull/9971

The same fix for StochasticDiffEq is on its master. The other solvers (like Sundials.jl and ODEInterface.jl) will only have this if their respective solvers allow it, which I am not certain. But since that's not changeable anyways, I'd considered it ecosystem-wide fixed unless there are any other remarks. Just Pkg.update() after that merges and you should be good.
