### ISSUE TITLE
Performance macro usage tracking

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#189]
Right now `@inbounds` and `@muladd` are used in the loops. `@fastmath` is not used because of https://github.com/JuliaLang/julia/issues/22275, but it seems like because of https://github.com/JuliaLang/julia/issues/18654 finished we can in the near future look at replacing `@muladd` usage by `@fastmath` (of course after the splat bugs are fixed).

The master issue for "long arithmetic line issues" is the following: https://github.com/JuliaLang/julia/issues/22370 . It's the main blocker/constraint on design right now. This all could be fixed by https://github.com/JuliaLang/julia/pull/22545?

**Comment by Armavica** [comment]
I have always been told to never enable `-ffast-math` in scientific programming, so I am a little worried about its introduction in this library. Not only this will probably [change all the results](https://stackoverflow.com/a/22135559) in a [compiler-dependent way](http://programerror.com/2009/09/when-gccs-ffast-math-isnt/), but it will make programs [much more difficult to debug](http://pointclouds.org/news/2011/08/29/ffast-math/) and we will also lose `NaN` propagation and error checking (like division by zero). Or is Julia's `@fastmath` safer than gcc's or clang's?

**Comment by ChrisRackauckas** [comment]
Yes, it is less safe loses `NaN` propagation. There is a tradeoff. Maybe there is a good design that allows this to be a user's choice, like some kind of environment variable. We already have `@tight_loop_macros` setup so that way performance macros can be instantly applied throughout `*DiffEq` packages, so maybe we can use that infrastructure to make it user-overridable.

**Comment by ChrisRackauckas** [comment]
Yes, it is less safe loses `NaN` propagation. There is a tradeoff. Maybe there is a good design that allows this to be a user's choice, like some kind of environment variable. We already have `@tight_loop_macros` setup so that way performance macros can be instantly applied throughout `*DiffEq` packages, so maybe we can use that infrastructure to make it user-overridable.

**Comment by ChrisRackauckas** [comment]
I was assured that Pkg3 would have a way to set "package options", so `@tight_loop_macros` will be used to allow users the choice of applying `@fastmath` and other things (`@threads`) globally to all inner loops.

**Comment by ChrisRackauckas** [comment]
Everything is being changed to broadcast, so this can be controlled by the user in the array type.
