### ISSUE TITLE
no method matching for interp_summary 

### ISSUE THREAD

**Issue by onoderat** [JuliaDiffEq/DifferentialEquations.jl#191]
Here is a bug I ran into when I ran the code from the tutorial, 

using DifferentialEquations
f(t,u) = 1.01*u
u0=1/2
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)

MethodError: no method matching interp_summary(::OrdinaryDiffEq.InterpolationData{#f,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}})
Closest candidates are:
  interp_summary(::Void) at /Users/tatsuhiroonodera/.julia/v0.6/DiffEqBase/src/interpolation.jl:15
  interp_summary(::DiffEqBase.HermiteInterpolation) at /Users/tatsuhiroonodera/.julia/v0.6/DiffEqBase/src/interpolation.jl:13
  interp_summary(::DiffEqBase.LinearInterpolation) at /Users/tatsuhiroonodera/.julia/v0.6/DiffEqBase/src/interpolation.jl:14
  ...

Stacktrace:
 [1] show(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("text/plain")}, ::DiffEqBase.ODESolution{Float64,1,Array{Float64,1},Void,Void,Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,#f,Void,UniformScaling{Int64}},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{#f,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}) at /Users/tatsuhiroonodera/.julia/v0.6/DiffEqBase/src/solutions/solution_interface.jl:35
 [2] limitstringmime(::MIME{Symbol("text/plain")}, ::DiffEqBase.ODESolution{Float64,1,Array{Float64,1},Void,Void,Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,#f,Void,UniformScaling{Int64}},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{#f,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}) at /Users/tatsuhiroonodera/.julia/v0.6/IJulia/src/inline.jl:25
 [3] display_dict(::DiffEqBase.ODESolution{Float64,1,Array{Float64,1},Void,Void,Array{Float64,1},Array{Array{Float64,1},1},DiffEqBase.ODEProblem{Float64,Float64,false,#f,Void,UniformScaling{Int64}},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{#f,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}) at /Users/tatsuhiroonodera/.julia/v0.6/IJulia/src/execute_request.jl:27
 [4] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/tatsuhiroonodera/.julia/v0.6/IJulia/src/execute_request.jl:188
 [5] eventloop(::ZMQ.Socket) at /Users/tatsuhiroonodera/.julia/v0.6/IJulia/src/eventloop.jl:8
 [6] (::IJulia.##11#14)() at ./task.jl:335

---------

I think the sol object itself is ok since it allows me to plot the solution as well as to evaluate its interpolated result at different times. 

Thanks for writing this package. I am trying to simulate quantum systems described by sde and think the package will be really helpful.

**Comment by ChrisRackauckas** [comment]
What's your `Pkg.status()`? That might be from an old version of DiffEqBase.

**Comment by onoderat** [comment]
Thanks for your reply. The Pkg.status is below. Please note that I pinned some packages, is that what is causing the issue? 

Pkg.status()
19 required packages:
 - Atom                          0.6.1
 - Colors                        0.8.0
 - DSP                           0.3.2
 - DifferentialEquations         2.2.1
 - Distributions                 0.14.2
 - FFTW                          0.0.2
 - GLPKMathProgInterface         0.3.4
 - GR                            0.22.0
 - IJulia                        1.5.1
 - Interpolations                0.6.2
 - IterTools                     0.1.0
 - JLD                           0.6.11
 - JuMP                          0.17.1
 - LsqFit                        0.3.0
 - MAT                           0.3.2
 - Plots                         0.12.1
 - PyCall                        1.14.0
 - PyPlot                        2.3.2
 - UnicodePlots                  0.2.4
113 additional packages:
 - AbstractFFTs                  0.1.0              pinned.f9772b0a.tmp
 - AlgebraicDiffEq               0.1.0
 - AxisAlgorithms                0.1.6
 - BinDeps                       0.7.0
 - Blink                         0.5.3
 - Blosc                         0.2.1
 - BufferedStreams               0.3.3
 - Calculus                      0.2.2
 - ChunkedArrays                 0.1.1
 - CodeTools                     0.4.6
 - Codecs                        0.3.0
 - ColorTypes                    0.6.0
 - Combinatorics                 0.4.1
 - Compat                        0.26.0             pinned.2436d35c.tmp
 - Conda                         0.5.3
 - Contour                       0.3.0
 - DataStructures                0.6.1
 - DelayDiffEq                   0.4.0
 - DiffBase                      0.2.0
 - DiffEqBase                    1.14.1             4843464f (dirty)
 - DiffEqBiological              0.2.0
 - DiffEqCallbacks               0.1.1
 - DiffEqDevTools                0.9.3
 - DiffEqFinancial               0.3.0
 - DiffEqJump                    0.5.0
 - DiffEqMonteCarlo              0.8.0
 - DiffEqNoiseProcess            0.3.2
 - DiffEqPDEBase                 0.3.3
 - DiffEqParamEstim              0.5.0
 - DiffEqSensitivity             0.3.0
 - DiffEqUncertainty             0.0.1
 - DimensionalPlotRecipes        0.0.2
 - Distances                     0.4.1
 - DistributedArrays             0.4.0
 - DualNumbers                   0.3.0
 - EllipsisNotation              0.2.2
 - FileIO                        0.5.1
 - FiniteElementDiffEq           0.4.0
 - FixedPointNumbers             0.3.9
 - ForwardDiff                   0.4.2
 - GLPK                          0.4.2
 - GenericSVD                    0.1.0
 - HDF5                          0.8.2
 - Hiccup                        0.1.1
 - Homebrew                      0.5.8
 - HttpCommon                    0.2.7
 - HttpParser                    0.3.0
 - HttpServer                    0.2.0
 - IterativeSolvers              0.3.1
 - Iterators                     0.3.1
 - JSON                          0.13.0
 - Juno                          0.3.0
 - LNR                           0.0.2
 - LaTeXStrings                  0.2.1
 - Lazy                          0.11.7
 - LearnBase                     0.1.6
 - LegacyStrings                 0.2.2
 - Libz                          0.2.4
 - LineSearches                  0.1.5
 - LinearMaps                    1.0.0
 - LossFunctions                 0.1.0
 - MacroTools                    0.3.7
 - MathProgBase                  0.6.4
 - MbedTLS                       0.4.5
 - Measures                      0.1.0
 - Media                         0.3.0
 - MultiScaleArrays              0.4.0
 - Mustache                      0.1.4
 - Mux                           0.2.3
 - NLSolversBase                 2.1.3
 - NLsolve                       0.9.1
 - NaNMath                       0.2.6
 - Optim                         0.7.8
 - OptimBase                     0.1.0
 - OrdinaryDiffEq                2.4.0
 - PDMats                        0.7.0
 - ParameterizedFunctions        2.1.2
 - Parameters                    0.7.2
 - PlotThemes                    0.1.4
 - PlotUtils                     0.4.3
 - Polynomials                   0.1.5
 - PositiveFactorizations        0.0.4
 - Primes                        0.1.3
 - QuadGK                        0.1.2
 - RandomNumbers                 0.1.0
 - Ratios                        0.1.0
 - RecipesBase                   0.2.0
 - RecursiveArrayTools           0.11.2
 - Reexport                      0.0.3
 - Requires                      0.4.3
 - ResettableStacks              0.1.0
 - ReverseDiffSparse             0.7.3
 - Rmath                         0.1.7
 - Roots                         0.4.0
 - SHA                           0.5.0
 - ShowItLikeYouBuildIt          0.0.1
 - Showoff                       0.1.1
 - SimpleTraits                  0.5.0
 - SpecialFunctions              0.2.0
 - StaticArrays                  0.6.1
 - StatsBase                     0.18.0
 - StatsFuns                     0.5.0
 - SteadyStateDiffEq             0.1.0
 - StochasticDiffEq              2.2.1
 - SugarBLAS                     0.0.4
 - Sundials                      0.13.0
 - SymEngine                     0.2.0
 - Tokenize                      0.1.8
 - URIParser                     0.1.8
 - VectorizedRoutines            0.0.2
 - WebSockets                    0.2.3
 - WoodburyMatrices              0.2.2
 - ZMQ                           0.4.3

**Comment by ChrisRackauckas** [comment]
OrdinaryDiffEq.jl is at v2.11.3, but you're keeping it back at v2.4.0. I believe that's because you're on ForwardDiff v0.4.2 and OrdinaryDiffEq v2.5.0 and onwards requires ForwardDiff v0.5.0. There might be some package which is keeping that back, because that was a big breaking change (ForwardDiff v0.5.0 introduces the tagging system, which ReverseDiff doesn't even support yet!), though it's not readily apparent to me which package is keeping it back.

That said it is just an error with printing, so there's two things you can do. One is you can roll back DiffEqBase.jl a little bit to before it added the pretty printing. There must be a version bound missing there that let it go forward without OrdinaryDiffEq.jl. Or just copy the printing method from here:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/45cde9291c1a7c4a15b474d0ff42435e53b3d9be/src/interp_func.jl#L24

and it'll be fine. Either way, it's a versioning issue and not an issue with the current code, so I'm going to close this. But if you need any more help making the version you're using work just let me know.
