### ISSUE TITLE
UndefVarError: DiffEqMonteCarlo not defined

### ISSUE THREAD

**Issue by shankyjain** [JuliaDiffEq/DifferentialEquations.jl#195]
Hi,
     I'm new to Julia and i was trying to run an example code from DifferentialEquations.jl and got an error.
 I found similar issue reported in [https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/190](url) but in my case though i run the correct code as suggested i have the error

code ran
```julia
addprocs()
using DifferentialEquations
prob = ODEProblem((t,u)->1.01u,0.5,(0.0,1.0))
prob_func = function (prob,i)
  prob.u0 = rand()*prob.u0
  prob
end
monte_prob = MonteCarloProblem(prob,prob_func=prob_func)
sim = solve(monte_prob,Tsit5(),num_monte=100)
using Plots
plotly()
plot(sim,linealpha=0.4)
```

I get error. Julia version is Julia 0.6.0 and i'm running it on my local windows machine
```julia
On worker 2:
UndefVarError: DiffEqMonteCarlo not defined
deserialize_module at .\serialize.jl:754
handle_deserialize at .\serialize.jl:695
deserialize at .\serialize.jl:634
deserialize_datatype at .\serialize.jl:968
handle_deserialize at .\serialize.jl:674
deserialize at .\serialize.jl:634
handle_deserialize at .\serialize.jl:681
deserialize at .\serialize.jl:634
ntuple at .\tuple.jl:108
handle_deserialize at .\serialize.jl:664
deserialize at .\serialize.jl:634
ntuple at .\tuple.jl:108
handle_deserialize at .\serialize.jl:664
deserialize_msg at .\distributed\messages.jl:98
message_handler_loop at .\distributed\process_messages.jl:161
process_tcp_streams at .\distributed\process_messages.jl:118
#99 at .\event.jl:73
```

  i also ran a simple code to check if addprocs() works and it does.
```julia
addprocs(3)
S = SharedArray(Int, (3,4), init = S -> S[Base.localindexes(S)] = myid())
```

ps: my main interest in using this package/language is for running monte-carlo for stiff/non-stiff ODE systems with parameters defining the system drawn from normal distributions. This is for studying electronic circuit response with variation. I have been using Matlab ODE45/ODE15s to solve but as my interest is in solving and understanding monte-carlo variation i want a better solution in computation time than for loop in Matlab. My understanding from the last few days knowing Julia and DifferentialEquations package is i can run monte-carlo sims of my interest and get computation time similar to a vectorized code instead of using for loop in Matlab. Note, computation time for solving the ODE is few secs but i want to run it for 1000 samples to get a 3 sigma distribution of output.  Please correct me if i'm wrong.

**Comment by ChrisRackauckas** [comment]
Hi,
  The issue here is that adding processes before `using` makes it so that way the package is only added to the main worker. That's why it's saying `UndefVarError: DiffEqMonteCarlo not defined`. The solution is to use `@everywhere`:

```julia
addprocs()
@everywhere using DifferentialEquations
```

You need to make sure that the package is precompiled on a single worker first though (it's a v0.6 issue that I think is fixed on Julia's master, so it won't be necessary by 1.0 but for now it's required)

>My understanding from the last few days knowing Julia and DifferentialEquations package is i can run monte-carlo sims of my interest and get computation time similar to a vectorized code instead of using for loop in Matlab. Note, computation time for solving the ODE is few secs but i want to run it for 1000 samples to get a 3 sigma distribution of output. Please correct me if i'm wrong.

Yup, that's what it's for. At that size though, you may want to use the multithreading. If you setup your Julia installation with threads enabled:

https://docs.julialang.org/en/release-0.6/manual/parallel-computing/#Multi-Threading-(Experimental)-1

then, instead of doing the `addprocs()` route, adding `parallel_type=:threads` will make it multithread. This will be faster if you're using a single computer/node, whereas the `addprocs()` parallelism lets you use multiple computers at once.

**Comment by ChrisRackauckas** [comment]
Also, it should be

```julia
prob_func = function (prob,i,repeat)
  prob.u0 = rand()*prob.u0
  prob
end
```

**Comment by shankyjain** [comment]
I did the changes and have new error

```Julia
WARNING: Method definition WARNING: Method definition countcount(() in module Iterators) in module Iterators at deprecated.jl:56 overwritten in module IterTools at deprecated.jl:56.
WARNING: Method definition count(Number) in module Iterators at deprecated.jl:56WARNING: Method definition WARNING: Method definition  at deprecated.jl:56 overwritten in module IterToolscount overwrittencount at deprecated.jl:56.
WARNING: Method definition count(Number) in module Iterators at deprecated.jl:56 overwritten( in module IterTools) at deprecated.jl:56() in module Iterators at deprecated.jl:56 overwritten in module IterTools at deprecated.jl:56.
WARNING: Method definition count(Number) in module Iterators at deprecated.jl:56 overwritten in module IterTools at deprecated.jl:56.
WARNING: Method definition count(Number, Number) in module Iterators at deprecated.jl:56 overwritten in module IterTools at deprecated.jl:56.
 in module IterTools in module Iterators at deprecated.jl:56 overwritten in module IterTools.
WARNING: Method definition  at deprecated.jl:56.
 at deprecated.jl:56.
WARNING: Method definition count(NumberWARNING: Method definition , Number) in module Iterators at deprecated.jl:56 overwritten in module IterTools at deprecated.jl:56.
count(Number, Number) in module Iterators at deprecated.jl:56 overwritten in module IterTools at deprecated.jl:56.
count(Number) in module Iterators at deprecated.jl:56 overwritten in module IterTools at deprecated.jl:56.
WARNING: Method definition count(Number, Number) in module Iterators at deprecated.jl:56 overwritten in module IterTools at deprecated.jl:56.
On worker 2:
MethodError: no method matching (::Base.Serializer.__deserialized_types__.##15#16)(::DiffEqBase.ODEProblem{Float64,Float64,false,Base.Serializer.__deserialized_types__.##13#14,Void,UniformScaling{Int64}}, ::Int64)
Closest candidates are:
  #15(::Any, ::Any, ::Any) at In[5]:5
#4 at C:\JuliaPro-0.6.0.1\pkgs-0.6.0.1\v0.6\DiffEqMonteCarlo\src\solve.jl:45
#exec_from_cache#193 at .\distributed\workerpool.jl:284
exec_from_cache at .\distributed\workerpool.jl:283
#106 at .\distributed\process_messages.jl:268 [inlined]
run_work_thunk at .\distributed\process_messages.jl:56
macro expansion at .\distributed\process_messages.jl:268 [inlined]
#105 at .\event.jl:73
```

  thanks for confirming on my understanding of how i can benefit from Julia and DifferentialEquations package. I'm really excited to get to make it work and understand it more.

**Comment by ChrisRackauckas** [comment]
You have a very old version of DifferentialEquations.jl. Iterators.jl has not been a dependency for months due to this issue. Do you happen to be using JuliaPro?

**Comment by shankyjain** [comment]
yes, i installed Julia through the JuliaPro package [https://juliacomputing.com/products/juliapro.html](url) 
After installation, i added the package DifferentialEquations.jl . Anything i should do different ?

**Comment by ChrisRackauckas** [comment]
JuliaPro is generally incompatible with adding new packages because it pins the version of pretty core dependencies. I would recommend uninstalling JuliaPro and using a standard Julia installation.

**Comment by shankyjain** [comment]
Thanks for the suggestion. I'll do as said and update if things resolve.

**Comment by shankyjain** [comment]
It works. I installed Julia, IJulia which i had trouble with adding the package and had to set ENV JUPYTER to use anaconda jupyter instead of ijulia installing its own private jupyter.After which i added DifferentialEquations package, version installed is v"2.2.1".  I ran the same code and it works.
    Now that my setup is clean, i would spend time learning your package and needed Julia knowledge. I'm planning to use your references below [http://ucidatascienceinitiative.github.io/IntroToJulia/](url), [https://github.com/JuliaDiffEq/DiffEqTutorials.jl](url), [http://docs.juliadiffeq.org/latest/index.html](url) to learn. 
     Can you suggest the right platform if i need help with this package once i start developing my actual ODE system.

Cheers!

**Comment by ChrisRackauckas** [comment]
>Can you suggest the right platform if i need help with this package once i start developing my actual ODE system.

Feel free to ask anything in the chat. Take care.

https://gitter.im/JuliaDiffEq/Lobby
