### ISSUE TITLE
Interpolation error when integrating backwards

### ISSUE THREAD

**Issue by danielmatz** [JuliaDiffEq/DifferentialEquations.jl#196]
I'm trying to integrate some equations of motion backwards in time.  I did this by using `tspan = (0.0, -1000.0)`, which was just a guess at how to do it.  I am also passing a `CallbackSet` that contains two `ContinuousCallback`s.  I'm using the `Tsit5` integrator.

I put a `@show` in my equations of motion, and I see that time is marching backwards fine.  But then `solve` throws the following:

> ERROR: LoadError: Current interpolant only works between tprev and t
> Stacktrace:
>  [1] change_t_via_interpolation!(::OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.Tsit5,Array{Float64,1},Float64,Float64,Float64,Array{Array{Float64,1},1},DiffEqBase.ODESolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Trajectories.##3#8{Trajectories.Vehicle},Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{Trajectories.##3#8{Trajectories.Vehicle},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},Array{Float64,1},Trajectories.##3#8{Trajectories.Vehicle},Void,OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{DiffEqBase.ContinuousCallback{Trajectories.##4#9{Float64,Trajectories.Vehicle},Trajectories.##5#10,Void,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void},DiffEqBase.ContinuousCallback{Trajectories.##6#11{Trajectories.Vehicle},Void,Trajectories.##7#12,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void}},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},Void,Void,Int64},Array{Float64,1}}, ::Float64, ::Type{Val{false}}) at /Users/dmatz/.julia/v0.6/OrdinaryDiffEq/src/integrators/integrator_interface.jl:6
>  [2] apply_callback!(::OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.Tsit5,Array{Float64,1},Float64,Float64,Float64,Array{Array{Float64,1},1},DiffEqBase.ODESolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Trajectories.##3#8{Trajectories.Vehicle},Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{Trajectories.##3#8{Trajectories.Vehicle},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},Array{Float64,1},Trajectories.##3#8{Trajectories.Vehicle},Void,OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{DiffEqBase.ContinuousCallback{Trajectories.##4#9{Float64,Trajectories.Vehicle},Trajectories.##5#10,Void,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void},DiffEqBase.ContinuousCallback{Trajectories.##6#11{Trajectories.Vehicle},Void,Trajectories.##7#12,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void}},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},Void,Void,Int64},Array{Float64,1}}, ::DiffEqBase.ContinuousCallback{Trajectories.##4#9{Float64,Trajectories.Vehicle},Trajectories.##5#10,Void,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void}, ::Float64, ::Float64) at /Users/dmatz/.julia/v0.6/OrdinaryDiffEq/src/callbacks.jl:150
>  [3] handle_callbacks!(::OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.Tsit5,Array{Float64,1},Float64,Float64,Float64,Array{Array{Float64,1},1},DiffEqBase.ODESolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Trajectories.##3#8{Trajectories.Vehicle},Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{Trajectories.##3#8{Trajectories.Vehicle},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},Array{Float64,1},Trajectories.##3#8{Trajectories.Vehicle},Void,OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{DiffEqBase.ContinuousCallback{Trajectories.##4#9{Float64,Trajectories.Vehicle},Trajectories.##5#10,Void,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void},DiffEqBase.ContinuousCallback{Trajectories.##6#11{Trajectories.Vehicle},Void,Trajectories.##7#12,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void}},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},Void,Void,Int64},Array{Float64,1}}) at /Users/dmatz/.julia/v0.6/OrdinaryDiffEq/src/integrators/integrator_utils.jl:297
>  [4] loopfooter!(::OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.Tsit5,Array{Float64,1},Float64,Float64,Float64,Array{Array{Float64,1},1},DiffEqBase.ODESolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Trajectories.##3#8{Trajectories.Vehicle},Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{Trajectories.##3#8{Trajectories.Vehicle},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},Array{Float64,1},Trajectories.##3#8{Trajectories.Vehicle},Void,OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{DiffEqBase.ContinuousCallback{Trajectories.##4#9{Float64,Trajectories.Vehicle},Trajectories.##5#10,Void,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void},DiffEqBase.ContinuousCallback{Trajectories.##6#11{Trajectories.Vehicle},Void,Trajectories.##7#12,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void}},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},Void,Void,Int64},Array{Float64,1}}) at /Users/dmatz/.julia/v0.6/OrdinaryDiffEq/src/integrators/integrator_utils.jl:266
>  [5] solve!(::OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.Tsit5,Array{Float64,1},Float64,Float64,Float64,Array{Array{Float64,1},1},DiffEqBase.ODESolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Trajectories.##3#8{Trajectories.Vehicle},Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{Trajectories.##3#8{Trajectories.Vehicle},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},Array{Float64,1},Trajectories.##3#8{Trajectories.Vehicle},Void,OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{DiffEqBase.ContinuousCallback{Trajectories.##4#9{Float64,Trajectories.Vehicle},Trajectories.##5#10,Void,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void},DiffEqBase.ContinuousCallback{Trajectories.##6#11{Trajectories.Vehicle},Void,Trajectories.##7#12,DiffEqBase.#INITIALIZE_DEFAULT,Float64,Int64,Void}},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan},Void,Void,Int64},Array{Float64,1}}) at /Users/dmatz/.julia/v0.6/OrdinaryDiffEq/src/solve.jl:305
>  [6] #solve#1685(::Array{Any,1}, ::Function, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Trajectories.##3#8{Trajectories.Vehicle},Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at /Users/dmatz/.julia/v0.6/OrdinaryDiffEq/src/solve.jl:7
>  [7] (::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Trajectories.##3#8{Trajectories.Vehicle},Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at ./<missing>:0 (repeats 2 times)
>  [8] run!(::Trajectories.Trajectory, ::Trajectories.Direction, ::Float64) at /Users/dmatz/Data/Aerocapture Alpha Control/Trajectories.jl:230
>  [9] run(::Trajectories.State, ::Trajectories.Direction, ::Float64) at /Users/dmatz/Data/Aerocapture Alpha Control/run.jl:29
>  [10] converge(::Trajectories.State) at /Users/dmatz/Data/Aerocapture Alpha Control/run.jl:56
>  [11] include_from_node1(::String) at ./loading.jl:569
>  [12] include(::String) at ./sysimg.jl:14
>  [13] process_options(::Base.JLOptions) at ./client.jl:305
>  [14] _start() at ./client.jl:371
> while loading /Users/dmatz/Data/Aerocapture Alpha Control/run.jl, in expression starting on line 73

**Comment by ChrisRackauckas** [comment]
Sorry about that. Didn't have something testing that case, but that error was just being thrown because it wasn't checking for direction while everything was already setup to work. Fixed and added a test for both OrdinaryDiffEq.jl and StochasticDiffEq.jl. 

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/5df6f7cbf77be8e01b00c25b93b64f0744e40e49
https://github.com/JuliaDiffEq/StochasticDiffEq.jl/commit/a786e2969da5413effbff9a88c156003c973f13a

This will be in the next OrdinaryDiffEq.jl and StochasticDiffEq.jl releases which I hope is by Monday (it's not in my control, it's how fast Julia's update registration process goes). If you need it in the meantime, you can `Pkg.checkout("OrdinaryDiffEq")` and it should work, but remember to `Pkg.free("OrdinaryDiffEq")` to get back to the regular releases. Hope this helps.

**Comment by danielmatz** [comment]
Thank you for the quick response!

I'm past the original error, but I seem to have hit another place where the checks on time don't account for backwards integration.

> ERROR: LoadError: Solution interpolation cannot extrapolate past the final timepoint. Either solve on a longer timespan or use the local extrapolation from the integrator interface.
> Stacktrace:
>  [1] ode_interpolation(::Float64, ::Function, ::Void, ::Type{T} where T) at /Users/dmatz/.julia/v0.6/OrdinaryDiffEq/src/dense/generic_dense.jl:225
>  [2] (::DiffEqBase.ODESolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{Array{Float64,1},Float64,false,Trajectories.##3#8{Trajectories.Vehicle},Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{Trajectories.##3#8{Trajectories.Vehicle},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}})(::Float64) at /Users/dmatz/.julia/v0.6/DiffEqBase/src/solutions/ode_solutions.jl:14
>  [3] run!(::Trajectories.Trajectory, ::Trajectories.Direction, ::Float64) at /Users/dmatz/Data/Aerocapture Alpha Control/Trajectories.jl:244
>  [4] run(::Trajectories.State, ::Trajectories.Direction, ::Float64) at /Users/dmatz/Data/Aerocapture Alpha Control/run.jl:29
>  [5] converge(::Trajectories.State) at /Users/dmatz/Data/Aerocapture Alpha Control/run.jl:56
>  [6] include_from_node1(::String) at ./loading.jl:569
>  [7] include(::String) at ./sysimg.jl:14
>  [8] process_options(::Base.JLOptions) at ./client.jl:305
>  [9] _start() at ./client.jl:371
> while loading /Users/dmatz/Data/Aerocapture Alpha Control/run.jl, in expression starting on line 73
>

**Comment by ChrisRackauckas** [comment]
This is on the master branch of OrdinaryDiffEq.jl? Do you have an example I can run?

**Comment by danielmatz** [comment]
Yes, it's on the master branch.  Let me try to cook up a simplified example...

**Comment by danielmatz** [comment]
Actually, the simplest of examples is showing this error for me:

```julia
using DifferentialEquations

derivatives(t, u) = t

prob = ODEProblem(derivatives,
                  0.0,
                  (0.0, -100.0))
sol = solve(prob, Tsit5())
@show sol(-1.0)
```

**Comment by ChrisRackauckas** [comment]
Thanks for reporting it. It's fixed on the new OrdinaryDiffEq.jl master. Just `Pkg.update()` if you've already checked it out. Once again newer error messages getting in the way of already working code... I'm sorry about that!

**Comment by danielmatz** [comment]
Thank you again for the fast response!
