### ISSUE TITLE
Turn off forced endpoint saving

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaDiffEq/DifferentialEquations.jl#197]
- When using callbacks, the last step is saved even if it does not satisfy the condition. A `save_end` option should be added.
- When using a callback with `save_start=false` with a condition that is always false, `solve` throws a `BoundsError`.

Code to reproduce:
```
using DifferentialEquations

function HamiltonEqs_q(t, q, p, dq)
    dq[1] = p[1]
    dq[2] = p[2]
end

function HamiltonEqs_p(t, q, p, dp)
    dp[1] = -q[1] - (q[2]^2 - q[1]^2)
    dp[2] = -q[2] * (1 + 2 * q[1])
end

q0 = [0.1, 0.]
p0 = [0., 0.5]
tspan = (0., 20.)

condition(t, u, integrator) = 1
affect!(integrator) = nothing
cb = ContinuousCallback(condition, affect!, affect!, save_positions = (true, false));
prob = DynamicalODEProblem{true}(HamiltonEqs_q, HamiltonEqs_p, q0, p0, tspan);
sol = solve(prob, KahanLi8(), save_everystep = false, save_start=false, callback=cb, dt=1/10)
```
Error:
```
BoundsError: attempt to access 0-element Array{Float64,1} at index [0]
in #48 at base/task.jl:80
in macro expansion at Atom/src/eval.jl:49
in withpath at Atom/src/eval.jl:38
in withpath at CodeTools/src/utils.jl:30
in #49 at Atom/src/eval.jl:50
in include_string at CodeTools/src/eval.jl:34
in include_string at CodeTools/src/eval.jl:30
in #solve at base/<missing>
in #solve at base/<missing>
in #solve#1558 at OrdinaryDiffEq/src/solve.jl:7
in solve! at OrdinaryDiffEq/src/solve.jl:316
in postamble! at OrdinaryDiffEq/src/integrators/integrator_utils.jl:139
in solution_endpoint_match_cur_integrator! at OrdinaryDiffEq/src/integrators/integrator_utils.jl:147
```

**Comment by ChrisRackauckas** [comment]
Yes, right now everything is setup so that it always saves the last step. This is a good idea.

**Comment by ChrisRackauckas** [comment]
Changed the title to be clear that the issue has nothing to do with callbacks. In general it always saves the endpoint. There is actually a piece of code that specifically forces this to happen. We just need to add an option to turn it off.

Though yes, I do see that the only valid use case for this is when you want your saving to be tied to your callbacks since in any other case I would assume you could just make `tspan` shorter.

**Comment by ChrisRackauckas** [comment]
`save_end` is in the docs and on master branches.
