### ISSUE TITLE
Real noise process with complex variables

### ISSUE THREAD

**Issue by onoderat** [JuliaDiffEq/DifferentialEquations.jl#198]
I am trying to solve the Stochastic Schrondinger Equation which is an SDE with this library. Unfortunately, I am running to the issue where because the wavefunction is complex, the noise process dW is automatically assumed to be the complex noise process dW^2 = 0, dW*dW^* = dt. Is there a way to set the noise so that it is real in this situation?

**Comment by ChrisRackauckas** [comment]
Yes, it requires that you create a `NoiseProcess`. Specifically, if you create a real-valued Wiener process:

http://docs.juliadiffeq.org/latest/features/noise_process.html#Wiener-Process-(White-Noise)-1

You can then pass it to the `SDEProblem` using the constructor.

http://docs.juliadiffeq.org/latest/types/sde_types.html#Constructors-1

**Comment by onoderat** [comment]
Thanks for the quick reply.
