### ISSUE TITLE
Full compatibility with ArrayFire

### ISSUE THREAD

**Issue by rveltz** [JuliaDiffEq/DifferentialEquations.jl#199]
Hi,

I am trying to use two great packages, `DifferentialEquations` and `ArrayFire` from @gaika. 
So far the following gives the unexpected result that `u` and `du` do not have the same type.

Is it easy to see why?

Tank you,

Best regards 

```julia
using ArrayFire, DifferentialEquations
const TY=Float32

ArrayFire.set_backend(AF_BACKEND_OPENCL)

N = 2^8
const parms = TY.([2.1,1.])

print_mem_info("GPU-Mem avant loop", 0)

@afgc function rhs!(t,u,du)
	println(typeof(u)," - ",typeof(du))
	du .= -u
	nothing
end

#################################################################
V0 = zeros(AFArray{TY},N)
tspan = (0.0,100.01)
alg   = Euler()
prob  = ODEProblem(rhs!,V0,tspan)
sol   = @time DifferentialEquations.solve(prob,alg,saveat=collect(linspace(tspan[1],tspan[2],100)),adaptive=false,dt=0.1);
```

gives 

```julia
ArrayFire v3.5.0 (OpenCL, 64-bit Mac OSX, build 05999f3)
[0] APPLE: AMD Radeon R9 M370X Compute Engine, 2048 MB
-1- APPLE: Iris Pro, 1536 MB
GPU-Mem avant loop
---------------------------------------------------------
|     POINTER      |    SIZE    |  AF LOCK  | USER LOCK |
---------------------------------------------------------
---------------------------------------------------------
ArrayFire.AFArray{Float32,1} - Array{Float64,1}
ERROR: LoadError: MethodError: Base.Broadcast.promote_containertype(::Type{Array}, ::Type{ArrayFire.AFArray}) is ambiguous. Candidates:
  promote_containertype(ct, ::Type{ArrayFire.AFArray}) in ArrayFire at /Users/rveltz/.julia/v0.6/ArrayFire/src/array.jl:288
  promote_containertype(::Type{Array}, ct) in Base.Broadcast at broadcast.jl:37
Possible fix, define
  promote_containertype(::Type{Array}, ::Type{ArrayFire.AFArray})
Stacktrace:
 [1] broadcast! at ./broadcast.jl:204 [inlined]
 [2] perform_step!(::OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.Euler,ArrayFire.AFArray{Float32,1},Float64,Float64,Float64,Array{Array{Float64,1},1},DiffEqBase.ODESolution{Float32,2,Array{ArrayFire.AFArray{Float32,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{ArrayFire.AFArray{Float32,1},Float64,true,#rhs!,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Euler,OrdinaryDiffEq.InterpolationData{#rhs!,Array{ArrayFire.AFArray{Float32,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.EulerCache{ArrayFire.AFArray{Float32,1},Array{Float64,1}}}},Array{Float64,1},#rhs!,Void,OrdinaryDiffEq.EulerCache{ArrayFire.AFArray{Float32,1},Array{Float64,1}},OrdinaryDiffEq.DEOptions{Float32,Float32,Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Void,Void,Int64},Array{Float64,1}}, ::OrdinaryDiffEq.EulerCache{ArrayFire.AFArray{Float32,1},Array{Float64,1}}, ::Bool) at /Users/rveltz/.julia/v0.6/OrdinaryDiffEq/src/integrators/fixed_timestep_integrators.jl:71
 [3] solve!(::OrdinaryDiffEq.ODEIntegrator{OrdinaryDiffEq.Euler,ArrayFire.AFArray{Float32,1},Float64,Float64,Float64,Array{Array{Float64,1},1},DiffEqBase.ODESolution{Float32,2,Array{ArrayFire.AFArray{Float32,1},1},Void,Void,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DiffEqBase.ODEProblem{ArrayFire.AFArray{Float32,1},Float64,true,#rhs!,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Euler,OrdinaryDiffEq.InterpolationData{#rhs!,Array{ArrayFire.AFArray{Float32,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.EulerCache{ArrayFire.AFArray{Float32,1},Array{Float64,1}}}},Array{Float64,1},#rhs!,Void,OrdinaryDiffEq.EulerCache{ArrayFire.AFArray{Float32,1},Array{Float64,1}},OrdinaryDiffEq.DEOptions{Float32,Float32,Float64,Float64,DiffEqBase.#ODE_DEFAULT_NORM,DiffEqBase.CallbackSet{Tuple{},Tuple{}},DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN,DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE,DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK,DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Void,Void,Int64},Array{Float64,1}}) at /Users/rveltz/.julia/v0.6/OrdinaryDiffEq/src/solve.jl:308
 [4] #solve#1636(::Array{Any,1}, ::Function, ::DiffEqBase.ODEProblem{ArrayFire.AFArray{Float32,1},Float64,true,#rhs!,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.Euler, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at /Users/rveltz/.julia/v0.6/OrdinaryDiffEq/src/solve.jl:7
 [5] (::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.ODEProblem{ArrayFire.AFArray{Float32,1},Float64,true,#rhs!,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.Euler, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at ./<missing>:0 (repeats 2 times)
 [6] include_from_node1(::String) at ./loading.jl:569
 [7] include(::String) at ./sysimg.jl:14
 [8] process_options(::Base.JLOptions) at ./client.jl:305
 [9] _start() at ./client.jl:371
while loading /Users/rveltz/work/prog_gd/julia/NeuralFields/nf-af-1d-diffeq.jl, in expression starting on line 237
```

**Comment by ChrisRackauckas** [comment]
It's not clear to me why it would do this. Can you try `BS3()` with `adaptive=false`? That example has been checked already with GPUArrays.jl.

```julia
rate_prototype = similar(u,typeof(oneunit(uEltype)/oneunit(tType)))
```

Does using `similar` on a `ArrayFire.AFArray` not return another `ArrayFire.AFArray`?

**Comment by gaika** [comment]
right, `similar` is not fully, implemented, I'll fix

**Comment by rveltz** [comment]
Thank you!

That's quite slow though.

Also, `.=` or `swap!` affect `u` which should be `const`, no?

```julia
using ArrayFire, DifferentialEquations
const TY=Float32
AF = AFArray 


ArrayFire.set_backend(AF_BACKEND_OPENCL)
# ArrayFire.set_backend(AF_BACKEND_CPU)

N = 2^8
const parms = TY.([2.1,1.])

print_mem_info("GPU-Mem avant loop", 0)

@afgc function rhs!(t,u,du)
	# println(typeof(u)," - ",typeof(du))
	du .= -u
	nothing
end

#################################################################
V0 = zeros(AF{TY},N)
# V0 = zeros(TY,N)
tspan = TY.((0.0,100.01))
alg   = Euler()
prob  = ODEProblem(rhs!,V0,tspan)
sol   = DifferentialEquations.solve(prob,alg,saveat=collect(linspace(tspan[1],tspan[2],20)),adaptive=false,dt=0.1);
sol   = @time DifferentialEquations.solve(prob,alg,saveat=collect(linspace(tspan[1],tspan[2],40)),adaptive=false,dt=0.1);
@show length(sol)
```

**Comment by ChrisRackauckas** [comment]
>Also, .= or swap! affect u which should be const, no?

No, that should make it a linear ODE: `u' = u`.

>That's quite slow though.

You mean solving with an AFArray? There are two things I would check:

1) Does ArrayFire handle `muladd` correctly?
2) Is anything else in the cache not actually on the GPU due to missing the 3-variable `similar`? Instead of solve, use `integrator = init(prob,alg)` and then check `integrator.cache` and see if anything is not an AFArray. 

Otherwise it'll need some profiling to find out where it's getting stuck.

**Comment by rveltz** [comment]
```julia
using ArrayFire, DifferentialEquations
const TY=Float32
AF = AFArray 


ArrayFire.set_backend(AF_BACKEND_OPENCL)
# ArrayFire.set_backend(AF_BACKEND_CPU)

N = 2
const parms = TY.([2.1,1.])

print_mem_info("GPU-Mem avant loop", 0)

@afgc function rhs!(t,u,du)
	# println(typeof(u)," - ",typeof(du))
	du .= -u
	nothing
end

#################################################################
V0 = zeros(AF{TY},N)
# V0 = zeros(TY,N)
tspan = TY.((0.0,100.01))
alg   = Euler()
prob  = ODEProblem(rhs!,V0,tspan)
integrator = init(prob,alg,dt=0.1)
println(integrator.cache)
sol   = DifferentialEquations.solve(prob,alg,saveat=collect(linspace(tspan[1],tspan[2],20)),adaptive=false,dt=0.1);
sol   = @time DifferentialEquations.solve(prob,alg,saveat=collect(linspace(tspan[1],tspan[2],40)),adaptive=false,dt=0.1);
@show length(sol)
```
gives

```julia
ArrayFire v3.5.0 (OpenCL, 64-bit Mac OSX, build 05999f3)
[0] APPLE: AMD Radeon R9 M370X Compute Engine, 2048 MB
-1- APPLE: Iris Pro, 1536 MB
GPU-Mem avant loop
---------------------------------------------------------
|     POINTER      |    SIZE    |  AF LOCK  | USER LOCK |
---------------------------------------------------------
---------------------------------------------------------
OrdinaryDiffEq.EulerCache{ArrayFire.AFArray{Float32,1},ArrayFire.AFArray{Float32,1}}(AFArray: Float32[0.0, 0.0], AFArray: Float32[0.0, 0.0], AFArray: Float32[0.0, 0.0], AFArray: Float32[0.0, 0.0], AFArray: Float32[0.0, 0.0])
  2.366356 seconds (231.74 k allocations: 11.697 MiB, 0.34% gc time)
length(sol) = 40
```

I would say it looks OK for the `integrator`. Can you point to the use of `muladd` please?

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/fixed_timestep_integrators.jl#L71

That's the entire inner loop for `Euler`. `@muladd` applies `muladd` everywhere it can, so that's `u .= muladd.(dt,integrator.fsalfirst,uprev)`. Should check that `muladd` broadcasting with a scalar in there works well for AFArrays.

**Comment by gaika** [comment]
For some reason it goes into indexing all elements with recursivecopy!
```
  if isinplace(integrator.sol.prob)
    recursivecopy!(integrator.uprev,integrator.u)
  else
    integrator.uprev = integrator.u
  end
```
that goes into mutidimensional.jl  `copy!`  Being an `AbstractArray` is hard, maybe should drop the inheritance and implement all required methods?

**Comment by rveltz** [comment]
@gaika you mean implement all required methods in AF?

**Comment by ChrisRackauckas** [comment]
`recursivecopy!` in this case just calls `copy!`, and it sounds like `AFArray` doesn't override `copy!` right now.

**Comment by gaika** [comment]
implementing `copy!` helps a lot, now it goes into `any` with an iterator somewhere in `integrator.opts.unstable_check`, don't know how to track the actual code for it.

**Comment by ChrisRackauckas** [comment]
Oh that's just a global default function defined here:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/common_defaults.jl#L9

The user can pass in their own function though. It's described here:

http://docs.juliadiffeq.org/latest/basics/common_solver_opts.html#Miscellaneous-1

For now you can test with `unstable_check = (dt,t,u) -> false` to disable it. But for making the default, is there a better choice than using `any` to check if any of the values are NaN? I assumed that using the iterator on the array would be a good default, but I guess GPU-based arrays are a pretty good example where that fails. I need some kind of generic map-reduce here, do you have that construct?

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaGPU/GPUArrays.jl#scope

Looks like GPUArrays has `mapreduce`. So I can replace this default with `mapreduce(isnan,(x,y)->x||y,u)`

**Comment by gaika** [comment]
AFArray would be happy with `any(nan.(u))`

**Comment by ChrisRackauckas** [comment]
>AFArray would be happy with any(nan.(u))

That would allocate. I'd like to try and find a solution which doesn't allocate.

**Comment by gaika** [comment]
then keep it as is, easier to add `any` that does the same than to add `mapreduce` with arbitrary stuff in it. And since it is user controllable, then don't worry. 

On a separate topic, since `ArrayFire` does its own JIT so this whole non-allocation business doesn't help at all. Is there a version or a flag that doesn't try to optimize for allocations?

**Comment by ChrisRackauckas** [comment]
>On a separate topic, since ArrayFire does its own JIT so this whole non-allocation business doesn't help at all. Is there a version or a flag that doesn't try to optimize for allocations?

In most of DiffEq, yes. If the user gives a function `f(t,u)` then everything is out-of-place, while the input function `f(t,u,du)` where the answer is written to `du` makes everything automatically use in-place operations. So this example is switched to the other form via:

```julia
@afgc function rhs(t,u)
	-u
end
```

and then using that in the `ODEProblem`.

For this one default? No, it always assumes that if it's an `AbstractArray` then you won't want this function call to allocate. I am not sure of a trait in Base to be able to differentiate here without a new dependency.

>then keep it as is, easier to add any that does the same than to add mapreduce with arbitrary stuff in it. And since it is user controllable, then don't worry.

Is there a reason why ArrayFire.jl doesn't have `mapreduce` or `reduce`?

**Comment by gaika** [comment]
> Is there a reason why ArrayFire.jl doesn't have mapreduce or reduce?

I try to keep it simple by limiting the scope to existing `ArrayFire` C API or small one liners that improve Julia native use. I guess it could be done just like `broadcast` was done.

**Comment by ChrisRackauckas** [comment]
Well since `any(u)` is good and you don't have to worry about allocations, can't you define `any(f,u::AFArray) = any(f(u))`?

**Comment by gaika** [comment]
yep, just added `any` and `all`. @rveltz , do you have a more demanding example? All current visible bottlenecks seem to be gone.

**Comment by rveltz** [comment]
Even after a  Pkg.update the code take 15s to complete.

```
using ArrayFire, DifferentialEquations
const TY=Float32
AF = AFArray 


ArrayFire.set_backend(AF_BACKEND_OPENCL)
# ArrayFire.set_backend(AF_BACKEND_CPU)

N = 2^9
const parms = TY.([2.1,1.])

print_mem_info("GPU-Mem avant loop", 0)

@afgc function rhs!(t,u,du)
	# println(typeof(u)," - ",typeof(du))
	du .= -u
	nothing
end

#################################################################
V0 = zeros(AF{TY},N)
# V0 = zeros(TY,N)
tspan = TY.((0.0,100.01))
alg   = Euler()
prob  = ODEProblem(rhs!,V0,tspan)
integrator = init(prob,alg,dt=0.1)
# println(integrator.cache)
sol   = DifferentialEquations.solve(prob,alg,saveat=collect(linspace(tspan[1],tspan[2],20)),adaptive=false,dt=0.1);
sol   = @time DifferentialEquations.solve(prob,alg,saveat=collect(linspace(tspan[1],tspan[2],40)),adaptive=false,dt=0.1);
@show length(sol), typeof(sol)
```

**Comment by gaika** [comment]
with `rhs!` I have 2s, with `rhs` it is 0.14s, still far cry from 2ms with `Array`, but at least something you can start tracking down yourself. My profile skills are failing me here :( `@profile` is not very helpful for some reason with `ArrayFire`. I would just ctrl-c randomly to see where it is stuck. Another approach for you could be to drop `AbstractArray` inheritance for `AFArray` and see what functions are not implemented but are still requested.

**Comment by ChrisRackauckas** [comment]
Can you try `alg   = BS3()` and `adaptive=true`? That's probably the most standard case.

**Comment by gaika** [comment]
not sure how it works at all because `lufact!` is called `lu_inplace` and was not tested. Probably drops back to `lu`?

Some overhead, but hard to track what exactly: 0.038835 seconds (47.34 k allocations: 1.055 MiB),

**Comment by ChrisRackauckas** [comment]
I can now confirm that with this we're not hitting any slow path with AFArrays:

```julia
using ArrayFire, DifferentialEquations
const TY=Float32
AF = AFArray


ArrayFire.set_backend(AF_BACKEND_OPENCL)
# ArrayFire.set_backend(AF_BACKEND_CPU)

N = 10^5
const parms = TY.([2.1,1.])

print_mem_info("GPU-Mem avant loop", 0)

@afgc function rhs!(t,u,du)
	# println(typeof(u)," - ",typeof(du))
	du .= -u
	nothing
end

allowslow(AFArray, false)

#################################################################
V0 = zeros(AF{TY},N)
# V0 = zeros(TY,N)
tspan = TY.((0.0,100.01))
alg   = Euler()
prob  = ODEProblem(rhs!,V0,tspan)
integrator = init(prob,alg,dt=0.1)
# println(integrator.cache)
sol   = DifferentialEquations.solve(prob,alg,save_everystep=false,adaptive=false,dt=0.1);
sol   = @time DifferentialEquations.solve(prob,save_everystep=false,alg,adaptive=false,dt=0.1);
@show length(sol), typeof(sol)


prob2  = ODEProblem(rhs!,zeros(N),tspan)
sol   = DifferentialEquations.solve(prob2,alg,save_everystep=false,adaptive=false,dt=0.1);
sol   = @time DifferentialEquations.solve(prob2,alg,save_everystep=false,adaptive=false,dt=0.1);
```

That being said, this isn't the best usage of GPUs since it's all small kernel broadcasts. So it could be slower than CPU just because of the algorithm (GPUs do much better with matrix-vector multiplications which are compute-bound instead of memory-bound which could be the issue here), or it could be that we need to use the out-of-place version and ArrayFire's GC which is currently using a slow path due to https://github.com/JuliaComputing/ArrayFire.jl/issues/173 . Anything else may be a performance issue with the type itself which is probably better addressed at ArrayFire's repo, but in general I think this may be an algorithmic issue where no matrices involved here means the GPU isn't well-utilized.

As for using the stiff solvers, it needs the ability to solve linear equations (https://github.com/JuliaComputing/ArrayFire.jl/issues/174). These seem more like type issues though, so I'll let ArrayFire handle that and feel free to ping me as needed in the future.
