### ISSUE TITLE
Fail to install "DifferentialEquations"

### ISSUE THREAD

**Issue by xiaoguozhi** [JuliaDiffEq/DifferentialEquations.jl#205]
When  I install the package by Pkg.add("DifferentialEquations")，it occurs that “juila  unknown package Blobs required by RecSys requirements”.

**Comment by ChrisRackauckas** [comment]
Huh, those packages do not sound familiar. Do you also get this if you just `Pkg.update()`? I'm catching a flight soon so I can't really help much further right now.

**Comment by aviks** [comment]
Please remove the `RecSys` package from your installation. Alternately, clone the `https://github.com/tanmaykm/blobs.jl` package. These packages are not registered, and thus are not actively maintained yet. This has nothing to do with DifferentialEquations in particular.

**Comment by xiaoguozhi** [comment]
Rmove the package by Pkg.rm("RecSys"), and then install the package by Pkg.add("DifferentialEquations"), and it takes a long  time, many new errors occurs.

**Comment by appleparan** [comment]
What kind of errors? And please show your Pkg.status() results also.

**Comment by ChrisRackauckas** [comment]
Well this isn't a DiffEq issue so I'm closing it.
