### ISSUE TITLE
Missing one output point if saveat is a given number

### ISSUE THREAD

**Issue by jaakkor2** [JuliaDiffEq/DifferentialEquations.jl#206]
With tspan = ( 0, 0.599e-6 ) , saveat=0.1e-6  I get sol.t
```
0.0
1.0e-7
2.0e-7
3.0e-7
4.0e-7
5.99e-7
```
Documentation at http://docs.juliadiffeq.org/stable/basics/common_solver_opts.html#Output-Control-1 says
- The solver will save at each of the timepoints in this array in the most efficient manner (always including the points of tspan). 
- If saveat is given a number, then it will automatically expand to tspan[1]:saveat:tspan[2]. 

I would interpret that 5.0e-7 should be included,

**Comment by ChrisRackauckas** [comment]
Yes, this is a bug. Which algorithm was used to get the solution here?

**Comment by jaakkor2** [comment]
Tsit5()

**Comment by ChrisRackauckas** [comment]
Yes, I can re-create it:

```julia
using DifferentialEquations
f(t,u) = 1.01*u
u0=1/2
tspan = ( 0, 0.599e-6 )
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),saveat = 1e-7)

integrator = init(prob,Tsit5(),saveat = 1e-7)
integrator.opts.saveat

4-element Array{Float64,1}:
 1.0e-7
 2.0e-7
 3.0e-7
 4.0e-7
```

looks like `saveat` is cutting off the end.

**Comment by ChrisRackauckas** [comment]
```julia
saveat = 1e-7
tType = Float64
(tspan[end]-saveat)
collect(tType,tspan[1]+saveat:saveat:(tspan[end]-saveat))
```

The way that we are chopping off the end is the issue.

**Comment by ChrisRackauckas** [comment]
Fixed on master for each of the solver packages. Tagging will come soon.
