### ISSUE TITLE
MethodError when in-place updating ArrayPartitions with more than 2 elements

### ISSUE THREAD

**Issue by pwstokes225** [JuliaDiffEq/DifferentialEquations.jl#207]
In-place updating doesn't work for ArrayPartitions with more than 2 elements.
e.g. This works:
`ODEProblem((t,u,du)->du.=-u, ArrayPartition([1.0],[1.0]), (0.0, 5.0))`
while this does not:
`ODEProblem((t,u,du)->du.=-u, ArrayPartition([1.0],[1.0],[1.0]), (0.0, 5.0))`

**Comment by ChrisRackauckas** [comment]
MWE:

```julia
using OrdinaryDiffEq
prob = ODEProblem((t,u,du)->du.=-u, ArrayPartition([1.0],[1.0],[1.0]), (0.0, 5.0))
sol = solve(prob,Tsit5())
```

**Comment by ChrisRackauckas** [comment]
Fixed on RecursiveArrayTools.jl master by https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/commit/a70c164497c6e89618cfe85532829339e4f8abe9
