### ISSUE TITLE
plotting the solution in a controlled time interval

### ISSUE THREAD

**Issue by dapias** [JuliaDiffEq/DifferentialEquations.jl#208]
Let us consider the Lorenz ODE taken from the documentation

```julia
using DifferentialEquations
g = @ode_def LorenzExample begin
  dx = σ*(y-x)
  dy = x*(ρ-z) - y
  dz = x*y - β*z
end σ=>10.0 ρ=>28.0 β=(8/3)

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(g,u0,tspan)
sol = solve(prob)
```
We would like to plot the phase portraits in the time interval (10.0, 100.0) because we are not interested in the behavior at the initial points. For that we would have to do
```julia
using Plots
sol_time = sol(10:100)
plot(soltime[1,:], soltime[2,:])
```
which works but it is more involved than the direct solution for the whole interval
```julia
using Plots
plot(sol, vars=(:x,:y))
```

**Comment by ChrisRackauckas** [comment]
a `tspan` argument now exists in the plot recipe for DiffEqBase master:

```julia
using Plots; pyplot(); plot(sol,tspan=(0.0,40.0))
```

I'll tag to release that soon.
