### ISSUE TITLE
SIR model from Documentation

### ISSUE THREAD

**Issue by schrauf** [JuliaDiffEq/DifferentialEquations.jl#212]
Thanks to all contributors for this GREAT family of packages,
and sorry if there is an obvious error, but I tried to reproduce the documentation and had this issue.

The following snippet (from the [documentation](http://docs.juliadiffeq.org/latest/tutorials/discrete_stochastic_example.html)):

```julia
rs = @reaction_network begin
  1e-4, S + I --> 2I
  0.01,  I --> R
end
prob = DiscreteProblem([999,1,0],(0.0,250.0))
jump_prob = GillespieProblem(prob,Direct(),rs)
sol = solve(jump_prob,Discrete())
```
outputs: `ERROR: UndefVarError: initialize_save not defined`

I think my package are updated.
```
julia> Pkg.status("DifferentialEquations")
 - DifferentialEquations         3.0.2              master
```
Best Regards, Matías

**Comment by ChrisRackauckas** [comment]
Yeah sorry! The fix already exists on OrdinaryDiffEq.jl master (https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/222) but I forgot to release it. Let me tag this right now. You can `Pkg.update()` to get the fix after https://github.com/JuliaLang/METADATA.jl/pull/11908 is merged.

**Comment by schrauf** [comment]
Wow! Incredible response time : )
Thanks again for your work

**Comment by ChrisRackauckas** [comment]
If you `Pkg.update()` it is fixed.
