### ISSUE TITLE
Running on juliabox.com

### ISSUE THREAD

**Issue by sje30** [JuliaDiffEq/DifferentialEquations.jl#214]
Hi,
I'm having difficulty getting the pkg to run on juliabox.com.  I think it is simply because of its large size, 177Mb (?), I go over quota of 477Mb.  Have you any suggestions for getting your  package to run on juliabox.com?  (It would be great if it were pre-installed!)

Thanks for such a great package.

**Comment by ChrisRackauckas** [comment]
This is an extension of the issue https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/107 . 

You can use DifferentialEquations.jl by simply grabbing its component libraries. For example, if you just want to solve ODEs, you can grab OrdinaryDiffEq.jl and just use that. This is described in the docs:

http://docs.juliadiffeq.org/stable/features/low_dep.html

Hopefully when Pkg3 comes out we can prune the repo and fix this for real.

**Comment by sje30** [comment]
p.s. this is the repo/notebook I'm having trouble with (I'm creating an introduction to neursocience notebook, and one bit used your package for numerical integration of hodgkin huxley equations).

https://github.com/sje30/cnw

**Comment by sje30** [comment]
Thanks, I'll take a look!

**Comment by ChrisRackauckas** [comment]
Yeah, I looked through your stuff and if you just replaced `using DifferentialEquations` with `using OrdinaryDiffEq` you'll be fine.

**Comment by sje30** [comment]
Thanks Chris, it all worked perfectly yesterday in my workshop.  Great tip, and great package.
