### ISSUE TITLE
Callback condition not working for fixed timesteps

### ISSUE THREAD

**Issue by ede91** [JuliaDiffEq/DifferentialEquations.jl#215]
When I try to trigger a ContinuousCallback with an integration-time dependent condition-function, the affect-function is not called, if the trigger time coincides with a fixed timestep.
MWE:
```julia
using DifferentialEquations
t_event = 100.0
f(t,u) = 1.00001*u
condition(t,u,integrator) = t_event-t
affect!(integrator) = println("Event detected at $(integrator.t)")
cb = ContinuousCallback(condition, nothing, affect!)
prob = ODEProblem(f, [1.0], (0.0, 2.0*t_event))
sol = solve(prob,callback=cb, adaptive = false, dt = 10.0)
```
=> `affect()` not called, since it is a multiple of `dt`
when the code is changed to `t_event = 100.1` (or anything else with `t_event!=N*dt`), the affect-function is called at the right instant

**Comment by ChrisRackauckas** [comment]
Hmm, interesting edge case. Let me look into it. But, is there a reason you don't use a `DiscreteCallback` for this?

**Comment by ede91** [comment]
Thanks.
I was not able to trigger a DiscreteCallback at arbitrary instants. If condition is changed to
```julia
condition(t,u,integrator) = t == t_event
```
, affect is only called if `t_event` is a multiple of `dt`.

**Comment by ChrisRackauckas** [comment]
you just need to add a tstop.

```julia
sol = solve(prob,callback=cb, tstops = [t_event])
```

Now even with adaptive timestepping it will hit that point to trigger the callback.

**Comment by ChrisRackauckas** [comment]
A discrete callback with `tstops` is what you want to do, but anyways this is now fixed on master so the continuous callback will work just fine.
