### ISSUE TITLE
Failed to precompile DifferentialEquations

### ISSUE THREAD

**Issue by wg030** [JuliaDiffEq/DifferentialEquations.jl#216]
I got the following error today although yesterday everything worked fine with exactly the same code:

> INFO: Precompiling module DifferentialEquations.
ERROR: LoadError: LoadError: UndefVarError: TimeDerivativeWrapper not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/wg030/.julia/v0.6/DelayDiffEq/src/utils.jl, in expression starting on line 47
while loading /home/wg030/.julia/v0.6/DelayDiffEq/src/DelayDiffEq.jl, in expression starting on line 33
ERROR: LoadError: Failed to precompile DelayDiffEq to /home/wg030/.julia/lib/v0.6/DelayDiffEq.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/wg030/.julia/v0.6/DifferentialEquations/src/DifferentialEquations.jl, in expression starting on line 17
LoadError: Failed to precompile DifferentialEquations to /home/wg030/.julia/lib/v0.6/DifferentialEquations.ji.
while loading /home/wg030/Documents/model.jl, in expression starting on line 11
in require at base/loading.jl:405
in _require at base/loading.jl:497
in compilecache at base/loading.jl:710

I have already tried to rebuild the package with Pkg.build as well as to reinstall it with Pkg.rm followed by Pkg.add, but the error still occurs.

**Comment by ChrisRackauckas** [comment]
Sorry, I messed up versioning with a release last night. However, the fixes are now merged so if you `Pkg.update()` it should be fixed.
