### ISSUE TITLE
Trivial timespan

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaDiffEq/DifferentialEquations.jl#221]
It would be nice to support the trivial timespan (tspan = (0.0, 0.0)). This came up when I had a simulation with a final time T and wanted to remind myself of what the initial condition was, so I just set T = 0 and got

`ERROR: LoadError: Timespan is trivial`

**Comment by ChrisRackauckas** [comment]
Wouldn't `prob.u0` be a better way to check?

**Comment by antoine-levitt** [comment]
Definitely, but I already had the code set up to integrate and plot, didn't want to go fiddling inside it, and it was mildly annoying that just setting T=0 didn't work. I ended up doing T = 1e-8 as a workaround.

**Comment by ChrisRackauckas** [comment]
I can get rid of the check. Honestly, I don't know what it would do, it might just error due to something weird going on in this case. But it's worth a try.

**Comment by ChrisRackauckas** [comment]
Yeah, works if the manual error is taken away, so on master this is good now.

**Comment by antoine-levitt** [comment]
Thanks!
