### ISSUE TITLE
has_reinit not defined during DifferentialEquations.jl precompilation

### ISSUE THREAD

**Issue by matfill** [JuliaDiffEq/DifferentialEquations.jl#226]
I'm using Julia 0.6.0 on Windows. During the precompilation stage of DifferentialEquations.jl the variable has_reinit seems undefined in DiffEqNoiseProcess.jl: 

INFO: Precompiling module DifferentialEquations.
ERROR: LoadError: LoadError: 
UndefVarError: has_reinit not defined
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:569
 [2] include(::String) at .\sysimg.jl:14
 [3] include_from_node1(::String) at .\loading.jl:569
 [4] include(::String) at .\sysimg.jl:14
 [5] anonymous at .\<missing>:2
while loading C:\Users\filimat15173\AppData\Local\JuliaP-0.6.0.1\pkgs-0.6.0.1\v0.6\DiffEqNoiseProcess\src\noise_interfaces/common.jl, in expression starting on line 1
while loading C:\Users\filimat15173\AppData\Local\JuliaP-0.6.0.1\pkgs-0.6.0.1\v0.6\DiffEqNoiseProcess\src\DiffEqNoiseProcess.jl, in expression starting on line 24
ERROR: LoadError: 
Failed to precompile DiffEqNoiseProcess to C:\Users\filimat15173\AppData\Local\JuliaP-0.6.0.1\pkgs-0.6.0.1\lib\v0.6\DiffEqNoiseProcess.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:703
 [2] _require(::Symbol) at .\loading.jl:456
 [3] require(::Symbol) at .\loading.jl:398
 [4] include_from_node1(::String) at .\loading.jl:569
 [5] include(::String) at .\sysimg.jl:14
 [6] anonymous at .\<missing>:2
while loading C:\Users\filimat15173\AppData\Local\JuliaP-0.6.0.1\pkgs-0.6.0.1\v0.6\DifferentialEquations\src\DifferentialEquations.jl, in expression starting on line 9

Failed to precompile DifferentialEquations to C:\Users\filimat15173\AppData\Local\JuliaP-0.6.0.1\pkgs-0.6.0.1\lib\v0.6\DifferentialEquations.ji.
in require at base\loading.jl:398
in _require at base\loading.jl:490
in compilecache at base\loading.jl:703

any suggestion?

Thanks in advance

**Comment by ChrisRackauckas** [comment]
JuliaPro seems to be keeping you back to old versions. There's a newer version of JuliaPro that I think fixed this though?

**Comment by matfill** [comment]
Yes! Now it works! Thank you
