### ISSUE TITLE
Problem occurs when solving ODE with complex number variables

### ISSUE THREAD

**Issue by honghuzi** [JuliaDiffEq/DifferentialEquations.jl#227]
I tried to solve the problem u' = -im * E * u, of which the solution is like u = const * e^(-im * E * t).

My code is:
```
using DifferentialEquations
using Plots; pyplot()

E = 200.0
function Eq(t::Float64, u::Array{Complex128,1}, du::Array{Complex128,1})
    du[1] = -im * E * u[1]
    du[2] = -im * E * u[2]
end

u = [1.0 + 0.0im, 1.5 + 0.0im]
T = 1000.0
prob = ODEProblem(Eq, u, (0, T))
prob.u0[1] = u[1]; prob.u0[2] = u[2]
sol = solve(prob; save_everystep=true, dense=false)

nt2 = length(sol.t)
c1 = zeros(nt2)
c2 = zeros(nt2)
for i in 1:nt2
    c1[i] = abs(sol.u[i][1])
    c2[i] = abs(sol.u[i][2])
end
plot()
plot!(sol.t, c1)
plot!(sol.t, c2)
```

I expected c1 and c2 to be const, but the results computed with DifferentialEquations.jl are not. How would this happen?

**Comment by ChrisRackauckas** [comment]
Crosspost here: https://discourse.julialang.org/t/differentialequations-jl-error-when-solving-equations-with-complex-variables/7939/2 . Since this is a user discussion and not really related to package issues itself, the discussion can continue there.
