### ISSUE TITLE
Dynamic steady state solver

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#228]
A new steady state method could be to just solve the equation until some relative and absolute tol (`du <= abstol && du <=reltol*u`). A user can easily set this up via a callback that checks the derivative size, but this would be nice to have as a generic method on steady state problems.

**Comment by rudrasohan** [comment]
The steady state solver package SteadyStateDiffEq.jl uses nlsolve as it's subroutine for computation of the solution to the steady-state problem. @ChrisRackauckas could you please tell if it's needed to implement a separate function for its computation using abstol and reltol values or does nlsolve has a separate routine for that?

**Comment by ChrisRackauckas** [comment]
Right now it does not make use of the `abstol` and `reltol` but it should. That's just oversight in the current implementation.
