### ISSUE TITLE
Feature request: Slicing for MonteCarloSolutions

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaDiffEq/DifferentialEquations.jl#231]
It would be useful to be able to slice a `MonteCarloSolution`. This feature would be helpful when one wants to filter the solutions obtained in a Monte Carlo simulation.

**Comment by ChrisRackauckas** [comment]
Works and tests added for it in https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/351
