### ISSUE TITLE
WARNING conflicting identifier when compiling DifferentialEquations.jl

### ISSUE THREAD

**Issue by teored90** [JuliaDiffEq/DifferentialEquations.jl#240]
I get the following warning when compiling `DifferentialEquations.jl`  on Julia v0.6.2 after `Pkg.add("DifferentialEquations")`

```
WARNING: using LinAlg.Hessenberg in module IterativeSolvers conflicts with an existing identifier.
```

**Comment by ChrisRackauckas** [comment]
It's harmless so don't worry about it. It's an issue with an upstream package so I notified them and hopefully that gets fixed sooner rather than later. But it shouldn't actually do anything noticeable to us.

**Comment by teored90** [comment]
@ChrisRackauckas yes I imagined that it is harmless but I filed the issue anyway, since I couldn't see any report on this and it seems to be easily fixable.

**Comment by ChrisRackauckas** [comment]
Solved upstream. It will stop warning whenever IterativeSolvers.jl does its next release. Thanks!
