### ISSUE TITLE
Does DEProblem have to be given with explicit indexing?

### ISSUE THREAD

**Issue by zekeriyasari** [JuliaDiffEq/DifferentialEquations.jl#243]
The solution to the problem written as,
```julia
using DifferentialEquations

function func(dx, x, p, t)
    dx = [-1 0; 0 -1] * x
end

x0  = [1., 1.]
tspan = (0., 1.)
prob = ODEProblem{true}(func, x0, tspan)
sol = solve(prob)
println(sol.u)
```
is found as,
```
Array{Float64,1}[
[1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0]]
```
which seems that ODE system does not evolve.  I also tried `ODEProblem{true}(func, x0, tspan)` and it did not change anything.. But, instead, if the function of the problem is expressed with explicit indexing as,
```julia
function func(dx, x, p, t)
    dx[1] = -x[1]
    dx[2] = -x[2]
end
```
the solution is found as,
```
Array{Float64,1}[[1.0, 1.0], [0.904819, 0.904819], [0.710289, 0.710289], [0.519235, 0.519235], [0.36788, 0.36788]]
```
which seems ok. I did not understand the problem with the first function definition. Any ideas?

**Comment by ChrisRackauckas** [comment]
The in-place syntax `func(dx, x, p, t)` does not need to use indexing, but it needs to mutate `dx`. For example:

```julia
function func(dx, x, p, t)
    dx .= [-1 0; 0 -1] * x
end
```

the `.=` mutates `dx` instead of replacing it with a new vector. If you do not want to use mutation, you can instead use the out-of-place syntax which makes the derivative equation to the return value:

```julia
function func(x, p, t)
    [-1 0; 0 -1] * x
end
```

Mutation is a standard feature across and Julia and we recommend using the in-place mutating form for more efficiency when solving systems of equations. However, feel free to use the out-of-place form as necessary. In addition, for small systems, out-of-place with StaticArrays is faster than in-place with arrays anyways, so that's a useful option to consider. 

If there's anything we could do to make the docs more clear please let us know.

**Comment by zekeriyasari** [comment]
Thanks a lot. `.=` solved the problem. I am also in favor of using mutation for performance issues as explained in the docs.

Docs are great but I think it is full of nonlinear examples. In my case, I tried to define a very simple linear problem ``\dot{x}(t) = Ax(t) + Bu(t)`` using mutation. But I could not figure out if the problem has to be defined using explicit indexing. I also did not know to use `.=` notation for the mutation, I knew that Julia's `.` notation is just for vectorization. So, it may be helpful to provide a little bit more explanation (like you gave here) about the other possible ways of defining in-place DEProblem definition using mutating. Thank you very much for your reply.

**Comment by ChrisRackauckas** [comment]
Note that the mutating matrix multiplication is `A_mul_B!`, i.e.

```julia
A_mul_B!(C,A,B)
```

is the same as

```julia 
C = A*B
```

but does so by writing into the existing matrix `C`. `C .= A*B` will create the temporary array for `A*B` and then mutate `C` with the result, so it's not the same. What I showed above is similar to this and should be avoided if you want full efficiency.

I can create an example notebook that demonstrates a lot of these techniques if it seems necessary.

**Comment by zekeriyasari** [comment]
Your last reply (the part, `A_mul_B!`) reminded me the `Frequently Asked Questions` of the docs and I realized that there was a question `My ODE is solving really slow... what do I do?` where some great performance tips are explained. But that example notebook you mentioned elaborating on these techniques would be priceless. I appreciate  for all these invaluable efforts.

**Comment by ChrisRackauckas** [comment]
See http://nbviewer.jupyter.org/github/JuliaDiffEq/DiffEqTutorials.jl/blob/master/Introduction/OptimizingDiffEqCode.ipynb
