### ISSUE TITLE
Implementing predictor corrector method for SDEs

### ISSUE THREAD

**Issue by onoderat** [JuliaDiffEq/DifferentialEquations.jl#247]
The predictor corrector method of order 0.5 from [Stochastics and Dynamics, Vol. 8, No. 3 (2008) 561–581](http://www.worldscientific.com/doi/pdf/10.1142/S0219493708002457) is a useful solver because it has better stability than EM. It also has order 1 scaling for many problems even though it is proven to be order 0.5. This is convenient as the solver does not require any Wiktorsson approximations for general non-commuting SDEs.

**Comment by ChrisRackauckas** [comment]
Thanks for the issue. From the Gitter: do you want to take a stab at implementing or should I take it?

**Comment by onoderat** [comment]
I would like to give it a shot for a couple of days since I want to learn more about the DiffEq ecosystem.

**Comment by ChrisRackauckas** [comment]
Alright, let me know if you need more help than the devdocs.

**Comment by ChrisRackauckas** [comment]
Complete! https://github.com/JuliaDiffEq/StochasticDiffEq.jl/pull/53
