### ISSUE TITLE
Non-constant initial conditions and time spans

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#251]
It would be nice to allow a function be used for the initial condition. I think what we can do is check `u0 <: Function`, and if so, call it to generate the initial condition. I think a good syntax would be something like
`u0(p,t0)`. 

Additionally, we could allow a `Distribution` to be used for the initial condition, in which case the initial condition is generated by sampling from the distribution. This may be helpful for parameter estimation stuff.

@simonbyrne

**Comment by ChrisRackauckas** [comment]
Would allowing `nothing` (and making it optional) and a function `get_timespan(p0)` for initial time spans be something that would make DiffEq work better for DynamicalSystems.jl? @Datseris @tkf

**Comment by Datseris** [comment]
@ChrisRackauckas Thanks so much for considering DynSys! Optional `tspans` would be awesome, however, it would not be possible to have `nothing` about the initial time, since for non-autonomous systems you need it as well to uniquely define the problem.

On the other side, having a *default* initial time 0 and optional ending time that could be `nothing` or `Inf` by default would be awesome, and also useful from my perspective.  Also, now in DynSys I got the function `inittime(prob)` that returns `tspan[1]`, similar to your suggestion, because it is very useful to have a handy shortcut for initial time.

**Comment by ChrisRackauckas** [comment]
Dispatch on number `x` to mean `(promote_type(0,x),x)`, and dispatch on `nothing` to mean `(nothing,nothing)`? So then:

1. Allow `u0 = u0(p,t0)`
2. Allow `tspan = tspan(p)`
3. Allow `tspan = x => (0,x)` with promotion
4. Allow `tspan = nothing => (nothing,nothing)`. This will error anywhere it's used unless you `remake`.
5. Default arg it: `tspan = nothing`?

I am scared caching "forgetting tspan" will be an issue.

>On the other side, having a default initial time 0 and optional ending time that could be nothing or Inf by default would be awesome, and also useful from my perspective.

Defaulting to `Inf` is a good way to cause people's simulations to run infinitely long for any accident.

**Comment by Datseris** [comment]
Seems like a nice idea! I especially like the `tspan = x => (0,x)` and the `u0 = u0(p,t0)`!

This also seems like a tough change to make though, no?

> Defaulting to Inf is a good way to cause people's simulations to run infinitely long for any accident.

Seems a very good point! 

But I think I have not understood:  what is the default value for `tspan[2]` then?

**Comment by ChrisRackauckas** [comment]
>This also seems like a tough change to make though, no?

Nope. Someone just needs to go in and do:

```julia
# Inner constructor, inside of the struct definition
ODEProblem{iip}(f,u0,tspan2::Number,args...;kwargs...) = ODEProblem{iip}(f,u0,(0,tspan2);kwargs...)
ODEProblem{iip}(f,u0,tspan2=nothing,args...;kwargs...) = ODEProblem{iip}(f,u0,(nothing,nothing);kwargs...)
# Outer
ODEProblem(f,u0,tspan2::Number;kwargs...) = ODEProblem(f,u0,(0,tspan2);kwargs...)
ODEProblem(f,u0,tspan2=nothing,args...;kwargs...) = ODEProblem(f,u0,(nothing,nothing);kwargs...)
```

Since this scheme is type-matching and still `Tuple{tType,tType}` it works. The only thing I don't like about this is that if they call `init`/`solve`/etc. on this with `(nothing,nothing)`, they will get a cryptic message about `Void` not being a container when the keyword arguments of `init` are calculated. In order to fix that and not have an ambiguity problem, we'd need to go to every solver package and place a dispatch on their algorithms to throw the error `error("Problems with tType=Void cannot be solved. Please give a timespan")`, unless someone knows how to solve this at a higher level with metaprogramming.

**Comment by Datseris** [comment]
You think it is not a better idea to not allow `(nothing, nothing)` altogether, and instead have `(0.0, 1.0)` as the default? Or some other number you deem fitting? Then it also fits nicely with the other options like e.g. the just number.

**Comment by ChrisRackauckas** [comment]
>EDIT: Hm, but this 1.0 really depends on the problem. What if someone has a problem that operates on a crazy small timescale.

Yes, I did this before because it made for easy testing. This is a bad idea.

**Comment by Datseris** [comment]
What about `(0, eps(0)` with appropriate Typing of course?

**Comment by ChrisRackauckas** [comment]
Anything that automatically runs without the user setting a timespan is suspect.

**Comment by tkf** [comment]
I don't think there are any good default for `tspan`.  I mean, 0 and 1 are the only meaningful identities in reals...  If you want to make it optional at problem creation time, I think making `tspan` keyword argument for `init` mandatory is the right way to go.  Does this work?:

```julia
init(prob::AbstractODEProblem{uType, Void, isinplace}, args...;
     tspan = error("Please specify keyword argument tspan: init(prob, ...; tspan = (t0, t1), ...)");
     kwargs...) where {uType, isinplace} =
  init(remake(prob; tspan = tspan), args...; kwargs...)
```

If this approach does not work for all problem types, how about (1) changing solver packages to extend `_solve[!]` and `_init` and (2) wrapping them into `solve[!]` and `init` in DiffEqBase with user-friendly error messages?  I guess it is still a *huge* change but it would help you if you want similar extension in the future.  Maybe most of the part can be done by `sed -i`.

I really like `u0(p,t0)` idea.  I also wonder `u0(rng, p, t0)` make sense especially if you are interested in random initialization.  On one hand, it sounds too specialized.  But on the other hand, I wouldn't be surprised if `u0(rng, p, t0)` is more than 90% of the whole use-cases.

**Comment by ChrisRackauckas** [comment]
>I really like u0(p,t0) idea. I also wonder u0(rng, p, t0) make sense especially if you are interested in random initialization. On one hand, it sounds too specialized. But on the other hand, I wouldn't be surprised if u0(rng, p, t0) is more than 90% of the whole use-cases.

Why would it need to be a function of `rng` instead of just enclosing an `rng` object? Or that case also falls under "return a distribution" anyways.

**Comment by Datseris** [comment]
Do you think not having some initial default time (zero) will be helpful?

Integrators do not care about final time but do care about initial time. 

and the function suggestion `Allow u0 = u0(p,t0)` also needs an initial time.

**Comment by ChrisRackauckas** [comment]
>Do you think not having some initial default time (zero) will be helpful?

Giving just a number will assume that `t0=0`, that's what we discussed before. In the problem type or in the keyword, that seems to make sense either way.

>Integrators do not care about final time but do care about initial time.

They do care about a final time since they add the `tstop` there. 

>and the function suggestion Allow u0 = u0(p,t0) also needs an initial time.

Yup that's in the suggestion.

**Comment by tkf** [comment]
> Why would it need to be a function of rng instead of just enclosing an rng object? Or that case also falls under "return a distribution" anyways.

Yea, a callable/functor wrapping a rng works.  It was just me thinking out loud.  Dispatching on the return type of `u0(p, t0)` and do the sampling if it is a distribution (and/or sampleable?) seems to be a great idea.  I missed that point.
