### ISSUE TITLE
Add parameter field for CVODE_BDF integrator

### ISSUE THREAD

**Issue by Gaussia** [JuliaDiffEq/DifferentialEquations.jl#253]
Might be talking about things of which I do not know so much. However, the integrator for the `CVODE_BDF` solver for ordinary Differential Equations do not have a field p, which means that you can not access the parameters of the problem if you are using this specific solver (unlike some other solvers). This can be used by e.g. callbacks modifying parameter values. As I've said there might be a good reason for this, just raising the issue if that is not the case.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/Sundials.jl/issues/153 I (or someone else) just need to get around to it. It's not particularly difficult though, and for now `integrator.sol.prob.p` works.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/Sundials.jl/commit/b6bc35770cbeacb77de57a3a5e9e4e71860fbe51
