### ISSUE TITLE
Give solver a list of dts

### ISSUE THREAD

**Issue by onoderat** [JuliaDiffEq/DifferentialEquations.jl#255]
For some systems I study, I sometime apply a strong pulse at a particular time to excite the system. Thus, I know exactly when I need to use smaller dt during the engineered pulse kick time, while to use larger dt after the system stabilizes. Essentially this is adaptive time-stepping done ad-hoc. 

Would it be possible to add a additional solve keyword argument so that the user can supply a list of dts? I have looked roughly at the source code for StochasticDiffEq and see that there is a tType. Is there a simple solution to this issue by generalizing this tType?

**Comment by ChrisRackauckas** [comment]
Pass `tstops`?

**Comment by onoderat** [comment]
Great :) I will be using that in the future then.
