### ISSUE TITLE
Computing jacobians by finite differences with out of place functions

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaDiffEq/DifferentialEquations.jl#259]
Apologies if this is not the proper place for this / is somewhere in the docs already: I searched but couldn't find anything in a decent amount of time, hence this issue.

I want to solve a differential equation for playing around with the adiabatic theorem of quantum mechanics, so something like `i dgamma/dt = [H(eps t), gamma(t)]`, with gamma and H 2x2 complex matrices, H(t) being prescribed. It works nicely with a nonstiff solver, but obviously these equations are very oscillatory and I wanted to play with nonstiff solvers to see if that did anything. I don't want to bother computing the jacobian (and I'm not actually sure how in which format I should build it given that the variable is itself a matrix). Forward diff doesn't work because the variable is complex. I was hoping https://github.com/JuliaDiffEq/DiffEqDiffTools.jl could support that out of the box by finite differences, is that integrated in the DiffEq main package? How should I access it?

**Comment by ChrisRackauckas** [comment]
It's in there. But if you couldn't find it then we should edit the docs to make it more obvious. I also thing we should do a part 2 of the ODE tutorial for some more advanced topics like this.

http://docs.juliadiffeq.org/latest/solvers/ode_solve.html#Extra-Options-1

http://docs.juliadiffeq.org/latest/basics/faq.html#I-get-Dual-number-errors-when-I-solve-my-ODE-with-Rosenbrock-or-SDIRK-methods...?-1

**Comment by antoine-levitt** [comment]
Thanks! I looked in performance overloads, in the solver options, used the documentation search for "finite differences" and googled things like "julia DifferentialEquations finite difference jacobians", no luck.

So now with autodiff=false it's giving me a different error:

`ERROR: LoadError: MethodError: no method matching extract_derivative(::Type{ForwardDiff.Tag{DiffEqDiffTools.TimeDerivativeWrapper{#fun#2289{Float64,Float64,#∂gamma∂t#2288},StaticArrays.SArray{Tuple{2,2},Complex{Float64},2,4},Void},Float64}}, ::Complex{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.TimeDerivativeWrapper{#fun#2289{Float64,Float64,#∂gamma∂t#2288},StaticArrays.SArray{Tuple{2,2},Complex{Float64},2,4},Void},Float64},Float64,1}})`

Is this because I'm using a StaticArray matrix?

**Comment by antoine-levitt** [comment]
That still doesn't appear to work: even with `sol = solve(prob,Rosenbrock23(autodiff=false))`, I still get the same error:

`ERROR: LoadError: MethodError: no method matching extract_derivative(::Type{ForwardDiff.Tag{DiffEqDiffTools.TimeDerivativeWrapper{#fun#2469{Float64,Float64,#∂gamma∂t#2468},StaticArrays.SArray{Tuple{2,2},Complex{Float64},2,4},Void},Float64}}, ::Complex{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.TimeDerivativeWrapper{#fun#2469{Float64,Float64,#∂gamma∂t#2468},StaticArrays.SArray{Tuple{2,2},Complex{Float64},2,4},Void},Float64},Float64,1}})`

**Comment by ChrisRackauckas** [comment]
Interesting. That shouldn't have any dual numbers. Can I get an MWE?

**Comment by antoine-levitt** [comment]
```
using StaticArrays
using ProfileView

fun(gamma,p,t) = imag(gamma)
gamma0 = @SMatrix [1.0+im 0;0 1]
# gamma0 = eye(2,2)
prob = ODEProblem(fun,gamma0,(0.,1.))
sol = solve(prob,Rosenbrock23(autodiff=false))
```

There seems to be a few bugs in there as even the uncommented line does not work. Everything works fine with non-stiff solvers.

**Comment by ChrisRackauckas** [comment]
Oh, this issue is that out of place functions are currently hardcoded to use ForwardDiff.jl because the previous differentiation tools couldn't handle it. With DiffEqDiffTools.jl we need to re-write these parts.

**Comment by antoine-levitt** [comment]
Thanks, it does work with inplace! (though inplace will not work with StaticArrays)

**Comment by ChrisRackauckas** [comment]
Yeah, I don't plan on having this as a long-term thing. Now that we've settled on a differentiation setup, this part of each solver needs to be refactored and then we can uniformly fix all of these together.
