### ISSUE TITLE
Should setting dt turn off adaptive timestepping?

### ISSUE THREAD

**Issue by jebej** [JuliaDiffEq/DifferentialEquations.jl#264]
I almost always find myself passing both `adaptive=false` and `dt=dt`. Wouldn't it make more sense to turn off adaptive timestepping if you are passing a `dt`?

It seems to me that if you are passing this option, it's because you want the stepsize to be `dt`.

**Comment by ChrisRackauckas** [comment]
I'm not sure about this. It's a very good idea to pass a `dt` for starting with adaptive timestepping in many cases since the heuristic algorithm for choosing a starting `dt` is just a heuristic which can be too conservative in some cases.

**Comment by jebej** [comment]
Thanks for the quick reply Chris.

> It's a very good idea to pass a dt for starting with adaptive timestepping

But is it a bad idea to pass `dt` and not have the adaptive timestepping on? It seems to me that if you are passing `dt`, it is because you know it's a good value, and so it should work without adaptive timestepping.

**Comment by jebej** [comment]
Maybe another option could be introduced that does that :P
I was really just thinking about having shorter `solve(...)` calls, since they usually involve many arguments, and `adaptive=false` is longish, but I'm nitpicking.
As always, thanks for the hard work!

**Comment by jebej** [comment]
The current meaning could get renamed to `dt_init` maybe?

**Comment by ChrisRackauckas** [comment]
That's a possibility. But out of curiosity, what are you turning adaptivity off so often for?

**Comment by jebej** [comment]
The main motivation is that for the same number of steps, turning off adaptivity executes faster. I also turn it off just because I know a good stepping value and so do not need it.

**Comment by ChrisRackauckas** [comment]
How much faster? And for the same error? It shouldn't be much faster if the `f` function is not tiny.

**Comment by jebej** [comment]
I haven't done benchmarks recently, but I used to see 10-15% difference. I might do some soon, I need to update my package to the last version of DifferentialEquations, but have no time at the moment.

> And for the same error?

For a particular solving method, isn't the error entirely determined by the step size?

**Comment by ChrisRackauckas** [comment]
>For a particular solving method, isn't the error entirely determined by the step size?

Yes, but not the number of steps. The steps can be distributed differently which can change the total error. How many ODEs is it though? The adaptivity part should be a really quick computation in most cases.

**Comment by jebej** [comment]
I'll check again and get back to you.

**Comment by AnderMuruaUria** [comment]
When numerically integrating  with adaptivity=true, in some particular problems the step-sizes oscillates with small amplitude around a value, which indicates that adaptivity was not needed after all. In such cases (if after numerically integrating it with adaptivity=true, we check that all the components of the vector of step-sizes sol.t[2:end]-sol.t[1:(end-1)] have similar values), and we want the output in a uniform time discretization, integrating the problem with adaptivity=false makes more sense (it is cleaner, and more accurate because interpolation is avoided).

As for the calling sequence, I agree with Chris that  since the docs are clear about dt is is fine as it is. Another option might be the following:  by default, adaptivity=true, unless dt is explicitly given by the user, in which case, by default adaptivity=false. If both adaptivity=true and dt=h is explicitly set by the user, then h is meant to be the initial step-size.

**Comment by ChrisRackauckas** [comment]
```julia
julia> @benchmark a^b setup = (a=rand();b=rand())
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     68.494 ns (0.00% GC)
  median time:      77.726 ns (0.00% GC)
  mean time:        80.968 ns (0.00% GC)
  maximum time:     187.020 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     983

julia> @benchmark a*b setup = (a=rand();b=rand())
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.170 ns (0.00% GC)
  median time:      1.464 ns (0.00% GC)
  mean time:        1.701 ns (0.00% GC)
  maximum time:     19.320 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```

If your problem is cheap enough, the 2 floating point exponents for the adaptivity calculation can be expensive. This is only when `f` is super cheap of course, but it's within the realm of possibility and a lot of the small 2-3 ODE examples seem to exhibit some of this.

**Comment by YingboMa** [comment]
I'd like to keep the current version. `dt=0.1, adaptive=false` seems fine.

**Comment by sipah00** [comment]
I agree with @YingboMa.

**Comment by ChrisRackauckas** [comment]
In the chats and stuff it seems like the current setup is fine, so we won't make the change for DiffEq v5.0 and I'll close this. But if this comes up again (i.e. if I hear more people getting confused about this) I'd be happy to revisit it for a future major release.
