### ISSUE TITLE
JuliaPro 0.6.2.2 is incompatible with DiffEq 4.0

### ISSUE THREAD

**Issue by valfaro** [JuliaDiffEq/DifferentialEquations.jl#265]
Your tutorial first example gave me an error on solve:

Code:

using DifferentialEquations
f(u,p,t) = 1.01*u
u0=1/2
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),reltol=1e-8,abstol=1e-8)

Error:

MethodError: no method matching f(::Float64, ::Float64)
Closest candidates are:
  f(::Any, ::Any, !Matched::Any) at C:\Users\victo\OneDrive\Documentos\J-juliadocs_18\03-jpidcs_jpro\jODE_test01.jl:4
in  at base\<missing>
in  at base\<missing>
in #solve#1830 at OrdinaryDiffEq\src\solve.jl:6
in  at base\<missing>
in #init#1831 at OrdinaryDiffEq\src\solve.jl:279
in initialize! at OrdinaryDiffEq\src\integrators\low_order_rk_integrators.jl:683

**Comment by ChrisRackauckas** [comment]
I believe you're on an old version. What does `Pkg.status("OrdinaryDiffEq")` say?

**Comment by valfaro** [comment]
- DifferentialEquations 4.1.0 master

Dr. Víctor M. Alfaro
victor.alfaro@ucr.ac.cr
web: https://pidplanet.wordpress.com

De: Christopher Rackauckas
Enviado: viernes, 2 de marzo de 2018 13:54
Para: JuliaDiffEq/DifferentialEquations.jl
CC: valfaro; Author
Asunto: Re: [JuliaDiffEq/DifferentialEquations.jl] solve MethodError (#265)

I believe you're on an old version. What does Pkg.status("OrdinaryDiffEq") say?

**Comment by ChrisRackauckas** [comment]
What does`Pkg.status("OrdinaryDiffEq")` say?

**Comment by valfaro** [comment]
- OrdinaryDiffEq 2.26.0

Dr. Víctor M. Alfaro
victor.alfaro@ucr.ac.cr
web: https://pidplanet.wordpress.com

De: Christopher Rackauckas
Enviado: viernes, 2 de marzo de 2018 13:54
Para: JuliaDiffEq/DifferentialEquations.jl
CC: valfaro; Author
Asunto: Re: [JuliaDiffEq/DifferentialEquations.jl] solve MethodError (#265)

I believe you're on an old version. What does Pkg.status("OrdinaryDiffEq") say?

**Comment by ChrisRackauckas** [comment]
Yes, the ODE solvers are being held back. Does `Pkg.update()` not fix it? Could I get the full `Pkg.status()` listing to see if there's a clear reason? 

Note that right now we are not compatible with the latest JuliaPro since that pins back some of the libraries.

**Comment by valfaro** [comment]
Pkg.update() info

Unsatisfiable requirements detected for package NLSolversBase:

Pkg.status() info

193 required packages: - ASTInterpreter2 0.1.1 - AbstractFFTs 0.2.0 - Atom 0.6.6 - AutoGrad 0.0.9 - AutoHashEquals 0.2.0 - AxisAlgorithms 0.2.0 - AxisArrays 0.2.0 - BinDeps 0.8.1 - Blink 0.5.4 - Blosc 0.3.0 - BufferedStreams 0.3.3 - BusinessDays 0.7.3 - CSV 0.1.5 - Calculus 0.2.2 - CatIndices 0.1.0 - CategoricalArrays 0.1.6 - Clustering 0.9.1 - CodeTools 0.4.7 - CodecZlib 0.4.1 - Codecs 0.4.0 - ColorTypes 0.6.6 - ColorVectorSpace 0.5.2 - Colors 0.8.2 - Combinatorics 0.5.0 - CommonSubexpressions 0.0.1 - Compat 0.39.0 - Compose 0.5.4 - ComputationalResources 0.2.0 - Conda 0.7.1 - Contour 0.4.0 - ControlSystems 0.3.0+ master - CoordinateTransformations 0.4.1 - CoupledFields 0.0.1 - CustomUnitRanges 0.1.0 - DBAPI 0.1.0 - DSP 0.3.4 - Dagger 0.5.0 - DataArrays 0.6.2 - DataFlow 0.3.0 - DataFrames 0.10.1 - DataStreams 0.1.3 - DataStructures 0.7.3 - DataValues 0.3.1 - DebuggerFramework 0.1.2 - DecisionTree 0.6.5 - DiffBase 0.2.0 - DifferentialEquations 4.1.0 master - Distances 0.5.0 - Distributions 0.15.0 - DocSeeker 0.1.0 - DualNumbers 0.3.0 - FFTViews 0.1.0 - FFTW 0.0.4 - FileIO 0.6.1 - FixedPointNumbers 0.4.3 - Flux 0.3.4 - Formatting 0.3.0 - ForwardDiff 0.5.0 - GLM 0.8.1 - GR 0.26.0 - GZip 0.3.0 - Gadfly 0.6.4 - Gallium 0.1.0 - Glob 1.1.1 - Graphics 0.2.0 - HDF5 0.8.8 - Hexagons 0.1.0 - Hiccup 0.1.1 - HttpCommon 0.3.0 - HttpParser 0.3.0 - HttpServer 0.2.0 - HypothesisTests 0.6.0 - IJulia 1.6.2 - IdentityRanges 0.1.0 - ImageAxes 0.4.0 - ImageCore 0.5.0 - ImageFiltering 0.2.3 - ImageMetadata 0.4.0 - ImageMorphology 0.0.2 - ImageTransformations 0.4.1 - Images 0.11.5 - IndexedTables 0.4.4 - IndirectArrays 0.3.0 - Interact 0.6.3 - Interpolations 0.7.2 - IntervalSets 0.1.1 - IterTools 0.2.0 - IteratorInterfaceExtensions 0.0.2 - Iterators 0.3.1 - JDBC 0.2.1 - JLD 0.8.3 - JSON 0.16.3 - JavaCall 0.5.2 - JuMP 0.18.0 - JuliaWebAPI 0.3.6 - Juno 0.3.2 - KernelDensity 0.4.0 - Knet 0.8.5 - LNR 0.0.2 - LaTeXStrings 0.3.0 - Lazy 0.12.0 - LearnBase 0.1.6 - LegacyStrings 0.3.0 - LibExpat 0.4.0 - Libz 0.2.4 - LightGraphs 0.11.1 - LightXML 0.5.0 - LineSearches 3.2.3 - Loess 0.3.0 - Logging 0.3.1 - LossFunctions 0.2.0 - MLBase 0.7.0 - MNIST 0.0.2 - MacroTools 0.4.0 - MappedArrays 0.0.7 - MathProgBase 0.7.0 - MbedTLS 0.5.1 - Measures 0.1.0 - Media 0.3.0 - MemPool 0.0.4 - Mustache 0.3.0 - Mux 0.2.3 - NLSolversBase 3.1.0 - NLopt 0.3.6 - NNlib 0.2.0 - NaNMath 0.3.0 - NamedArrays 0.6.1 - NamedTuples 4.0.0 - NearestNeighbors 0.3.0 - Nettle 0.3.0 - NullableArrays 0.1.2 - Nullables 0.0.1 - Nulls 0.1.2 - ODBC 0.5.2 - OffsetArrays 0.4.2 - OnlineStats 0.13.2 - OnlineStatsBase 0.3.1 - Optim 0.11.0 - PDMats 0.7.1 - PaddedViews 0.2.0 - Parameters 0.8.1 - ParserCombinator 1.7.11 - PenaltyFunctions 0.0.2 - Plots 0.15.0+ master - Polynomials 0.1.6 - PooledArrays 0.1.1 - PositiveFactorizations 0.1.0 - Primes 0.2.0 - ProtoBuf 0.4.0 - PyCall 1.15.0 - PyPlot 2.3.2 - QuadGK 0.1.3 - QuantEcon 0.14.0 - RCall 0.8.1 - RangeArrays 0.2.0 - Ratios 0.2.0 - Reactive 0.6.0 - RealInterface 0.0.3 - RecipesBase 0.2.3 - Reexport 0.0.3 - Requests 0.5.1 - Requires 0.4.3 - ReverseDiffSparse 0.8.0 - Rmath 0.3.0 - Roots 0.4.1 - Rotations 0.6.1 - SHA 0.5.2 - SIUnits 0.1.0 - ScikitLearnBase 0.3.0 - ShowItLikeYouBuildIt 0.2.0 - Showoff 0.1.1 - SimpleTraits 0.5.1 - SortingAlgorithms 0.2.0 - SpecialFunctions 0.3.5 - StaticArrays 0.6.6 - StatsBase 0.19.2 - StatsFuns 0.5.0 - StringDistances 0.2.0 - SweepOperator 0.1.0 - TableTraits 0.0.3 - TableTraitsUtils 0.1.2 - TexExtensions 0.1.0 - TextParse 0.3.5 - TiledIteration 0.1.0 - Tokenize 0.4.2 - TranscodingStreams 0.4.1 - URIParser 0.3.0 - WeakRefStrings 0.2.0 - WebSockets 0.4.0 - WinRPM 0.3.1 - WinReg 0.2.0 - WoodburyMatrices 0.2.2 - ZMQ 0.5.1 47 additional packages: - AlgebraicDiffEq 0.1.0 - BandedMatrices 0.4.0 - BinaryProvider 0.1.4 - BoundaryValueDiffEq 0.2.0 - ChunkedArrays 0.1.1 - DecFP 0.3.0 - DelayDiffEq 1.6.0 - DiffEqBase 3.6.2 - DiffEqBiological 1.0.0 - DiffEqCallbacks 0.6.1 - DiffEqDevTools 0.11.3 - DiffEqDiffTools 0.1.2 - DiffEqFinancial 1.0.0 - DiffEqJump 1.1.0 - DiffEqMonteCarlo 0.10.0 - DiffEqNoiseProcess 1.0.0 - DiffEqPDEBase 0.3.5 - DiffEqParamEstim 1.0.0 - DiffEqPhysics 0.1.0 - DiffEqSensitivity 0.5.1 - DiffEqUncertainty 0.1.0 - DimensionalPlotRecipes 0.0.2 - DistributedArrays 0.4.0 - EllipsisNotation 0.3.0 - FillArrays 0.0.1 - FiniteElementDiffEq 0.4.0 - FunctionWrappers 0.1.0 - GenericSVD 0.1.0 - IterativeSolvers 0.5.0 - LinearMaps 1.0.4 - LsqFit 0.3.0 - MuladdMacro 0.0.2 - MultiScaleArrays 0.6.0 - NLsolve 0.12.1 - OptimBase 1.0.0 - OrdinaryDiffEq 2.26.0 - ParameterizedFunctions 3.0.0 - PlotThemes 0.2.0 - PlotUtils 0.4.4 - RandomNumbers 0.1.1 - RecursiveArrayTools 0.12.4 - ResettableStacks 0.3.1 - SteadyStateDiffEq 0.1.0 - StochasticDiffEq 2.16.0 - Sundials 1.3.0 - SymEngine 0.3.0 - VectorizedRoutines 0.0.2

Dr. Víctor M. Alfaro
victor.alfaro@ucr.ac.cr
web: https://pidplanet.wordpress.com

De: Christopher Rackauckas
Enviado: viernes, 2 de marzo de 2018 14:07
Para: JuliaDiffEq/DifferentialEquations.jl
CC: valfaro; Author
Asunto: Re: [JuliaDiffEq/DifferentialEquations.jl] solve MethodError (#265)

Yes, the ODE solvers are being held back. Does Pkg.update() not fix it? Could I get the full Pkg.status() listing to see if there's a clear reason?
Note that right now we are not compatible with the latest JuliaPro since that pins back some of the libraries.

**Comment by ChrisRackauckas** [comment]
@pkofod do you know what's still holding NLSolversBase.jl back? Some upper bound on Optim or NLsolve?

**Comment by pkofod** [comment]
This is probably LsqFit. If you don't really need it @valfaro you can remove that package... If not.. I can fix it "soon", but I'm absolutely swamped.

**Comment by ChrisRackauckas** [comment]
LsqFit is fine. That's a standard dep of DiffEq. I can't find what has the upper bound... deleting `.julia/v0.6` and then re-adding packages will allow it to upgrade but that's a very heavy handed method for this.

**Comment by pkofod** [comment]
ah, yes, I see he's on the correct OptimBase/LsqFit combination. NLsolve is an old version though? But NLsolve doesn't have an upper bound, so there has to be another package in the mix.

**Comment by ChrisRackauckas** [comment]
Maybe it's just a resolver issue? @valfaro can you try:

```julia
ENV["JULIA_PKGRESOLVE_ACCURACY"] = "3"; Pkg.update()
```

**Comment by valfaro** [comment]
I try your suggestion, and get
Unsatisfiable requirements detected for package NLSolversBase:
├─version range [3.1.0,3.1.0+) set by an explicit requirement └─version range [4.2.0,∞) required by package DelayDiffEq, whose allowed version range is [2.0.0,∞): └─version range [2.0.0,∞) required by package DifferentialEquations, whose only allowed version is 4.1.0: ├─version 4.1.0 set by fixed requirement (package is checked out, dirty or pinned) └─version range [0.0.0-,∞) set by an explicit requirement The intersection of the requirements is empty.
in update at base\pkg\pkg.jl:228
in #cd#1 at base\pkg\dir.jl:32
in withenv at base\env.jl:157
in cd at base\file.jl:59
in at base\pkg\dir.jl:33
in update at base\pkg\entry.jl:461
in resolve at base\pkg\entry.jl:498
in prune_dependencies at base\pkg\query.jl:546
in prune_versions at base\pkg\query.jl:328
in filter_versions at base\pkg\query.jl:299
 


Dr. Víctor M. Alfaro
victor.alfaro@ucr.ac.cr
web: https://pidplanet.wordpress.com

De: Christopher Rackauckas
Enviado: sábado, 3 de marzo de 2018 06:58
Para: JuliaDiffEq/DifferentialEquations.jl
CC: valfaro; Mention
Asunto: Re: [JuliaDiffEq/DifferentialEquations.jl] solve MethodError (#265)

Maybe it's just a resolver issue? @valfaro can you try:
ENV["JULIA_PKGRESOLVE_ACCURACY"] = "3"; Pkg.update()

**Comment by ChrisRackauckas** [comment]
```
├─version range [3.1.0,3.1.0+) set by an explicit requirement
```

Aha, that gives us a lot to go off of though. There's something out there which explicitly is saying NLSolversBase cannot go higher than 3.1.0. We need to grep METADATA branch metadata-v2 for that upper bound

**Comment by pkofod** [comment]
Hm, I dont remember setting such a limit

**Comment by ChrisRackauckas** [comment]
@valfaro just to double check again, you're not using JuliaPro?

I created a dep checker:

```julia
cd()
cd(".julia/v0.6/METADATA")
packages = Pkg.dependents("NLSolversBase")
for p in packages
  println(p)
  cd("$p/versions")
  versions = readdir()
  for v in versions
    println(v)
    cd(v)
    new_requires = open("requires") do f
      new_requires = ""
      has_dep = false
      for ln in eachline(f)
        vals = split(ln," ")
        if vals[1] == "NLSolversBase"
          println(ln)
        end
      end
    end
    cd("..")
  end
  cd("../../")
end
```

```julia
DelayDiffEq
0.0.1
0.1.0
0.10.0
0.2.0
0.3.0
0.4.0
0.5.0
0.5.1
0.5.2
0.6.0
0.7.0
0.8.0
0.9.0
0.9.1
1.0.0
1.0.1
1.1.0
1.10.0
1.11.0
1.11.1
1.12.0
1.2.0
1.2.1
1.3.0
1.4.0
1.5.0
1.6.0
1.7.0
1.8.0
1.8.1
1.9.0
2.0.0
NLSolversBase 4.2.0
2.1.0
NLSolversBase 4.2.0
LineSearches
0.0.1
NLSolversBase 0.0.1 3.0
0.0.2
NLSolversBase 0.0.1 3.0
0.1.0
NLSolversBase 0.0.1 3.0
0.1.1
NLSolversBase 0.0.1 3.0
0.1.2
NLSolversBase 0.0.1 3.0
0.1.3
NLSolversBase 0.0.1 3.0
0.1.4
NLSolversBase 0.0.1 3.0
0.1.5
NLSolversBase 0.0.1 3.0
1.0.0
NLSolversBase 1.0 2.0
2.0.0
NLSolversBase 2.0 3.0
2.1.0
NLSolversBase 2.0 3.0
2.1.1
NLSolversBase 2.0 3.0
2.2.0
NLSolversBase 2.0 3.0
2.2.1
NLSolversBase 2.0 3.0
3.0.0
NLSolversBase 3.0
3.0.1
NLSolversBase 3.0
3.1.0
NLSolversBase 3.0
3.2.0
NLSolversBase 3.0
3.2.1
NLSolversBase 3.0
3.2.2
NLSolversBase 3.0
3.2.3
NLSolversBase 3.0
3.2.4
NLSolversBase 3.0
3.2.5
NLSolversBase 3.0
OptimBase
0.1.0
NLSolversBase 2.0 4.0
1.0.0
NLSolversBase
NLsolve
0.1.0
0.1.1
0.1.2
0.1.3
0.1.4
0.10.0
NLSolversBase 0.0.1 3.0
0.10.1
NLSolversBase 2.1.0 3.0
0.11.0
NLSolversBase 2.1.0 3.0
0.12.0
NLSolversBase 2.1.0 4.0
0.12.1
NLSolversBase 2.1.0 4.0
0.13.0
NLSolversBase 2.1.0 4.0
0.14.0
NLSolversBase 4.0.0
0.14.1
NLSolversBase 4.0.0
0.2.0
0.3.0
0.3.1
0.3.2
0.3.3
0.4.0
0.5.0
0.6.0
NLSolversBase 0.0.1 3.0
0.6.1
NLSolversBase 0.0.1 3.0
0.7.0
NLSolversBase 0.0.1 3.0
0.7.1
NLSolversBase 0.0.1 3.0
0.7.2
NLSolversBase 0.0.1 3.0
0.7.3
NLSolversBase 0.0.1 3.0
0.8.0
NLSolversBase 0.0.1 3.0
0.9.0
NLSolversBase 0.0.1 3.0
0.9.1
NLSolversBase 0.0.1 3.0
1.0.0
NLSolversBase 4.0.0
1.0.1
NLSolversBase 4.0.0
Optim
0.0.0
0.1.0
0.1.1
0.1.2
0.1.3
0.1.4
0.1.5
0.1.6
0.1.7
0.10.0
NLSolversBase 3.0.0 4.0
0.10.1
NLSolversBase 3.0.0 4.0
0.11.0
NLSolversBase 3.0.0 4.0
0.12.0
NLSolversBase 4.0.0
0.13.0
NLSolversBase 4.0.0
0.14.0
NLSolversBase 4.0.0
0.2.0
0.3.0
0.3.1
0.4.0
0.4.1
0.4.2
0.4.3
0.4.4
0.4.5
NLSolversBase 0.0.1 3.0
0.4.6
NLSolversBase 0.0.1 3.0
0.4.7
NLSolversBase 0.0.1 3.0
0.5.0
NLSolversBase 0.0.1 3.0
0.6.0
NLSolversBase 0.0.1 3.0
0.6.1
NLSolversBase 0.0.1 3.0
0.7.0
NLSolversBase 0.0.1 3.0
0.7.1
NLSolversBase 0.0.1 3.0
0.7.2
NLSolversBase 0.0.1 3.0
0.7.3
NLSolversBase 0.0.1 3.0
0.7.4
NLSolversBase 0.0.1 3.0
0.7.5
NLSolversBase 0.0.1 3.0
0.7.7
NLSolversBase 0.0.1 3.0
0.7.8
NLSolversBase 0.0.1 3.0
0.9.0
NLSolversBase 2.1.0 3.0
0.9.1
NLSolversBase 2.1.0 3.0
0.9.2
NLSolversBase 2.1.0 3.0
0.9.3
NLSolversBase 2.1.0 3.0
```

It's pretty clear that there's a solution to the versioning just by picking newer versions of the packages. The resolver is saying there's something that is specifically placing a limit on NLSolversBase 3.1.0 and the only thing I could think of that can do that is JuliaPro...

**Comment by valfaro** [comment]
I am using JuliaPro 0.6.2.1.  Is it the problem?

Dr. Víctor M. Alfaro
victor.alfaro@ucr.ac.cr
web: https://pidplanet.wordpress.com

De: Christopher Rackauckas
Enviado: sábado, 3 de marzo de 2018 10:07
Para: JuliaDiffEq/DifferentialEquations.jl
CC: valfaro; Mention
Asunto: Re: [JuliaDiffEq/DifferentialEquations.jl] solve MethodError (#265)

@valfaro just to double check again, you're not using JuliaPro?
I created a dep checker:
cd()
cd(".julia/v0.6/METADATA")
packages = Pkg.dependents("NLSolversBase")
for p in packages
  println(p)
  cd("$p/versions")
  versions = readdir()
  for v in versions
    println(v)
    cd(v)
    new_requires = open("requires") do f
      new_requires = ""
      has_dep = false
      for ln in eachline(f)
        vals = split(ln," ")
        if vals[1] == "NLSolversBase"
          println(ln)
        end
      end
    end
    cd("..")
  end
  cd("../../")
end
DelayDiffEq
0.0.1
0.1.0
0.10.0
0.2.0
0.3.0
0.4.0
0.5.0
0.5.1
0.5.2
0.6.0
0.7.0
0.8.0
0.9.0
0.9.1
1.0.0
1.0.1
1.1.0
1.10.0
1.11.0
1.11.1
1.12.0
1.2.0
1.2.1
1.3.0
1.4.0
1.5.0
1.6.0
1.7.0
1.8.0
1.8.1
1.9.0
2.0.0
NLSolversBase 4.2.0
2.1.0
NLSolversBase 4.2.0
LineSearches
0.0.1
NLSolversBase 0.0.1 3.0
0.0.2
NLSolversBase 0.0.1 3.0
0.1.0
NLSolversBase 0.0.1 3.0
0.1.1
NLSolversBase 0.0.1 3.0
0.1.2
NLSolversBase 0.0.1 3.0
0.1.3
NLSolversBase 0.0.1 3.0
0.1.4
NLSolversBase 0.0.1 3.0
0.1.5
NLSolversBase 0.0.1 3.0
1.0.0
NLSolversBase 1.0 2.0
2.0.0
NLSolversBase 2.0 3.0
2.1.0
NLSolversBase 2.0 3.0
2.1.1
NLSolversBase 2.0 3.0
2.2.0
NLSolversBase 2.0 3.0
2.2.1
NLSolversBase 2.0 3.0
3.0.0
NLSolversBase 3.0
3.0.1
NLSolversBase 3.0
3.1.0
NLSolversBase 3.0
3.2.0
NLSolversBase 3.0
3.2.1
NLSolversBase 3.0
3.2.2
NLSolversBase 3.0
3.2.3
NLSolversBase 3.0
3.2.4
NLSolversBase 3.0
3.2.5
NLSolversBase 3.0
OptimBase
0.1.0
NLSolversBase 2.0 4.0
1.0.0
NLSolversBase
NLsolve
0.1.0
0.1.1
0.1.2
0.1.3
0.1.4
0.10.0
NLSolversBase 0.0.1 3.0
0.10.1
NLSolversBase 2.1.0 3.0
0.11.0
NLSolversBase 2.1.0 3.0
0.12.0
NLSolversBase 2.1.0 4.0
0.12.1
NLSolversBase 2.1.0 4.0
0.13.0
NLSolversBase 2.1.0 4.0
0.14.0
NLSolversBase 4.0.0
0.14.1
NLSolversBase 4.0.0
0.2.0
0.3.0
0.3.1
0.3.2
0.3.3
0.4.0
0.5.0
0.6.0
NLSolversBase 0.0.1 3.0
0.6.1
NLSolversBase 0.0.1 3.0
0.7.0
NLSolversBase 0.0.1 3.0
0.7.1
NLSolversBase 0.0.1 3.0
0.7.2
NLSolversBase 0.0.1 3.0
0.7.3
NLSolversBase 0.0.1 3.0
0.8.0
NLSolversBase 0.0.1 3.0
0.9.0
NLSolversBase 0.0.1 3.0
0.9.1
NLSolversBase 0.0.1 3.0
1.0.0
NLSolversBase 4.0.0
1.0.1
NLSolversBase 4.0.0
Optim
0.0.0
0.1.0
0.1.1
0.1.2
0.1.3
0.1.4
0.1.5
0.1.6
0.1.7
0.10.0
NLSolversBase 3.0.0 4.0
0.10.1
NLSolversBase 3.0.0 4.0
0.11.0
NLSolversBase 3.0.0 4.0
0.12.0
NLSolversBase 4.0.0
0.13.0
NLSolversBase 4.0.0
0.14.0
NLSolversBase 4.0.0
0.2.0
0.3.0
0.3.1
0.4.0
0.4.1
0.4.2
0.4.3
0.4.4
0.4.5
NLSolversBase 0.0.1 3.0
0.4.6
NLSolversBase 0.0.1 3.0
0.4.7
NLSolversBase 0.0.1 3.0
0.5.0
NLSolversBase 0.0.1 3.0
0.6.0
NLSolversBase 0.0.1 3.0
0.6.1
NLSolversBase 0.0.1 3.0
0.7.0
NLSolversBase 0.0.1 3.0
0.7.1
NLSolversBase 0.0.1 3.0
0.7.2
NLSolversBase 0.0.1 3.0
0.7.3
NLSolversBase 0.0.1 3.0
0.7.4
NLSolversBase 0.0.1 3.0
0.7.5
NLSolversBase 0.0.1 3.0
0.7.7
NLSolversBase 0.0.1 3.0
0.7.8
NLSolversBase 0.0.1 3.0
0.9.0
NLSolversBase 2.1.0 3.0
0.9.1
NLSolversBase 2.1.0 3.0
0.9.2
NLSolversBase 2.1.0 3.0
0.9.3
NLSolversBase 2.1.0 3.0
It's pretty clear that there's a solution to the versioning just by picking newer versions of the packages. The resolver is saying there's something that is specifically placing a limit on NLSolversBase 3.1.0 and the only thing I could think of that can do that is JuliaPro...

**Comment by ChrisRackauckas** [comment]
Yes, JuliaPro is directly placing a bound on NLSolversBase.jl which is holding it back. This makes it incompatible with any of the newest versions of the JuliaNLSolvers repos (Optim, NLsolve, etc.) and the JuliaDiffEq repos (along with any other packages which require the newest versions of course). I am discussing it with the JuliaPro maintainers and hope that this gets resolved sooner rather than later, but until then a standard Julia installation is required.

**Comment by ChrisRackauckas** [comment]
I changed the issue title so it's more informative about the actual issue for people searching this. This issue will be closed when there's a resolution, so feel free to track this issue for updates.

**Comment by pkofod** [comment]
Then everything makes sense :)

**Comment by valfaro** [comment]
Patrick,

Thank you for your support.  I have not rush and may wait till diffeq packs work with JuliaPro.

Best reagrds,

Dr. Víctor M. Alfaro
victor.alfaro@ucr.ac.cr
web: https://pidplanet.wordpress.com

De: Patrick Kofod Mogensen
Enviado: sábado, 3 de marzo de 2018 10:22
Para: JuliaDiffEq/DifferentialEquations.jl
CC: valfaro; Mention
Asunto: Re: [JuliaDiffEq/DifferentialEquations.jl] JuliaPro 0.6.2.1 isincompatible with DiffEq 4.0 (#265)

Then everything makes sense :)

**Comment by ChrisRackauckas** [comment]
JuliaPro 0.6.2.2 fixes this issue, but is not compatible with BinaryProvider.jl with its MKL build due to the lack of busybox (so JuliaPro with OpenBLAS should be fine), but this can get fixed by bypassing the busybox check. Issue: https://github.com/JuliaPackaging/BinaryProvider.jl/issues/45 . Once that's fixed all of the JuliaPro builds should be fine.

**Comment by valfaro** [comment]
Thanks for the info.

Dr. Víctor M. Alfaro
victor.alfaro@ucr.ac.cr
web: https://pidplanet.wordpress.com

De: Christopher Rackauckas
Enviado: martes, 6 de marzo de 2018 02:19
Para: JuliaDiffEq/DifferentialEquations.jl
CC: valfaro; Mention
Asunto: Re: [JuliaDiffEq/DifferentialEquations.jl] JuliaPro 0.6.2.2 isincompatible with DiffEq 4.0 (#265)

JuliaPro 0.6.2.2 fixes this issue, but is not compatible with BinaryProvider.jl with its MKL build due to the lack of busybox (so JuliaPro with OpenBLAS should be fine), but this can get fixed by bypassing the busybox check. Issue: JuliaPackaging/BinaryProvider.jl#45 . Once that's fixed all of the JuliaPro builds should be fine.

**Comment by ChrisRackauckas** [comment]
The upstream issues have been fixed. The latest JuliaPro releases work with DiffEq.

**Comment by rafaqz** [comment]
FYI I'm getting something similar again trying to install Julia Pro 0.6.4 on windows for my supervisor...

```
julia> Pkg.add("OrdinaryDiffEq")
Unsatisfiable requirements detected for package NLSolversBase:
├─version range [6.1.1,6.1.1+) set by an explicit requirement
├─version range [5.0.0,∞) required by package Optim, whose allowed version range is [0.15.2,0.15.2+)
:
│ ├─version range [0.15.2,0.15.2+) set by an explicit requirement
│ ├─version range [0.0.0-,∞) required by package QuantEcon, whose allowed version range is [0.14.2,0
.14.2+):
│ │ └─version range [0.14.2,0.14.2+) set by an explicit requirement
│ └─version range [0.0.0-,∞) required by package KernelDensity, whose allowed version range is [0.4.
1,0.4.1+):
  │ ├─version range [0.4.1,0.4.1+) set by an explicit requirement
  │ └─version range [0.0.0-,∞) required by package Gadfly, whose allowed version range is [0.7.0,0.7
.0+):
    │ └─version range [0.7.0,0.7.0+) set by an explicit requirement
├─version range [5.0.0,∞) required by package LineSearches, whose allowed version range is [6.0.2,6.
0.2+):
│ ├─version range [6.0.2,6.0.2+) set by an explicit requirement
│ ├─version range [6.0.1,∞) required by package Optim, whose allowed version range is [0.15.2,0.15.2
+):
│ │ └─[see above for Optim backtrace]
│ └─version range [0.0.1,1.0.0-) or [1.0.0,∞) required by package NLsolve, whose allowed version range is [0.7.3,∞):
  │ └─version range [0.7.3,∞) required by package OrdinaryDiffEq, whose allowed version range is [0.0.0-,∞):
    │ └─version range [0.0.0-,∞) set by an explicit requirement
└─version range [0.0.1,5.0.0) required by package NLsolve, whose allowed version range is [0.7.3,∞):
  └─[see above for NLsolve backtrace]
The intersection of the requirements is empty.
```

**Comment by ChrisRackauckas** [comment]
Yeah, older JuliaPros just will not work because of how they fix versions. This is all fixed in v0.7 so I'm not worrying about it.

**Comment by noisyoscillator** [comment]
> 
> 
> Yeah, older JuliaPros just will not work because of how they fix versions. This is all fixed in v0.7 so I'm not worrying about it.

I am getting similar errors while adding Pkg.add("DifferentialEquations"). When can we expect the realease of Pro 0.7?

**Comment by noisyoscillator** [comment]
For the sake of completeness here is the error message for the developers:

```
julia> Pkg.add("DifferentialEquations")
ERROR: Unsatisfiable requirements detected for package NLSolversBase:
├─version range [6.1.1,6.1.1+) set by an explicit requirement
├─version range [5.0.0,∞) required by package Optim, whose allowed version range is [0.15.2,0.15.2+)
:
│ ├─version range [0.15.2,0.15.2+) set by an explicit requirement
│ ├─version range [0.0.0-,∞) required by package QuantEcon, whose allowed version range is [0.14.2,0
.14.2+):
│ │ └─version range [0.14.2,0.14.2+) set by an explicit requirement
│ └─version range [0.0.0-,∞) required by package KernelDensity, whose allowed version range is [0.4.
1,0.4.1+):
  │ ├─version range [0.4.1,0.4.1+) set by an explicit requirement
  │ └─version range [0.0.0-,∞) required by package Gadfly, whose allowed version range is [0.7.0,0.7
.0+):
    │ └─version range [0.7.0,0.7.0+) set by an explicit requirement
├─version range [5.0.0,∞) required by package LineSearches, whose allowed version range is [6.0.2,6.
0.2+):
│ ├─version range [6.0.2,6.0.2+) set by an explicit requirement
│ ├─version range [6.0.1,∞) required by package Optim, whose allowed version range is [0.15.2,0.15.2
+):
│ │ └─[see above for Optim backtrace]
│ └─version range [0.0.1,1.0.0-) or [1.0.0,∞) required by package NLsolve, whose allowed version ran
ge is [0.7.3,∞):
  │ └─version range [0.7.3,∞) required by package OrdinaryDiffEq, whose allowed version range is [0.
0.0,∞):
    │ └─version range [0.0.0,∞) required by package DifferentialEquations, whose allowed version ran
ge is [0.0.0-,∞):
      │ └─version range [0.0.0-,∞) set by an explicit requirement
└─version range [0.0.1,5.0.0) required by package NLsolve, whose allowed version range is [0.7.3,∞):

  └─[see above for NLsolve backtrace]
The intersection of the requirements is empty.
filter_versions(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.
Types.Available}}, ::Dict{AbstractString,Base.Pkg.Types.ResolveBacktraceItem}) at .\pkg\query.jl:341

prune_versions(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.T
ypes.Available}}, ::Dict{AbstractString,Base.Pkg.Types.ResolveBacktraceItem}) at .\pkg\query.jl:370
prune_dependencies(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.P
kg.Types.Available}}, ::Dict{AbstractString,Base.Pkg.Types.ResolveBacktraceItem}) at .\pkg\query.jl:
584
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Av
ailable}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{Str
ing,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:500
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Av
ailable}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\e
ntry.jl:479
edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where
N) at .\pkg\entry.jl:30
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at .\task.jl:335
```

**Comment by ChrisRackauckas** [comment]
NLSolversBase.jl is the issue. They have an old version of Optim that fixes the version. That old version of NLSolversBase is the one where NLsolve is `(x,dx)` instead of `(dx,x)`, so it's completely incompatible with any normal NLsolve code that you would've found in the last year, so the upper bound makes sense. However, that means that our lower bound of saying "you have to use a reasonable NLsolve" is not satisfied on JuliaPro, and will not be satisfied until JuliaPro uses a reasonable version of NLsolve + NLSolversBase, which means they have to update Optim.  That's why this is a closed issue since there's really not much we can do, it's all JuliaPro. And any v0.7 version of Optim is okay, so even just upgrading to v0.7, without the package manager fixes that would help in this kind of situation, will be a fix.
