### ISSUE TITLE
saveat with jump problem

### ISSUE THREAD

**Issue by EddaSchulz** [JuliaDiffEq/DifferentialEquations.jl#267]
Hi, I'm performing a Gillespie simulation with 

prob = DiscreteProblem(x0_int,tspan,p)
jump_prob = JumpProblem(prob,Direct(),all_r_deg)
sol = solve(jump_prob,FunctionMap())

which gives back the solution at around 40 000 time points if tspan=0:100

I would like to get output at less time points, so I tried

sol = solve(jump_prob,FunctionMap(),saveat=1)
or
sol = solve(jump_prob,FunctionMap(),saveat=0:100)

but it doens't change the size of the output. What am I doing wrong?

Thanks for your help!
Edda

**Comment by ChrisRackauckas** [comment]
@EddaSchulz I noticed this question kept coming up so I added the solution to the tutorial.

http://docs.juliadiffeq.org/latest/tutorials/discrete_stochastic_example.html#Controlling-Saving-Behavior-1

Let me know if that isn't sufficiently clear.
