### ISSUE TITLE
The upgrade to Julia 1.0

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#271]
We might as well start. No rush yet, but let's work through some things. The beginning is

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/utils.jl#L43
https://travis-ci.org/JuliaDiffEq/DiffEqBase.jl/jobs/362949744#L1450
@tkf do you know of a solution to this?

**Comment by ChrisRackauckas** [comment]
Right now the major block is just NLsolve.jl, but @pkofod will probably tag a fix on that tomorrow.

**Comment by pkofod** [comment]
I plan to, yes

**Comment by pkofod** [comment]
waiting for https://github.com/JuliaLang/METADATA.jl/pull/14861 to continue tagging nlsolve...

**Comment by pkofod** [comment]
https://github.com/JuliaNLSolvers/NLsolve.jl/pull/170 is next

**Comment by pkofod** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/14875

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/julia/pull/24605

This may cause a problem in Sundials.jl's wrapper, so keep it in mind when updating if there are any GC segfaults.

**Comment by ChrisRackauckas** [comment]
For those following it, DiffEqBase.jl, RecursiveArrayTools.jl, and DiffEqOperators.jl have updated. This means that a substantial amount of the solver packages are new set to do upgrades. Next upgradathon can yield some nice results.

**Comment by ChrisRackauckas** [comment]
We're basically done. Some of the non-core libraries will take a few more days but the libraries the vast majority of people are using are done.
