### ISSUE TITLE
Changing returned value of step!

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/DifferentialEquations.jl#280]
There are two motivations for changing the returned value type of `step!`.

1. Currently `step!(integrator)` returns `nothing` and `step!(integrator, dt)` returns the actual advanced step.  However, @ChrisRackauckas wants to make them consistent https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/101#issuecomment-381326963 .

2. `step!` callers have to check `integrator.sol.retcode` to see if they need to abort whatever they are doing when integrator has an error.  Furthermore, since both `:Default` and `:Success` means "it's OK to continue", users have to remeber to write `retcode in (:Default, :Success)` which is a bit cumbersome.  It would be nice if `step!` returns the retcode or some object including `retcode`.  This way, `retcode` can be different from whatever stored in `integrator.sol.retcode` so we can return `:Success` even when `integrator.sol.retcode` is `:Default`.

So, I think there are several options:

1. Return `nothing`.
2. Return `retcode`.
3. Return a `Bool`: `true` for success, `false` for error.  Users don't have to remember `:Success` (or `:Default`) is the right `retcode` and they can avoid bugs by typo.
4. Return a struct (or a named tuple) with `.retcode` and `.dt` fields.  Field `.dt` could useful even for `step!(integrator)` for adaptive stepping.

Note that changes other than option 1 require changes outside DiffEqBase.jl.

**Comment by ChrisRackauckas** [comment]
>Note that changes other than option 1 require changes outside DiffEqBase.jl.

Where at? What code uses this return?

**Comment by tkf** [comment]
A quick benchmark shows that option 4 has no performance penalty when returned values is not used: https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/101#issuecomment-381349461

**Comment by tkf** [comment]
> What code uses this return?

I mean, `step!` *definitions* in OrdinaryDiffEq.jl etc. have to be changed.

**Comment by ChrisRackauckas** [comment]
Okay. Since it's not really breaking downstream (maybe a user code makes use of it, I doubt it would be anyone but you haha, but there are quick fixes anyways), we should just go with whatever is best. Which do you prefer?

**Comment by tkf** [comment]
Well, it won't break my code either since I'm only using "exact stepping" `step!(integrator, dt, true)` at the moment :)  But using non-exact stepping is in my plan.

I think returning a struct (option 4) would be the best, since it's the richest and most extensible interface.

But actually, since there is not much gain from my suggestions other than cleaning up user's code a bit, probably it is better to not rush the change?  I mean, users can do all of that without relying on `step!`'s returned value.  Since this discussion is partially due to my half-baked API addition in https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/86 (which is still not used in my code yet), I started thinking I should wait until I use those API.  Then, the best temporary choice would be returning `nothing`.  It would be forward-compatible to other options (well, kind of).

**Comment by ChrisRackauckas** [comment]
>Then, the best temporary choice would be returning nothing. It would be forward-compatible to other options (well, kind of).

I think that's the best idea until we see a need for the return.

**Comment by tkf** [comment]
OK.  It looks like that the API that `step!(integrator, dt)` returns `dt` is not mentioned in DiffEqDocs.jl so https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/103 is all we need.
