### ISSUE TITLE
(somewhat) Unfriendly warning from step!

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/DifferentialEquations.jl#282]
It's probably very rare to find people doing something stupid like this, well, except me :), but executing

```julia
using DifferentialEquations
prob = ODEProblem(((u, p, t) -> 0), 0.0, (0, 1.0))
integrator = init(prob, Tsit5())
step!(integrator, 1.0, true)
step!(integrator, 1.0, true)
```

yields

```julia
WARNING: dt <= dtmin. Aborting. If you would like to force continuation with dt=dtmin, set force_dtmin=true

julia> integrator.sol.retcode
:DtLessThanMin

julia> integrator
t: 1.0
u: 0.0

julia> integrator.opts.tstops
DataStructures.BinaryHeap{Float64,DataStructures.LessThan}(DataStructures.LessThan(), [1.0, 2.0])
```

Note that `step!(integrator, 2.0, true)` works:

```julia
julia> integrator = init(prob, Tsit5())
t: 0.0
u: 0.0

julia> step!(integrator, 2.0, true)

julia> integrator
t: 2.0
u: 0.0

julia> integrator.opts.tstops
DataStructures.BinaryHeap{Float64,DataStructures.LessThan}(DataStructures.LessThan(), Float64[])
```

I guess the "fix" would be to add a if block in `step!(integrator, dt)` to pop `tstops` if the front one is equal to `integrator.t`.  But does it make sense to support such behavior?  Maybe a nice warning message is better?

**Comment by ChrisRackauckas** [comment]
Yes, it would be nice to fix this @tkoolen noticed it last month:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/273

We should probably find a way to handle that now that we've unified the error handling a bit.

**Comment by tkf** [comment]
I see.  https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/273 seems to be more general, in the sense that the time step does not have to hit the exact time.  I'm closing this issue.
