### ISSUE TITLE
Documentation example for stochastic differential equations doesn't work

### ISSUE THREAD

**Issue by woutersj** [JuliaDiffEq/DifferentialEquations.jl#283]
When running the code for "[Example 1: Scalar SDEs](http://docs.juliadiffeq.org/latest/tutorials/sde_example.html)", I get the following error on Julia 0.6.2 on Fedora 27:
```
julia> sol = solve(prob,EM(),dt=dt)
ERROR: MethodError: objects of type Float64 are not callable
```
Oddly enough, the code does work on juliabox.com. There is a difference in the type of SDEProblem in the two cases, in Fedora I get
```
DiffEqBase.SDEProblem with uType Float64 and tType Float64. In-place: true
```
while on juliabox.com it's
```
DiffEqBase.SDEProblem with uType Float64 and tType Float64. In-place: false
```

**Comment by ChrisRackauckas** [comment]
What does your `Pkg.status("DiffEqBase")` say? You may be on an old version.

**Comment by woutersj** [comment]
You're right, Pkg.update() fixed the problem. Thanks!
