### ISSUE TITLE
Matrix coupled equations

### ISSUE THREAD

**Issue by jebej** [JuliaDiffEq/DifferentialEquations.jl#285]
I have a system of many coupled equations, where the output of each equation is a matrix. When you have a coupled system of scalar functions, you can just set up `u` and `du` to be `Vector`s, and unpack the system in a single vector ODE. What can you do when each equation instead outputs a matrix?

I tried simply choosing my `u` to be a vector of matrices, but the solver fails while trying to set the cache up:
```
MethodError: no method matching zero(::Type{Array{Complex{Float64},2}})
in #solve#1419 at OrdinaryDiffEq\src\solve.jl:6
in  at base\<missing>
in #init#1420 at OrdinaryDiffEq\src\solve.jl:246
in alg_cache at OrdinaryDiffEq\src\caches\verner_caches.jl:95
```

I also tried putting everything in a 3D array, and using views, but that didn't work either.

**Comment by ChrisRackauckas** [comment]
I don't quite understand your issue. If you use `u0` as a matrix/3-tensor though then it will use that in the system. Can I get a minimal example of the problem?

**Comment by ChrisRackauckas** [comment]
>Could the solver somehow be made to work with a vector of matrices instead?

It would take a lot of work to make arrays of arrays work. That's https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/254 . Arrays of static arrays work, so a vector of static matrices will do the trick if those matrices are small enough. Another way to do this is using an `ArrayPartition` from RecursiveArrayTools.jl. This will only work with Julia-defined solvers. This will do well on Julia v0.7, but on Julia v0.6 there's an issue with broadcast and so it will be slow on these methods: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/106. When Julia v0.7 comes out though, it will be a fantastic option.

**Comment by jebej** [comment]
RecursiveArrayTools seems to use a tuple of arrays as storage, is it possible to use that directly? Maybe by manually specifying some needed functions?

**Comment by ChrisRackauckas** [comment]
You'd have to define a recursive broadcast, which is the most difficult part of the code.

**Comment by jebej** [comment]
Understood, thanks Chris.
