### ISSUE TITLE
How to define parameterized functions with more than one parameter?

### ISSUE THREAD

**Issue by honghuzi** [JuliaDiffEq/DifferentialEquations.jl#293]
I want to define parameterized functions with two parameters
```
function lorenz(du, u, p1, p2, t)
           du[1] = p1[1]*p2[1]*(u[2]-u[1])
           du[2] = u[1]*(p1[2]*p2[2]-u[3]) - u[2]
           du[3] = u[1]*u[2] - p1[3]*p2[3]*u[3]
end
u0 = [1.0,0.0,0.0]
tspan = (0.0,1.0)
p1 = [10.0,28.0,8/3]
p2 = [1.0, 1.0, 1.0]
prob = ODEProblem(lorenz, u0, tspan, p1, p2)
```
which seems not correct. Do I have to declare the parameter in the form of a tuple (p1, p2)?

**Comment by dkarrasch** [comment]
Yes, in the `ODEProblem` call; and then replace `p1[1]` by `p[1]` (and similarly for `p2`) in the function definition of `lorenz`.
