### ISSUE TITLE
DEDataArray not implemented with all solvers

### ISSUE THREAD

**Issue by getzze** [JuliaDiffEq/DifferentialEquations.jl#295]
Some solvers give a `type Array has no field f1` error when defining `u0` as a `DEDataArray` type instead of an array, as if only the `x` attribute of the `DEDataArray` was conserved.
For instance, the error occurs when running the example found in the documentation without defining an algorithm (choosing the default alg):
http://docs.juliadiffeq.org/stable/features/diffeq_arrays.html#DEDataArrays-1

It also happens with SDE solvers like SOSRA, but not with EM.

Having a way of keeping the history of the parameters `p` (as commented in https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/235#issuecomment-358120123) would also solve this issue, but has this been implemented yet? Although to save memory, it would be good to be able to save only some of the `p`, not all.

**Comment by ChrisRackauckas** [comment]
OrdinaryDiffEq.jl has good test coverage on this. StochasticDiffEq.jl needs more tests. And there's a lot more documenting that needs to be done here.

**Comment by ChrisRackauckas** [comment]
See https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/test/downstream/data_array_regression_tests.jl for a corrected example.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/393 closed pretty much all issues on DEDataArrays. It will never work with non-Julia solvers, but I think we got it down for Julia solvers now. Any other issue on this should be more specific to the solver now that we have more broad support.
