### ISSUE TITLE
Build Error with Sundials package

### ISSUE THREAD

**Issue by mattcbro** [JuliaDiffEq/DifferentialEquations.jl#297]
JuliaPro 0.6.2,  I attempted to install DifferentialEquations and get the following error:
INFO: Building Sundials
=====================================================================[ ERROR: Sundials ]======================================================================

LoadError: MethodError: no method matching BinaryProvider.LibraryProduct(::BinaryProvider.Prefix, ::Array{String,1}, ::Symbol)
Closest candidates are:
  BinaryProvider.LibraryProduct(::BinaryProvider.Prefix, ::Array{S<:AbstractString,1}) where S<:AbstractString at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/BinaryProvider/src/Products.jl:42
  BinaryProvider.LibraryProduct(::BinaryProvider.Prefix, ::AbstractString) at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/BinaryProvider/src/Products.jl:38
  BinaryProvider.LibraryProduct(::AbstractString, ::Array{S<:AbstractString,1}) where S<:AbstractString at /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/BinaryProvider/src/Products.jl:56
while loading /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6/Sundials/deps/build.jl, in expression starting on line 6

==============================================================================================================================================================
INFO: Building Conda
INFO: Building SymEngine

=======================================================================[ BUILD ERRORS ]=======================================================================

WARNING: Sundials had build errors.

 - packages with build errors remain installed in /home/matt/programs/juliapro/JuliaPro-0.6.2.1/JuliaPro/pkgs-0.6.2.1/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Sundials")`
 - build a single package by running its `deps/build.jl` script

==============================================================================================================================================================

**Comment by ChrisRackauckas** [comment]
You are on an old version of JuliaPro. You need JuliaPro v0.6.2.2 which will fix this issue. See this issue for more details:

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/265
