### ISSUE TITLE
Plot recipes for backwards timespans not working?

### ISSUE THREAD

**Issue by jlperla** [JuliaDiffEq/DifferentialEquations.jl#300]
I don't think that plot recepies are working with backwards timespans.  See the following code
```
using DifferentialEquations
function f(du,u,p,t)
    L = [1.0 0.0; 0.0 1.0]
    A_mul_B!(du,L,u)
end
tspan = (0.0, 1.0)
u_0 = [0.5; 1.0]
prob = ODEProblem(f, u_0, tspan)
sol = solve(prob)
using Plots
plot(sol)
```
That all works fine.  Now go backwards
```
tspan = (1.0, 0.0)
u_T = [0.5; 1.0]
prob = ODEProblem(f, u_T, tspan)
sol = solve(prob)
using Plots
plot(sol)
```
It displays the right range and labels, but no data.  Is there a workaround, or am I missing something?

**Comment by ChrisRackauckas** [comment]
Axis limits are off. It's plotting on `[2.0,1.0]` for some reason.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DiffEqBase.jl/commit/d72d5d0597b9d10e5b0d8c91e344400071456dfe
