### ISSUE TITLE
InexactError() with implicit system of ODEs

### ISSUE THREAD

**Issue by Stivanification** [JuliaDiffEq/DifferentialEquations.jl#305]
I'd like to solve an implicit three-dimensional system. For physical reasons, I expect the system to have a well-behaved solution, however I'm getting an InexactError() upon trying to solve it. Here is a minimal example:

```julia 

using DifferentialEquations

Rs = 0.005604676908296427
R1 = 0.001591157492652442
R2 = 0.007842690856099944
C1 = 7457.4594262499995
C2 = 713112.0644897448

P = 7.59

function test_system(du,u,p,t)
    I = -8280*du[1]
    (2.6+0.867*u[1] - u[2] - u[3] - I*Rs)*I .= P
    du[2] = -u[2]/R1/C1 + I/C1
    du[3] = -u[3]/R2/C2 + I/C2
end

u0 = [0.5;0.;0.]
tspan = (0,15*60)

prob = ODEProblem(test_system,u0,tspan)
sol = solve(prob,reltol=1e-9,abstol=1e-9)
```
What is the problem here?

**Comment by dkarrasch** [comment]
The first two lines of `test_system` look messed up. How is `du[1]` defined? What is this "inverse assignment" `.= P` good for? The function is not even callable.
```
u0 = [0.5;0.;0.]
du = similar(u0)
test_system(du,u0,nothing,0.0)
```
is giving an error.

**Comment by Stivanification** [comment]
The problem is precisely that `du[1]` is only defined implicitly (and I'm not sure how to define implicit ODEs with this package). I thought that the "inverse assignment" `.=` can be used to communicate implicit ODEs to the package, as in [this issue](https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/263). 

The function in the link defining the ODE is also not callable. Unfortunately, I haven't found any documentation or currently working examples of implicit ODEs for this package, so maybe it doesn't work this way anymore.

**Comment by Stivanification** [comment]
Ah yes, that's what I'm looking for. Thanks for pointing me in the right direction and sorry for creating a "non-issue".
