### ISSUE TITLE
Unify to new DiffEq testing structure

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#319]
The DiffEqDevTools.jl repo shows the old test structure. We had a `runtests.jl` file which includes a bunch of files:

```julia
using DiffEqDevTools
using Test

# write your own tests here
@time @testset "Benchmark Tests" begin include("benchmark_tests.jl") end
@time @testset "ODE AppxTrue Tests" begin include("ode_appxtrue_tests.jl") end
@time @testset "Analyticless Convergence Tests" begin include("analyticless_convergence_tests.jl") end
@time @testset "ODE Tableau Convergence Tests" begin include("ode_tableau_convergence_tests.jl") end ## Windows 32-bit fails on Butcher62 convergence test
@time @testset "Analyticless Stochastic WP" begin include("analyticless_stochastic_wp.jl") end
@time @testset "Stability Region Tests" begin include("stability_region_test.jl") end
```

and then each individual file was an autonomous script. This is okay, but since `include` is global the tests from different `@testset` blocks actually leak out and can effect each other. One common way around this is to put all usings in the `runtests.jl` file and `include` `@testset`s from the files, but the issue there is that the files themselves are not nice runnable scripts. What I wanted out of testing is:

1. If you pick up the test file, it should just be an easily runnable piece of code.
2. It should keep tests completely separate: if you run that code in isolation it should be the same as run via the package testing and CI.

The way we can do this is via the new structure in DiffEqNoiseProcesses.jl. The top level just includes the files with tests:

```julia
using Test

@time begin
  include("interpolation_test.jl")
  include("RSwM1_test.jl")
  include("RSwM2_test.jl")
  include("RSwM3_test.jl")
  include("noise_wrapper.jl")
  include("noise_function.jl")
  include("noise_grid.jl")
  include("noise_approximation.jl")
  include("sde_noise_wrapper.jl")
  include("multi_dim.jl")
  include("geometric_bm.jl")
  include("ornstein.jl")
  include("bridge_test.jl")
  include("sde_adaptivedistribution_tests.jl")
end
```

Then each test file is an autonomous script wrapped in a non-indented `@testset`:

```julia
@testset "OU" begin

using DiffEqNoiseProcess, DiffEqBase, DiffEqMonteCarlo, Test, Statistics
Θ = 1.0
μ = 1.2
σ = 0.3

W = OrnsteinUhlenbeckProcess(Θ,μ,σ,0.0,2.0,1.0)
prob = NoiseProblem(W,(0.0,1.0))
sol = solve(prob;dt=0.1)

t = 1.0
u0 = 2.0
expected_mean = μ + (u0 - μ)*exp(-Θ*t)
expected_variance = (1-exp(-2Θ*t))*σ^2/(2Θ)
monte_prob = MonteCarloProblem(prob;output_func = (sol,i)-> (sol[end],false))
sol = solve(monte_prob;dt=0.1,num_monte=10000)
@test abs(mean(sol) - expected_mean) < 0.04
@test abs(var(sol) - expected_variance) < 0.04

W = OrnsteinUhlenbeckProcess!(Θ,μ,σ,0.0,ones(2),ones(2))
prob = NoiseProblem(W,(0.0,1.0))
sol = solve(prob;dt=0.1)

end
```

The key point is that, since we are not indenting for the full testset/file, it plays nicely with tools like Juno for walking through step-by-step, it copy-pastes well to notebooks and the REPL. But also, with the `@testset`s done like this, the tests will fail if they do not locally `using` the right tools and they are completely separated (no variables shared between tests). Of course, this structure still allows layering testsets within each other and things like that, but this hits the points I wanted: simple to use and share as a normal script but plays nicely as a unit test.

I would like to get all of DiffEq upgraded to this style. Since it's not breaking it doesn't need to be in DifferentialEquations.jl v5.0 (it will be a lot of work too), but this is the style we should be building all new things towards.

**Comment by devmotion** [comment]
Just two comments since I had to deal with this for another project lately:

> But also, with the `@testset`s done like this, the tests will fail if they do not locally `using` the right tools and they are completely separated (no variables shared between tests).

The first part is not correct: if the whole testsuite is run via `runtests.jl` a `@testset` passes without errors if it loads its required packages OR if any other `@testset` has loaded its requirements before. Of course, if the test files are run individually they will fail without `using` the right tools; but if I understand you correctly that's not your point. Usually that should not be a problem (if one does not try to run the test files separately) but in my case `export`s of two different packages collided of which one was required by only one specific `@testset`. Since I did not want to qualify all uses of this export in other completely unrelated test files I had to `import` the second colliding package.

> What I wanted out of testing is:
    1. If you pick up the test file, it should just be an easily runnable piece of code.
    2. It should keep tests completely separate: if you run that code in isolation it should be the same as run via the package testing and CI.

To me it seems that these goals require the test files to be written as
```julia
using Test

@testset "A test" begin
@test 1 == 1
end
```
since otherwise they cannot be run separately from the command line. Of course, with this setup `using Test` is not required in `runtests.jl` anymore.

**Comment by tkf** [comment]
An alternative structure I ended up using a lot is to have a module for each test.  I found creating namespace via module is a bit nicer since I can access intermediate variables after running tests (even the test failed or not).  Say, if I have `test/test_something.jl` with

```julia
module TestSomething
using Test
a = 1
b = 1
@test a == b
error("Oops!")
c = a + b
@test c == 2
end
```

and run `include("test/test_something.jl")` in the REPL, I can investigate the test by looking at, e.g., `TestSomething.a`.

It also eliminates the pitfall @devmotion pointed out. Sure, writing `module` for each file is a bit cumbersome but I think it is worth doing it if you get a guarantee that the namespace is always clean.

**Comment by ChrisRackauckas** [comment]
I've toyed around with the idea of `@testset_module`. Doing the module form would actually be fine with

```julia
@time @testset_module BenchmarkTests "Benchmark Tests" begin include("benchmark_tests.jl") end
```

since then include would be global to the generated `BenchmarkTests` module, and yeah you can grab the variables later. The only thing I am worried about is that then the GC would never ever run.

**Comment by ChrisRackauckas** [comment]
Well I guess we could do

```julia
@time @testset_module "Benchmark Tests" begin include("benchmark_tests.jl") end
@time @testset_module BenchmarkTests = "Benchmark Tests" begin include("benchmark_tests.jl") end
```

The first can gensym a module and using it to run it, and discard it, while the second would use the given name, run the test, and then be referencable later.

**Comment by tkf** [comment]
Where is the `@testset_module` macro? Are you using `gensym` inside it? As test file name is always unique why not use the file name to generate the module name? For example, you can define `@testset_module("benchmark_tests.jl")` which generates a module named `benchmark_tests` (say) wrapped by `@testset`.

**Comment by ChrisRackauckas** [comment]
>Where is the @testset_module macro?

I was just thinking of making a package for it.

>For example, you can define @testset_module("benchmark_tests.jl") which generates a module named benchmark_tests (say) wrapped by @testset.

That could work too.

**Comment by ChrisRackauckas** [comment]
@oxinabox has a nice package for testing interface implementations as well. There's probably a whole lot of these kinds of things that would make a nice utility package.

**Comment by tkf** [comment]
Ah, InterfaceTesting.jl is interesting.

**Comment by oxinabox** [comment]
InterfaceTesting.jl is  broken as of julia 0.6  (but fixable) see https://github.com/oxinabox/InterfaceTesting.jl/issues/2

But I think it is an important and good idea.
We should have generated tests for interfaces.

**Comment by ChrisRackauckas** [comment]
SafeTestsets.jl works well!
