### ISSUE TITLE
Decision: Change linear indexing in the solution type to be array linear indexing?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#321]
Currently, `typeof(sol) <: DESolution <: AbstractDiffEqArray <: AbstractVectorOfArray` which makes it inherit the behavior `sol[i] = sol.u[i]`, i.e. that linear indexing the solution is the same as linear indexing the array of arrays. However, multidimensional indexing like `sol[i,j] = sol.u[j][i]` makes the solution act like a matrix/tensor. Thus `sol` is not strictly an abstract matrix or tensor because its linear index violates the linear index rules you would expect from such an object (it also means that `length(sol) = length(sol.u)` instead of `length(sol.u)*prod(size(sol.u[1]))`. Given the ease of `sol.u[i]`, I am reconsidering whether this is a good idea on v0.7 and DifferentialEquations.jl v5.0. This choice seems to have broken the use of `vec(sol)` for example. I wonder how much this linear index was really used.

**Comment by Datseris** [comment]
To chime in, I do not use `sol[i]` in DynamicalSystems so this change is not breaking for my part. 

Removing the `sol[i]` comes with the benefit of making `sol(i)` a bit more clear: solution at time `i`. I think there was one discussion with some users quite some time ago about how this was confusing... I don't remember very well though.

**Comment by ChrisRackauckas** [comment]
`vec(sol)` has been fixed by an overload. A lot of iteration relies on working like this, so users seem to generally assume that they can iterate over the timeseries "correctly" by state so let's keep this for now but this can always be re-opened later.
