### ISSUE TITLE
Default linear solver problem-adaptive behavior

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#323]
From https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/443

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/linear_nonlinear.jl#L14-L17

>We can make the default be nothing and have that smartly check f and use that to determine lu vs lu!. I think that default can handle most cases well (until we get to DAEs, when we will want to make it smarter and automatically switch to qr, and on BandedMatrices it should default to the banded QR (@dlfivefifty ?), etc). Separate issue.

**Comment by dlfivefifty** [comment]
If it’s a classic time-stepping problem banded LU might be better as it is diagonally dominant for small time steps.

**Comment by ChrisRackauckas** [comment]
Great just didn't know if BandedMatrices.jl had an `lu`. Then this proposed default works for a good set of types.

**Comment by dlfivefifty** [comment]
Yes it has an LU, and just uses LAPACK’s banded lu.
