### ISSUE TITLE
Certificate for docs.juliadiffeq.org expired

### ISSUE THREAD

**Issue by tkoolen** [JuliaDiffEq/DifferentialEquations.jl#324]
![image](https://user-images.githubusercontent.com/2585880/43403275-a8049c74-93e2-11e8-9e09-64e86fc7e4e0.png)

**Comment by ChrisRackauckas** [comment]
https://docs.juliadiffeq.org/latest/ seems good now, https://juliadiffeq.org still has an issue for some reason.

**Comment by ChrisRackauckas** [comment]
All of our websites are https now with new working certificates.
