### ISSUE TITLE
Problem with solve() of a MonteCarloProblem on julia 0.7

### ISSUE THREAD

**Issue by mcfefa** [JuliaDiffEq/DifferentialEquations.jl#329]
I can create a MonteCarloProblem of N differential equations with different initial conditions, but I get the following error when I try to solve it.
```julia
source = "data.csv"
datatable = readdlm(source, ',');
data = datatable[2:end,:];
# Setting up to solve the problem N times (for the N different initial conditions)

# N is the number of rows
N = size(data,1);

# Pulling initial conditions from first three columns of dataset
initial_conditions = Array{Any}(N,3)

for i=1:N
   initial_conditions[i] = [Float64(data[i,1]),Float64(data[i,2]),Float64(data[i,3])]
end

function prob_func(prob,i,repeat)
  println("$prob, $i, $repeat")
  return ODEProblem(prob.f,initial_conditions[i],prob.tspan)
end

monte_prob = MonteCarloProblem(prob,prob_func=prob_func)
sim = solve(monte_prob,Vern8(),num_monte=N)
```

> DiffEqBase.ODEProblem with uType Array{Float64,1} and tType Float64. In-place: true
>timespan: (0.0, 72.0)
> u0: [5.0e-5, 0.00025, 0.005], 1, 1
> MethodError: no method matching start(::Void)
> Closest candidates are:
>   start(::SimpleVector) at essentials.jl:258
>   start(::Base.MethodList) at reflection.jl:560
>   start(::ExponentialBackOff) at error.jl:107
>   ...
> 
> Stacktrace:
>  [1] #571 at ./asyncmap.jl:178 [inlined]
>  [2] foreach(::Base.##571#573, ::Array{Any,1}) at ./abstractarray.jl:1733
>  [3] maptwice(::Function, ::Channel{Any}, ::Array{Any,1}, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at ./asyncmap.jl:178
>  [4] wrap_n_exec_twice(::Channel{Any}, ::Array{Any,1}, ::Base.Distributed.##204#207{CachingPool}, ::Function, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at ./asyncmap.jl:154
>  [5] #async_usemap#556(::Function, ::Void, ::Function, ::DiffEqMonteCarlo.##4#8{DiffEqBase.MonteCarloProblem{DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,NTuple{16,Float64},#FibMacLym,Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},#prob_func,DiffEqBase.##239#252,DiffEqBase.##241#254,Array{Any,1}},OrdinaryDiffEq.Vern8,Tuple{}}, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at ./asyncmap.jl:103
>  [6] (::Base.#kw##async_usemap)(::Array{Any,1}, ::Base.#async_usemap, ::Function, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64},N} where N) at ./<missing>:0
>  [7] (::Base.#kw##asyncmap)(::Array{Any,1}, ::Base.#asyncmap, ::Function, ::UnitRange{Int64}) at ./<missing>:0
>  [8] #pmap#203(::Bool, ::Int64, ::Void, ::Array{Any,1}, ::Void, ::Function, ::CachingPool, ::Function, ::UnitRange{Int64}) at ./distributed/pmap.jl:126
>  [9] (::Base.Distributed.#kw##pmap)(::Array{Any,1}, ::Base.Distributed.#pmap, ::CachingPool, ::Function, ::UnitRange{Int64}) at ./<missing>:0
>  [10] solve_batch(::DiffEqBase.MonteCarloProblem{DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,NTuple{16,Float64},#FibMacLym,Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},#prob_func,DiffEqBase.##239#252,DiffEqBase.##241#254,Array{Any,1}}, ::OrdinaryDiffEq.Vern8, ::Symbol, ::UnitRange{Int64}, ::Int64) at /Users/mcfefa/.julia/v0.6/DiffEqMonteCarlo/src/solve.jl:44
>  [11] macro expansion at /Users/mcfefa/.julia/v0.6/DiffEqMonteCarlo/src/solve.jl:28 [inlined]
>  [12] macro expansion at ./util.jl:293 [inlined]
>  [13] #solve#1(::Int64, ::Int64, ::Int64, ::Symbol, ::Array{Any,1}, ::Function, ::DiffEqBase.MonteCarloProblem{DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,NTuple{16,Float64},#FibMacLym,Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},#prob_func,DiffEqBase.##239#252,DiffEqBase.##241#254,Array{Any,1}}, ::OrdinaryDiffEq.Vern8, ::Type{Val{true}}) at /Users/mcfefa/.julia/v0.6/DiffEqMonteCarlo/src/solve.jl:22
>  [14] (::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.MonteCarloProblem{DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,NTuple{16,Float64},#FibMacLym,Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem},#prob_func,DiffEqBase.##239#252,DiffEqBase.##241#254,Array{Any,1}}, ::OrdinaryDiffEq.Vern8, ::Type{Val{true}}) at ./<missing>:0 (repeats 2 times)

The MonteCarloProblem monte_prob is: DiffEqBase.MonteCarloProblem with problem DiffEqBase.ODEProblem

When I use solve() with a regular ODE problem (DiffEqBase.ODEProblem), the command works fine. 

Please advise what I can do to use solve() with a MonteCarloProblem. 

```julia
Pkg.status()

26 required packages:
 - BlackBoxOptim                 0.3.0
 - CSV                           0.2.5
 - DataFrames                    0.11.7
 - DifferentialEquations         4.5.0
 - Distributions                 0.15.0
 - GR                            0.32.0
 - Gadfly                        0.7.0
 - GaussianMixtures              0.2.0
 - Hiccup                        0.1.1
 - HypothesisTests               0.7.0
 - IJulia                        1.9.1
 - IndexedTables                 0.7.3
 - LSODA                         0.3.0
 - Missings                      0.2.10
 - MixedModels                   0.18.1
 - MultivariateAnomalies         0.1.2
 - MultivariateStats             0.5.0
 - NamedColors                   0.1.0
 - ParameterizedFunctions        3.1.0
 - Plotly                        0.1.1
 - Plots                         0.17.4
 - PyPlot                        2.6.0
 - Query                         0.9.3
 - StatPlots                     0.7.3
 - Stats                         0.1.0
 - Vega                          0.8.0
```

**Comment by mcfefa** [comment]
I've made a minimal example that reproduces the bug on a clean install of Julia 0.7.

```julia
using Pkg
Pkg.status()

using Plots;
using DifferentialEquations;
using RecursiveArrayTools; 
using ParameterizedFunctions; 
using Optim;

# Monte Carlo Problem Set Up for solving set of ODEs with different initial conditions

function MyModel(du,u,p,t)    
    
    # parameters
    bf,df,bm,dm,bl,dl,a1,a2,a3,a4 = p
    
    # ODE describing the population (F)
    du[1] = bf*u[1]*(1-u[1]-u[2]-u[3]) - df*u[1] - a1*u[1]*u[3]
    # ODE describing the population (M)
    du[2] = bm*u[2]*(1-u[1]-u[2]-u[3]) - dm*u[2] - a2*u[2]*u[2] 
    # ODE describing the population (L)
    du[3] = bl*u[3]*(1-u[1]-u[2]-u[3]) - dl*u[3] - a3*u[2]*u[3] - a4*u[1]*u[3]

end

param = (0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1);
u0 = [5.0e-5,2.5e-4,5.0e-3]; 
tspan = (0.0,72.0);

# Define and solve ODE Problem
prob = ODEProblem(MyModel,u0,tspan,param)

sol = solve(prob,Vern8(),abstol=1e-8,reltol=1e-8); 

# Setting up to solve the problem N times (for the N different initial conditions)
data = [0.0 0.0 0.005 0.0 0.0 0.0 6.30605e-5 0.005 0.00506583 0.0288652;
    5.0e-5 0.0 0.005 5.0e-5 0.001 0.0 1.051e-5 0.005 0.00620091 0.0321528;
    0.0005 0.0 0.005 0.0005 0.007 0.0 0.0 0.005 0.00725191 0.0326065;
    0.005 0.0 0.005 0.005 0.056 0.0 0.0 0.005 0.0067054 0.0259552;
    0.0 0.0 0.005 0.0 0.0 0.0 0.0 0.005 0.00567541 0.0297935]


# N is the number of rows
N = size(data,1);

# Pulling initial conditions from first three columns of dataset
initial_conditions = Array{Any}(N,3)

for i=1:N
   initial_conditions[i] = [Float64(data[i,1]),Float64(data[i,2]),Float64(data[i,3])]
end

function prob_func(prob,i,repeat)
    println("$prob, $i, $repeat")
  return ODEProblem(prob.f,initial_conditions[i],prob.tspan)
end

monte_prob = MonteCarloProblem(prob,prob_func=prob_func)
sim = solve(monte_prob,num_monte=N)
```

[Unpinned-ParamEst-2018-08-09.pdf](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/2274340/Unpinned-ParamEst-2018-08-09.pdf)

**Comment by ChrisRackauckas** [comment]
You forgot to pass down your parameters:

```julia
function prob_func(prob,i,repeat)
    println("$prob, $i, $repeat")
  return ODEProblem(prob.f,initial_conditions[i],prob.tspan,prob.p)
end
```
