### ISSUE TITLE
Vector of crossing functions for condition/affect!

### ISSUE THREAD

**Issue by MartinOtter** [JuliaDiffEq/DifferentialEquations.jl#331]
The current approach to define zero-crossing functions for event triggering with condition/affect! is no longer practical if many zero-crossing functions are present (as e.g. in Modia and Modia3D). It would be helpful, if these functions could be generalized to support a vector of zero-crossing functions. For example, the interface could be changed to:
```
function condition!(x,t,integrator,z)
    z[1] = ..         # vector of zero-crossing functions
    z[2] = ...
    return nothing
end

function affect!(x,t,integrator,z_changed)
    #z_changed[2] = true   # if sign of z[2] changed
end
```
Additionally, the dimension of "z" must be "somehow" be reported when defining the model (probably in the "problem" function call). 

Note, in Modia/Modia3D, z_changed is not needed and would not be used (so, from this side, it need not be included in the affect! function). The issue is that if one z[i] has changed, then suddenly other parts of the model may be evaluated in a different way (different if-clauses) and then suddenly other z[i] would change (at the event) as well. So, the only meaningful way is to evaluate the complete model
and inspect **every** z[i] during the event.  

In ModiaMath, special helper-functions are used for this purpose. See for example [example SimpleStateEvents](https://github.com/ModiaSim/ModiaMath.jl/blob/master/examples/withoutMacros_withoutVariables/models/SimpleStateEvents.jl):
```
sPos = ModiaMath.positive!(integrator, 1, s, "s")   # helper function to define  "sPos = s > 0" with events 
f = sPos ? 0.0 : m.fMax 
```
during continuous integration, the helper function positive!(..) returns the value of s>0 from the last
event. At an event instant, the value of s > 0 is newly computed, stored for the integration phase and returned. For details, see the [documentation of positive!](https://modiasim.github.io/ModiaMath.jl/latest/lib/DAE.html#ModiaMath.DAE.positive!-Tuple{ModiaMath.DAE.SimulationState,Int64,Float64,String}) and its [source code](https://github.com/ModiaSim/ModiaMath.jl/blob/master/src/DAE/events.jl). 

You may consider to use this approach for DifferentialEquations.jl as well, so instead of using functions
condition(..), affect!(..), use helper functions (positive!, negative!, edge!, change!) that the user can call in the model function. This is much more convenient for the user and probably the only practical way to 
handle complex models (as in Modia or Modia3D).

**Comment by ChrisRackauckas** [comment]
Just to be clear, no more breaking changes are making it into DifferentialEquations.jl v5.0, but 

>You may consider to use this approach for DifferentialEquations.jl as well, so instead of using functions
condition(..), affect!(..), use helper functions (positive!, negative!, edge!, change!) that the user can call in the model function. This is much more convenient for the user and probably the only practical way to
handle complex models (as in Modia or Modia3D).

That's not true. These functions do handle arbitrarily complex models, just differently. Instead of letting you query for upcrossings, downcrossings, and changes, it just lets you put a callback function in there for those cases and use call-overloading for holding caches. Though it probably is just easier to have a single function and query for the affect. 

`affect!(x,t,integrator,z_changed)` doesn't make sense in the immutable case though since then you'd have an `x` which you'd want to ignore.

What we can do is make `VectorContinuousCallback` and `VectorDiscreteCallback` which can have multiple crossings. They can have just one `affect!` and have some query functions for upcrossings, downcrossings, etc. and direct access to the `z`. I think that covers everything you need, and then we can discuss merging vector and not vector callbacks as a v6.0 breaking change later.

**Comment by MartinOtter** [comment]
> What we can do is make VectorContinuousCallback and VectorDiscreteCallback which can have multiple crossings. They can have just one affect! and have some query functions for upcrossings, downcrossings, etc. and direct access to the z. I think that covers everything you need, and then we can discuss merging vector and not vector callbacks as a v6.0 breaking change later.

This sounds good and is sufficient to treat all cases.

Regarding the helper functions (for some future version v6.0 or later): Consider that a modeler would like to implement the following:
```
f1 = x > 0 ? x^2 : x^3
f2 = f1 > 0 ? sin(f1) : cos(f1)
f3 = f2 > 0 ? f1*f2 : f2*f2*x
```
and a zero crossing should be detected when x > 0, f1 > 0, f2 > 0 changes their value (so 3 zero-crossing functions). The condition/affect! interface can treat these cases, but it is hard to implement for the modeler. In ModiaMath this is basically written as:
```
f1 = positive!(.., x, ...) ? x^2 : x^3
f2 = positive!(.., f1, ..) ? sin(f1) : cos(f1)
f3 = positive!(.., f2,..) ? f1*f2 : f2*f2*x
``` 
and calling the model function at an event is sufficient to figure out the right "if-branch" that is then used for the further continuous integration. At the same time, the zero-crossing function is computed during continuous integration and reported to the integrator.

**Comment by ChrisRackauckas** [comment]
I don't see what is so nice about the positive function. It seems like a more verbose way to do the first?

**Comment by MartinOtter** [comment]
> I don't see what is so nice about the positive function. It seems like a more verbose way to do the first?

Yes, mathematically what is needed from the model side are the following two *high level* modeling constructs:
```
event(expr)    # all relations in expr trigger a state event and construct zero-crossing functions
event(x > 0)   # special case of event(expr)

edge(expr)     # is true at the time instant when expr changes from false to true and is false otherwise.
edge(h <= 0)  # special case of edge (expr)
```
Instead of the positive!(...) function, it would be better to have a macro (@event(..), @edge(..)) that transforms to positive!(..)/edge!(..) and hides all irrelevant details from the modeler. 

The zero-crossing functions from standard integrator interfaces are a **very low level** construct to be able to construct the above two cases (but the above two cases are basically, what the modeler needs).

Implementing the example with condition/affect! is of course possible:
```
function condition1(x,t,integrator)
    return x[1]
end
function condition2(x,t,integrator)
    return integrator.p.f1_positive  ? x[1]^2 : x[1] ^3
end
function condition3(x,t,integrator)
   return integrator.p.f2_positive ? sin(f1) : cos(f1)
end
```
Implementing the  "affect!" is already hard since one affect depends on another one etc. 

For information: This is the implementation of positive!(...) (for simplicity, I removed optional logging stuff):
```
function positive!(h::EventHandler, nr::Int, crossing::Float64, restart::EventRestart=Restart)::Bool
   if h.initial
      h.zPositive[nr] = crossing > 0.0
   elseif h.event
      new_zPositive = crossing > 0.0
      change = (h.zPositive[nr] && !new_zPositive) || (!h.zPositive[nr] && new_zPositive)
      h.zPositive[nr] = new_zPositive
      if change
         h.restart = max(h.restart, restart)
         h.newEventIteration = true
      end
   end
   h.z[nr] = crossing + (h.zPositive[nr] ? zEps : -zEps)
   return h.zPositive[nr]
end
```
In some way or the other, this code needs to be implemented for every zero-crossing function from the modeler and is hidden here in a function.

**Comment by ChrisRackauckas** [comment]
Why is it a boolean? A ContinuousCallback should just be a zero crossing function. What is all of this for?

**Comment by MartinOtter** [comment]
The essential variables are:
- h.z[nr] is the continuous-time zero-crossing function. "nr" is the integer that identifies the index of z that is used at this place. h.z[nr] is reported to the integrator (so correspond to what is returned from condition(...) in DifferentialEquations).
- h.zPositive[nr] = h.z[nr] > 0 **from the last event instant**. So in h.zPositive[n] the value of the Boolean h.z[nr] > 0 at the last event instant is stored, so corresponds to the value of "Event(x > 0)" in the example. This value is used in the model function (is returned from function positive!(..) and used in the model). This means that during continuous integration the model uses the value of the relation "x > 0" that it had at the last event instant. Once, h.z[nr] (which is here just "x") crosses zero, an event occurs. At the event instant, the new value of "x > 0" is determined in the branch "elseif h.event" and then stored in h.zPositive[nr] and then used in the model. The result is that during continuous integration (including the iteration to find the root of the zero crossing), the statement:
```
f1 = positive!(..., x, ...) : x^2 ? x^3
```
remains on the if-branch that it had at the last event instant (defined by h.zPositive[nr] that is returned from positive!(..). At an event instant, the new value of h.zPositive[nr] is determined and then this if-statement switches to a new branch (defined by the return value of positive!(...)).

**Comment by MartinOtter** [comment]
I recognized that I made it too complicated.

Please, just support a vector of zero crossing function (the value that is currently returned by "condition"). This is sufficient that Modia can be interfaced reasonably.

Since DifferentialEquations.jl is a very generic simulation engine, the "positive!(..)" etc operators are a special case of a domain-specific-model. I also recognized that the discussion with positive! is just one part. Whenever such functions are introduced, then suddenly the simulation enginen is reponsible that the expression like x > 0 and the crossing function x is consistent to each other. This in turn means that event iteration has to be introduced and also special handling at initialization (so all this makes the simulation engine more complex and less stable).

**Comment by ChrisRackauckas** [comment]
Alright, what I plan on doing is refactoring callbacks so there's a single diffeq-wide implementation since right now there's a few due to pre-integrator interface issues (all worked out now). Once it's refactored we can add a `MultipleContinuousCallback` which does exactly this. The issue at that point will be that there's no package to rely on for rootfinding in this case. We use Roots.jl for the rootfinding, but we can fallback to a simple bisection method for `MultipleContinuousCallback` for now, and come up with a false position method later.

**Comment by ChrisRackauckas** [comment]
A big update here is that we just merged https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/164 , so all of the packages now use the same callback handling code. I want to address https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/353 first, and then once that's good we can add universal vector callback handling.

**Comment by ChrisRackauckas** [comment]
Event detection issues have been handled. Next step is the new callback.

**Comment by ChrisRackauckas** [comment]
The snag here is that there's no rootfinding functions in Julia for handling vectors in this fashion. We will need to write our own "vector element-wise Bisection" method, which isn't too difficult but needs to get done. This would be a good GSoC project.

**Comment by ChrisRackauckas** [comment]
Some movement in this direction: https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/221

**Comment by ChrisRackauckas** [comment]
Completed with `VectorContinuousCallbacks`.
