### ISSUE TITLE
Windows 10 - installation errors Dual not defined

### ISSUE THREAD

**Issue by hearnsj** [JuliaDiffEq/DifferentialEquations.jl#335]
When installing the latest version on Windows 10 Julia version 1.0.0 I get a failure with building RandomNumbers - which is clearly to be reported to that package maintainer.
But then:

julia> using DifferentialEquations
┌ Warning: Error requiring ForwardDiff from DiffEqBase:
│ UndefVarError: Dual not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\hearn\.julia\packages\DiffEqBase\b81P9\src\init.jl:7
│  [2] eval at .\boot.jl:319 [inlined]
│  [3] eval at C:\Users\hearn\.julia\packages\DiffEqBase\b81P9\src\DiffEqBase.jl:1 [inlined]
│  [4] (::getfield(DiffEqBase, Symbol("##443#452")))() at C:\Users\hearn\.julia\packages\Requires\9Jse8\src\require.jl:67
│  [5] err(::getfield(DiffEqBase, Symbol("##443#452")), ::Module, ::String) at C:\Users\hearn\.julia\packages\Requires\9Jse8\src\require.jl:38
│  [6] #442 at C:\Users\hearn\.julia\packages\Requires\9Jse8\src\require.jl:66 [inlined]
│  [7] withpath(::getfield(DiffEqBase, Symbol("##442#451")), ::String) at C:\Users\hearn\.julia\packages\Requires\9Jse8\src\require.jl:28
│  [8] (::getfield(DiffEqBase, Symbol("##441#450")))() at C:\Users\hearn\.julia\packages\Requires\9Jse8\src\require.jl:65
│  [9] #invokelatest#1 at .\essentials.jl:686 [inlined]
│  [10] invokelatest at .\essentials.jl:685 [inlined]
│  [11] #3 at C:\Users\hearn\.julia\packages\Requires\9Jse8\src\require.jl:19 [inlined]
│  [12] iterate at .\generator.jl:47 [inlined]
│  [13] _collect(::Array{Function,1}, ::Base.Generator{Array{Function,1},getfield(Requires, Symbol("##3#4"))}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at .\array.jl:632
│  [14] map at .\array.jl:561 [inlined]
│  [15] loadpkg(::Base.PkgId) at C:\Users\hearn\.julia\packages\Requires\9Jse8\src\require.jl:19
│  [16] #invokelatest#1 at .\essentials.jl:686 [inlined]
│  [17] invokelatest at .\essentials.jl:685 [inlined]
│  [18] _tryrequire_from_serialized(::Base.PkgId, ::UInt64, ::String) at .\loading.jl:645
│  [19] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:696
│  [20] _tryrequire_from_serialized(::Base.PkgId, ::UInt64, ::String) at .\loading.jl:642
│  [21] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:696
│  [22] _tryrequire_from_serialized(::Base.PkgId, ::UInt64, ::String) at .\loading.jl:642
│  [23] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:696
│  [24] _require(::Base.PkgId) at .\loading.jl:931
│  [25] require(::Base.PkgId) at .\loading.jl:852
│  [26] macro expansion at .\logging.jl:311 [inlined]
│  [27] require(::Module, ::Symbol) at .\loading.jl:834
│  [28] eval(::Module, ::Any) at .\boot.jl:319
│  [29] eval_user_input(::Any, ::REPL.REPLBackend) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:85
│  [30] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:117 [inlined]
│  [31] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at .\task.jl:259
└ @ Requires C:\Users\hearn\.julia\packages\Requires\9Jse8\src\require.jl:40

**Comment by ChrisRackauckas** [comment]
Yeah, that's harmless but fixed in https://github.com/JuliaLang/METADATA.jl/pull/17124

**Comment by hearnsj** [comment]
Thankyou. Tests now passed!
