### ISSUE TITLE
Can't build RandomNumbers

### ISSUE THREAD

**Issue by daxinnan** [JuliaDiffEq/DifferentialEquations.jl#337]
I run julia v0.7,0 on Win10 x64.
An error occured，when I build DifferentialEquations.
┌ Error: Error building `RandomNumbers`:
│
│ Please submit a bug report with steps to reproduce this fault, and any error messages that
follow (in their entirety). Thanks.
│ Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffdee8c3077 --
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068

**Comment by ChrisRackauckas** [comment]
https://github.com/sunoru/RandomNumbers.jl/issues/41

**Comment by ChrisRackauckas** [comment]
Fixed on the latest release of RandomNumbers. Do `]build DifferentialEquations` to redo it. `]up` first.
