### ISSUE TITLE
When trying to run the example ODE in the documentation - MethodError: no method matching ...

### ISSUE THREAD

**Issue by kylebeggs** [JuliaDiffEq/DifferentialEquations.jl#340]
I am on a Linux machine (Ubuntu v18.04) using Julia v1.0.0 via Atom with julia-client v0.7.5. DifferentialEquations is up to date v0.5.3. When trying to run the simple ODE example in the documentation
```
using DifferentialEquations
f(u,p,t) = 1.01*u
u0=1/2
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),reltol=1e-8,abstol=1e-8)
 ```

 I get this error - 

``MethodError: no method matching size(::ODESolution{Float64,1,Array{Float64,1},Nothing,Nothing,Array{Float64,1},Array{Array{Float64,1},1},ODEProblem{Float64,Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}})
The applicable method may be too new: running in world age 25029, while current world is 25082.
Closest candidates are:
  size(::AbstractVectorOfArray) at /home/kylebeggs/.julia/packages/RecursiveArrayTools/ukc19/src/vector_of_array.jl:43 (method too new to be called from this world context.)
  size(::AbstractArray{T,N}, !Matched::Any) where {T, N} at abstractarray.jl:38
  size(!Matched::BitArray{1}) at bitarray.jl:70
  ...
length at abstractarray.jl:159 [inlined]
isempty(::ODESolution{Float64,1,Array{Float64,1},Nothing,Nothing,Array{Float64,1},Array{Array{Float64,1},1},ODEProblem{Float64,Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}) at abstractarray.jl:841
typeinfo_prefix(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::ODESolution{Float64,1,Array{Float64,1},Nothing,Nothing,Array{Float64,1},Array{Array{Float64,1},1},ODEProblem{Float64,Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}) at arrayshow.jl:479
show_vector(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::ODESolution{Float64,1,Array{Float64,1},Nothing,Nothing,Array{Float64,1},Array{Array{Float64,1},1},ODEProblem{Float64,Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}, ::Char, ::Char) at arrayshow.jl:432
show_vector(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::ODESolution{Float64,1,Array{Float64,1},Nothing,Nothing,Array{Float64,1},Array{Array{Float64,1},1},ODEProblem{Float64,Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}) at arrayshow.jl:432
show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::ODESolution{Float64,1,Array{Float64,1},Nothing,Nothing,Array{Float64,1},Array{Array{Float64,1},1},ODEProblem{Float64,Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}) at arrayshow.jl:418
show_delim_array(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Tuple{ODESolution{Float64,1,Array{Float64,1},Nothing,Nothing,Array{Float64,1},Array{Array{Float64,1},1},ODEProblem{Float64,Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}}, ::Char, ::Char, ::Char, ::Bool, ::Int64, ::Int64) at show.jl:695
show_delim_array at show.jl:680 [inlined]
show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Tuple{ODESolution{Float64,1,Array{Float64,1},Nothing,Nothing,Array{Float64,1},Array{Array{Float64,1},1},ODEProblem{Float64,Tuple{Float64,Float64},false,Nothing,ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}}) at show.jl:714
show_default(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Any) at show.jl:332
show(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Any) at show.jl:315
print(::Base.GenericIOBuffer{Array{UInt8,1}}, ::MethodError) at io.jl:31
#print_to_string#326(::Nothing, ::Function, ::MethodError) at io.jl:124
print_to_string at io.jl:112 [inlined]
string(::MethodError) at io.jl:143
handlemsg(::Dict{String,Any}, ::Dict{String,Any}) at comm.jl:171
(::getfield(Atom, Symbol("##14#17")){Array{Any,1}})() at task.jl:259``

**Comment by ChrisRackauckas** [comment]
Does it work in the REPL? A fresh Julia session? That world age error is odd.

**Comment by kylebeggs** [comment]
Sorry, should have included these details. Fresh Julia session does not work, but it does work when running from the REPL. Perhaps it is not a DifferentialEquations.jl issue after all. Wondering where I should move this issue to?

**Comment by ChrisRackauckas** [comment]
This is one of the issues that the prereleases of Juno had. Are you on an old dev version of any of the Juno packages, either on the Julia or Atom side?

**Comment by pfitzseb** [comment]
Yeah, the output of `pkg> status` would be helpful. I'll see if I can repro this locally.

**Comment by kylebeggs** [comment]
On the Atom side of things:
uber-juno v0.2.0

Julia side:
```
(v1.0) pkg> status
    Status `~/.julia/environments/v1.0/Project.toml`
  [c52e3926] Atom v0.7.4
  [336ed68f] CSV v0.3.1
  [53a63b46] CodeTools v0.6.1
  [944b1d66] CodecZlib v0.5.0
  [a93c6f00] DataFrames v0.13.1
  [0c46a032] DifferentialEquations v5.3.0
  [38e38edf] GLM v0.11.0
  [e5e0dc1b] Juno v0.5.2
  [91a5bcdd] Plots v0.20.1
```

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/Atom.jl/commit/3d2240f739779183d59a884a5b5b7c69ee6f8aec. Until the next release is out you can just call `using DifferentialEquations` before using `Ctrl-Shift-Enter` to eval the complete file (or just eval the file as a code block).

Thanks for finding this issue :)

**Comment by kylebeggs** [comment]
More thanks to you for fixing it!
