### ISSUE TITLE
error in precompilation of DifferentialEquations in Julia 1.0 in ubuntu 16.04

### ISSUE THREAD

**Issue by sahaskn** [JuliaDiffEq/DifferentialEquations.jl#350]
I have extracted the 64bit archive file of Julia 1.0 downloaded from download page of julialang website.

The precompilation of the package shows error particularly in package dependencies.
[precompile_error.log](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/2399370/precompile_error.log)

**Comment by ChrisRackauckas** [comment]
It looks like the package repository got a little messed up and isn't dealing with dependencies right. This is an upstream issue that should get fixed shortly. The commit in question is:

https://github.com/JuliaRegistries/General/commit/c6032b203253268dc7151064fff5158da81b3b84#diff-60ad0b44e938d9b35732a3e174a29627

**Comment by sahaskn** [comment]
@ChrisRackauckas , Thanks for the reply. 
when using DifferentialEquations, I got those errors and was not able to use the package before.
Then I deleted the .julia folder and reinstall all packages. Still, it shows the same message about dependecies. This time DifferentialEquations worked as usual. I'm not sure what happened before.

**Comment by ChrisRackauckas** [comment]
Yesterday there was an issue with the Julia package manager. It cleared itself up though.
