### ISSUE TITLE
Edge case discrete callback at t0

### ISSUE THREAD

**Issue by ArnoJL** [JuliaDiffEq/DifferentialEquations.jl#354]
Discrete callbacks don't seem to work when they evaluate to true at the first time point.

```
using DifferentialEquations
using ForwardDiff: Dual
using Plots

const tstop1 = [0.0,5.0]
mutable struct ParametersDE
  unknown_par::Array{Dual{Float64,Float64,1},1}
  control_par::Array{Float64,1}
end
function condition(u,t,integrator)
  t in tstop1
end
function affect!(integrator)
  integrator.p.control_par[1] = 1.0
end
save_positions = (true,true)
cb = DiscreteCallback(condition, affect!, save_positions=save_positions)
cbs = CallbackSet(cb)
function func(du,u,p,t)
  du[1] = -p.unknown_par[1]*u[1] + p.control_par[1]
end


p1dual = Dual{Float64}(1.0, (1.0))
parameters = ParametersDE([p1dual],[0.8])
u0_dual =  eltype(p1dual).([1.0])
tspan = (0.0, 10.0)

prob= ODEProblem(func, u0_dual, tspan, parameters)
sol_control = solve(prob,Tsit5(), callback = cbs, tstops=tstop1)

plot_states = zeros(length(sol_control.u), length(sol_control.u[1]))
for i = 1:length(sol_control.u)
  for j = 1:length(sol_control.u[1])
    plot_states[i,j] = sol_control.u[i][j].value
  end
end
plot(sol_control.t, plot_states, seriestype=:scatter)
```
I do not know if you want to allow this, or force people to initialize the parameters correctly. 

A use case would be an optimization problem where the time for a control switch has to be optimized. 
It would be neater if you didn't have to define an edge case manually for the degenerate solution, where the switch happens immediately.

**Comment by ChrisRackauckas** [comment]
In http://docs.juliadiffeq.org/latest/features/callback_functions.html#ContinuousCallbacks-1 there is 

>initialize: This is a function (c,u,t,integrator) which can be used to initialize the state of the callback c. It should modify the argument c and the return is ignored.

If you want to call the callback at the initial time point, you can just do

```julia
initialize(c,u,t,integrator) = c.affect!(integrator)
```

It's not done by default since there's a lot of edge cases that can come out of it, so not all callbacks work well with this. But since it has an easy opt-in I think we're fine.
