### ISSUE TITLE
Resize integrator is not working in basic example posted on documentation

### ISSUE THREAD

**Issue by cavargar** [JuliaDiffEq/DifferentialEquations.jl#355]
Dear DifferentialEquations team

Love your work!!! I would like to adopt the example shown at the end of the callback section in the documentation. However, when I try to run the basic program:

`using DifferentialEquations
const α = 0.3
function f(du,u,p,t)
  for i in 1:length(u)
    du[i] = α*u[i]
  end
end
function condition(u,t,integrator) # Event when event_f(u,t) == 0
  1-maximum(u)
end
function affect!(integrator)
  u = integrator.u
  resize!(integrator,length(u)+1)
  maxidx = findmax(u)[2]
  Θ = rand()
  u[maxidx] = Θ
  u[end] = 1-Θ
  nothing
end
callback = ContinuousCallback(condition,affect!)
u0 = [0.2]
tspan = (0.0,10.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,callback=callback)`

It throws the following error:

> type CompositeCache has no field u

Please any help on this is appreciated

Cesar

**Comment by ChrisRackauckas** [comment]
This was fixed and we forgot to close the issue!

**Comment by zahachtah** [comment]
hm, when I run this it does not give any error but the integrator does not add new "cells"

```julia
const α = 0.3
function f(du,u,p,t)
  for i in 1:length(u)
    du[i] = α*u[i]
  end
end
function condition(u,t,integrator) # Event when event_f(u,t) == 0
  1-maximum(u)
end
function affect!(integrator)
  u = integrator.u
  resize!(integrator,length(u)+1)
  maxidx = findmax(u)[2]
  Θ = rand()
  u[maxidx] = Θ
  u[end] = 1-Θ
  nothing
end
callback = ContinuousCallback(condition,affect!)
u0 = [0.2]
tspan = (0.0,100.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,callback=callback)

map((x)->length(x),sol[:])
```
the output of the last line is an array of ints and all values are 1.... they should increase, no?

@ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
```julia
using OrdinaryDiffEq
const α = 0.3
function f(du,u,p,t)
  for i in 1:length(u)
    du[i] = α*u[i]
  end
end
function condition(u,t,integrator) # Event when event_f(u,t) == 0
  1-maximum(u)
end
function affect!(integrator)
  u = integrator.u
  resize!(integrator,length(u)+1)
  maxidx = findmax(u)[2]
  Θ = rand()
  u[maxidx] = Θ
  u[end] = 1-Θ
  nothing
end
callback = ContinuousCallback(condition,affect!)
u0 = [0.2]
tspan = (0.0,100.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),callback=callback)
map((x)->length(x),sol[:])
sol = solve(prob,AutoTsit5(Rosenbrock23()),callback=callback)
map((x)->length(x),sol[:])
```

looks to be an issue specific to the automatic switching methods. File an issue in OrdinaryDiffEq.
