### ISSUE TITLE
ERROR: UndefVarError: norm not defined

### ISSUE THREAD

**Issue by pucicu** [JuliaDiffEq/DifferentialEquations.jl#356]
Using Julia 1.0.0 I get the error "ERROR: UndefVarError: norm not defined" when calling ode45.

**Comment by ChrisRackauckas** [comment]
Fixed on ODE.jl v2.3.0 via https://github.com/JuliaDiffEq/ODE.jl/commit/68227a1175dc8c6f903c62d25da3fd55747b142d . We still wouldn't recommend using `ode45` though since the other methods should be much more efficient on most problems.
