### ISSUE TITLE
Docs: parameter dependence for ODEProblem 

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaDiffEq/DifferentialEquations.jl#367]
On this page
http://docs.juliadiffeq.org/latest/types/ode_types.html

the statement of constructor `ODEProblem(f::ODEFunction,u0,tspan,callback=CallbackSet())` 
doesn't appear consistent with parameter passing - what happened to `p` in `f(u,p,t)`?

 Is `p` one of `CallbackSet()`? If so, it is internally consistent, but still not immediately clear to a new user where `p` should be passed to set up `ODEProblem`.

**Comment by ChrisRackauckas** [comment]
`ODEProblem(f::ODEFunction,u0,tspan,callback=CallbackSet())` is without the optional `ODEProblem(f::ODEFunction,u0,tspan,p,callback=CallbackSet())`. We should definitely show the optional arg, but I'm not sure the best way.

**Comment by AshtonSBradley** [comment]
maybe just show both as you have here, so that it is clear where `p` should go?
