### ISSUE TITLE
Is progress monitoring available on Jupyter notebook ?

### ISSUE THREAD

**Issue by Tagussan** [JuliaDiffEq/DifferentialEquations.jl#369]
I wrote some code to solve ODE on Jupyter notebook. I called solve function with option progress=true. However, no progress indicator appear on notebook. Is this feature available on jupyter notebook?

**Comment by ChrisRackauckas** [comment]
If you add https://github.com/adamslc/ProgressLogging.jl does it work in the notebook? Julia v1.0 now has a common format for progress logging, but not the display. If someone makes the display (this package?) then it should just work.

**Comment by Tagussan** [comment]
Currently my environment is v0.6. I install that package, but I wasn't able to use it, because of the lack of Printf package, which my package manager couldn't find, neither do I on github.
I'm don't upgrade my julia, because some of my project uses packages which are reported to be not available on Julia v1.0.

**Comment by ChrisRackauckas** [comment]
Okay. Yes, a solution will only exist in Julia v1.0 because that's when the common logging interface was introduced.

**Comment by mleprovost** [comment]
Hello, 
I am using Jupyter notebook with Julia 1.0.1 to solve ODE and I can't get the progressbar.
Here is the code: 
``` 
using ProgressMeter
using ProgressLogging
using DifferentialEquations
using Plots
using Juno

function lorenz(du,u,p,t)
 du[1] = 10.0*(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz,u0,tspan)
sol = solve(prob, progressbar = true)
```

**Comment by ChrisRackauckas** [comment]
It's `progress=true`, and whether that works is dependent on whether there is a progress bar package for Jupyter (which I am not sure there is?)

**Comment by ChrisRackauckas** [comment]
See #424 as a new related issue for this.
