### ISSUE TITLE
Second order sensitivities

### ISSUE THREAD

**Issue by gugushvili** [JuliaDiffEq/DifferentialEquations.jl#375]
It could be that I didn't read the documentation carefully, but does DifferentialEquations.jl support solution of the second order sensitivity equations? Second order derivatives with respect to parameters are needed in some statistical tasks for ODEs, and this is not an idle question. 

Thanks.

**Comment by ChrisRackauckas** [comment]
Sadly, we don't have this directly on the interface yet, but it would be a good thing to add. However, doing this manually isn't that difficult with AD. You just have to seed the dual numbers similarly to how ForwardDiff does for its Hessian function. While you can just use ForwardDiff.Hessian, manual seeding allows you to extract the value and gradients at the same time as the Hessian calculation.

Another way to do this is to use hyperdual numbers.

**Comment by gugushvili** [comment]
Thanks. Would be nice to have a built-in function like `ODELocalSensitivityProblem`, that would define the corresponding (matrix) ODE system, that can then be numerically integrated with `solve`.

**Comment by ChrisRackauckas** [comment]
For reference, the best way to do it right now is to send dual numbers in and call the adjoint function. The dual parts will then be the Jacobian.

**Comment by ChrisRackauckas** [comment]
@ranjan is taking this on
