### ISSUE TITLE
General ODE problem result does not match specific ODE problems results

### ISSUE THREAD

**Issue by homocomputeris** [JuliaDiffEq/DifferentialEquations.jl#380]
To be honest, I don't know if it is a bug, a lack of explanation in the docs or I don't understand something.

As an example, I want to solve the Kepler problem with a time-dependent mass, namely `q'' = -mu(t)*q/norm(q)^(3/2)`:
```julia
using DifferentialEquations

function mu(t)
	mu0 = 1.0;
	gamma = 1e-2;
	delta = 1.4;
	pw = (1.0 - delta);
	inner = mu0.^pw + gamma * (delta - 1.0) * t;
	Ydot = inner.^(1.0 / pw);
	return Ydot
end

function f(du, u, p, t)
	r = sqrt(dot(u,u))
	return -mu(t) * u / r^(3.0/2.0)	
end

function g(Y, p, t)
	mut = mu(t)
	Yd = zeros(size(Y))
	Yd[1] = Y[2];
	Yd[2] = -mut * Y[1] / (Y[1]^2 + Y[3]^2)^(3 / 2);
	Yd[3] = Y[4];
	Yd[4] = -mut * Y[3] / (Y[1]^2 + Y[3]^2)^(3 / 2);
	Ydot = [Yd[1]; Yd[2]; Yd[3]; Yd[4]];
end

tspan = (0.0, 20.0)
ec = 0.8
du0 = [0.0, sqrt((1.0 + ec)/(1.0 - ec))]
u0 = [1.0-ec, 0.0]

gu0 = [1.0-ec, 0, 0, sqrt((1.0 + ec)/(1.0 - ec))]

probODE = ODEProblem(g, gu0, tspan)
prob2ndODE = SecondOrderODEProblem(f, du0, u0, tspan)

solODE = solve(prob, abstol=1e-12, reltol=1e-12)
sol2ndODE = solve(prob2ndODE,SofSpa10(),dt=0.001)
```
The ODEproblem result is fine:  `[-2.04024, 0.207495, -0.340981, -0.259405] `, but the SecondOrderODEProblem is nonsence: `[3.08912, -7.08715]`. The same problem is, eg, with RKNs.

1. Am I defining the 2nd order problem correctly?
2. Why do results differ so much?
3. Can I define a Hamiltonian problem with time dependence?

**Comment by ChrisRackauckas** [comment]
Your equations are different. `(Y[1]^2 + Y[3]^2)^(3 / 2)` is not the same as `sqrt(dot(u,u))`. You have an extra `/2` in the exponent there. I would instead just do: 

```julia
function f(du, u, p, t)
	r = sum(abs2,u)
	return -mu(t) * u ./ r^(3.0/2.0)
end
```

when I do that, they return the same solution.

>Can I define a Hamiltonian problem with time dependence?

Currently we do not allow that. I am not sure the current integrators can handle that? I think symplectic needs a time-invariant Hamiltonian. I do want to add this for variational integrators but we don't have any yet so it's not so interesting (though you could use non-symplectic integrators on it...). We should add it.

**Comment by homocomputeris** [comment]
> Your equations are different. (Y[1]^2 + Y[3]^2)^(3 / 2) is not the same as sqrt(dot(u,u)). You have an extra /2 in the exponent there.

Yeah, now I see my question is stupid. I need the Euclidean norm, but I had been adding an extra square root in the 1st problem that broke everything.

> Currently we do not allow that.

If a 2nd order ODE time-dependent problem can be solved, then its Hamiltonian equivalent can be too, can't it? For my example, it would be `H = 1/2 p' p - mu(t)/norm(r)` and then the equations are obtained as the Poisson brackets of q (p) with H.

> I am not sure the current integrators can handle that? I think symplectic needs a time-invariant Hamiltonian.

Well, they can if you treat time in [an appropriate way](http://personales.upv.es/serblaza/2012RACSAM.pdf).

**Comment by ChrisRackauckas** [comment]
Yeah, there's some low hanging fruit there. Mind opening an issue for time dependent Hamiltonians?
