### ISSUE TITLE
Make Arpack.jl an optional dependency?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaDiffEq/DifferentialEquations.jl#381]
Arpack.jl is currently [broken](https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5) with Julia built from source. How hard would it be to remove it as a required dependency?

**Comment by ChrisRackauckas** [comment]
Where is it even coming from?

**Comment by dlfivefifty** [comment]
Hmm, there's too many other issues with Julia built from source, so let's just close this.

**Comment by dlfivefifty** [comment]
Actually, my homebrew was just messed up. Fixing that fixed Arpack.
