### ISSUE TITLE
Error building 

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaDiffEq/DifferentialEquations.jl#382]
Hi, when installing the package, I got the following error:

uild DifferentialEquations
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`
  Building DiffEqBase ──────→ `~/.julia/packages/DiffEqBase/nW6r3/deps/build.log`
  Building RandomNumbers ───→ `~/.julia/packages/RandomNumbers/t1NfT/deps/build.log`
┌ Error: Error building `RandomNumbers`: 
│ ERROR: LoadError: LoadError: IOError: could not spawn `make`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _jl_spawn(::String, ::Array{String,1}, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at ./process.jl:367
│  [2] (::getfield(Base, Symbol("##494#495")){Cmd})(::Tuple{RawFD,RawFD,RawFD}) at ./process.jl:509
│  [3] setup_stdio(::getfield(Base, Symbol("##494#495")){Cmd}, ::Tuple{RawFD,RawFD,RawFD}) at ./process.jl:490
│  [4] #_spawn#493(::Nothing, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at ./process.jl:508
│  [5] _spawn at ./process.jl:504 [inlined]
│  [6] #run#504(::Bool, ::Function, ::Cmd) at ./process.jl:662
│  [7] macro expansion at ./process.jl:661 [inlined]
│  [8] build() at /home/kelvyn/.julia/packages/RandomNumbers/t1NfT/deps/Random123/build.jl:13
│  [9] top-level scope at /home/kelvyn/.julia/packages/RandomNumbers/t1NfT/deps/Random123/build.jl:40
│  [10] include at ./boot.jl:317 [inlined]
│  [11] include_relative(::Module, ::String) at ./loading.jl:1041
│  [12] include(::Module, ::String) at ./sysimg.jl:29
│  [13] include(::String) at ./client.jl:388
│  [14] top-level scope at none:0
│  [15] include at ./boot.jl:317 [inlined]
│  [16] include_relative(::Module, ::String) at ./loading.jl:1041
│  [17] include(::Module, ::String) at ./sysimg.jl:29
│  [18] include(::String) at ./client.jl:388
│  [19] top-level scope at none:0
│ in expression starting at /home/kelvyn/.julia/packages/RandomNumbers/t1NfT/deps/Random123/build.jl:39
│ in expression starting at /home/kelvyn/.julia/packages/RandomNumbers/t1NfT/deps/build.jl:1
└ @ Pkg.Operations /build/julia-PQ6K4D/julia-1.0.1/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069
  Building Arpack ──────────→ `~/.julia/packages/Arpack/UiiMc/deps/build.log`
┌ Error: Error building `Arpack`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/kelvyn/.julia/packages/Arpack/UiiMc/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/kelvyn/.julia/packages/BinaryProvider/1nGWd/src/Products.jl:408
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1041
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:388
│  [9] top-level scope at none:0
│ in expression starting at /home/kelvyn/.julia/packages/Arpack/UiiMc/deps/build.jl:74
└ @ Pkg.Operations /build/julia-PQ6K4D/julia-1.0.1/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069
  Building Rmath ───────────→ `~/.julia/packages/Rmath/Py9gH/deps/build.log`
  Building SymEngine ───────→ `~/.julia/packages/SymEngine/sh7Yz/deps/build.log`
  Building Sundials ────────→ `~/.julia/packages/Sundials/AL2Km/deps/build.log`

I am using a fresh install of kubuntu 10.10, anaconda is installed. I also installed libgfortran and gcc.

**Comment by ChrisRackauckas** [comment]
Have you installed Make? It seems like RandomNumbers.jl had an issue calling make during the build phase.

**Comment by Kelvyn88** [comment]
Hi, I just installed the build-essential and the first error was fixed, now the problem is the second one:


  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`
  Building DiffEqBase ──────→ `~/.julia/packages/DiffEqBase/nW6r3/deps/build.log`
  Building RandomNumbers ───→ `~/.julia/packages/RandomNumbers/t1NfT/deps/build.log`
  Building Arpack ──────────→ `~/.julia/packages/Arpack/UiiMc/deps/build.log`
┌ Error: Error building `Arpack`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/kelvyn/.julia/packages/Arpack/UiiMc/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/kelvyn/.julia/packages/BinaryProvider/1nGWd/src/Products.jl:408
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1041
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:388
│  [9] top-level scope at none:0
│ in expression starting at /home/kelvyn/.julia/packages/Arpack/UiiMc/deps/build.jl:74
└ @ Pkg.Operations /build/julia-PQ6K4D/julia-1.0.1/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069
  Building Rmath ───────────→ `~/.julia/packages/Rmath/Py9gH/deps/build.log`
  Building SymEngine ───────→ `~/.julia/packages/SymEngine/sh7Yz/deps/build.log`
  Building Sundials ────────→ `~/.julia/packages/Sundials/AL2Km/deps/build.log`

**Comment by ChrisRackauckas** [comment]
Try `]build ARPACK` again? I thought ARPACK.jl uses BinaryProvider so you don't have to build the binaries locally? That means, for some reason the download failed or it just doesn't provide a binary for your system. That should get upstreamed to ARPACK.jl.

**Comment by Kelvyn88** [comment]
Thanks for your answer. I was reading a lot of this error in the Arpack repository, the problem was that I downloaded Julia from the Arch repo. Using official binaries solved the problem.
