### ISSUE TITLE
L2Loss() fails for Monte Carlo problems if saveat is not used

### ISSUE THREAD

**Issue by jibaneza** [JuliaDiffEq/DifferentialEquations.jl#392]
When using L2Loss( ) for parameter estimation in Monte Carlo problems it is necessary to specify saveat and it will only work if the experimental data of each Monte Carlo iteration is saved at the same timepoints.
It would be useful to have at least one or both of these options:

1. Being able to specify different 'saveat' for each Monte Carlo iteration (ideal, since it will also work for solvers not compatible with dense output)
2. Having L2Loss() correctly interpolate in sol[i](t) for Monte Carlo problems as it does for ODE problems.

**Comment by ChrisRackauckas** [comment]
This is all fixed up.
