### ISSUE TITLE
The IDA algorithm in DAE modifies the value of p in the callback, and the algorithm does not converge.

### ISSUE THREAD

**Issue by fuyingfuying** [JuliaDiffEq/DifferentialEquations.jl#399]
IDA algorithm in DAE. In the affect() function of the discrete event callback, the value of the parameter p is modified, and the algorithm does not converge.
[ex5-1-r4-DAE.zip](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/2648871/ex5-1-r4-DAE.zip)

![image](https://user-images.githubusercontent.com/12774287/49454568-5d22be00-f820-11e8-88da-17d6478b644e.png)

**Comment by fuyingfuying** [comment]
@ChrisRackauckas I updated my source code, the symbol of the formula in line 43 of diff-eq.jl (should be the + sign, I made the - sign), I am sorry, sorry.

**Comment by ChrisRackauckas** [comment]
I assume that means you fixed it?
