### ISSUE TITLE
problem_new_parameters does not work with functional initial conditions

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaDiffEq/DifferentialEquations.jl#400]
The following MWE illustrates the problem
```julia
using OrdinaryDiffEq
prob = ODEProblem((u,p,t)->u,(p,t0)->p[1],(p)->(0.0,p[2]),(2.0,1.0))
prob = problem_new_parameters( prob, (1.0,3.0) )
```
That could be addressed by storing the evaluated initial conditions in the problem type or by handling the functional case in `problem_new_parameters`. Personally I would prefer the first solution.

**Comment by ChrisRackauckas** [comment]
`problem_new_parameters` is being deprecated for `remake`. I would suggest not using it.
