### ISSUE TITLE
Symplectic integrators usage

### ISSUE THREAD

**Issue by henry2004y** [JuliaDiffEq/DifferentialEquations.jl#406]
Hi,

I encountered a problem when trying the symplectic integration for a simple harmonic oscillator:

ERROR: type Array has no field x

`using DifferentialEquations

f = @ode_def HarmonicOscillator begin
  dq = p
  dp = -q
end

u0 = [1.0; 0.0]
tspan = (0.0,12.0)
prob = ODEProblem(f,u0,tspan)
sol_Euler = solve(prob,Euler(),dt=π/10)
sol_modifiedEuler = solve(prob,SymplecticEuler(),dt=π/10)
sol_default = solve(prob)`

Is it a bug or do I miss something here?
Thanks!

**Comment by ChrisRackauckas** [comment]
Hey, the symplectic integrators need to have the ODE defined in a partitioned form as described here: http://docs.juliadiffeq.org/latest/types/dynamical_types.html . You may want to look at the following tutorials as examples:

https://nbviewer.jupyter.org/github/JuliaDiffEq/DiffEqTutorials.jl/blob/master/PhysicalModels/ClassicalPhysics.ipynb
https://nbviewer.jupyter.org/github/JuliaDiffEq/DiffEqTutorials.jl/blob/master/PhysicalModels/KeplerProblem.ipynb
https://nbviewer.jupyter.org/github/JuliaDiffEq/DiffEqTutorials.jl/blob/master/PhysicalModels/Outer-Solar-System.ipynb
