### ISSUE TITLE
error using "DifferentialEquations.jl" in JuliaPro 1.0.2, win 10

### ISSUE THREAD

**Issue by LianhaoYin** [JuliaDiffEq/DifferentialEquations.jl#413]
There is no pblem to install using "Pkg.add("DifferentialEquations")". 
However, errors occurs when "using DifferentialEquations"
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
┌ Warning: On Windows, creating file symlinks requires Administrator privileges
└ @ Base.Filesystem file.jl:789
┌ Warning: On Windows, creating file symlinks requires Administrator privileges
└ @ Base.Filesystem file.jl:789
┌ Warning: On Windows, creating file symlinks requires Administrator privileges
└ @ Base.Filesystem file.jl:789
ERROR: LoadError: LoadError: UndefVarError: is_windows not defined
Stacktrace:
 [1] top-level scope at C:\Users\Lianhao Yin\.juliapro\packages\SymEngine\sh7Yz\deps\deps.jl:3
 [2] include at .\boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1044
 [4] include at .\sysimg.jl:29 [inlined]
 [5] include(::String) at C:\Users\Lianhao Yin\.juliapro\packages\SymEngine\sh7Yz\src\SymEngine.jl:3
 [6] top-level scope at none:0
 [7] include at .\boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at .\loading.jl:1044
 [9] include(::Module, ::String) at .\sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at .\boot.jl:319 [inlined]
 [12] eval(::Expr) at .\client.jl:393
 [13] top-level scope at .\none:3
in expression starting at C:\Users\Lianhao Yin\.juliapro\packages\SymEngine\sh7Yz\deps\deps.jl:2
in expression starting at C:\Users\Lianhao Yin\.juliapro\packages\SymEngine\sh7Yz\src\SymEngine.jl:26
ERROR: LoadError: Failed to precompile SymEngine [123dc426-2d89-5057-bbad-38513e3affd8] to C:\Users\Lianhao Yin\.juliapro\compiled\v1.0\SymEngine\uZhcI.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] macro expansion at .\logging.jl:311 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1190
 [4] macro expansion at .\logging.jl:309 [inlined]
 [5] _require(::Base.PkgId) at .\loading.jl:947
 [6] require(::Base.PkgId) at .\loading.jl:858
 [7] macro expansion at .\logging.jl:309 [inlined]
 [8] require(::Module, ::Symbol) at .\loading.jl:840
 [9] include at .\boot.jl:317 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1044
 [11] include(::Module, ::String) at .\sysimg.jl:29
 [12] top-level scope at none:2
 [13] eval at .\boot.jl:319 [inlined]
 [14] eval(::Expr) at .\client.jl:393
 [15] top-level scope at .\none:3
in expression starting at C:\Users\Lianhao Yin\.juliapro\packages\ParameterizedFunctions\ozDxQ\src\ParameterizedFunctions.jl:11
ERROR: LoadError: Failed to precompile ParameterizedFunctions [65888b18-ceab-5e60-b2b9-181511a3b968] to C:\Users\Lianhao Yin\.juliapro\compiled\v1.0\ParameterizedFunctions\OKjOc.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] macro expansion at .\logging.jl:311 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1190
 [4] macro expansion at .\logging.jl:309 [inlined]
 [5] _require(::Base.PkgId) at .\loading.jl:947
 [6] require(::Base.PkgId) at .\loading.jl:858
 [7] macro expansion at .\logging.jl:309 [inlined]
 [8] require(::Module, ::Symbol) at .\loading.jl:840
 [9] include at .\boot.jl:317 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1044
 [11] include(::Module, ::String) at .\sysimg.jl:29
 [12] top-level scope at none:2
 [13] eval at .\boot.jl:319 [inlined]
 [14] eval(::Expr) at .\client.jl:393
 [15] top-level scope at .\none:3
in expression starting at C:\Users\Lianhao Yin\.juliapro\packages\DifferentialEquations\88DSk\src\DifferentialEquations.jl:18
ERROR: Failed to precompile DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa] to C:\Users\Lianhao Yin\.juliapro\compiled\v1.0\DifferentialEquations\UQdwS.ji.
Stacktrace:
 [1] macro expansion at .\logging.jl:311 [inlined]
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1190
 [3] macro expansion at .\logging.jl:309 [inlined]
 [4] _require(::Base.PkgId) at .\loading.jl:947
 [5] require(::Base.PkgId) at .\loading.jl:858
 [6] macro expansion at .\logging.jl:309 [inlined]
 [7] require(::Module, ::Symbol) at .\loading.jl:840

**Comment by ChrisRackauckas** [comment]
Looks like an error with building SymEngine, but I thought they fixed that. @isuruf ? Could you try doing `]build SymEngine` again?

**Comment by blackacat** [comment]
Same question
(JuliaPro) pkg> build DifferentialEquations
  Building SpecialFunctions → `C:\Users\82416\.juliapro\packages\SpecialFunctions\KvXoO\deps\build.
log`
  Building DiffEqBase ──────→ `C:\Users\82416\.juliapro\packages\DiffEqBase\Rj7cy\deps\build.log`
  Building RandomNumbers ───→ `C:\Users\82416\.juliapro\packages\RandomNumbers\cr9ta\deps\build.log
`
┌ Error: Error building `RandomNumbers`:
│ fatal: error thrown and no exception handler available.
│ InitError(mod=:MbedTLS, error=MethodError(f=typeof(Base.Filesystem.joinpath)(), args=(nothing, "..
", "..", "deps", "usr", "lib"), world=0x00000000000067f0))
│ rec_backtrace at /home/Administrator/buildbot/worker/package_win64/build/src\stackwalk.c:94
│ record_backtrace at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:246
│ jl_throw at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:577
│ jl_method_error_bare at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1616
│ jl_method_error at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1634
│ jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2161
│ __init__ at C:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\MbedTLS\src\MbedTLS.j
l:61
│ jfptr___init___14286 at C:\Users\82416\AppData\Local\JuliaPro-1.0.2.1\Julia-1.0.2\lib\julia\sys.dl
l (unknown line)
│ jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
│ jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
│ jl_module_run_initializer at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.
c:90
│ _julia_init at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buil
dbot/worker/package_win64/build/src\init.c:813
│ julia_init__threading at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:302
│ wmain at /home/Administrator/buildbot/worker/package_win64/build/ui\repl.c:227
│ __tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:329
│ mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:212
│ BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
│ RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\Pkg\src\Operatio
ns.jl:1119
  Building Arpack ──────────→ `C:\Users\82416\.juliapro\packages\Arpack\WP3ru\deps\build.log`
  Building Rmath ───────────→ `C:\Users\82416\.juliapro\packages\Rmath\Py9gH\deps\build.log`
  Building SymEngine ───────→ `C:\Users\82416\.juliapro\packages\SymEngine\sh7Yz\deps\build.log`
┌ Error: Error building `SymEngine`:
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Found a valid dl path libgmp-10.dll while looking for libmpfr
│ [ Info: Found a valid dl path libgmpxx-4.dll while looking for libmpfr
│ [ Info: Found a valid dl path libmpc-3.dll while looking for libmpfr
│ [ Info: Found a valid dl path libmpfr-6.dll while looking for libmpfr
│ [ Info: C:\Users\82416\.juliapro\packages\SymEngine\sh7Yz\deps\symengine-0.3\bin\libmpfr-6.dll mat
ches our search criteria of libmpfr
│ [ Info: Found a valid dl path libgmp-10.dll while looking for libsymengine
│ [ Info: Found a valid dl path libgmpxx-4.dll while looking for libsymengine
│ [ Info: Found a valid dl path libmpc-3.dll while looking for libsymengine
│ [ Info: Found a valid dl path libmpfr-6.dll while looking for libsymengine
│ [ Info: Found a valid dl path libsymengine.dll while looking for libsymengine
│ [ Info: C:\Users\82416\.juliapro\packages\SymEngine\sh7Yz\deps\symengine-0.3\bin\libsymengine.dll
matches our search criteria of libsymengine
│ [ Info: Found a valid dl path libgmp-10.dll while looking for libmpc
│ [ Info: Found a valid dl path libgmpxx-4.dll while looking for libmpc
│ [ Info: Found a valid dl path libmpc-3.dll while looking for libmpc
│ [ Info: C:\Users\82416\.juliapro\packages\SymEngine\sh7Yz\deps\symengine-0.3\bin\libmpc-3.dll matc
hes our search criteria of libmpc
│ [ Info: Found a valid dl path libgmp-10.dll while looking for libgmp
│ [ Info: C:\Users\82416\.juliapro\packages\SymEngine\sh7Yz\deps\symengine-0.3\bin\libgmp-10.dll mat
ches our search criteria of libgmp
│ ERROR: LoadError: SystemError: opening file C:\Users\82416\.juliapro\packages\SymEngine\sh7Yz\deps
\deps.jl: Permission denied
│ Stacktrace:
│  [1] #systemerror#39(::Nothing, ::Function, ::String, ::Bool) at .\error.jl:106
│  [2] systemerror at .\error.jl:106 [inlined]
│  [3] #open#293(::Nothing, ::Nothing, ::Nothing, ::Bool, ::Nothing, ::Function, ::String) at .\iost
ream.jl:283
│  [4] #open at .\none:0 [inlined]
│  [5] open(::String, ::String) at .\iostream.jl:339
│  [6] #open#294(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function,
 ::getfield(BinaryProvider, Symbol("##162#164")){Bool,String,Array{LibraryProduct,1},getfield(Binary
Provider, Symbol("##161#163")),SubString{String}}, ::String, ::Vararg{String,N} where N) at .\iostre
am.jl:367
│  [7] open at .\iostream.jl:367 [inlined]
│  [8] #write_deps_file#160(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at C:\Users\jul
ia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\BinaryProvider\src\Products.jl:413
│  [9] write_deps_file(::String, ::Array{LibraryProduct,1}) at C:\Users\julia\AppData\Local\Julia-1.
0.2\share\julia\stdlib\v1.0\BinaryProvider\src\Products.jl:395
│  [10] top-level scope at none:0
│  [11] include at .\boot.jl:317 [inlined]
│  [12] include_relative(::Module, ::String) at .\loading.jl:1044
│  [13] include(::Module, ::String) at .\sysimg.jl:29
│  [14] include(::String) at .\client.jl:392
│  [15] top-level scope at none:0
│ in expression starting at C:\Users\82416\.juliapro\packages\SymEngine\sh7Yz\deps\build.jl:41
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\Pkg\src\Operatio
ns.jl:1119
  Building Sundials ────────→ `C:\Users\82416\.juliapro\packages\Sundials\1a9iB\deps\build.log`

**Comment by ChrisRackauckas** [comment]
Yup once again a SymEngine build error. We'll see what @isuruf says

**Comment by isuruf** [comment]
> │ ERROR: LoadError: SystemError: opening file C:\Users\82416.juliapro\packages\SymEngine\sh7Yz\deps
\deps.jl: Permission denied

I've no idea why this is? Did you run using Administrator mode before?

**Comment by blackacat** [comment]
I used Administrator mode.

**Comment by isuruf** [comment]
Can you try deleting `C:\Users\82416.juliapro\packages\SymEngine\sh7Yz\deps
\deps.jl` in administrator mode and run again?

**Comment by LianhaoYin** [comment]
Does not work actually. Same error report

**Comment by blackacat** [comment]
I'm building DifferentialEquations in Administrator account now. It's very slow! when finishing it, I will try your suggestion. 

(JuliaPro) pkg> build DifferentialEquations
  Building SpecialFunctions → `C:\Users\Administrator\.juliapro\packages\SpecialFunctions\KvXoO\dep
s\build.log`
  Building DiffEqBase ──────→ `C:\Users\Administrator\.juliapro\packages\DiffEqBase\Rj7cy\deps\buil
d.log`
  Building RandomNumbers ───→ `C:\Users\Administrator\.juliapro\packages\RandomNumbers\cr9ta\deps\b
uild.log`
┌ Error: Error building `RandomNumbers`:
│ fatal: error thrown and no exception handler available.
│ InitError(mod=:MbedTLS, error=MethodError(f=typeof(Base.Filesystem.joinpath)(), args=(nothing, "..
", "..", "deps", "usr", "lib"), world=0x00000000000067f0))
│ rec_backtrace at /home/Administrator/buildbot/worker/package_win64/build/src\stackwalk.c:94
│ record_backtrace at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:246
│ jl_throw at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:577
│ jl_method_error_bare at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1616
│ jl_method_error at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1634
│ jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2161
│ __init__ at C:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\MbedTLS\src\MbedTLS.j
l:61
│ jfptr___init___14286 at C:\JuliaPro-1.0.2.1\Julia-1.0.2\lib\julia\sys.dll (unknown line)
│ jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
│ jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
│ jl_module_run_initializer at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.
c:90
│ _julia_init at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buil
dbot/worker/package_win64/build/src\init.c:813
│ julia_init__threading at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:302
│ wmain at /home/Administrator/buildbot/worker/package_win64/build/ui\repl.c:227
│ __tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:329
│ mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:212
│ BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
│ RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\Pkg\src\Operatio
ns.jl:1119
  Building Arpack ──────────→ `C:\Users\Administrator\.juliapro\packages\Arpack\WP3ru\deps\build.lo
g`
  Building Rmath ───────────→ `C:\Users\Administrator\.juliapro\packages\Rmath\Py9gH\deps\build.log
`
  Building SymEngine ───────→ `C:\Users\Administrator\.juliapro\packages\SymEngine\sh7Yz\deps\build
.log`
┌ Error: Error building `SymEngine`:
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ERROR: LoadError: LoadError: Could not list contents of tarball C:\Users\Administrator\.juliapro\p
ackages\SymEngine\sh7Yz\deps\symengine-0.3\downloads\MPFR.v4.0.1.x86_64-w64-mingw32.tar.gz
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #list_tarball_files#147(::Bool, ::Function, ::String) at C:\Users\julia\AppData\Local\Julia-1
.0.2\share\julia\stdlib\v1.0\BinaryProvider\src\Prefix.jl:468
│  [3] list_tarball_files at C:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\Binary
Provider\src\Prefix.jl:457 [inlined]
│  [4] macro expansion at .\logging.jl:307 [inlined]
│  [5] #install#137(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at C
:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\BinaryProvider\src\Prefix.jl:319
│  [6] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose)
,Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\none:0
│  [7] top-level scope at string:36
│  [8] include_string(::Module, ::String, ::String) at .\loading.jl:1008
│  [9] include_string(::Module, ::String) at .\loading.jl:1012
│  [10] top-level scope at C:\Users\Administrator\.juliapro\packages\SymEngine\sh7Yz\deps\build.jl:3
1
│  [11] include at .\boot.jl:317 [inlined]
│  [12] include_relative(::Module, ::String) at .\loading.jl:1044
│  [13] include(::Module, ::String) at .\sysimg.jl:29
│  [14] include(::String) at .\client.jl:392
│  [15] top-level scope at none:0
│ in expression starting at string:32
│ in expression starting at C:\Users\Administrator\.juliapro\packages\SymEngine\sh7Yz\deps\build.jl:
21
│ ERROR: C:\Users\Administrator\.juliapro\packages\SymEngine\sh7Yz\deps\symengine-0.3\downloads\MPFR
.v4.0.1.x86_64-w64-mingw32.tar.gz
│ Can not open the file as archive
│
│ ��һ���������ʹ�ô��ļ����޷����ʡ�
│
│ 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
│
│
│ Listing archive:
│
│ --
│ Path =
│ Type = tar
│ Code Page = UTF-8
│
│    Date      Time    Attr         Size   Compressed  Name
│ ------------------- ----- ------------ ------------  ------------------------
│ ------------------- ----- ------------ ------------  ------------------------
│                                      0               0 files
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\Pkg\src\Operatio
ns.jl:1119
  Building Sundials ────────→ `C:\Users\Administrator\.juliapro\packages\Sundials\1a9iB\deps\build.
log`

**Comment by blackacat** [comment]
It is work. When deleting C:\Users\82416.juliapro\packages\SymEngine\sh7Yz\deps\deps.jl, error report as follow:
(JuliaPro) pkg> build DifferentialEquations
  Building SpecialFunctions → `C:\Users\82416\.juliapro\packages\SpecialFunctions\KvXoO\deps\build.
log`
  Building DiffEqBase ──────→ `C:\Users\82416\.juliapro\packages\DiffEqBase\Rj7cy\deps\build.log`
  Building RandomNumbers ───→ `C:\Users\82416\.juliapro\packages\RandomNumbers\cr9ta\deps\build.log
`
┌ Error: Error building `RandomNumbers`:
│ fatal: error thrown and no exception handler available.
│ InitError(mod=:MbedTLS, error=MethodError(f=typeof(Base.Filesystem.joinpath)(), args=(nothing, "..
", "..", "deps", "usr", "lib"), world=0x00000000000067f0))
│ rec_backtrace at /home/Administrator/buildbot/worker/package_win64/build/src\stackwalk.c:94
│ record_backtrace at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:246
│ jl_throw at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:577
│ jl_method_error_bare at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1616
│ jl_method_error at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1634
│ jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2161
│ __init__ at C:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\MbedTLS\src\MbedTLS.j
l:61
│ jfptr___init___14286 at C:\Users\82416\AppData\Local\JuliaPro-1.0.2.1\Julia-1.0.2\lib\julia\sys.dl
l (unknown line)
│ jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
│ jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537[inlined]
│ jl_module_run_initializer at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.
c:90
│ _julia_init at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buil
dbot/worker/package_win64/build/src\init.c:813
│ julia_init__threading at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:302
│ wmain at /home/Administrator/buildbot/worker/package_win64/build/ui\repl.c:227
│ __tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:329
│ mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:212
│ BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
│ RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.0.2\share\julia\stdlib\v1.0\Pkg\src\Operatio
ns.jl:1119
  Building Arpack ──────────→ `C:\Users\82416\.juliapro\packages\Arpack\WP3ru\deps\build.log`
  Building Rmath ───────────→ `C:\Users\82416\.juliapro\packages\Rmath\Py9gH\deps\build.log`
  Building SymEngine ───────→ `C:\Users\82416\.juliapro\packages\SymEngine\sh7Yz\deps\build.log`
  Building Sundials ────────→ `C:\Users\82416\.juliapro\packages\Sundials\1a9iB\deps\build.log`

**Comment by ChrisRackauckas** [comment]
Yes, it looks like:

>│ ERROR: C:\Users\Administrator.juliapro\packages\SymEngine\sh7Yz\deps\symengine-0.3\downloads\MPFR
.v4.0.1.x86_64-w64-mingw32.tar.gz

was a download error.

**Comment by blackacat** [comment]
There is no errors when I use Julia1.1.0. So, maybe it is a problem with  juliapro or julia1.0.2?

**Comment by ChrisRackauckas** [comment]
I think the download just went through the second time.
