### ISSUE TITLE
Complex-valued ODE stiff solvers

### ISSUE THREAD

**Issue by daviehh** [JuliaDiffEq/DifferentialEquations.jl#414]
Is there any plan/roadmap to implement the stiff ode solvers for a system of complex-valued odes (e.g. Rosenbrock23)? Thanks!

**Comment by ChrisRackauckas** [comment]
It should work if you do `Rosenbrock23(autodiff=false)`

**Comment by daviehh** [comment]
Not really a stiff problem but just to illustrate the issue,

```
foo(u,p,t) = -0.2im*u;
prob = ODEProblem(foo,0.3im,(0.0,10.0))
sol = solve(prob,Rosenbrock23(autodiff=false))
```
fails with

> MethodError: no method matching similar(::Complex{Float64})
> Closest candidates are:
>   similar(!Matched::ZMQ.Message, !Matched::Type{T}, !Matched::Tuple{Vararg{Int64,N}} where N) where T at /Users/.../.julia/packages/ZMQ/ABGOx/src/message.jl:93
>   similar(!Matched::DataStructures.IntSet) at deprecated.jl:53
>   similar(!Matched::Sundials.NVector) at /Users/.../.julia/packages/Sundials/WX2kB/src/nvector_wrapper.jl:69
>   ...

whereas the non-stiff `sol = solve(prob,BS3())` succeeds. Am I doing anything wrong here? Thanks!

**Comment by ChrisRackauckas** [comment]
Ahh you found a hole. Complex with autodiff=false on arrays works:

```julia
using OrdinaryDiffEq
foo(du,u,p,t) = du[1] = -0.2im*u[1];
prob = ODEProblem(foo,[0.3im],(0.0,10.0))
sol = solve(prob,Rosenbrock23(autodiff=false))
```

What you found is equivalent to https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/373

**Comment by daviehh** [comment]
Got it, thanks a lot!
