### ISSUE TITLE
out-of-place complex-valued matrix stiff ode

### ISSUE THREAD

**Issue by daviehh** [JuliaDiffEq/DifferentialEquations.jl#416]
To solve a stiff complex-value matrix equation, I’m using the Rosenbrock23() solver. As a minimum working example, (may not be stiff, just to illustrate the error I got)

With in-place du, (function taking 4 arguments: du,u,p,t)

```
using DifferentialEquations
using LinearAlgebra

sz=[1 0;0 -1];

function rhs(du,u,p,t)
 du.=-(.3+.5im)*u+sz
end

hdim=2
tf=30.0
ft0=zeros(Complex{Float64}, hdim, hdim);
tspan=(0.0,tf)

prob=ODEProblem(rhs,ft0,tspan)

sol=solve(prob,Rosenbrock23(autodiff=false))
sol.retcode
```
works fine; however, the function that just returns du (taking 3 arguments: u,p,t)

```
using DifferentialEquations
using LinearAlgebra

sz=[1 0;0 -1];

function rhs(u,p,t)
 du=-(.3+.5im)*u+sz
end

hdim=2
tf=30.0
ft0=zeros(Complex{Float64}, hdim, hdim);
tspan=(0.0,tf)

prob=ODEProblem(rhs,ft0,tspan)

sol=solve(prob,Rosenbrock23(autodiff=false))
sol.retcode
```
fails with

> DimensionMismatch(“diagonal matrix is 4 by 4 but right hand side has 2 rows”)

Since this problem involves only 2x2 matrices, this message is quite confusing. Note that for this case, `sol = solve(prob)` works fine, but for my complex stiff equation I need `Rosenbrock23(autodiff=false)`.  Also, if I reshape

```
sz=[1 0;0 -1];

function rhs(ux,p,t)
 u=reshape(ux,2,2)
 du=-(0.3+0.5im)*u+sz
 reshape(du,4,1)
end

hdim=2
tf=30.0
ft0=zeros(Complex{Float64}, 4, 1);
tspan=(0.0,tf)

prob=ODEProblem(rhs,ft0,tspan)

sol=solve(prob,Rosenbrock23(autodiff=false))
sol.retcode
```
works fine also. Is it a possible bug or did I do something wrong here?
Thanks!

**Comment by ChrisRackauckas** [comment]
yeah, we're missing `vec` and `reshape` in `k₁ = W\(integrator.fsalfirst + γ*dT)`. @YingboMa do you know of a fancy regex for this?
