### ISSUE TITLE
Solver that works on GPUs/with CuArrays

### ISSUE THREAD

**Issue by SuperFluffy** [JuliaDiffEq/DifferentialEquations.jl#420]
As discussed on Slack, I'd like to play with the Tsit5 solver that already preliminarily works on GPUs. Requesting a PR or feature branch to give it a try.

**Comment by ChrisRackauckas** [comment]
We found a way to fix GPU compatibility for all algorithms in one go: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/639

**Comment by ChrisRackauckas** [comment]
Complete!
