### ISSUE TITLE
adaptive dt can be off due to float math

### ISSUE THREAD

**Issue by daviehh** [JuliaDiffEq/DifferentialEquations.jl#423]
Some problem can have very different solutions with adaptive time steps where the problem function only differ e.g. due to float numbers, such as sum from different directions. Possibly due to `@fastmath` or interpolation? minimum example (fa, fb only differ in the sum direction in the innermost loop):

```
dim=10
tf=50.0

function fa(du,u,p,t)
    for k in 1:dim
        du[k] = exp(-0.05*t)*(k+dim)
        for i in 1:dim
            du[k] += exp(-.15*t)*cos(u[i])+exp(-.1*t)*sin(u[i])
        end
    end
end

function fb(du,u,p,t)
    for k in 1:dim
        du[k] = exp(-0.05*t)*(k+dim)
        for i in dim:-1:1
            du[k] += exp(-.15*t)*cos(u[i])+exp(-.1*t)*sin(u[i])
        end
    end
end

u0=ones(dim);
tspan = (0.0,tf);

prob_a = ODEProblem(fa,u0,tspan)
prob_b = ODEProblem(fb,u0,tspan)

#sol_a=solve(prob_a,Vern8(),adaptive=false,dt=0.01);
#sol_b=solve(prob_b,Vern8(),adaptive=false,dt=0.01);

# sol_a=solve(prob_a,AutoVern8(Rosenbrock23()));
# sol_b=solve(prob_b,AutoVern8(Rosenbrock23()));

sol_a=solve(prob_a,Vern8());
sol_b=solve(prob_b,Vern8());

# sol_a=solve(prob_a,Rosenbrock23());
# sol_b=solve(prob_b,Rosenbrock23());

diff = [maximum(abs.(sol_a(t)-sol_b(t))) for t in 0:0.01:tf]
maximum(diff)
```

`Vern8` has about `1.09566` difference, `Rosenbrock23` at about `0.3049406`; with `adaptive=false,dt=0.01` the difference is somewhat within float differences, about `8.5e-13`.

Also, with `saveat=0.01`, `diff = [maximum(abs.(sol_a.u[i]-sol_b.u[i])) for i in 1:length(sol_a.u)]` still have the same difference, so maybe not an interpolation issue?

**Comment by daviehh** [comment]
Also note as a way to get a precise solution regardless of float differences with adaptive time steps: `u0=ones(BigFloat,dim)` gives about `1.1e-70` with adaptive dt

**Comment by ChrisRackauckas** [comment]
What about lowering the tolerances?

**Comment by ChrisRackauckas** [comment]
This doesn't look like an issue. `maximum(abs.(sol_a(tf)))` is 364.xxxx, and so the default `reltol=1e-3` would give aiming for error to be `~0.1`, which is right where it is. The fact that the method is exponentially propogating any errors is due to the ODE itself (interesting test case for sure!).

But you can see that if you drop the tolerance:

```julia
sol_a=solve(prob_a,Vern8(),reltol=1e-5);
sol_b=solve(prob_b,Vern8(),reltol=1e-5);
```

you get what you ask for:

```julia
diff = [maximum(abs.(sol_a(t)-sol_b(t))) for t in 0:0.01:tf]
maximum(diff) # 0.0008139819034909124
```
