### ISSUE TITLE
Find a console-based progress monitoring package that works

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#424]
MWE:

```julia
using ProgressLogging
using OrdinaryDiffEq

function lorenz(du,u,p,t)
 du[1] = 10.0*(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz,u0,tspan)
sol = solve(prob, Tsit5(), progress = true)
```

At least one should work?

**Comment by isentropic** [comment]
Perhaps this  https://github.com/cloud-oak/ProgressBars.jl  or this https://github.com/timholy/ProgressMeter.jl could work?

**Comment by ChrisRackauckas** [comment]
They don't use the Base progress logging information, so you have to modify a package to be directly for them. This could get fixed though:

https://github.com/cloud-oak/ProgressBars.jl/issues/12
https://github.com/timholy/ProgressMeter.jl/issues/102

**Comment by tkf** [comment]
Quoting https://github.com/timholy/ProgressMeter.jl/issues/102#issuecomment-543055591:

> I also created https://github.com/tkf/ProgressMeterLogging.jl as a console-based backend for handling the log messages using ProgressMeter.jl.

**Comment by ChrisRackauckas** [comment]
Can you do a PR to the docs http://docs.juliadiffeq.org/latest/features/progress_bar.html to show how to enable that progress meter? Then I think we can call this done.

**Comment by brendanjmeade** [comment]
Would love this too.  It would be fantastic for monitoring long-running remote jobs!

**Comment by tkf** [comment]
I need to register it first.

**Comment by ChrisRackauckas** [comment]
As mentioned in https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/158, 

```julia
using Logging
using OrdinaryDiffEq
using TerminalLoggers

with_logger(TerminalLogger()) do
    solve(
        ODEProblem((u, p, t) -> (sleep(0.01); -u), 1.0, nothing),
        Euler();
        dt = 0.5,
        tspan = (0.0, 100.0),
        progress = true,
        progress_steps = 1,
    )
end
```

works. Though @tkf is there a good way to default to TerminalLoggers if not using Juno?

**Comment by tkf** [comment]
You can link to https://c42f.github.io/TerminalLoggers.jl/stable/#Installation-and-setup-1

```julia
atreplinit() do repl
    try
        @eval begin
            using Logging: global_logger
            using TerminalLoggers: TerminalLogger
            global_logger(TerminalLogger())
        end
    catch
    end
end
```

**Comment by devmotion** [comment]
I thought about this for a bit when I switched AbstractMCMC (and hence Turing) to ProgressLogging, in particular how one could ensure that it works even for users that do not define a specific progress logging visualization backend such as TerminalLoggers (and don't use Juno). The current solution is a heuristic that (somewhat) checks if the current logger supports the progress logging and otherwise installs a suitable visualization backend (ConsoleProgressMonitor for IJulia and TerminalLoggers otherwise) that should not interfere with any user-defined loggers: https://github.com/TuringLang/AbstractMCMC.jl/blob/4bfe617eca199852251f6314627d7eba242e6294/src/AbstractMCMC.jl#L14-L31

**Comment by ChrisRackauckas** [comment]
Awesome! Added to the docs how to use this. It can keep improving, and maybe using a default setup like @devmotion describes would be good, but for now we can at least document how to change the logger. I am scared of setting the global logger though.

**Comment by tkf** [comment]
What @devmotion is doing is only changing the current logger that is active while executing a given block of code.  So it's safe in the sense it does not affect the tasks running in the background.

**Comment by ChrisRackauckas** [comment]
Oh so we can set a local logger in diffeq? Like have a function in DiffEqBase figure out a default logger and then have that be a keyword arg?

**Comment by tkf** [comment]
Yeah, that should be pretty easy. You can wrap [`Logging.with_logger`](https://docs.julialang.org/en/latest/stdlib/Logging/#Logging.with_logger) and do something like

```julia
maybe_with_logger(f, logger) = logger === nothing ? f() : with_logger(f, logger)

solve(...; ..., logger = nothing) =
    maybe_with_logger(logger) do
        ...
    end
```
