### ISSUE TITLE
DDE tutorial example crashes

### ISSUE THREAD

**Issue by reykboerner** [JuliaDiffEq/DifferentialEquations.jl#427]
Running the example code (see text file below) in the [DDE tutorial](http://docs.juliadiffeq.org/latest/tutorials/dde_example.html) for Delay Differential Equations fails. 

It produces the error

> MethodError: no method matching ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing},Vern6,OrdinaryDiffEq.InterpolationData{getfield(DelayDiffEq, Symbol("##35#41")){DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing}},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Vern6Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Vern6ConstantCache{Float64,Float64}}},StatType} where StatType(::Array{Array{Float64,1},1}, ::Nothing, ::Nothing, ::Array{Float64,1}, ::Array{Array{Array{Float64,1},1},1}, ::DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing}, ::Vern6, ::OrdinaryDiffEq.InterpolationData{getfield(DelayDiffEq, Symbol("##35#41")){DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing}},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Vern6Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Vern6ConstantCache{Float64,Float64}}}, ::Bool, ::Int64, ::Symbol)
> 
> Stacktrace:
>  [1] solve!(::DelayDiffEq.DDEIntegrator{Vern6,true,Array{Float64,1},Float64,Nothing,Float64,Float64,Float64,Array{Float64,1},Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing},Vern6,OrdinaryDiffEq.InterpolationData{getfield(DelayDiffEq, Symbol("##35#41")){DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing}},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Vern6Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Vern6ConstantCache{Float64,Float64}}},DiffEqBase.DEStats{Nothing}},ODEFunction{true,getfield(DelayDiffEq, Symbol("##37#43")){DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing}},LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.Vern6Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Vern6ConstantCache{Float64,Float64}},OrdinaryDiffEq.ODEIntegrator{Vern6,true,Array{Float64,1},Float64,Nothing,Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Array{Array{Float64,1},1},Dict{Symbol,Float64},Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Nothing,ODEFunction{true,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},LinearAlgebra.UniformScaling{Bool},getfield(DiffEqBase, Symbol("##180#186")){DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Vern6,OrdinaryDiffEq.InterpolationData{ODEFunction{true,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},LinearAlgebra.UniformScaling{Bool},getfield(DiffEqBase, Symbol("##180#186")){DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Vern6Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Vern6ConstantCache{Float64,Float64}}},DiffEqBase.DEStats{Nothing}},ODEFunction{true,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},LinearAlgebra.UniformScaling{Bool},getfield(DiffEqBase, Symbol("##180#186")){DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.Vern6Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Vern6ConstantCache{Float64,Float64}},OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(LinearAlgebra.opnorm),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Float64,DataStructures.LessThan},Nothing,Nothing,Int64,Array{Float64,1},Array{Float64,1},Array{Float64,1}},Array{Float64,1},Float64},typeof(DiffEqBase.ODE_DEFAULT_NORM),OrdinaryDiffEq.DEOptions{Float64,Float64,Float64,Float64,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(LinearAlgebra.opnorm),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float64,DataStructures.LessThan},DataStructures.BinaryHeap{Discontinuity{Float64},DataStructures.LessThan},Nothing,Nothing,Int64,Array{Float64,1},Array{Float64,1},Array{Discontinuity{Float64},1}},Nothing,Array{Float64,1},Float64}) at C:\Users\Reykiboy\.julia\packages\DelayDiffEq\7RddD\src\solve.jl:340
>  [2] #__solve#51(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing}, ::MethodOfSteps{Vern6,Nothing,Nothing,Nothing,false}, ::Array{Array{Float64,1},1}, ::Array{Float64,1}, ::Array{Any,1}) at C:\Users\Reykiboy\.julia\packages\DelayDiffEq\7RddD\src\solve.jl:365
>  [3] __solve at C:\Users\Reykiboy\.julia\packages\DelayDiffEq\7RddD\src\solve.jl:364 [inlined]
>  [4] #solve#429(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing}, ::MethodOfSteps{Vern6,Nothing,Nothing,Nothing,false}) at C:\Users\Reykiboy\.julia\packages\DiffEqBase\jvgWd\src\solve.jl:39
>  [5] solve(::DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Float64,1},Array{Any,1},true,Nothing,DDEFunction{true,typeof(bc_model),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(h),Nothing}, ::MethodOfSteps{Vern6,Nothing,Nothing,Nothing,false}) at C:\Users\Reykiboy\.julia\packages\DiffEqBase\jvgWd\src\solve.jl:27
>  [6] top-level scope at In[7]:1

[DDE_tutorial_example.txt](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/2894390/DDE_tutorial_example.txt)

**Comment by reykboerner** [comment]
Specifically, it is the line
`sol = solve(prob, alg)`
that fails. Replacing it with
`sol = solve(prob)`
works.

**Comment by ChrisRackauckas** [comment]
@YingboMa it looks like DEStats broke this.

**Comment by ChrisRackauckas** [comment]
Fixed.
