### ISSUE TITLE
type DDEIntegrator has no field destats

### ISSUE THREAD

**Issue by asprionj** [JuliaDiffEq/DifferentialEquations.jl#431]
When running the first/basic example for DDE's presented [in the documentation](http://docs.juliadiffeq.org/stable/tutorials/dde_example.html), I get the following error:

```
type DDEIntegrator has no field destats
in top-level scope at base\none
in solve at DiffEqBase\cPqrj\src\solve.jl:27
in #solve#429 at DiffEqBase\cPqrj\src\solve.jl:39
in __solve at DelayDiffEq\7RddD\src\solve.jl:364 
in #__solve#51 at DelayDiffEq\7RddD\src\solve.jl:365
in solve! at DelayDiffEq\7RddD\src\solve.jl:285
in loopfooter! at OrdinaryDiffEq\gtp9t\src\integrators\integrator_utils.jl
in getproperty at base\sysimg.jl:18
```

I'm using DifferentialEquations.jl version 6.2 on Julia 1.1.0.

**Comment by ChrisRackauckas** [comment]
Hmm, update your packages and try again? We can release a version that increases the minimum bounds to make sure everything is correct, but right now if have the latest DelayDiffEq release (which the package manager should be giving) then you'll be fine.

**Comment by asprionj** [comment]
Sorry for not trying to update everything first. Works fine now!
