### ISSUE TITLE
Installation command from the stable docs with Julia 1.1.0

### ISSUE THREAD

**Issue by homocomputeris** [JuliaDiffEq/DifferentialEquations.jl#432]
The docs say:

> To install the package, use the following command inside the Julia REPL:
> `]add DifferentialEquations`

However, Julia 1.1 does not recognise this syntax:
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> ]add DifferentialEquations
ERROR: syntax: unexpected "]"
```
What command should be used?

**Comment by ChrisRackauckas** [comment]
`]` makes it enter the pkg REPL, and in the pkg REPL you type `add DifferentialEquations`. Maybe our docs should mention something that copy/pastes better.

**Comment by homocomputeris** [comment]
Probably, something like `using Pkg; Pkg.add("DifferentialEquations")` is more copypastable and can be used in a script.

**Comment by dkarrasch** [comment]
I'd say this is a REPL issue, because that line of code is copypastable in Atom... But anyway, that wouldn't work in script. On the other hand, you wouldn't really use that in a script, would you? I mean, you add a package to the `Project.toml` once, and not everytime you run a script?

**Comment by ChrisRackauckas** [comment]
Yup, changed.
