### ISSUE TITLE
Jacobian using ForwardDiff doesn't seem to be working

### ISSUE THREAD

**Issue by astrorCoder** [JuliaDiffEq/DifferentialEquations.jl#434]
I am trying to compute the Jacobian of the result of an ODE using **ForwardDiff** as it seems that it is faster than using Calculus.jacobian. My problem is that I have been trying to get the same results with both methods with no success for a couple of days now. I have been following the documentation about local sensitivity analysis but no luck. The thing is that I was almost about to drop the ForwardDiff method when I tried to do the example in [here](https://docs.juliadiffeq.org/latest/basics/faq.html#Are-the-native-Julia-solvers-compatible-with-autodifferentiation?-1), which just creates two functions (the function that goes into the ODE and the wrapper for the jacobian computation of the final state of the ODE solution), screenshot here:
![image](https://user-images.githubusercontent.com/38725172/54071236-181c8680-426a-11e9-980c-5c6f9d9ae634.png)

Next is just to use ForwardDiff to compute the jacobian:
```
using ForwardDiff
ForwardDiff.jacobian(f,[1.5,1.0])
```
And to my surprise the output of this isn't the same as in the documentation, here is my output:
```
julia> ForwardDiff.jacobian(f,[1.5,1.0])
2×2 Array{Float64,2}:
 -0.0835457  -1.47612 
 -6.35982    -0.994476
```
Where in the documentation it says that the output is:
```
2×2 Array{Float64,2}:
  2.20214   0.189782
 -6.2273   -0.700188
```

Which coincides with the result using Calculus.jacobian for me and the documentation, so there is clearly a problem here, as my machine is giving me a wrong result using ForwardDiff, and I guess that this is why I haven't been able to make it work for my particular case.

Is the a way for me to find the problem?

**Comment by ChrisRackauckas** [comment]
Can you post (and format) the code you are running? It's hard to help with information in this sparse of a format. I think that the main issue is likely that you are taking the wrong derivative. The code you are posting is the derivative of the end value with respect to the parameters. From the previous discussions, I think you wanted to derivative w.r.t. the initial condition, but this code then shows how you'd do that if you swap out a few things.

**Comment by astrorCoder** [comment]
First thing thank you Chris for trying to help and sorry for my poor way of explaining the situation.
I am going to try explain the general idea of what I am trying to do, and then maybe it will be easier for you to grasp the madness of my code: I have an orbit to which I want to get from low earth orbit (LEO). **In the simplest case** there is only two impulses to get there, one in LEO and the other in the insertion point. My method is just to go backwards, from the insertion point (I know the position and velocity there) and given the velocity change there I compute the state at the beginning of the trajectory (to detect this instant I use a continuous callback of the derivative of the distance to Earth). With this setup I have that my variables just change the values of the `u0` in the ODE call, this gives at the end of the computation the state vector , and I need the derivatives with respect to the values of the impulse there, so that I can calculate how the distance to Earth changes with the inputs and I can use some optimization technique that takes advantage of this information. This is again the simplest case, that I haven't been able to make work with ForwardDiff because as I said it is giving me wrong data somehow (compared to finite differences). I didn't want to post anything about the whole problem because I didn't think that it was relevant, but instead I asked about that example in the documentation that doesn't seem to work either. I know that it is not the same, the example in the documentation is about sensitivity w.r.t the parameters of the problem, and my case is w.r.t the initial conditions (or half the initial conditions, I only change the velocity in them), but again even the documentation code (only two functions) gives me the wrong output and I thought it best to figure why is that first, and then worry about how to address my particular problem (maybe solving the first will solve the second, I hope).

And that's kind of the situation I'm at. I'm sorry if I'm not being helpful with my responses, if you really want more code I can post it here, anything you need.

**Comment by ChrisRackauckas** [comment]
>My method is just to go backwards, from the insertion point (I know the position and velocity there) and given the velocity change there I compute the state at the beginning of the trajectory (to detect this instant I use a continuous callback of the derivative of the distance to Earth).

Are you just trying to solve a BVP via a shooting method?

**Comment by astrorCoder** [comment]
I know it sounds weird for that particular case with one impulse at the beginning and other at the end, and it is true that I have been thinking on how to do it with a BVP technique but it isn't that simple. Even for this _simple_ case there isn't just one solution to the problem, my technique involves using global optimization first (with high tolerances) to find all the possible trajectories that perform the insertion in a cost effective way. Even that there is only one global optimal, I am interested in all local minima (and there are several normally), so that I can use them to perform a more fine optimization with them later. Right now I think that this is the best approach, as the next step in terms of trajectory types is to put an intermediate impulse, that I address with Events (in a close approach with the Moon) and another change in the velocity (which I input as a parameter, although this is just so that I can compute the trajectory in one call, instead of `terminate!` the first one and repeat the process for the second part until it reaches the Earth).

So answering to your question yes, I am trying to use a shooting method, but this is because I need to get all the local minima of the problem. Just so you can better understand why I do it like this (not that I don't believe that it can be done better, in fact I am looking forward to find better ways to do it), here is an example where there are two perfectly valid solutions, one is cheaper (in terms of deltaV) and the other is faster:
![image](https://user-images.githubusercontent.com/38725172/54073204-a00f8a00-4284-11e9-8338-7960dbba7b65.png)

And I don't know how would I find this kind of solutions If I used some BVP method (but I haven't put much though into it). That picture is from a little research work that I did using Matlab (with the ode solvers it has) and the _MultiStart_ function of the _GlobalOptimization_ suite, I am now trying to go beyond Matlab (the only thing that they teach at my career, Aerospace Engineering, for computation) and use other solvers and techniques (basically to learn and maybe get a better overall method). I was lucky enough that I found Julia and this suite of numerical integration for ODEs, so I am trying to squeeze everything I can out of this incredible piece of software to solve this particular problem.

**Comment by ChrisRackauckas** [comment]
Can I get a small piece of code that demonstrates your issue with calculating the Jacobian? I am still not sure how to help you.

**Comment by astrorCoder** [comment]
> Can I get a small piece of code that demonstrates your issue with calculating the Jacobian? I am still not sure how to help you.

Sure, I'm on it, I will give you something today. But can you explain the problem with the example of the documentaion? It makes no sense for me, I just copied and paste it, shouldn't it give just the same output?

**Comment by ChrisRackauckas** [comment]
The docs have been fixed. The derivative was accidentally never set. Example:

```julia
using OrdinaryDiffEq
function f(du,u,p,t)
  du[1] = p[1]*u[1] - p[2]*u[1]*u[2]
  du[2] =-p[3]*u[2] + u[1]*u[2]
end

p = [1.5,1.0,3.0]
u0 = [1.0;1.0]
prob = ODEProblem(f,u0,(0.0,10.0),p)

function test_f(p)
  _prob = remake(prob;u0=convert.(eltype(p),prob.u0),p=p)
  solve(_prob,Vern9(),save_everystep=false)[end]
end

test_f(2p)

using ForwardDiff, Calculus
fd_res = ForwardDiff.jacobian(test_f,p)
@show fd_res
fd_res2 = Calculus.finite_difference_jacobian(test_f,p)
@show fd_res2
```

```
fd_res = [2.35547 0.179005 0.609379; -6.13664 -0.701502 -1.68474]
fd_res2 = [2.206 0.179742 0.528034; -6.25232 -0.69557 -1.70833]
```

As expected, ForwardDiff is a bit more accurate but the results are similar.

**Comment by astrorCoder** [comment]
> Can I get a small piece of code that demonstrates your issue with calculating the Jacobian? I am still not sure how to help you.

[testAutoDiff_easyExample.jl.zip](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/2948651/testAutoDiff_easyExample.jl.zip)

I have put it there as simple as I can, there isn't even an event to stop the ODE, it is just a generic ode solver and I try to compute the derivatives of the final coordinates over the impulse components by three methods, and _ForwardDiff_ gives a different result than the other two (even in sign sometimes). I have discarded that it is a noisy solution by plotting the result of one component around the point at which I am computing the derivatives.

**Comment by ChrisRackauckas** [comment]
You just weren't passing in the tolerances. Please just post code next time.

```julia
using OrdinaryDiffEq, Plots, BenchmarkTools, ForwardDiff, Calculus

function dineq!(dy,y,p,t)
    mu  = p[1]
    ro1 = sqrt((y[1]+mu)^2      +y[2]^2 +y[3]^2)
    ro2 = sqrt((y[1]-(1-mu))^2  +y[2]^2 +y[3]^2)
    dy[1] = y[4]
    dy[2] = y[5]
    dy[3] = y[6]
    dy[4] = 2*y[5]+y[1]-(1-mu)*(y[1]+mu)/ro1^3-mu*(y[1]-(1-mu))/ro2^3
    dy[5] = -2*y[4]+y[2]*(1 - (1-mu)/ro1^3-mu/ro2^3)
    dy[6] = -y[3]*((1-mu)/ro1^3+mu/ro2^3)
end

y0 =   [0.8778722440416007 , -6.179952383167375e-16,  0.19253903944176462  , -5.138115530468239e-8 ,  0.2274580849388482   ,1.9654917816881116e-7] #state inside the Halo orbit

goodImp = [0.4251997957169885, 0.0461560165629843, -0.7181655670125794] # This is the last impulse that puts you in the orbit going under the Moon after t = 1.33471 aprox
t = 1.33471

tspan   = (0.0, -t)
# impulse
imp = [0.001,-0.001,0.001] #test impulse (almost no change from the initial state)
data = Dict(    "tspan"     => tspan,
                "Y0"        => y0,
                "x0"        => imp,
                "alg"       => DP5(),
                "tol"       => 1e-12) # Structure to prepare for the optimization

prob    = ODEProblem(dineq!, y0, data["tspan"], 0.01215 )

function calc_data(x)
    type = eltype(x)
    ny0 = data["Y0"] - vcat([0.0,0.0,0.0],x[1:3])
    _prob    = remake(prob, u0 = ny0) # I have tried the four cases
    sol     = solve(_prob, data["alg"], abstol=data["tol"], reltol=data["tol"],dense=false,save_everystep=false) # solution in minimal distance points
    return sol[end][1:3] # Giving only the position (although I ultimately would give the altitude at the end point, this is still a good example of ForwardDiff not doing what I expect)
end

deltaX = 1e-8
d1 = calc_data(imp)
d2 = calc_data(imp-[deltaX,0,0])
d3 = calc_data(imp-[0,deltaX,0])
d4 = calc_data(imp-[0,0,deltaX])

der1 = hcat((d1-d2)/deltaX,(d1-d3)/deltaX,(d1-d4)/deltaX) # The jacobian calculated by myself
@show der1
der2 = ForwardDiff.jacobian(calc_data,imp) # Using ForwardDiff
@show der2
der3 = Calculus.jacobian(calc_data,imp, :central) # Using Calculus
@show der3

#### Ploting the solution close to imp to see if it is noisy (it isnt with the solvers DP8() or DP5())
vector = range(-1e-8, stop = 1e-8 , length=1000)
solu = Vector(undef,length(vector))
for i in 1:length(vector)
    solu[i] = calc_data(imp+[vector[i],0,0])[2] # If I plot the u[2](x[1]) it can be seen that the derivative is negative, but ForwardDiff gives a positive value
end
using Plots
gr()
plot(vector+ones(length(vector))*imp[1],solu)
```

Notice `sol     = solve(_prob, data["alg"], abstol=data["tol"], reltol=data["tol"],dense=false,save_everystep=false) ` is the main difference. Any of the different ways you were remaking the problem would work, but all were unnecessary.

**Comment by astrorCoder** [comment]
> Notice `sol = solve(_prob, data["alg"], abstol=data["tol"], reltol=data["tol"],dense=false,save_everystep=false) ` is the main difference. Any of the different ways you were remaking the problem would work, but all were unnecessary.

ok now it is when I jump through the window... Aside from thanks I don't now what else to say, I feel kind of stupid (this type of thing happens to me more than I'd like to admit). I promise I will try not to bother you with this dumb questions any more, thank you again for the help!

**Comment by ChrisRackauckas** [comment]
No problem. We really need to add some kwarg parsing, that's on our end but to do it correctly is time consuming.
