### ISSUE TITLE
Rodas4 (and others): error on simple problem

### ISSUE THREAD

**Issue by asprionj** [JuliaDiffEq/DifferentialEquations.jl#435]
Consider this simple ODE problem:
```
function min_example(dx, x, p, t)
    dx[1] = t < 5.0 ? 2.5+t/2 : 5.0
    return nothing
end

prob = ODEProblem(min_example, [0.0], (0.0, 10.0))
sol  = solve(prob, Rodas4())
```
As expected, this works fine. Changing the model-function body to
```
y = t < 5.0 ? 2.5+t/2 : 5.0
dx[1] = y[1]
```
does not change a thing. But changing it to
```
y = zeros(1)
y[1] = t < 5.0 ? 2.5+t/2 : 5.0
dx[1] = y[1]
```
yields the following error:
```
MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.TimeGradientWrapper{ODEFunction{true,typeof(min_example),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float64,1},Nothing},Float64},Float64,1})
Closest candidates are:
  Float64(::Real, !Matched::RoundingMode) where T<:AbstractFloat at rounding.jl:194
  Float64(::T<:Number) where T<:Number at boot.jl:741
  Float64(!Matched::Int8) at float.jl:60
  ...
in top-level scope at base\none
in solve at DiffEqBase\ZQVwI\src\solve.jl:27
in #solve#429 at DiffEqBase\ZQVwI\src\solve.jl:39
in __solve at OrdinaryDiffEq\miOSH\src\solve.jl:6 
in __solve at OrdinaryDiffEq\miOSH\src\solve.jl:6 
in __solve at OrdinaryDiffEq\miOSH\src\solve.jl:6 
in #__solve#257 at OrdinaryDiffEq\miOSH\src\solve.jl:7
in solve! at OrdinaryDiffEq\miOSH\src\solve.jl:345
in perform_step! at OrdinaryDiffEq\miOSH\src\perform_step\rosenbrock_perform_step.jl:841 
in perform_step! at OrdinaryDiffEq\miOSH\src\perform_step\rosenbrock_perform_step.jl:874
in calc_rosenbrock_differentiation! at OrdinaryDiffEq\miOSH\src\derivative_utils.jl:347 
in calc_tderivative! at OrdinaryDiffEq\miOSH\src\derivative_utils.jl:13
in derivative! at OrdinaryDiffEq\miOSH\src\derivative_wrappers.jl:3
in derivative! at ForwardDiff\N0wMF\src\derivative.jl:63 
in derivative! at ForwardDiff\N0wMF\src\derivative.jl:66 
in  at DiffEqDiffTools\visbP\src\function_wrappers.jl:7
in ODEFunction at DiffEqBase\ZQVwI\src\diffeqfunction.jl:107 
in min_example at <my_julia_script>.jl:190
in setindex! at base\array.jl:767
in convert at base\number.jl:7
```

Funny thing is that I do not get an error if I use, for example, solver `Tsit5`. Also, removing the time dependency from the first case resolves the error (yes, I know, it's not smooth anymore):
```
y = zeros(1)
y[1] = t < 5.0 ? 4.5 : 5.0
dx[1] = y[1]
```

This is no made-up example, I encountered this when composing my model function from various other functions. I feel like there's a family of solvers which have this error; maybe the ones calling the `calc_rosenbrock_differentiation!` method?

**Comment by ChrisRackauckas** [comment]
`Rodas4(autodiff=false)` will work fine. Your issue is that your values are not dual-number ware so autodiff is failing. Instead of `y = zeros(1)`, you should do `y = zeros(u)` so it matches the types.

**Comment by asprionj** [comment]
Shouldn't `y = Array{Float64,1}(undef,1)` help then? (Hint: It doesn't...)On 13 Mar 2019 16:14, Christopher Rackauckas <notifications@github.com> wrote:Rodas4(autodiff=false) will work fine. Your issue is that your values are not dual-number ware so autodiff is failing. Instead of y = zeros(1), you should do y = zeros(u) so it matches the types.

**Comment by ChrisRackauckas** [comment]
No, the issue is that during automatic differentiation the numbers are not Float64s. We use ForwardDiff to do autodiff via dual numbers, like is discussed in here: https://en.wikipedia.org/wiki/Automatic_differentiation#Automatic_differentiation_using_dual_numbers . `y = Array{eltype(x),1}(undef,1)` would then work, since it would be dual matching. Or you can do `Rodas4(autodiff=false)` to do good ole numerical differencing (with the standard caveats of course).

**Comment by asprionj** [comment]
Would like to keep autodiff-ing...
`Array{eltype(x),1}(undef,1)` does not work, but `Array{eltype(t),1}(undef,1)` does. In the expression defining the single entry of `y`, only `t` is used as variable. But if I then use (some elements of) `x` and `t` in an expression, I would have to use `Array{Union{eltype(t),eltype(x)},1}(undef,1)`, right? (At least this works...)
For the use case at hand, I'll anyway go towards a different implementation not using a single indexed array for all intermediate quantities (calculated by function calls), but one uniquely named variable per function call.

**Comment by ChrisRackauckas** [comment]
Oh yeah, there's the derivative w.r.t. `x` and the derivative w.r.t. `t`. So then `Array{promote_type(eltype(t),eltype(x)),1}(undef,1)` is what you want. If you then want to stop the allocations by caching everything outside the function, then you will want to do http://docs.juliadiffeq.org/latest/basics/faq.html#I-get-Dual-number-errors-when-I-solve-my-ODE-with-Rosenbrock-or-SDIRK-methods...?-1 .

**Comment by asprionj** [comment]
Thanks for the explanation and the link on how to avoid caching in this case. Hope I'll never need it though... ;-)
