### ISSUE TITLE
Problem with DAE Solvers

### ISSUE THREAD

**Issue by pennerale96** [JuliaDiffEq/DifferentialEquations.jl#441]
As the title suggests, I encountered a problem that all the DAE Solver from DifferentialEquations share: I defined a struct **nd** with a field f that may be called as a function with the typical (dx,x,p,t) - ODE pattern. The basic problem that I have encountered schematically looks the following:

```
struct A
    f::Array{SubArray}
end

function(A::nd)(dx,x,p,t)
      A.f[idx] .= x[idx]
      dx .= something...
end
```

So far so good. Now if I try to set up an ODEProblem with this struct via

```
prob = ODEProblem(A(arr),x0,tspan)
sol = solve(prob, Rodas4())
```
, I run into the following Error:

MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{DiffEqDiffTools.UJacobianWrapper{ODEFunction{true,A,UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,Nothing},Float64},Float64,12})

This one appears not just for Rodas4 but for every DAE Solver. Other non-DAE Solvers may solve the problem like its nothing special, so I suppose there is something going on with the from the Solver expected DAE function structure I don't understand. I could make the above work if I substitute the x[idx] in the function to e.g. some Number. For my means, the above structure is sadly crucial and I need to use a DAE Solver since I want to use mass matrices. 

Is it supposed to be not working when using functions of this structure?

Best regards!

**Comment by pennerale96** [comment]
The first Code Line should of course be struct nd, sorry.

**Comment by ChrisRackauckas** [comment]
This is described here: http://docs.juliadiffeq.org/latest/basics/faq.html#I-get-Dual-number-errors-when-I-solve-my-ODE-with-Rosenbrock-or-SDIRK-methods...?-1 . Let me know if you have any other questions.
