### ISSUE TITLE
Banded matrix lu!

### ISSUE THREAD

**Issue by JianghuiDu** [JuliaDiffEq/DifferentialEquations.jl#451]
Doing some tests and found out that none of the methods (`Rosenbrock23`,`TRBDF2`,`ABDF2`,`Kvaerno5`,`KenCarp4` etc.) work with `SparseMatrixCSC{Float64,Int64}`. They all return this error
```
ERROR: MethodError: no method matching lu!(::SparseMatrixCSC{Float64,Int64})
```
They do work with `BandedMatrices`.
Does specifying `jac_prototype` automatically cause dispatch of relevant linear solvers? Or some other things are required?

**Comment by ChrisRackauckas** [comment]
You need to set `linsolve=LinSolveFactorize(lu)`. This is solved in the next release though: https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/210 so I'm closing since we already known the default linsolve mechanism will be sparse and GPU safe when it's released (hopefully this week. It depends on getting Project.toml files).

**Comment by JianghuiDu** [comment]
What about the bandedmatrices? Does it also require to set `linsolve`?

**Comment by ChrisRackauckas** [comment]
It shouldn't. It'll default to `lu`, but it would likely be better to default to `lu!`.

**Comment by JianghuiDu** [comment]
With this I have the error `ERROR: UndefVarError: lu not defined`

**Comment by ChrisRackauckas** [comment]
Banded matices have `lu!` but not `lu`?

**Comment by JianghuiDu** [comment]
Neither banded nor sparse has neither lu nor lu!

**Comment by ChrisRackauckas** [comment]
Sparse has `lu` but not `lu!`.

**Comment by JianghuiDu** [comment]
No. I'm saying that `lu` and `lu!` doesn't work for either sparse or banded.

**Comment by JianghuiDu** [comment]
```
@time sol = solve(prob_sparse_jac,Rosenbrock23(linsolve=LinSolveFactorize(lu)),reltol=1e-3,abstol=1e-12,saveat=500); #252 
```
returns  `ERROR: UndefVarError: lu not defined`
```
@time sol = solve(prob_banded_jac,Rosenbrock23(linsolve=LinSolveFactorize(lu!)),reltol=1e-3,abstol=1e-12,saveat=500); #2s
```
returns
`ERROR: UndefVarError: lu! not defined`

**Comment by ChrisRackauckas** [comment]
`using LinearAlgebra`

**Comment by JianghuiDu** [comment]
So stupid! I can't help forgetting that `LinearAlgebra` is not in the base anymore.

**Comment by ChrisRackauckas** [comment]
```julia
using SparseArrays, LinearAlgebra
lu(sprand(100,100,0.1))

using BandedMatrices
lu(brand(100,100,4,3))
lu!(brand(100,100,4,3))
```

that shows the new PR gives the optimal way of doing it (no `lu!` for banded)

**Comment by JianghuiDu** [comment]
It appears banded matrix is faster than sparse, even when only ~0.3% elements are non-empty.
