### ISSUE TITLE
DifferentialEquations and Unitful

### ISSUE THREAD

**Issue by giordano** [JuliaDiffEq/DifferentialEquations.jl#455]
This script used to work at some point in the past (probably it's also in one of the tutorials):
```julia
using DifferentialEquations, Unitful

year = 86400 * 365.25 * u"s"
# Half-life and mean lifetime of radiocarbon
c = 5730 * year
τ = c / log(2)
# Setup
u₀ = 1.0
tspan = (0.0 * year, 10000.0 * year)
# Define the problem
radioactivedecay(u,p,t) = - u / τ
# Pass to solver
prob = ODEProblem(radioactivedecay, u₀, tspan)
sol = solve(prob, Tsit5(), reltol = 1e-8)
# Analytic solution
u = exp.(-sol.t / τ)
```

Chris noted that it works if `u₀` has a dimension (like `u₀ = 1.0 * u"kg"`), but in that case also `reltol` keyword argument to `solve` would need to have the same dimension (`reltol = 1e-8u"kg"`) which is kind of wrong, since the relative tolerance is supposed to be dimensionless.  Also, physically speaking the case with `u₀` dimensionless is acceptable.

**Comment by ChrisRackauckas** [comment]
I'm trying to figure out if this is really just an upstream issue, since indeed units on `u` makes it work, so it seems to be a missing dispatch in Unitful for how to handle unitless quantities?
