### ISSUE TITLE
Higher order derivatives in ode_def

### ISSUE THREAD

**Issue by seadra** [JuliaDiffEq/DifferentialEquations.jl#468]
Having a syntax for specifying higher order derivatives will be very useful, with ODEs involving high order derivatives. This would allow almost simply typing the differential equation as is, similar to the way it can be done in Mathematica.

**Comment by ChrisRackauckas** [comment]
We are moving away from ode_def, and ModelingToolkit.jl can already automatically lower derivatives: https://github.com/JuliaDiffEq/ModelingToolkit.jl/blob/master/test/system_construction.jl#L112-L123 . The way we will do this in the near future will be by integrating ModelingToolkit.jl to make this happen more automatically.

**Comment by ChrisRackauckas** [comment]
Fixed by the ODE lowering in ModelingToolkit.jl
