### ISSUE TITLE
DiscreteCallback save_positions broken

### ISSUE THREAD

**Issue by benneti** [JuliaDiffEq/DifferentialEquations.jl#474]
If I use `save_positions=(false, true)` all timepoints except the first one are doubled.
An example of this is also if I just run this  [example from the docs](https://docs.juliadiffeq.org/latest/features/callback_library.html#Manifold-Conservation-and-Projection-1), which as I understand it should only save after the projection but it saves before and after.
Setting `save_positions=(false, false)` still saves before which let's me assume that the first boolean of this tuple takes no effect.

**Comment by benneti** [comment]
I think the issue is that due to line (591)
```
    # handle saveat
    _, savedexactly = savevalues!(integrator)
```
it always saves.

**Comment by ChrisRackauckas** [comment]
I updated the docs.

>Note that the standard saving occurs after the step and before the callback, and thus we set save_everystep=false to turn off all standard saving and let the callback save after the projection is applied.

**Comment by benneti** [comment]
thank you :+1:
