### ISSUE TITLE
Adjoint doesn´t yield the same result as other methods

### ISSUE THREAD

**Issue by JMmontilla** [JuliaDiffEq/DifferentialEquations.jl#475]
I was trying the example of the adjoint method to compute the local sensitivity with a discrete cost functional, but it doesn´t give me the same result as the other methods that appear as a comparaison (ForwardDiff, Calculus, Flux.Tracker and ReverseDiff), this is the code I´m using (slightly modified from the [example](https://docs.juliadiffeq.org/latest/analysis/sensitivity.html#Adjoint-Sensitivity-Analysis-1), as it was lacking the `t` points and the syntax of the cost functional derivative was not correct, apparently):
```julia
using DifferentialEquations, DiffEqSensitivity, BenchmarkTools

function f(du,u,p,t)
  du[1] = dx = p[1]*u[1] - p[2]*u[1]*u[2]
  du[2] = dy = -p[3]*u[2] + u[1]*u[2]
end

p = [1.5,1.0,3.0]
const prob = ODEProblem(f,[1.0;1.0],(0.0,10.0),p)
sol = solve(prob,Vern9(),abstol=1e-10,reltol=1e-10)

function dg(out,u,p,t,i)
  out .= 1.0 .- u
end
const t = collect(0.5:0.5:10)
res = adjoint_sensitivities(sol,Vern9(),dg,t;abstol=1e-14,reltol=1e-14,iabstol=1e-14,ireltol=1e-12)

using ForwardDiff, Calculus, ReverseDiff, Flux
function G(p)
  tmp_prob = remake(prob,u0=convert.(eltype(p),prob.u0),p=p)
  sol_i = solve(tmp_prob,Vern9(),abstol=1e-14,reltol=1e-14,saveat=t)
  A = convert(Array,sol_i)
  sum(((1.0 .- A).^2)./2)
end
G(p)
res2 = ForwardDiff.gradient(G,p)
res3 = Calculus.gradient(G,p)
res4 = Flux.Tracker.gradient(G,p)
res5 = ReverseDiff.gradient(G,p)
```
The adjoint method yields:
```julia
1×3 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:
 64.6219  -103.155  74.5524
```
While the others:
```julia
3-element Array{Float64,1}:
  25.50063723178837
 -77.25507741525354
  93.53212756432487
```
And I´m guessing that's too much of a difference. Is there something wrong with my code?

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/pull/82. This also has a test now. The issue was that `t0` was not in the times, and this messed with the integral calculation. We now properly always go back to `t0` in the backpass. This fixes some things that @jessebett noticed.

**Comment by ChrisRackauckas** [comment]
Thanks for the report!
