### ISSUE TITLE
Wrong return type container for NTuple

### ISSUE THREAD

**Issue by tomaklutfu** [JuliaDiffEq/DifferentialEquations.jl#477]
As discussed [here](https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/issues/63#issuecomment-506777972).

**Comment by tomaklutfu** [comment]
Also this [line](https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/c8c42b09cc476886b75e75bb327d0d94c3293068/src/solve.jl#L93) in JuliaDiffEq/OrdinaryDiffEq.jl seems fishy and root of the cause. There are some more `ArrayPartition` conversion of `Tuple` initial conditions in that package and the reason is not clear to me.
@ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Indeed, it's baked into the package and we should just get rid of it.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/255

and then we just have to merge https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/799 after that's tagged in DiffEqBase and we're good.

**Comment by tomaklutfu** [comment]
Thanks, great work.
