### ISSUE TITLE
Convert error when specifying jacobian for Rosenbrock method

### ISSUE THREAD

**Issue by jibaneza** [JuliaDiffEq/DifferentialEquations.jl#480]
When specifying the jacobian as in the example provided in the docs the solver returns a convert error if Rosenbrock23() is used.
Code example:
`using LinearAlgebra, DifferentialEquations
f = (du,u,p,t) -> du .= t .* u
jac = (J,u,p,t) -> (J[1,1] = t; J[2,2] = t; J)
jp = Diagonal(zeros(2))
fun = ODEFunction(f; jac=jac, jac_prototype=jp)
prob = ODEProblem(fun,ones(2),(0.0,10.0))
solve(prob,Rosenbrock23(;autodiff=false))`

returns: ERROR: MethodError: Cannot `convert` an object of type Nothing to an object of type Float64

**Comment by ChrisRackauckas** [comment]
Should make sure we do the same in StochasticDiffEq.jl

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/837
https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/300
https://github.com/JuliaDiffEq/StochasticDiffEq.jl/pull/206

We want to make sure this is all good with color differentiation though.

**Comment by ChrisRackauckas** [comment]
Structured matrices now work!
