### ISSUE TITLE
Collect solution.u into multidimensional array without specifying type

### ISSUE THREAD

**Issue by jessebett** [JuliaDiffEq/DifferentialEquations.jl#482]
```
prob = ODEProblem(trueODEfunc,u0,tspan)
sol = solve(prob,Tsit5(),saveat=t)
ode_data = Array(sol)
```

Often we collect the `sol` into a multidimensional array using `Array`. However, if the `sol.u` are `CuArrays` then this does not preserve their type, and brings them to the CPU.

Unfortunately `collect` on `CuArrays` also has this side effect, where it pulls them to the CPU.

If I replace `Array` with `CuArray` then this will work.

It would be nice to have this function to turn the array of vectors into a multidimensional array that preserves the type of the underlying vectors.

**Comment by jessebett** [comment]
Also noticed that `CuArray` on a gpu `sol` will try to `collect` into the `cpu` and then put it back, I believe. This is bad because if `CuArrays.allowscalar(false)` then `CuArray(sol)` fails.

**Comment by ChrisRackauckas** [comment]
`reduce(hcat,sol.u)` and things like that are now the canonical ways from Base to do this.
