### ISSUE TITLE
Documentation on EnsembleProblem - need to first add "using DifferentialEquations.EnsembleAnalysis"

### ISSUE THREAD

**Issue by Ksmith144** [JuliaDiffEq/DifferentialEquations.jl#496]
I couldn't find in the docs the fact that you needed to add "using DifferentialEquations.EnsembleAnalysis" in order to use the analysis functions, e.g., get_timestep.

**Comment by ChrisRackauckas** [comment]
Updated the docs. Thanks for the report!
