### ISSUE TITLE
Monte Carlo simulations using Parallel Ensemble Simulations are not entirely random

### ISSUE THREAD

**Issue by TorkelE** [JuliaDiffEq/DifferentialEquations.jl#498]
I'm having a weird issue where SDE simulations sometimes turns out identical in an ensemble:

```julia
using DifferentialEquations, DiffEqBiological, Plots
function monte(rn,p,tspan,n)
  prob = SDEProblem(rn,fill(1.,length(rn.syms)),tspan,p)
  ensemble_prob = EnsembleProblem(prob,prob_func=(p,i,r)->p)
  return solve(ensemble_prob,ImplicitEM(),EnsembleThreads(),trajectories=n)
end
rn = @reaction_network begin
  (1.,2.), ∅ ↔ X
end k1 k2
sol = monte(rn,[1.,2.],(0.,1.),4)
plot(sol)
```

rerunning this a few times and investigating the plots, one should always have 4 distinct trajectories. However, quite often, there are only 3 or even 2. This as some perfectly overlap (indicating that they were simulated using the same random Seed?).

Some additional information; removing `ImplicitEM()` and just having `return solve(ensemble_prob,EnsembleThreads(),trajectories=n)` seems to solve this. Which kinda further confuses me, but might be helpful for those with better understanding.

**Comment by ChrisRackauckas** [comment]
What Julia version is this on? My guess is that the issue may be due to multithreading causing an overlap in `_seed` here:

https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/src/solve.jl#L246

On v1.1 this might not be thread-safe, while on v1.2 I think using the global rand on different threads should always give a different seed?

**Comment by TorkelE** [comment]
This is on Julia 1.2, providing the output from `Pkg.status`
```julia
 Status `~/.julia/environments/v1.2/Project.toml`
  [c52e3926] Atom v0.9.1
  [6e4b80f9] BenchmarkTools v0.4.2
  [a134a8b2] BlackBoxOptim v0.5.0
  [34da2185] Compat v2.1.0
  [864edb3b] DataStructures v0.17.0
  [31a5f54b] Debugger v0.5.0
  [2b5f629d] DiffEqBase v5.20.0
  [eb300fae] DiffEqBiological v3.9.1 [`~/.julia/dev/DiffEqBiological`]
  [c894b116] DiffEqJump v6.2.0
  [c3c3384c] DiffEqParameters v0.1.0 #master (https://gitlab.com/slcu/teamHJ/niklas/DiffEqParameters.jl.git)
  [0c46a032] DifferentialEquations v6.6.0
  [7c1d4256] DynamicPolynomials v0.3.2
  [28b8d3ca] GR v0.41.0
  [f213a82b] HomotopyContinuation v1.1.1
  [7073ff75] IJulia v1.20.0
  [4076af6c] JuMP v0.20.0
  [aa1ae85d] JuliaInterpreter v0.6.1
  [e5e0dc1b] Juno v0.7.2
  [23fbe1c1] Latexify v0.8.2
  [1914dd2f] MacroTools v0.5.1
  [1dea7af3] OrdinaryDiffEq v5.15.0
  [65888b18] ParameterizedFunctions v4.2.1
  [d96e819e] Parameters v0.11.0
  [91a5bcdd] Plots v0.26.2
  [f27b6e38] Polynomials v0.5.2
  [d330b81b] PyPlot v2.8.1
  [3cdcf5f2] RecipesBase v0.7.0
  [189a3867] Reexport v0.2.0
  [14e83994] SimulationSupport v0.1.0 [`../../dev/SimulationSupport`]
  [9672c7b4] SteadyStateDiffEq v1.5.0
  [789caeaf] StochasticDiffEq v6.8.0
  [123dc426] SymEngine v0.7.0
  [2f01184e] SparseArrays 
```

**Comment by ChrisRackauckas** [comment]
```julia
sol[1].seed
sol[2].seed
sol[3].seed
sol[4].seed
```

shows that they can get the same seed. This is because there is one global RNG call to get a seed:

https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/master/src/solve.jl#L246

and that's not thread-safe until Julia v1.3 🤷‍♂ . What you could do on your side, which would also make the results reproducible, is to set a seed:

```julia
function monte(rn,p,tspan,n)
  prob = SDEProblem(rn,fill(1.,length(rn.syms)),tspan,p)
  ensemble_prob = EnsembleProblem(prob,prob_func=(p,i,r)->remake(p,seed=i))
  return solve(ensemble_prob,ImplicitEM(),EnsembleThreads(),trajectories=n)
end
rn = @reaction_network begin
  (1.,2.), ∅ ↔ X
end k1 k2
sol = monte(rn,[1.,2.],(0.,1.),4)
plot(sol)
```

Maybe a hack that we can do is to multiply the seed by the `Threads.threadid()` so that even if the RNG collides they are highly unlikely to be the same.

**Comment by ChrisRackauckas** [comment]
One other place can hit this as well: https://github.com/JuliaDiffEq/DiffEqJump.jl/blob/a336dc63b30b5904939928a956a5c68c8c51bb94/src/solve.jl#L14

**Comment by TorkelE** [comment]
I understand. But this would mean that the problem would be solved by Julia 1.3?

Multiply by the Threads.threadid() seems like the clever solution. I might go for that, or just wait for 1.3.

**Comment by ChrisRackauckas** [comment]
This is fixed in the packages now, and there's a piece of code that won't be needed in Julia v1.3. So you don't need to worry about it. Thanks for the report.

**Comment by TorkelE** [comment]
Thanks for the quick fix!
