### ISSUE TITLE
Example: Heat Equation System

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#50]
At ln[3]

LoadError: UndefVarError: heatProblemExample_diffusionconstants not defined
while loading In[3], in expression starting on line 6

**Comment by ChrisRackauckas** [comment]
The bottom part in the example needs to be `prob_femheat_diffusionconstants` as shown in the first cell. I'll push that fix ASAP.

**Comment by ChrisRackauckas** [comment]
BTW, thanks for digging through all of the examples. I thought I found all of the `(du,u,t)` -> `(t,u,du)` and problem function -> problem object changes, but clearly I missed a few.

**Comment by ChrisRackauckas** [comment]
This example was updated and tested with the fix from the previous comments.
