### ISSUE TITLE
MethodError on solve()

### ISSUE THREAD

**Issue by sosiristseng** [JuliaDiffEq/DifferentialEquations.jl#504]
An error occurred when I called `solve(odeproblem)`
```
MethodError: no method matching solve_call(::ODEProblem{Float64,Tuple{Float64,Float64},false,Float64,ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem})
```
The minimal 'working' example:
https://nextjournal.com/sosiristseng/diffeq-test

This kind of code was working fine previously, with the same base Nextjurnal environment. I'm not sure what caused this error.

**Comment by sosiristseng** [comment]
And package testing also failed. I've updated my Nextjournal article above.

**Comment by ChrisRackauckas** [comment]
Yes, this was an issue with a recent release and I'll get this fixed up today. Thanks for notifying us.

**Comment by ChrisRackauckas** [comment]
sorry about the error in the release. v6.8.0 was just release which fixes the default argument handling. Thanks for the report.
