### ISSUE TITLE
Computational time

### ISSUE THREAD

**Issue by rvignolo** [JuliaDiffEq/DifferentialEquations.jl#506]
Dear @ChrisRackauckas,

Did you have time to check out the issue I submitted [here](https://github.com/JuliaDiffEq/StochasticDiffEq.jl/issues/232)? It seems important. 

Thank you very much,
Ramiro.

**Comment by ChrisRackauckas** [comment]
Yup I responded. Since there's quite a lot of SDE-specific stuff going on in there, let's keep it there. Hopefully that response wasn't too long.
