### ISSUE TITLE
StochasticDiffEq's version of FillArray may be preventing updates

### ISSUE THREAD

**Issue by daviehh** [JuliaDiffEq/DifferentialEquations.jl#507]
[If one has the current `BandedMatrices` (version 0.11.1), DifferentialEquations will not update to v6.8.0]

Just noticed that my DifferentialEquations is kept at 6.6.0 and will not update to 6.8.0. Starting with a fresh `.julia` directory, this can be reproduced by:
```
]add BandedMatrices
]add DifferentialEquations
```
which will only install v6.6.0 of DifferentialEquations; digging through it looks like `StochasticDiffEq.jl` is forcing v0.6 of `FillArrays` [here](https://github.com/JuliaDiffEq/StochasticDiffEq.jl/blob/46e153417158c2f3dc5dbad83530db6a10fef2c8/Project.toml#L33); changing that line to e.g. `FillArrays = "≥ 0.6"` will allow the 6.8.0 update, [test ok](https://travis-ci.org/daviehh/StochasticDiffEq.jl/builds/585664955).

- Details:

Install v6.8.0 explicitly gives this error:
`]add DifferentialEquations@6.8.0`

>  Resolving package versions...
> ERROR: Unsatisfiable requirements detected for package LazyArrays [5078a376]:
>  LazyArrays [5078a376] log:
>  ├─possible versions are: [0.0.1, 0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0-0.3.2, 0.4.0, 0.5.0-0.5.2, 0.6.0, 0.7.0-0.7.1, 0.8.0-0.8.1, 0.9.0-0.9.1, 0.10.0, 0.11.0] or uninstalled
>  ├─restricted by compatibility requirements with BandedMatrices [aae01518] to versions: 0.11.0
>  │ └─BandedMatrices [aae01518] log:
>  │   ├─possible versions are: [0.0.1-0.0.9, 0.1.0-0.1.2, 0.2.0-0.2.3, 0.3.0-0.3.1, 0.4.0, 0.5.0-0.5.2, 0.6.0, 0.7.0-0.7.2, 0.8.0-0.8.2, 0.9.0-0.9.4, 0.10.0-0.10.1, 0.11.0-0.11.1] or uninstalled
>  │   └─restricted to versions 0.11.1 by an explicit requirement, leaving only versions 0.11.1
>  └─restricted by compatibility requirements with FillArrays [1a297f60] to versions: [0.0.1, 0.1.0, 0.8.1, 0.9.0-0.9.1, 0.10.0] or uninstalled — no versions left
>    └─FillArrays [1a297f60] log:
>      ├─possible versions are: [0.0.1, 0.1.0, 0.2.0-0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.4, 0.7.0] or uninstalled
>      ├─restricted by julia compatibility requirements to versions: [0.2.0-0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.4, 0.7.0] or uninstalled
>      ├─restricted by compatibility requirements with BandedMatrices [aae01518] to versions: [0.6.4, 0.7.0]
>      │ └─BandedMatrices [aae01518] log: see above
>      └─restricted by compatibility requirements with StochasticDiffEq [789caeaf] to versions: 0.6.0-0.6.4, leaving only versions: 0.6.4
>        └─StochasticDiffEq [789caeaf] log:
>          ├─possible versions are: [0.0.1-0.0.5, 0.1.0-0.1.1, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0, 2.0.0-2.0.4, 2.1.0, 2.2.0-2.2.1, 2.3.0, 2.4.0, 2.5.0-2.5.1, 2.6.0, 2.7.0-2.7.1, 2.8.0, 2.9.0-2.9.1, 2.10.0, 2.11.0-2.11.1, 2.12.0-2.12.1, 2.13.0-2.13.1, 2.14.0, 2.15.0-2.15.2, 2.16.0, 2.17.0, 2.18.0-2.18.1, 2.19.0, 2.20.0-2.20.1, 2.21.0, 2.22.0, 2.23.0-2.23.4, 3.0.0, 3.1.0, 3.2.0, 4.0.0, 4.1.0, 4.2.0-4.2.4, 4.3.0, 4.4.0-4.4.5, 5.0.0, 5.1.0, 5.2.0-5.2.3, 5.3.0, 5.4.0, 5.5.0, 5.6.0-5.6.1, 5.7.0-5.7.1, 5.8.0, 5.9.0-5.9.2, 5.10.0-5.10.4, 5.11.0-5.11.4, 5.12.0, 6.0.0, 6.1.0-6.1.1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 6.8.0, 6.9.0-6.9.1, 6.10.0, 6.11.0] or uninstalled
>          ├─restricted by julia compatibility requirements to versions: [5.0.0, 5.1.0, 5.2.0-5.2.3, 5.3.0, 5.4.0, 5.5.0, 5.6.0-5.6.1, 5.7.0-5.7.1, 5.8.0, 5.9.0-5.9.2, 5.10.0-5.10.4, 5.11.0-5.11.4, 5.12.0, 6.0.0, 6.1.0-6.1.1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 6.8.0, 6.9.0-6.9.1, 6.10.0, 6.11.0] or uninstalled
>          └─restricted by compatibility requirements with DifferentialEquations [0c46a032] to versions: [6.9.0-6.9.1, 6.10.0, 6.11.0]
>            └─DifferentialEquations [0c46a032] log:
>              ├─possible versions are: [0.0.1-0.0.3, 0.1.0-0.1.4, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.2, 0.5.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0-1.3.1, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0-1.9.1, 1.10.0-1.10.1, 2.0.0, 2.1.0, 2.2.0-2.2.1, 2.3.0, 3.0.0-3.0.2, 3.1.0, 4.0.0, 4.1.0-4.1.1, 4.3.0, 4.4.0-4.4.1, 4.5.0, 5.0.0, 5.1.0, 5.2.0-5.2.1, 5.3.0-5.3.1, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.6.0, 6.7.0, 6.8.0] or uninstalled
>              └─restricted to versions 6.8.0 by an explicit requirement, leaving only versions 6.8.0
> 

where
```
pkg> st
```
returns
```
  [aae01518] BandedMatrices v0.11.1
  [0c46a032] DifferentialEquations v6.6.0
```

**Comment by ChrisRackauckas** [comment]
Fixed and setup a new release for this. Thanks for the notice!
