### ISSUE TITLE
Parallel Ensemble Simulations JumpProblem using Gillespie not working

### ISSUE THREAD

**Issue by danielchen26** [JuliaDiffEq/DifferentialEquations.jl#509]
```julia 
using DiffEqBiological, DifferentialEquations
rn = @reaction_network begin
 (α, ϵ),            2A + B ↔ C
  β,                C → C + A
  η,                B → B + A
 (γ,θ),             B ↔ D
  δ,                A → ∅
end α ϵ β η γ θ δ


u0 = [10.,1.,0.,0.];  tspan = (0.,1e1)
params = [5., 5., 5., 0.03, 5., 5., 5.]


dprob = DiscreteProblem(rn, u0, tspan, params)
jprob = JumpProblem(dprob, Direct(), rn)

# test func 1
function prob_func(prob, i, repeat)
    prob.u0[2:4] = rand()
    prob
end
# test func 2
function prob_func(prob, i, repeat)
  ODEProblem(prob.f, rand()*prob.u0, prob.tspan, prob.p)
end

ensemble_prob = EnsembleProblem( jprob, prob_func=prob_func)
sim = solve(ensemble_prob, SSAStepper(), EnsembleThreads(),trajectories=10)
```

**Comment by ChrisRackauckas** [comment]
```julia
# test func 2
function prob_func(prob, i, repeat)
  ODEProblem(prob.f, rand()*prob.u0, prob.tspan, prob.p)
end
```

doesn't make sense. A `prob` is a `JumpProblem`, so `prob.f` doesn't exist. And `SSAStepper()` can't solve an `ODEProblem`: it's for `JumpProblem{DiscreteProblem}`. I'm giving it a better error message but I don't know what you were trying to do with this.

**Comment by danielchen26** [comment]
oh, sorry I wasn't suppose to put test func 2 here.
but for
` function prob_func(prob,i,repeat)
    # prob.u0[2:4] = fun.randfixsum(1,3,1)
    prob.u0[1] = rand()
    prob
end`
ensemble_prob = EnsembleProblem(jprob,prob_func=prob_func)
sim = solve(ensemble_prob,SSAStepper(),EnsembleThreads(),trajectories=10)
This still gives me error.

**Comment by ChrisRackauckas** [comment]
`prob.u0` doesn't exist because it's a `JumpProblem`. Did you mean to build a new `DiscreteProblem` and put `JumpProblem` over that?

**Comment by danielchen26** [comment]
Yeah, that's what I want. Basically, build a new `DiscreteProblem` with changing `u0` and `p` and put `JumpProblem` over that.

**Comment by ChrisRackauckas** [comment]
`prob` is the `JumpProblem`, so `prob.prob` is the `DiscreteProblem`.

**Comment by danielchen26** [comment]
`using DiffEqBiological, DifferentialEquations
rn = @reaction_network begin
 (α, ϵ),            2A + B ↔ C
  β,                C → C + A
  η,                B → B + A
 (γ,θ),             B ↔ D
  δ,                A → ∅
end α ϵ β η γ θ δ
u0 = [10.,1.,0.,0.]
tspan = (0.,1e1)
params = [5., 5., 5., 0.03, 5., 5., 5.]

dprob = DiscreteProblem(rn1d_leak, u0, tspan, params)
jprob = JumpProblem(dprob, Direct(), rn1d_leak)

function prob_func(prob,i,repeat)
    prob.prob.u0 = rand(4)
    prob
end

ensemble_prob = EnsembleProblem(jprob,prob_func=prob_func)
sim = solve(ensemble_prob,SSAStepper(),EnsembleThreads(),trajectories=10)`


You mean this? the error is `ERROR: Inappropiate solve command. The arguments do not make sense. Likely, you gave an algorithm which does not actually exist (or does not <:DiffEqBase.DEAlgorithm)`, which I don't understand.

**Comment by ChrisRackauckas** [comment]
I just fixed that. When the tag merges this code should work.

**Comment by danielchen26** [comment]
ok, I see. thank you
