### ISSUE TITLE
Example: Unit Checked Arithmetic via SIUnits

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#51]
LoadError: Dimension mismatch in convert. Attempted to convert a (SIUnits.SIUnit{1,1,-2,0,0,0,0,0,0}) to (SIUnits.SIUnit{1,1,-3,0,0,0,0,0,0})
while loading In[6], in expression starting on line 6

 in convert(::Type{SIUnits.SIQuantity{Float64,1,1,-3,0,0,0,0,0,0}}, ::SIUnits.SIQuantity{Float64,1,1,-2,0,0,0,0,0,0}) at C:\Users\Denis\.julia\v0.5\SIUnits\src\SIUnits.jl:148
 in ode_solve(::DifferentialEquations.ODEIntegrator{:Midpoint,SIUnits.SIQuantity{Float64,1,1,-2,0,0,0,0,0,0},SIUnits.SIQuantity{Float64,1,1,-2,0,0,0,0,0,0},1,SIUnits.SIQuantity{Float64,0,0,1,0,0,0,0,0,0},Float64,SIUnits.SIQuantity{Float64,1,1,-3,0,0,0,0,0,0},SIUnits.SIQuantity{Float64,1,1,-3,0,0,0,0,0,0}}) at C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\ode\ode_integrators.jl:107
 in #solve#559(::Array{Any,1}, ::Function, ::DifferentialEquations.ODEProblem{SIUnits.SIQuantity{Float64,1,1,-2,0,0,0,0,0,0},SIUnits.SIQuantity{Float64,1,1,-2,0,0,0,0,0,0}}, ::Array{Int64,1}) at C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\ode\ode_solve.jl:190
 in (::DifferentialEquations.#kw##solve)(::Array{Any,1}, ::DifferentialEquations.#solve, ::DifferentialEquations.ODEProblem{SIUnits.SIQuantity{Float64,1,1,-2,0,0,0,0,0,0},SIUnits.SIQuantity{Float64,1,1,-2,0,0,0,0,0,0}}, ::Array{Int64,1}) at .\<missing>:0

and at ln[10]

LoadError: MethodError: no method matching linspace(::SIUnits.SIQuantity{Float64,0,0,1,0,0,0,0,0,0}, ::SIUnits.SIQuantity{Float64,0,0,1,0,0,0,0,0,0}, ::Int64)
Closest candidates are:
  linspace{T<:AbstractFloat}(!Matched::T<:AbstractFloat, !Matched::T<:AbstractFloat, ::Real) at range.jl:249
  linspace(!Matched::Real, !Matched::Real, ::Real) at range.jl:253
  linspace{T<:ColorTypes.Color{T,N}}(!Matched::T<:ColorTypes.Color{T,N}, !Matched::T<:ColorTypes.Color{T,N}, ::Any) at C:\Users\Denis\.julia\v0.5\Colors\src\utilities.jl:63
while loading In[10], in expression starting on line 1

 in macro expansion at C:\Users\Denis\.julia\v0.5\DifferentialEquations\src\general\plotrecipes.jl:79 [inlined]
 in apply_recipe(::Dict{Symbol,Any}, ::DifferentialEquations.ODESolution) at C:\Users\Denis\.julia\v0.5\RecipesBase\src\RecipesBase.jl:238
 in _process_userrecipes(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{DifferentialEquations.ODESolution}) at C:\Users\Denis\.julia\v0.5\Plots\src\pipeline.jl:73
 in _plot!(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{DifferentialEquations.ODESolution}) at C:\Users\Denis\.julia\v0.5\Plots\src\plot.jl:157
 in (::Plots.#kw##plot)(::Array{Any,1}, ::Plots.#plot, ::DifferentialEquations.ODESolution) at .\<missing>:0

**Comment by ChrisRackauckas** [comment]
The first shows the error correctly. It's supposed to error since there's a unit mismatch (this is mentioned in the text).

**Comment by ChrisRackauckas** [comment]
The second is due to an issue with SIUnits: Keno/SIUnits.jl/issues/79 . This only became an issue after dense plotting was enabled as the default yesterday. The easy fix is to disable the dense plotting:

```julia
plot(sol,yguide="Force ($(string(SIUnits.unit(sol.u))))",xguide="Time ($(string(SIUnits.unit(sol.t[1]))))",denseplot=false)
```

The better fix in the long run will be to add compatibility with `linspace` directly to SIUnits.jl.

**Comment by ChrisRackauckas** [comment]
SIUnits was dropped in favor of Unitful. If you use UnitfulPlots then you shouldn't have an issue with plotting (but you need `denseplot=false` for now).

**Comment by ChrisRackauckas** [comment]
Nevermind, `denseplot` should no longer be an issue there. There are some issues in UnitfulPlots that need to get worked out, but that's on the units side. Everything here is now Unitful compatible, down to the plots.

**Comment by finmod** [comment]
It follows that the Unit Checked Arithmetic ipynb of the examples is going to be updated and checked accordingly.

**Comment by ChrisRackauckas** [comment]
Indeed. I am waiting for them to fix the plots first.
