### ISSUE TITLE
seems DE dosen't work with distributed.

### ISSUE THREAD

**Issue by kuro26** [JuliaDiffEq/DifferentialEquations.jl#518]
### problem
when I add the code using DE solver in `@distributed`, the code inside will not execute.

### code
```julia
using DifferentialEquations, ParameterizedFunctions
using SharedArrays, Distributed
addprocs(2)
function parameterized_lorenz(du,u,p,t)
  x,y,z = u
  σ,ρ,β = p
  du[1] = dx = σ*(y-x)
  du[2] = dy = x*(ρ-z) - y
  du[3] = dz = x*y - β*z
end
function acc_p(p)
    u0 = [1.0;0.0;0.0]
    tspan = (0.0,1.0)
    prob = ODEProblem(parameterized_lorenz,u0,tspan,p)
    sol = solve(prob)
    return sum(sol.u[:, 1])
end

# p = [10.0,28.0,8/3]
arr = 8.0:0.1:10
res = SharedArray{Float64}(1, length(arr))
@distributed for i in 1:length(arr)
    p = [arr[i], 28.0, 8/3]
    res[i] = acc_p(p)[1]
end
```
check the var res, nothing changed.

**Comment by ChrisRackauckas** [comment]
Did you sync first?

**Comment by kuro26** [comment]
> Did you sync first?

this should be all the test code, and there is no problem when I remove the DE part

**Comment by ChrisRackauckas** [comment]
If you didn't `@sync`, then you haven't guaranteed the code is ran before you checked the value.

**Comment by kuro26** [comment]
> If you didn't `@sync`, then you haven't guaranteed the code is ran before you checked the value.
Yes, I didn't use `@sync`, but I wait long enough to make sure this block is done which is longer than without using `@distributed`. And, I ran code in jupyter notebook.

**Comment by ChrisRackauckas** [comment]
Seems to work just fine if you `@everywhere` the right pieces:

```julia
using Distributed
addprocs(2)
@everywhere using DifferentialEquations, SharedArrays, ParameterizedFunctions
@everywhere function parameterized_lorenz(du,u,p,t)
  x,y,z = u
  σ,ρ,β = p
  du[1] = dx = σ*(y-x)
  du[2] = dy = x*(ρ-z) - y
  du[3] = dz = x*y - β*z
end
@everywhere function acc_p(p)
    u0 = [1.0;0.0;0.0]
    tspan = (0.0,1.0)
    prob = ODEProblem(parameterized_lorenz,u0,tspan,p)
    sol = solve(prob)
    return sum(sol.u[:, 1])
end

# p = [10.0,28.0,8/3]
arr = 8.0:0.1:10
res = SharedArray{Float64}(1, length(arr))
@sync @distributed for i in 1:length(arr)
    p = [arr[i], 28.0, 8/3]
    res[i] = acc_p(p)[1]
end
res
```

Besides, even then, this doesn't have anything to do with DifferentialEquations since really this is about SharedArrays and it doesn't matter what function you put in there. Let me know if you have any other questions, though for non-DiffEq questions you should probably use https://discourse.julialang.org/ .

**Comment by kuro26** [comment]
Great thanks for your helping! It's really so bad asking such questions without reading through the chapter. I read the chapter to distributed computing and find out what's the problem. <br />
Thanks again for your help!

**Comment by ChrisRackauckas** [comment]
No worries, there's a lot to read and a lot to learn. But sometimes a chat can help, so feel free to ask questions on the Discourse and I'll likely answer there. Or join the Julia Slack: https://slackinvite.julialang.org/ : that might help you get more immediate feedback. Take care.
