### ISSUE TITLE
Persistent compilation problems

### ISSUE THREAD

**Issue by Vectornaut** [JuliaDiffEq/DifferentialEquations.jl#524]
The first time I loaded the `DifferentialEquations` package, `solve` threw the runtime error
```
ERROR: type ODEProblem has no field callback
```
whenever I called it. When I restarted Julia and loaded `DifferentialEquations` again, I got the message
```
[ Info: Recompiling stale cache file ~/.julia/compiled/v1.2/DifferentialEquations/UQdwS.ji for DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
```
and `solve` worked properly from then on, so I figured this was just an installation quirk.

Now, however, I'm working in a custom environment which leaves `DifferentialEquations` free. (In other words, I haven't explicitly added `DifferentialEquations` to the custom environment, so loading it should give me the version from the default environment.) The original runtime error is back, and now it doesn't go away when I restart Julia and re-enter the custom environment.

*I'm running Julia 1.2 on Ubuntu 18.04.*

**Comment by ChrisRackauckas** [comment]
What packages did you add? I need information that makes this reproducible.

**Comment by Vectornaut** [comment]
### Custom environment
Here's `Project.toml` for the custom environment.
```
[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
ValidatedNumerics = "d621b6e3-7715-5857-9c6f-c67000ef6083"
```
I've attached [`Manifest.toml`](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/3832098/Manifest.toml.txt) for the custom environment. Here's one potentially salient block.
```
[[DiffEqBase]]
deps = ["ArrayInterface", "Compat", "Distributed", "DocStringExtensions", "FunctionWrappers", "IterativeSolvers", "IteratorInterfaceExtensions", "LinearAlgebra", "MuladdMacro", "Parameters", "Printf", "RecipesBase", "RecursiveArrayTools", "RecursiveFactorization", "Requires", "Roots", "SparseArrays", "StaticArrays", "Statistics", "SuiteSparse", "TableTraits", "TreeViews"]
git-tree-sha1 = "6fd18712151e16d575ce9f564bee39c4c2fe7706"
uuid = "2b5f629d-d688-5b77-993f-72d75c75574e"
version = "6.2.3"
```
### Default environment
```
(v1.2) pkg> status
    Status `~/.julia/environments/v1.2/Project.toml`
  [8e7c35d0] BlockArrays v0.10.1
  [159f3aea] Cairo v0.8.0
  [5ae59095] Colors v0.9.6
  [a81c6b42] Compose v0.7.4
  [a93c6f00] DataFrames v0.19.4
  [0c46a032] DifferentialEquations v6.6.0
  [186bb1d3] Fontconfig v0.3.0
  [c91e804a] Gadfly v1.1.0
  [6218d12a] ImageMagick v0.7.5
  [916415d5] Images v0.18.0
  [91a5bcdd] Plots v0.27.0
  [3a141323] PolynomialRoots v0.2.0
  [f27b6e38] Polynomials v0.5.3
  [d330b81b] PyPlot v2.8.2
  [d621b6e3] ValidatedNumerics v0.11.0
  [72f80fcb] VoronoiDelaunay v0.4.0
```

**Comment by ChrisRackauckas** [comment]
I added release versions and got the correct version of DifferentialEquations.jl:

```julia
(tester) pkg> status
    Status `D:\OneDrive\Computer\Desktop\tester\Project.toml`
  [8e7c35d0] BlockArrays v0.10.2
  [159f3aea] Cairo v0.8.0
  [5ae59095] Colors v0.9.6
  [a81c6b42] Compose v0.7.3
  [a93c6f00] DataFrames v0.19.4
  [0c46a032] DifferentialEquations v6.8.0
  [186bb1d3] Fontconfig v0.3.0
  [6218d12a] ImageMagick v0.7.5
  [916415d5] Images v0.18.0
  [91a5bcdd] Plots v0.27.0
  [3a141323] PolynomialRoots v0.2.0
  [f27b6e38] Polynomials v0.6.0
  [d330b81b] PyPlot v2.8.2
  [d621b6e3] ValidatedNumerics v0.11.0
  [72f80fcb] VoronoiDelaunay v0.4.0
```

With this everything works fine.

Sounds like the issue is in your development version of Compose blocking something, but that's not a DifferentialEquations issue itself.

**Comment by ChrisRackauckas** [comment]
If there's a version bound we should be bumping please let us know.
