### ISSUE TITLE
Julia Crashes during Ode solve

### ISSUE THREAD

**Issue by FrankBerninger** [JuliaDiffEq/DifferentialEquations.jl#527]
I tried to run the following code (copied from Differential Equations) and Julia Crashes consistently.

using DifferentialEquations
function lorenz!(du,u,p,t)
 du[1] = 10.0*(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end
u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz!,u0,tspan)
sol = solve(prob)

Julia Running on an Ubuntu 18.04 . Currently using the pull request of Julia. The but occurs also on the current stable version.  Ubuntu ⛬  julia/1.2.0+dfsg-1~18.04.york0

Crash 

Illegal inttoptr
      %96 = ptrtoint double addrspace(13)* %95 to i64
Illegal inttoptr
      %111 = inttoptr i64 %110 to i8 addrspace(13)*

signal (6): Aborted
in expression starting at /home/franb/data/tingting2/Bamboomodel.jl:168
__libc_signal_restore_set at /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80 [inlined]
raise at /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:48
abort at /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:79
unknown function (ip: 0x7f03baf27bd6)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-7.so.1 (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-7.so.1 (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-7.so.1 (unknown line)
unknown function (ip: 0x7f03baef7afd)
unknown function (ip: 0x7f03baefbe98)
unknown function (ip: 0x7f03baefcf04)
unknown function (ip: 0x7f03baea365c)
unknown function (ip: 0x7f03baef240f)
unknown function (ip: 0x7f03bae3ab83)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
#__solve#328 at /home/franb/.julia/packages/OrdinaryDiffEq/rdNK0/src/solve.jl:5
#__solve at ./none:0
unknown function (ip: 0x7f03a442815d)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
#__solve#2 at /home/franb/.julia/packages/DifferentialEquations/2PnT0/src/default_solve.jl:15
#__solve at ./none:0 [inlined]
#__solve#1 at /home/franb/.julia/packages/DifferentialEquations/2PnT0/src/default_solve.jl:5 [inlined]
__solve at /home/franb/.julia/packages/DifferentialEquations/2PnT0/src/default_solve.jl:2 [inlined]
#solve_call#433 at /home/franb/.julia/packages/DiffEqBase/4V8I6/src/solve.jl:40
solve_call at /home/franb/.julia/packages/DiffEqBase/4V8I6/src/solve.jl:37 [inlined]
#solve#434 at /home/franb/.julia/packages/DiffEqBase/4V8I6/src/solve.jl:59 [inlined]
solve at /home/franb/.julia/packages/DiffEqBase/4V8I6/src/solve.jl:45
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f03baf7aea7)
unknown function (ip: 0x7f03baf7aaef)
unknown function (ip: 0x7f03baf7afe0)
unknown function (ip: 0x7f03baf7b5b0)
unknown function (ip: 0x7f03baf7bdbf)
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7f03172b450f)
unknown function (ip: 0xffffffffffffffff)
unknown function (ip: 0x7f03baf7c1fe)
unknown function (ip: 0x7f03bae64b89)
unknown function (ip: 0x7f03bae434ed)
include_string at ./loading.jl:1064
include_string at /home/franb/.julia/packages/CodeTools/xGemk/src/eval.jl:30
unknown function (ip: 0x7f03a43902a3)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
#127 at /home/franb/.julia/packages/Atom/lBERI/src/eval.jl:94
withpath at /home/franb/.julia/packages/CodeTools/xGemk/src/utils.jl:30
withpath at /home/franb/.julia/packages/Atom/lBERI/src/eval.jl:47 [inlined]
#126 at /home/franb/.julia/packages/Atom/lBERI/src/eval.jl:93 [inlined]
with_logstate at ./logging.jl:395
with_logger at ./logging.jl:491 [inlined]
#125 at /home/franb/.julia/packages/Atom/lBERI/src/eval.jl:92 [inlined]
hideprompt at /home/franb/.julia/packages/Atom/lBERI/src/repl.jl:85
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
macro expansion at /home/franb/.julia/packages/Atom/lBERI/src/eval.jl:91 [inlined]
macro expansion at /home/franb/.julia/packages/Media/ItEPc/src/dynamic.jl:24 [inlined]
#124 at /home/franb/.julia/packages/Atom/lBERI/src/eval.jl:86
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
handlemsg at /home/franb/.julia/packages/Atom/lBERI/src/comm.jl:164
unknown function (ip: 0x7f03a4377f2c)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
jl_f__apply at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
#19 at ./task.jl:268
unknown function (ip: 0x7f03a43fb9b4)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f03bae4f140)
unknown function (ip: 0xffffffffffffffff)
Allocations: 129303958 (Pool: 129284013; Big: 19945); GC: 217

Julia has exited.
Press Enter to start a new session.

**Comment by ChrisRackauckas** [comment]
Is this the standard Julia binary from https://julialang.org/downloads/ or a special source build?

**Comment by FrankBerninger** [comment]
I will reinstall and check. Frankly I do not remember if I used a ppa.  I suspect that I used a ppa which could explain the problem . I will come back to you in a few hours

**Comment by FrankBerninger** [comment]
Looks like it was a version issue.
