### ISSUE TITLE
Update all doclinks from latest to dev

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#529]
https://github.com/JuliaDocs/Documenter.jl/blob/master/CHANGELOG.md

>BREAKING Documenter no longer creates a symlink between the old latest url to specified devurl. (#1151)

https://github.com/JuliaDocs/Documenter.jl/pull/1151

We will need help to actually upgrade here correctly.

**Comment by ChrisRackauckas** [comment]
@fredrikekre how can we add in that symlink manually?

**Comment by mortenpi** [comment]
It's already there and won't go anywhere: https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/gh-pages/latest

**Comment by fredrikekre** [comment]
Unless you manually remove it it will stay.

**Comment by ChrisRackauckas** [comment]
Got it. Great thanks!

**Comment by ChrisRackauckas** [comment]
so it's just, new docs will never have it?

**Comment by mortenpi** [comment]
> so it's just, new docs will never have it?

If you mean new docs as in docs for a new package, then yes.

By the way, you can also set `devurl = "latest"` if you wanna stick to the old convention.

**Comment by fredrikekre** [comment]
> so it's just, new docs will never have it?

Yes. If you start a new repository.

If you prefer `latest` you can just pass `devurl="latest"` to makedocs though.

See https://github.com/JuliaLang/julia/issues/26825#issuecomment-413450489 for some discussion. IMO `latest` is misleading, hence why we changed the default to `dev`.

**Comment by mortenpi** [comment]
> pass `devurl="latest"` to makedocs though.

`deploydocs`*

**Comment by ChrisRackauckas** [comment]
Is a canonical tag set? https://webmasters.googleblog.com/2009/02/specify-your-canonical.html

**Comment by fredrikekre** [comment]
Not but you can do it: https://github.com/JuliaLang/julia/blob/e706e83eea9057f6ee910cf9ca006c6c4484d643/doc/make.jl#L172

**Comment by ChrisRackauckas** [comment]
so just `format = Documenter.HTML(analytics = "UA-90474609-3",canonical="stable")`?

**Comment by fredrikekre** [comment]
I believe `canonical` should be an absolute URL.

**Comment by ChrisRackauckas** [comment]
`format = Documenter.HTML(analytics = "UA-90474609-3",canonical="https://docs.juliadiffeq.org/stable/")` ?

**Comment by fredrikekre** [comment]
Yea, looks ok.
