### ISSUE TITLE
Integration with accelerator frameworks

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#53]
I would like to try integrating DifferentialEquations with some of the accelerator frameworks. For example, these include things like ParallelAccelerator, Spraso, ArrayFire, CUDArt, etc.

I think the way to do these things would be write them as a separate package which:
- Imports DifferentialEquations
- Requires these extra components
- Implements a new `:alg` dispatch (this would be a good way to show how it's done anyways)
- Tests on its own (to not add test dependencies)
- Document as a conditional dependency

This way, these components would be entirely optional (to avoid extra build problems). The GPU ones would be necessary because, if the method was on the CPU, then items would need to be transferred back to the CPU each step. These would be employed only by the PDE methods because that's where this level of parallelization is needed (and maybe fully parallel RK methods for ODE like waveform relaxation when we get there). Xeon Phi support should be provided by ParallelAccelerator (waiting on Knights Landing to do more, but see IntelLabs/CompilerTools.jl#1)

**Comment by ChrisRackauckas** [comment]
For Spraso integration, see IntelLabs/Sparso#1

**Comment by finmod** [comment]
I see that you commented on using CUDArt with CUDA 8 and Visual Studio 2015. Can you outline/confirm the steps to running the CUDArt tests on Windows 10:

1 Install Visual Studio 2015. Which one: Community, Pro or other?
2. Install CUDA 8 for a 64 bit machine with Quadro K1100M;
3. Pkg.add("CUDArt")

 Thanks.

**Comment by ChrisRackauckas** [comment]
@musm knows how to do it with VS2015. I just use CUDA 8 with CUDArt and edit in Juno (works quite well). I'd assume VS2015 supports it out of the box (other than the one failing test), right @musm?

**Comment by musm** [comment]
1. Install community unless you want to spend money
2. Install CUDA8,
3 Pkg.add("CUDArt")
4 Pkg.checkout("CUDArt")
5 grab coffee

**Comment by finmod** [comment]
Spot on with VS 2015 Community, all default settings

 

“INFO: CUDArt tests passed”

 

6. I am enjoying the coffee because

 

5. Grab coffee should be 5. Pkg. build(“CUDArt”) 

 

Thanks

**Comment by musm** [comment]
fantastic!

**Comment by ChrisRackauckas** [comment]
This issue is taken care of by the modular design which is now employed. Anyone could make a package with ParallelAccelerator versions, and once the common linear algebra is sorted out, one could just pass in Sparso methods. 

For details, see the blog post.

http://www.stochasticlifestyle.com/modular-algorithms-scientific-computing-julia/
