### ISSUE TITLE
How to integrate backwards using Integrator Interface

### ISSUE THREAD

**Issue by polarberg** [JuliaDiffEq/DifferentialEquations.jl#538]
I am solving differential equations. 
My goal is to set a tspan and find a solution value before the first time stamp.

1.  Current plan is to integrate backwards. 
2.  Other possible idea is extrapolating based on my current solution?

I am not the most experienced programmer and not very familiar with nuances of the package so please advise me if you have any suggestions. Thanks

```julia
import Pkg; using Pkg
Pkg.add("DifferentialEquations"); Pkg.add("Plots"); 
using DifferentialEquations, Plots 

function eq1(dv,v,y,p,t)
    dv[1] = -y[1]
end

tspan = (0.0,5.0) 
#tspan = (0.0,-5.0) #Current goal
u0 = 2.0
du0= 1.0

ode = SecondOrderODEProblem(eq1, [du0], [u0], (tspan))
sol=solve(ode,DPRKN12(),dense=true,abstol=1e-15,reltol=1e-15, maxiters=1e50)

integrator = init(ode,DPRKN12(),dense=true,abstol=1e-15,reltol=1e-15, maxiters=1e50)
dt=1.0
#dt=-1.0 #goal
step!(integrator,dt)
integrator
integrator.sol
sol
```

**Comment by ChrisRackauckas** [comment]
You just found a bug. It's fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/987 which we will release shortly (tomorrow?). In the mean time, you can work around it by setting a negative initial `dt`:

```julia
using DifferentialEquations, Plots

function eq1(dv,v,y,p,t)
    dv[1] = -y[1]
end

tspan = (0.0,-5.0) #Current goal
u0 = 2.0
du0= 1.0

ode = SecondOrderODEProblem(eq1, [du0], [u0], tspan)
sol=solve(ode,DPRKN12(),dense=true,abstol=1e-15,reltol=1e-15, dt=-1.0, maxiters=1e50)

integrator = init(ode,DPRKN12(),dense=true,abstol=1e-15,reltol=1e-15, dt=-1.0, maxiters=1e50)
dt=-1.0
#dt=-1.0 #goal
step!(integrator,dt)
integrator
integrator.sol
sol
```

Thanks for the report!

**Comment by polarberg** [comment]
Oh perfect, and wow you respond really fast. Thank you very much!
