### ISSUE TITLE
Plot recipe does not allow renaming of lines

### ISSUE THREAD

**Issue by sdobber** [JuliaDiffEq/DifferentialEquations.jl#546]
When plotting multiple variables, trying to change the labels of the individual curves gives an undesired output:
```
using DifferentialEquations, Plots
function lorenz(du,u,p,t)
 du[1] = p[1]*(u[2]-u[1])
 du[2] = u[1]*(p[2]-u[3]) - u[2]
 du[3] = u[1]*u[2] - p[3]*u[3]
end

u0 = [1., 5., 10.]
tspan = (0., 100.)
p = (10.0,28.0,8/3)
prob = ODEProblem(lorenz, u0, tspan,p)
sol = solve(prob)

plot(sol, vars=(1:3), label=["x", "y", "z"])
```
This gives the plot
<img width="562" alt="Snip" src="https://user-images.githubusercontent.com/40642560/72206390-a1ee3f00-348d-11ea-9d4e-869afff0d44c.png">

Changing labels works fine for individual components as in `plot(sol, vars=(2), label="y")`.

**Comment by ChrisRackauckas** [comment]
`plot(sol, vars=(1:3), label=["x" "y" "z"])` (i.e. a row vector) should be fine?

**Comment by ChrisRackauckas** [comment]
Plots.jl treats each column of a matrix as a different plot series, i.e. each column is a line. So that carries over to labels as well: each column is a label for a different line.

**Comment by sdobber** [comment]
Thank you for the clarification. Your code works fine - I was lead to believing this was an issue because `label=["x", "y", "z"]` worked fine in older version of `DifferentialEquations.jl`.
