### ISSUE TITLE
Example with wrong behavior of saveat

### ISSUE THREAD

**Issue by AnderMuruaUria** [JuliaDiffEq/DifferentialEquations.jl#556]
The following code

`using DifferentialEquations`

`f(u,p,t)= u` 

`u0 = 1.`

`tspan = (0.0, 15.0)`

`prob = ODEProblem(f,u0,tspan)`

`sol = solve(prob, Tsit5(), saveat=4.)`

`sol.t`

gives as output an Array{Float4,1} with entries 0.0, 4.0, 8.0, 15.0

This is not what I expected.

**Comment by ChrisRackauckas** [comment]
Thanks for the issue! It's fixed in this PR: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/1014. I'll try to get that patch out ASAP.

**Comment by ChrisRackauckas** [comment]
Fixed in OrdinaryDiffEq 5.28.1. Thanks!

P.S. We should try to get some of your integrators implemented.
