### ISSUE TITLE
Event restart: Stepsize not adapted for Tsit5

### ISSUE THREAD

**Issue by MartinOtter** [JuliaDiffEq/DifferentialEquations.jl#558]
When an event is triggered, integrators behave drastically different after the affect or affect_neg callbacks are called and the integrator is restarted (see test model below to reproduce these effects):

1. CVODE_BDF, IDA:\
After the event, the integrator is reinitialized and starts with an initial step-size *that is determined by an internal heuristics*. Typically, this results in a small step-size after event restart leading to a reliable simulation.

2. Tsit5 (and probably other native-Julia integrators):\
The integrator seems to start with the step-size *that it used before the event occured*. The problem is that this can lead to unreliable integration because a much too large initial step-size is used and the adaptive step-size control may not be able to cope with it. The work-around is that in the affect or affect_neg function function `set_proposed_dt!` needs to be called to set a more appropriate initial stepsize. However, if many different model types are supported (e.g. as in Modia), then this means that in the model a heuristic for initial stepsize selection must be implemented although such a heuristic is already available in the integrator, since used to determine the initial stepsize at the start of the integration.

A general drawback is that the affect/affect_neg functions must know which integrator is used in order to decide whether an own heuristic for an initial stepsize selection shall be used or whether this is not necessary.

**Please, add an option to the callbacks, that at event restart the integrator selects an initial step-size with the same algorithm as during initialization when the integrator is started.**

Here is simple model (bouncing ball) that demonstrates the issue:

```
module Test_bouncingBall

using DifferentialEquations, Sundials, PyPlot

function f(du,u,p,t)
  du[1] = u[2]
  du[2] = -9.81
end

function condition(u,t,integrator) # Event when event_f(u,t) == 0
 z = u[1] + 1e-12
 println("condition called at time = ", t, ", z = ", z)
 return z
end

function affect_neg(integrator)
  println("Event (affect_neg) at time = ", integrator.t, ", h = ", integrator.u[1])
  integrator.u[2] = -0.8*integrator.u[2]
  #set_proposed_dt!(integrator, 1e-5)
end

cb = ContinuousCallback(condition,nothing,affect_neg! = affect_neg)

u0 = [1.0,0.0]
tspan = (0.0,3.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),saveat=0.01,callback=cb)
#sol = solve(prob,CVODE_BDF(),saveat=0.01,callback=cb)

figure(1)
clf()
plot(sol.t, getindex.(sol.u, 1), label="h")

end
```

**Tsit5()** is used:
```
condition called at time = 0.0, z = 1.000000000001
condition called at time = 0.00010183496422028534, z = 0.9999999491343845
condition called at time = 1.1314996024476149e-5, z = 0.9999999993730171
condition called at time = 2.2629992048952297e-5, z = 0.9999999974890683
condition called at time = 3.394498807342844e-5, z = 0.9999999943491538
condition called at time = 4.5259984097904594e-5, z = 0.9999999899532734
condition called at time = 5.657498012238074e-5, z = 0.9999999843014273
...
condition called at time = 0.451523640985953, z = -1.5584806362327702e-15
condition called at time = 0.4515236409859529, z = 2.5047171559516084e-16
Event (affect_neg) at time = 0.4515236409859529, h = -9.997495282844048e-13
condition called at time = 0.4515236409859529, z = 2.5047171559516084e-16
condition called at time = 0.45177848862185427, z = 0.0009027486937449096
condition called at time = 3.0, z = -22.82598664241249
condition called at time = 3.0, z = -22.82598664241249
condition called at time = 0.4515236409859529, z = 2.5047171559516084e-16
condition called at time = 3.0, z = -22.82598664241249
condition called at time = 0.451523640985954, z = 4.184610879434157e-15
```
As can be seen, the integrator starts after the event with a much too large step-size.

**CVODE_BDF()** is used:
```
condition called at time = 0.0, z = 1.000000000001
condition called at time = 1.449134242703259e-9, z = 1.000000000001
condition called at time = 1.6101491585591764e-10, z = 1.000000000001
condition called at time = 3.220298317118353e-10, z = 1.000000000001
condition called at time = 4.830447475677529e-10, z = 1.000000000001
condition called at time = 6.440596634236706e-10, z = 1.000000000001
condition called at time = 8.050745792795884e-10, z = 1.000000000001
condition called at time = 9.660894951355059e-10, z = 1.000000000001
condition called at time = 1.1271044109914237e-9, z = 1.000000000001
...
condition called at time = 0.4514746914301603, z = 1.886551738152574e-16
condition called at time = 0.4514746914301602, z = 4.662109299715465e-16
Event (affect_neg) at time = 0.4514746914301602, h = -9.995337890700284e-13
condition called at time = 0.4514746914301602, z = 4.662109299715465e-16
condition called at time = 0.45147469143047125, z = 1.102529676702175e-12
condition called at time = 0.4514746945405592, z = 1.1020683316467014e-8
condition called at time = 0.4514746917757601, z = 1.2245207911607127e-9
condition called at time = 0.45147469212136, z = 2.449041082238296e-9
```
As can be seen, the integrator starts after the event with a similar stepsize strategy as at the beginning of the simulation.

**Comment by ChrisRackauckas** [comment]
Tsit5 and BDFs are very different in this regard, and should be very different. When BDF hits an event, it has a discontinuity so it has to drop all the way back to using Implicit Euler in the next step, so it knows it will need a stepsize reduction anyways simply because it's using a lower order method (sometimes a massive stepsize reduction). Tsit5 is still 5th order, so in many cases, like Poincure Maps, using the same dt isn't just a good idea but the right idea. I agree that we need this more configurable though, but right now indeed the user can take control of this on their own inside of the `affect!` function which may be as flexible as it can be. If you call https://docs.juliadiffeq.org/latest/basics/integrator/#DiffEqBase.auto_dt_reset! at the end of your callback it should do exactly what you want, and that gives the flexibility on the user side. 

I think the best approach would be for RK methods to keep the same behavior but implement https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/299 , since auto-dt is somewhat conservative so this should be better, but if it's wrong it would make the first step essentially be auto-dt.

**Comment by MartinOtter** [comment]
Thanks very much. Your advice solved this issue provided  `auto_dt_reset!` is followed by `set_proposed_dt!` (otherwise, it has no effect).

In the test model affect_neg was changed to:
```
function affect_neg(integrator)
    println("Event (affect_neg) at time = ", integrator.t, ", h = ", integrator.u[1])
    integrator.u[2] = -0.8*integrator.u[2]
    println("   before reset: integrator.dt = ", integrator.dt)
    auto_dt_reset!(integrator)
    println("   after reset : integrator.dt = ", integrator.dt)
    set_proposed_dt!(integrator, integrator.dt)
end
...
# resulting output:
condition called at time = 0.451523640985953, z = -1.5584806362327702e-15
condition called at time = 0.4515236409859529, z = 2.5047171559516084e-16
Event (affect_neg) at time = 0.4515236409859529, h = -9.997495282844048e-13
   before reset: integrator.dt = 0.33838499573721587
   after reset : integrator.dt = 0.00028212257419296053
condition called at time = 0.4515236409859529, z = 2.5047171559516084e-16
condition called at time = 0.4515236691982103, z = 9.99717536879893e-8
condition called at time = 0.45180576356014585, z = 0.0009993271690369404
condition called at time = 0.45155498793864096, z = 0.00011107491057317003
condition called at time = 0.4515863348913291, z = 0.00022214018153183206
````
