### ISSUE TITLE
no method matching has_Wfact

### ISSUE THREAD

**Issue by JulesBlubb** [JuliaDiffEq/DifferentialEquations.jl#559]
I am new to Julia and tried the Differential Equations Tutorial. I am using Julia 1.0.5.

```
using DifferentialEquations
f(u,p,t) = 0.98*u
u0 = 1.0
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob)
```

The solve function with the default solver (If I choose a special solver everything works fine) throws 
**ERROR:** LoadError: MethodError: no method matching has_Wfact(::DiffEqDiffTools.UDerivativeWrapper{ODEFunction{false,typeof(f),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,DiffEqBase.NullParameters})**

How can I solve this?

**Comment by ChrisRackauckas** [comment]
Normally we'd recommend using the current stable Julia release, which is 1.3.1 right now: https://julialang.org/downloads/ . That should work fine. But I see what's going on here and will get a fix together shortly.

**Comment by ChrisRackauckas** [comment]
If you update your packages (i.e. `]up`), then you should be good now.

**Comment by JulesBlubb** [comment]
The update solved the problem. Thanks.
