### ISSUE TITLE
Resizing system fails with stiff solvers

### ISSUE THREAD

**Issue by BrantCarlson** [JuliaDiffEq/DifferentialEquations.jl#561]
Greetings!

I am working on a simulation of a system that gradually grows with time, implemented in DifferentialEquations.jl via the the callback interface and using `resize!` to grow the system as needed.  This works fine with some solvers (I'm using `BS3()` right now), but when I decided to experiment with the `Rosenbrock32` solvers, the `resize!` method fails with `DimensionMismatch("array could not be broadcast to match destination")`.  A short working example is below.  I'll spare you the entire stack trace (mostly consists of pages of ForwardDiff type sigatures), but the lowest not-base-Julia function mentioned is `resize_jac_config!`.

I haven't exhaustively tested all the stiff solvers, but perhaps it's something to do with ForwardDiff usage, as using `Rosenbrock32(autodiff=false)` works...

I don't personally need this fixed as BS3 works fine for my purposes, but I thought I'd bring it up in the hopes that it's an easy fix.

Example code follows.  Thanks for all the hard work here; DifferentialEquations.jl is an incredibly functional and flexible system, and it's made my life much easier.  Cheers!

(In the example code below, run the `runMe()` function and BS3 should be fine while Rosenbrock32 crashes.  Commenting out the `resize!` call, both methods work fine.)

```julia
using DifferentialEquations

function dsdt(ds,s,_,t)
    # state looks like x1,v1, x2,v2, x3,v3,...
    ds[1:2:end] .= s[2:2:end] # velocity changes position
    ds[2:2:end] .= -1.0 # (constant downward acceleration)
end

function splitCheck(s,t,intgr)
    #If any of the position coordinates are negative, we need to bounce (and resize).
    if any(s[1:2:end] .< 0.0)
        return true
    else
        return false
    end
end

function splitMod!(intgr)
    s = intgr.u

    # flip the velocity sign
    for i = 1:2:length(s)
        if s[i]<0.0
            s[i] = 0.0
            s[i+1] = -s[i+1]
        end
    end

    # Add a particle to the system.
    # comment out these lines and it will work with Rosenbrock32.
    resize!(intgr,length(s)+2) # (resizes s -> intgr.u)
    s[end-1] = rand() # new position
    s[end] = rand() # new velocity
end

function runSim(method)
    s0 = rand(2)
    tspan = (0.0,20.0)
    prob = ODEProblem(dsdt,s0,tspan)

    # callback to bounce / split system.
    cb = DiscreteCallback(splitCheck,splitMod!)

    solve(prob,method,callback=cb,dtmax=0.01)
    # setting dtmax here so the discrete callback doesn't miss the zero-crossing too badly.
    # ...no real reason not to use a continuous callback here, I just chose not to.
end

function runMe()
    println("running with BS3 (fine with resize)")
    runSim(BS3())
    println("running with Rosenbrock32 (crashes with resize)")
    runSim(Rosenbrock32())
end
```

**Comment by ChrisRackauckas** [comment]
Just a bug! The fix is in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/1025 and will get released shortly.
