### ISSUE TITLE
Default to having progress bars on?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#562]
```julia
using OrdinaryDiffEq, StaticArrays, BenchmarkTools, SimpleDiffEq
@inline function lorenz(u,p,t)
    SA[10.0(u[2]-u[1]),u[1]*(28.0-u[3]) - u[2],u[1]*u[2] - (8/3)*u[3]]
end
u0 = SA[1.0;0.0;0.0]
tspan = (0.0,1000.0)
prob = ODEProblem(lorenz,u0,tspan)
@btime sol = solve(prob,Tsit5())
@btime sol = solve(prob,Tsit5(),progress=true)
@btime sol = solve(prob,Tsit5(),progress=true,progress_steps = 1)
```

It looks from this simple test that defaulting to have progress bars on could be safe performance wise. I'd like to see more tests confirming it.

**Comment by nudigamma** [comment]
Hi Chris , 
What kind of tests do you have in mind ?

**Comment by ChrisRackauckas** [comment]
Just a bunch of basic ODEs and see if the timing is noticeably effected.

**Comment by nudigamma** [comment]
Alright , Initial results for the provided code Julia 1.3
Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
6 cores 12 threads 
32 GB RAMS

Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz

4.189 ms (26744 allocations: 5.42 MiB) 
6.142 ms (27993 allocations: 5.47 MiB)
1.373 s (1179231 allocations: 50.55 MiB)

**Comment by ChrisRackauckas** [comment]
that doesn't make sense. Is that including compile time?

**Comment by nudigamma** [comment]
Should precompile the code? Yes it is with compile time.

**Comment by ChrisRackauckas** [comment]
The timing should be ran twice, since we know it won't effect compile time and it's highly stochastic.

**Comment by nudigamma** [comment]
so if I do it like that 
`using OrdinaryDiffEq, StaticArrays, BenchmarkTools, SimpleDiffEq
@inline function lorenz(u,p,t)
    SA[10.0(u[2]-u[1]),u[1]*(28.0-u[3]) - u[2],u[1]*u[2] - (8/3)*u[3]]
end
u0 = SA[1.0;0.0;0.0]
tspan = (0.0,1000.0)
prob = ODEProblem(lorenz,u0,tspan)

for i in 1:10
    @btime sol = solve(prob,Tsit5())
    @btime sol = solve(prob,Tsit5(),progress=true)
    @btime sol = solve(prob,Tsit5(),progress=true,progress_steps = 1)

end

`

**Comment by ChrisRackauckas** [comment]
oh wait, if it's `@btime` it should be accurate. Is that on Julia v1.3?

**Comment by nudigamma** [comment]
Fixed the code formatting , yes Julia 1.3.1 running it from the atom interface (JuliaPro) should I run it natively in a shell?

```julia
using OrdinaryDiffEq, StaticArrays, BenchmarkTools, SimpleDiffEq
@inline function lorenz(u,p,t)
    SA[10.0(u[2]-u[1]),u[1]*(28.0-u[3]) - u[2],u[1]*u[2] - (8/3)*u[3]]
end
u0 = SA[1.0;0.0;0.0]
tspan = (0.0,1000.0)
prob = ODEProblem(lorenz,u0,tspan)

for i in 1:10
    @btime sol = solve(prob,Tsit5())
    @btime sol = solve(prob,Tsit5(),progress=true)
    @btime sol = solve(prob,Tsit5(),progress=true,progress_steps = 1)

end
```

**Comment by nudigamma** [comment]
4.163 ms (26744 allocations: 5.42 MiB)
  6.148 ms (27993 allocations: 5.47 MiB)
  3.627 s (1917914 allocations: 61.83 MiB)
  4.168 ms (26744 allocations: 5.42 MiB)
  6.166 ms (27993 allocations: 5.47 MiB)
  1.278 s (1179230 allocations: 50.55 MiB)
  4.168 ms (26744 allocations: 5.42 MiB)
  6.240 ms (27993 allocations: 5.47 MiB)
  1.296 s (1179231 allocations: 50.55 MiB)
  4.203 ms (26744 allocations: 5.42 MiB)
  6.154 ms (27993 allocations: 5.47 MiB)
  1.619 s (1302344 allocations: 52.43 MiB)
  4.212 ms (26744 allocations: 5.42 MiB)
  6.127 ms (27993 allocations: 5.47 MiB)
  1.308 s (1179231 allocations: 50.55 MiB)
  4.200 ms (26744 allocations: 5.42 MiB)
  6.107 ms (27993 allocations: 5.47 MiB)
  1.281 s (1179231 allocations: 50.55 MiB)
  4.196 ms (26744 allocations: 5.42 MiB)
  6.082 ms (27993 allocations: 5.47 MiB)
  1.281 s (1179230 allocations: 50.55 MiB)
  4.210 ms (26744 allocations: 5.42 MiB)
  6.152 ms (27993 allocations: 5.47 MiB)
  1.304 s (1179230 allocations: 50.55 MiB)
  4.203 ms (26744 allocations: 5.42 MiB)
  6.181 ms (27993 allocations: 5.47 MiB)
  1.434 s (1247886 allocations: 51.64 MiB)
  4.194 ms (26744 allocations: 5.42 MiB)
  6.108 ms (27993 allocations: 5.47 MiB)
  1.298 s (1179230 allocations: 50.55 MiB)
  4.196 ms (26744 allocations: 5.42 MiB)
  6.092 ms (27993 allocations: 5.47 MiB)
  1.297 s (1179231 allocations: 50.55 MiB)
  4.193 ms (26744 allocations: 5.42 MiB)
  6.156 ms (27993 allocations: 5.47 MiB)
  1.303 s (1179230 allocations: 50.55 MiB)
  4.195 ms (26744 allocations: 5.42 MiB)
  6.081 ms (27993 allocations: 5.47 MiB)
  1.274 s (1179230 allocations: 50.55 MiB)

**Comment by ChrisRackauckas** [comment]
okay yeah, it has a massive overhead for you but not for me 🤷‍♂

**Comment by nudigamma** [comment]
Ok I will investigate some more and get back to you maybe some others ode

**Comment by nudigamma** [comment]
ok as I expected running from the juliaPro (atom ) the script adds some overhead. I ran the same code from the command line
```bash
$julia time.jl
```
  4.145 ms (26744 allocations: 5.42 MiB)
  4.201 ms (26746 allocations: 5.42 MiB)
  5.328 ms (26746 allocations: 5.42 MiB)
  4.154 ms (26744 allocations: 5.42 MiB)
  4.204 ms (26746 allocations: 5.42 MiB)
  5.344 ms (26746 allocations: 5.42 MiB)

**Comment by ChrisRackauckas** [comment]
Okay yeah, that means it's probably not a good idea to make it default: lots of overhead in Atom, but still noticable in the REPL.
