### ISSUE TITLE
Error in Documentation example code for Rosenbrock Equation 

### ISSUE THREAD

**Issue by cems2** [JuliaDiffEq/DifferentialEquations.jl#565]
The example give for Declaring Jacobian Functions is the Rosenbrock.
https://docs.juliadiffeq.org/dev/tutorials/advanced_ode_example

Issue: The code does not match the written equations 
Here is what is written in the doc:
```
using DifferentialEquations
function rober(du,u,p,t)
  y₁,y₂,y₃ = u
  k₁,k₂,k₃ = p
  du[1] = -k₁*y₁+k₃*y₂*y₃
  du[2] =  k₁*y₁-k₂*y₂^2-k₃*y₂*y₃
  du[3] =  k₂*y₂^2                             # In Math equation this is  y₃ not y₂
  nothing
end
```

Either the written differential equations are wrong or the code is wrong.  I'm not sure which.
(which makes you wonder how the plots were done).

**Comment by ChrisRackauckas** [comment]
The TeX is incorrect. I'll fix that.

**Comment by ChrisRackauckas** [comment]
Fixed in the next doc build. Thanks!

**Comment by cems2** [comment]
The confusing (probably misleading?) thing in this example is how the algebraic constraint is arrived at.  
That is, is du[3] the result of an index reduction that somehow leaves the simple constraint the the sum of the y is 1?  Or is that the manifold constraint one is applying.

TO explain why I find it confusing, consider writing a cartesian pendulum.  You'd like to write it as just an unconstrained forces plus x^2 + y^2 -L^2 = 0  
But I'm pretty sure that's totally not how it would be done.  I think one needs to solve the index reduction and use that instead.

If I'm not mistaken then the misleading thing here is the apparent simplicity of du[3].

**Comment by ChrisRackauckas** [comment]
I would just think about it as a chemical reaction system. It has to be conservative since it's 3 separate states of the same reactant, and you can see from the equations that the terms are just transition rates.

**Comment by cems2** [comment]
Oh I get where the constaint comes from.  Let me illustrate the point of confusion for a simple pendulum.

If you naively follw the pattern show for the rosenbrock equations, the seemingly natural thing to write down is this
```
function cartPend(du,u,p,t)
   du[1] = du[2]  # dy
   du[2] = -p[1]   #ddy   The only force is gravity in the Y-direction.
   du[3] = du[4]  #dx  
   du[4] = u[1]^2 + u[3]^2 - p[2]^2     # just leave out  ddx and instead have the constraint!
    nothing 
end
```

That fails.  I think it fails because one didn't do the proper lagrange parameter index reduction on dy but just naively threw in the constraint.

if i'm not mistaken the Rosenbrock equations are deceptively simple in this regard because they are a special case that doesn't require the index reduction step making it look like you can just toss the constrain in, replacing the equation.

**Comment by ChrisRackauckas** [comment]
Indeed it comes from the conservativity of the chemical reactions, which is a bit different from rigid bodies, so the derivation might look a little different.

**Comment by cems2** [comment]
I'll clarify why I think the example may be misleading.  Or maybe I'm an idiot:-)

Let's re-write this two different ways:
```
using DifferentialEquations
function rober(du,u,p,t)
  y₁,y₂,y₃ = u
  k₁,k₂,k₃ = p
  du[1] = -k₁*y₁+k₃*y₂*y_4                # note this is now y_4 not y_3
  du[2] =  k₁*y₁-k₂*y₂^2-k₃*y₂*y_4
  du[3] = y₁+y₂+y_4-1                       # this is the algebraic constraint.
  du[4] =  k₂*y₂^2                           
  nothing
end
```
I'm not quite sure how that will turn out.  Mathematically, the equations should obey the algebraic constraint without adding the redundant constraint y_3.  So this is kind of over-determining the problem numerically and might result in instability.  Don't know.
Now lets compare this to the way the docs wrote it:
```
using DifferentialEquations
function rober(du,u,p,t)
  y₁,y₂,y₃ = u
  k₁,k₂,k₃ = p
  du[1] = -k₁*y₁+k₃*y₂*y₃                  
  du[2] =  k₁*y₁-k₂*y₂^2-k₃*y₂*y₃
  du[3] =  y₁+     y₂+    y₃ -1    # just the constraint.                 
  nothing
end
```

You can now see why I put the four equations in the first case in a funny out-of-order numbering.  What's happeing here is that in the first case the term y_4 as it enters the expression for du[1] is being driven by du[4] which is a differential equation.  In the second case y_3 is playing the very same role as y_4 BUT this term isn't driven by a differnetial equation-- the algebraic equation.

I _think_ that if we picture this in a MassMatrix way then on the RHS one has a derivative expression for y_4 multiplied by zero.  (right?)

If so then what is it the derivative of?  Well again I _think_ it is the time derivative of a lagrange parameter that is enforcing the constraint.  If that is correct then it's not the derivative of y_4.  In that case how can we be plugging y_3 into the expressions for du[1] and du[2] in the second set of code?  it's not the same physcial thing at all.

I think what is going on is this maybe a super special case where the lagrange parameter and the physical thing represented by the differential equation (du[4]) are numerically identical.

That  can't be the general case.  So it seems misleading to use this pattern in an example.

Why?  Well here's something that would fail.  Imagine writing down differential equations of motion for an unconstrained particle in gravity.  in 2D thats just:

du[1] = -g # y-coordinate
du[2] = 0  # x-coordinate


Trivial of course.  Now you want to change it to a pendulum.  You can't do this simply by replacing adding on the constraint
du[3] = x^2+y^2-L^2
And you also can't do it by simply replacing the du[2] with the agebraic constraint.

But that's what this example "looks" like was done.  I think it's an artifact of a special case where the lagrange parameter value is the same as the physical variables value.

Hope this makes sense
