### ISSUE TITLE
This is a trival set of mistakes I found... spelling mistakes in the websites of GSoC in JSoC.

### ISSUE THREAD

**Issue by AsForMe** [JuliaDiffEq/DifferentialEquations.jl#576]
By accident, I see a spelling mistake in **https://julialang.org/jsoc/gsoc/diffeq**,
then I check the spelling mistakes in https://julialang.org/jsoc/projects/ and all subpages, and find out mistakes as following.
Maybe these should be fixed.
In **https://julialang.org/jsoc/projects/**,
1. The word '_skillsets_' should be spelled into '_skill sets_'; 
In **https://julialang.org/jsoc/gsoc/flux/**, **no mistakes**.
In **https://julialang.org/jsoc/gsoc/sciml/**, **no mistakes**.
In **https://julialang.org/jsoc/gsoc/compiler/**, **no mistakes**.
In **https://julialang.org/jsoc/gsoc/wasm/**,
2. The word '_implenting_' should be spelled into '_implementing_';
3. The word '_reproducability_' should be spelled into '_reproducibility_';
4. The word '_Experiemental_' should be spelled into '_Experimental_';
5. The word '_enivronments_' should be spelled into '_environments_';
6. The word '_asssume_' should be spelled into '_assume_';
In **https://julialang.org/jsoc/gsoc/hpc/**, **no mistakes**;
In **https://julialang.org/jsoc/gsoc/numerics/**,
7. The word '_algrithms_' should be spelled into '_algorithms_';
In **https://julialang.org/jsoc/gsoc/turing/**,
8. The word '_sattelite_' may be spelled wrongly; ( should it be 'satellite' ?)
9. The word '_probablity_' should be spelled into '_probability_';
In **https://julialang.org/jsoc/gsoc/science/**,
10. The word '_Simualation_' should be spelled into '_Simulation_';
In **https://julialang.org/jsoc/gsoc/tooling/**, **no mistakes**;
In **https://julialang.org/jsoc/gsoc/images/**, 
11. The word '_frequenly_' should be spelled into '_frequently_';
In **https://julialang.org/jsoc/gsoc/general/**, **no mistakes**;
In **https://julialang.org/jsoc/gsoc/graphs/**, **no mistakes**;
In **https://julialang.org/jsoc/gsoc/graphics/**,  **no mistakes**;
In **https://julialang.org/jsoc/gsoc/mlj/**, **no mistakes**;
In **https://julialang.org/jsoc/gsoc/tables/**, **no mistakes**;
In **https://julialang.org/jsoc/gsoc/diffeq**,
12. The word '_libraires_' in "There are two ways to approach libraires" should be spelled into '_libraries_';
13. The word '_enahnced_' in "DiffEqOperators.jl could be enahnced to allow non-uniform grids or composition of operators." should be spelled into '_enhanced_';
14. The word '_redundent_' in "Parameter identifiability analysis is an analysis that describes whether the parameters of a dynamical system can be identified from data or whether they are redundent." should be spelled into '_redundant_';
To avoid these mistakes is easy, just do an spelling examination is ok.
I don't know where to state these so state here. And maybe this issue too boring.

**Comment by ChrisRackauckas** [comment]
This should really go to https://github.com/JuliaLang/www.julialang.org

**Comment by AsForMe** [comment]
OK, I will go there. Thanks!
&nbsp;

----
致可遇不可求的你
---
All my best wishes!
-----
终身学习，向死而生。








&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Christopher Rackauckas"<notifications@github.com&gt;; 
发送时间: 2020年3月18日(星期三) 晚上10:56
收件人: "JuliaDiffEq/DifferentialEquations.jl"<DifferentialEquations.jl@noreply.github.com&gt;; 
抄送: "381237293"<381237293@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JuliaDiffEq/DifferentialEquations.jl] This is a trival set of mistakes I found... spelling mistakes in the websites of GSoC in JSoC. (#576)





 
This should really go to https://github.com/JuliaLang/www.julialang.org
