### ISSUE TITLE
ImageMagick in animation error on Windows

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DifferentialEquations.jl#58]
Running Julia 0.5.0 on Windows 10, I get the following warning:

``` julia
WARNING: Tried to create gif using convert (ImageMagick), but got error: ErrorException("failed process: Process(`convert -delay 7 -loop 0 'C:\\Users\\Denis\\AppData\\Local\\Temp\\jl_ACBC.tmp\\*.png' -alpha off 'C:\\Users\\Denis\\Documents\\Finmod\\DifferentialEquations.jl-master\\examples\\sh_animation.gif'`, ProcessExited(1)) [1]")
ImageMagick can be installed by executing `Pkg.add("ImageMagick")`
Will try ffmpeg, but it's lower quality...)
INFO: Saved animation to C:\Users\Denis\Documents\Finmod\DifferentialEquations.jl-master\examples\sh_animation.gif
```

Even though ImageMagick has been installed with `Pkg.add("ImageMagick")` + `Pkg.update()`. Why is this warning saying that ImageMagick is not installed?

**Comment by ChrisRackauckas** [comment]
Try the following code:

```julia
using Plots, ImageMagick
# initialize the attractor
n = 1500
dt = 0.02
σ, ρ, β = 10., 28., 8/3
x, y, z = 1., 1., 1.

# initialize a 3D plot with 1 empty series
plt = path3d(1, xlim=(-25,25), ylim=(-25,25), zlim=(0,50),
                xlab = "x", ylab = "y", zlab = "z",
                title = "Lorenz Attractor", marker = 1)

# build an animated gif, saving every 10th frame
@gif for i=1:n
    dx = σ*(y - x)     ; x += dt * dx
    dy = x*(ρ - z) - y ; y += dt * dy
    dz = x*y - β*z     ; z += dt * dz
    push!(plt, x, y, z)
end every 10
```

(This is from the Plots.jl documentation page). This code throws a similar error for me on Windows. 

```julia
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/508.
convert: no images defined `C:\Users\Chris\AppData\Local\Temp\jl_2B3B.tmp.gif' @ error/convert.c/ConvertImageCommand/3235.
WARNING: Tried to create gif using convert (ImageMagick), but got error: ErrorException("failed process: Process(`convert -delay 5 -loop 0 'C:\\Users\\Chris\\AppData\\Local\\Temp\\jl_484A.tmp\\*.png' -alpha off 'C:\\Users\\Chris\\AppData\\Local\\Temp\\jl_2B3B.tmp.gif'`, ProcessExited(1)) [1]")
ImageMagick can be installed by executing `Pkg.add("ImageMagick")`
Will try ffmpeg, but it's lower quality...)
INFO: Saved animation to C:\Users\Chris\AppData\Local\Temp\jl_2B3B.tmp.gif
Plots.AnimatedGif("C:\\Users\\Chris\\AppData\\Local\\Temp\\jl_2B3B.tmp.gif")
```

And the GIF is really wonky:

![jl_2b3b tmp](https://cloud.githubusercontent.com/assets/1814174/19017747/8876ae88-87fa-11e6-9b70-b18a52f322e8.gif)

If this code doesn't work, then that means DifferentialEquations.jl isn't involved and we should open an issue on Plots.jl.

**Comment by finmod** [comment]
This is the warning I get for the code you suggested thus confirming that opening an issue is appropriate. tbreloff/Plots.jl#516 

WARNING: redefining constant dt
WARNING: Tried to create gif using convert (ImageMagick), but got error: ErrorException("failed process: Process(`convert -delay 5 -loop 0 'C:\\Users\\Denis\\AppData\\Local\\Temp\\jl_9984.tmp\\*.png' -alpha off 'C:\\Users\\Denis\\Documents\\Finmod\\climlab\\tmp.gif'`, ProcessExited(1)) [1]")
ImageMagick can be installed by executing `Pkg.add("ImageMagick")`
Will try ffmpeg, but it's lower quality...)

**Comment by ChrisRackauckas** [comment]
Turns out it's all the way down to ImageMagick.jl. I opened an issue: JuliaIO/ImageMagick.jl#52. For me, the problem was that ImageMagick didn't actually install when it was `Pkg.add`ed, but it never said anything. I had to go to the library downloads folder (for me `C:\Users\Chris\.julia\v0.5\ImageMagick\deps\downloads`) and install ImageMagick using the binary there, and now it works on Windows. You may want to give that a try, though hopefully ImageMagick.jl fixes this because that's not easy behavior to debug.

**Comment by finmod** [comment]
Spot on. I had noticed the download taking place with the Pkg.add(“ImageMagic”) but did not realise that it did not install.

 

The READ.ME should be explicit about this because many users raise this issue in many for a and do not find a satisfactory answer.

**Comment by ChrisRackauckas** [comment]
Well ImageMagick's README does mention this. The problem is that, when the install fails, it fails silently. So there's no indication that you ever have to check ImageMagick's README for how to deal with a failed install. And there's 3 issues all dedicated to failed installs on Windows, so they should really come up with a fix.

**Comment by ChrisRackauckas** [comment]
The original reason this was open seems to be fixed, and other related issues are all well documented on Plots.jl and ImageMagick.jl's repos.
