### ISSUE TITLE
Rosenbrock23 gives wrongs solution when autodiff=false

### ISSUE THREAD

**Issue by jibaneza** [JuliaDiffEq/DifferentialEquations.jl#580]
When integrating this system of differential equations, the solver gives the correct solution with automatic differentiation but provides a wrong solution with autodiff=false, yet the retcode is success.
Minimal working example:
```julia
using DifferentialEquations, Plots

function rhs(du,u,p,t)
    du[1] = -u[1] - u[1]/u[3]*du[3]
    du[2] = u[1]  - u[2]/u[3]*du[3]
    du[3] = -u[1]*u[3]/1.0 +u[1]*u[3]/1.1
    nothing
end

problem = ODEProblem(rhs,[1.0,0.0,1.0],10.0)
sol_FD = solve(problem,Rosenbrock23(;autodiff=false))
sol_AD = solve(problem,Rosenbrock23())
plot(sol_FD)
plot(sol_AD)
```

I've tested this with Julia 1.3.1 and DifferentialEquations 6.11.0 in Windows 10 and OS X.
**Edit**: the challenge must lie in the equations, probably in the jacobian calculation, since it seems to fail to different degrees with lsoda, Sundials and Matlab solvers. I add a equivalent set of differential equations, which I would expect to provide the same solution, but can be solved without issues on those solvers:

```julia
function rhs_EOS(du,u,p,t)
    V = u[1]/1.0 + u[2]/1.1
    c1 = u[1]/V
    c2 = u[2]/V
    du[1] = -c1*V
    du[2] = c1*V
    nothing
end
problem_EOS = ODEProblem(rhs_EOS,[1.0,0.0],10.0)
sol_EOS = solve(problem_EOS,Rosenbrock23(;autodiff=false))
V_EOS = sol_EOS[1,:] + sol_EOS[2,:]/1.1
C_EOS = similar(sol_EOS[:,:])
C_EOS[1,:] = sol_EOS[1,:]./V_EOS
C_EOS[2,:] = sol_EOS[2,:]./V_EOS
plot(sol_EOS.t,C_EOS',linestyle=:dash)
plot!(sol_EOS.t,V_EOS,linestyle=:dash)
```

**Comment by ChrisRackauckas** [comment]
Rosenbrock methods need accurate derivatives. That's part of their derivation. Implicit ODE solvers can relax that since they are using a Newton method to correct an implicit term. So this was bound to show up somewhere, just by mathematical design of the method.

**Comment by jibaneza** [comment]
I see, thanks for the informative answer. Then I guess this should not be considered an issue :)

**Comment by ChrisRackauckas** [comment]
No worries. It might be worth a note in the documentation.
