### ISSUE TITLE
Documentation Restructuring

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#99]
- Break Apart Documentation Into Components?

There is a lot going on because (now) there are a lot of component packages (see the additional features section). Should some of the documentation be split out to the component packages themselves? It seems that would make some of the features harder to find. 
- Deprecate Documentation tutorials for Notebooks

There's no need to have different sets of tutorials, and having the ones in the documentation instead of a link to the right notebooks.
- Make an Additional Features Section

The "Manual" section should be a more in-depth look with the exact "here's everything you can do", but in there are some packages on "here's some extra features". I am going to be adding documentation on parameter estimation, bifurcation analysis, and sensitivity analysis: should the function definition macros too and make a new section on these additional features (which are provided by add-on libraries, ParameterEstimation.jl, Bifurcate.jl, Sensitivity.jl, and ParameterizedFunctions.jl respectively?)
- Move Documentation and Tutorials out of the DifferentialEquations.jl repository?

These seem to really be bloating the size of the repository: would it make sense to split these out to a DiffEqTutorials.jl and DiffEqDocs.jl, and instead link to them from DifferentialEquations.jl?

Anyone have any opinions? @gabrielgellner @finmod @musm?

**Comment by musm** [comment]
It might make a lot of sense to have just one master document page for `DiffEq`, and have subsections naturally correspond to the component packages.

I don't think it's a great idea to split the documents to the component packages themselves, since as you say, this will make it harder to locate some of the features.

I suspect most regular users will simply load `DiffEq`. After figuring out their needs, that may then lead them to using just the particular component packages that their requirements necessitates (which will be nice since its a small self contained package, instead loading all of DiffEq).

**Comment by finmod** [comment]
These are teething problems of any useful package. The direction to go is to split the notebooks and applications from the strict computing issues of DifferentialEquations.jl.
Templates to follow are provided by:

QuantEcon applications and Notebooks and QuantEcon.jl   https://github.com/QuantEcon or

Notebooks and GPy by SheffieldML   https://github.com/SheffieldML

**Comment by ChrisRackauckas** [comment]
Thanks. 

Following this advice, I think I will have central documentation, but split the notebooks out to a separate package (since they're huge). As a separate package, the notebooks would be easy to put in little folders and help document what's where, and then I could just load them up with tons of examples. Also it would make it easy for others to contribute notebooks. Making it as a registered package, you will still be able to just `Pkg.add` it, and so that will still be easy. There will be a link to the docs to nbviewer for these example notebooks so that way they are easy to find.

I think the docs will stay in DifferentialEquations.jl though since, well, as a metapackage it doesn't really hold much else anyways (after the modularization change goes through).

**Comment by ChrisRackauckas** [comment]
I realized the docs were huge (because of the animations) so they got their own DiffEqDocs.jl. That way people don't have to download the whole thing, but it's still available online. All docs will just link to that. DiffEqTutorials.jl and DiffEqBenchmarks.jl will hold notebooks (and links to them will be available via the docs). 

The most important forthcoming documentation will be a JuliaDiffEq webpage which will have a diagram of the structure and introduce the ecosystem. That's coming soon. Thanks for helping workshop the ideas!
